### ISSUE TITLE
The server returned a "500 Internal Server Error".

### ISSUE THREAD

**Issue by mushoodmujeeb05** [Myddleware/myddleware#1000]
Hi, 
I am facing an error when accessing the link http://199.127.180.225:30080/index.php/ it gives me below error:

"Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused."

i got the below logs 

"myddleware_1  | 103.151.43.70 - - [20/Apr/2023:21:39:54 +0000] "GET /index.php/ HTTP/1.1" 500 1044 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.48"
"

How to resolve this issue?[

the link is http://199.127.180.225:30080/index.php/

**Comment by mushoodmujeeb05** [comment]
I have used this docker-compose up --build &

**Comment by Myddleware** [comment]
Hi @mushoodmujeeb05 ,
Sorry but the docker installation doesn't work properly because not compatible with the latest version of Myddleware. We will work on it. 
Meanwhile you can install Myddlware by following this tutorial : https://myddleware.github.io/myddleware/#/?id=install-myddleware
We will keep you posted about docker

**Comment by mushoodmujeeb05** [comment]
I am still facing this 500 issue:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

I have installed through git as you mentioned above. what should i do

**Comment by Myddleware** [comment]
Hi, 
Could you check the logs in myddleware/var/logs or your php logs please?

**Comment by mushoodmujeeb05** [comment]
root@escoutils03:/var/www/html/myddleware# myddleware_1  | 103.151.43.70 - - [21/Apr/2023:18:23:51 +0000] "GET /index.php/ HTTP/1.1" 500 1044 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.48"
myddleware_1  | 103.151.43.70 - - [21/Apr/2023:18:23:53 +0000] "GET /favicon.ico HTTP/1.1" 304 251 "http://199.127.180.225:30080/index.php/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.48"


these are the logs

**Comment by mushoodmujeeb05** [comment]
/var/www/html/myddleware# myddleware_1  | 103.151.43.70 - - [21/Apr/2023:18:23:51 +0000] "GET /index.php/ HTTP/1.1" 500 1044 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.48"
myddleware_1  | 103.151.43.70 - - [21/Apr/2023:18:23:53 +0000] "GET /favicon.ico HTTP/1.1" 304 251 "http://199.127.180.225:30080/index.php/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.48"

**Comment by mushoodmujeeb05** [comment]
or any other way i can install myddleware and access it on the server?

**Comment by CamillePMyddleware** [comment]
Hi @mushoodmujeeb05, we apologize for the wait time. Could you please provide us with more information? Which version of Myddleware are you trying to install? What is your current PHP version? Don't hesitate to check the Myddleware requirements page to ensure your configuration is compatible (https://myddleware.github.io/myddleware/#/?id=technical-requirements). Thank you and have a nice day!

**Comment by mushoodmujeeb05** [comment]
I am using myddleware from github where it shows download myddleware.zip when extract it shows myddleware-main.
i am installing myddleware through an option using Dockerfile as shown below:

"Build the Myddleware image with docker-compose (developer's mode)
Build the container locally
Run the following commands in your myddleware directory :

docker-compose up --build

This will build a Myddleware image containing the Myddleware container (PHP with Apache) as well as a Node.js container to handle assets and a MySQL container for your database.

Once the images are up and running, you need to go to the Node.js terminal and type :

yarn install
yarn build

Once your assets are built, you can now go to http://localhost:30080/, where you should see the Myddleware homescreen."

(FROM --platform=linux/amd64 php:7.4.26-apache)


as it shows:

NTAINER ID   IMAGE                         COMMAND                  CREATED        STATUS        PORTS                                              NAMES
47ce756e4e7b   phpmyadmin/phpmyadmin         "/docker-entrypoint.…"   12 hours ago   Up 12 hours   0.0.0.0:30088->80/tcp                              myddleware-main_phpmyadmin_1
bc699c487bef   opencrmitalia/myddleware:v3   "docker-php-entrypoi…"   12 hours ago   Up 12 hours   0.0.0.0:30080->80/tcp                              myddleware-main_myddleware_1
a0c8bf7e0a3b   mysql:5.7.28                  "docker-entrypoint.s…"   12 hours ago   Up 12 hours   3306/tcp, 33060/tcp                                myddleware-main_mysql_1
974bf8827f2b   schickling/mailcatcher        "sh -c 'mailcatcher …"   12 hours ago   Up 12 hours   0.0.0.0:49188->1025/tcp, 0.0.0.0:49187->1080/tcp   myddleware-main_mailer_1
ac550570d78b   databack/mysql-backup         "/entrypoint"            12 hours ago   Up 12 hours                                                      myddleware-main_backup_1
cc89b706f3bb   javanile/openvpn:2.4          "docker-entrypoint"      12 hours ago   Up 12 hours   0.0.0.0:1194->1194/udp                             myddleware-main_vpn_1


but when i access the link http://199.127.180.225:30080/ it gives me this error:
Not Found
The requested URL was not found on this server.

Apache/2.4.54 (Debian) Server at 199.127.180.225 Port 30080
please guide me how should i resolve this issue or may be i am doing it wrong or may be my apache2 configuration may not correct. please guide me in detail

**Comment by mushoodmujeeb05** [comment]
even using this http://199.127.180.225:30080/index.php/ i dont get anything. But at top i see myddleware logo where it shows (404 Not Found)

**Comment by mushoodmujeeb05** [comment]
https://codeload.github.com/Myddleware/myddleware/zip/refs/heads/main

this is the link from where i download mydddleware

**Comment by CamillePMyddleware** [comment]
I think the issue could be coming from your PHP version 7.4.26. If you are using the latest version of Myddleware, you will need at least PHP 8, (the best would be 8.1.7). I would advise against using docker for the time being, as we are working on it through this issue: https://github.com/Myddleware/myddleware/issues/1004.

I would recommend going through the classic installation here: https://myddleware.github.io/myddleware/#/?id=technical-requirements.

feel free to reach out if you need additional assistance.

**Comment by mushoodmujeeb05** [comment]
W: --force-yes is deprecated, use one of the options starting with --allow instead.
/bin/sh: 1: docker-php-ext-configure: not found
The command '/bin/sh -c apt-get update && apt-get upgrade -y &&     apt-get -y install -qq --force-yes rsync mariadb-client libzip-dev libicu-dev git zlib1g-dev libc-client-dev libkrb5-dev cron rsyslog unzip libssh2-1-dev gnupg2 alien libaio1 nano vim net-tools iputils-ping telnet &&     docker-php-ext-configure intl && docker-php-ext-configure imap --with-kerberos --with-imap-ssl &&     docker-php-ext-install imap exif mysqli pdo pdo_mysql zip intl &&     echo "short_open_tag=off" >> /usr/local/etc/php/conf.d/syntax.ini &&     echo "memory_limit=-1" >> /usr/local/etc/php/conf.d/memory_limit.ini &&     echo "display_errors=0" >> /usr/local/etc/php/conf.d/errors.ini &&     sed -e 's!DocumentRoot /var/www/html!DocumentRoot /var/www/html/public!' -ri /etc/apache2/sites-available/000-default.conf &&     curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer &&     apt-get clean && rm -rf /tmp/* /var/tmp/* /var/lib/apt/lists/*' returned a non-zero code: 127


Igot this error while running 
docker build . -t myddleware

**Comment by mushoodmujeeb05** [comment]
is there any other way to install myddleware on my debian linux server except using Docker?

**Comment by CamillePMyddleware** [comment]
Of course, you can install Myddleware without using Docker by following our installation guide right here: https://myddleware.github.io/myddleware/#/?id=install-myddleware

feel free to reach out if you need additional assistance.

**Comment by mushoodmujeeb05** [comment]
ok let me try

**Comment by mushoodmujeeb05** [comment]
http://199.127.180.225/myddleware/public

after using yarn build command?

when i do so it shows:
Not Found
The requested URL was not found on this server.

Apache/2.4.56 (Debian) Server at 199.127.180.225 Port 80

**Comment by mushoodmujeeb05** [comment]
i have do this in my apache2:

 DocumentRoot /var/www/html/myddleware
    <Directory /var/www/html/myddleware>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Require all granted
    </Directory>

**Comment by Myddleware** [comment]
I am sorry @mushoodmujeeb05 , it is difficult for us to help you with a 404 error because it seems that the error is on the server side. So I guess there is some configuration to be changed to be able to reach the index.php file in the public repository.
Once you have reached it, we will be able to help you even if you have a 500 error.
Please keep us updated.

**Comment by CamillePMyddleware** [comment]
Hello,
We take the liberty to close this problem, however if you encounter a bug equal or similar to this one do not hesitate to reopen the problem. 
Thanks.
