### ISSUE TITLE
Modification search fields aren'tconverted in the right timezone

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#1003]
Here is an example, we have to search between 2 and 3 pm to find a document that has been modified between 4 and 5 pm : 
![image](https://user-images.githubusercontent.com/11330301/234616818-1355892c-2891-48fa-a774-f9feaab7fe84.png)

The search between 4 and 5 pm should find the result. The date/time filled by the user in the search view should be converted to UTC before the search in the database.

**Comment by AlexMyddleware** [comment]
Fixed in upcoming version 3.3.2
