### ISSUE TITLE
Alert for job interruption

### ISSUE THREAD

**Issue by RomanFaure** [Myddleware/myddleware#1009]
It will be helpful if an alert can appear when a rule has an interruption for this reasons : 
'All records read have the same reference date in rule Mobilisation - Contact vers USC. Myddleware cannot guarantee that all data will be read. Job interrupted. Please increase the number of data read by changing the limit attribute in job and rule classes.'

**Comment by AlexMyddleware** [comment]
was completed in this commit

https://github.com/Myddleware/myddleware/commit/5e12f9621c169559387d166dc0c6ee8ff51efde6
