### ISSUE TITLE
Setting up database

### ISSUE THREAD

**Issue by mushoodmujeeb05** [Myddleware/myddleware#1012]
Hi,
I am now accessing myddleware on my server as ipaddress:30080/index.php please guide me how can i set up its database? As i am using debian Linux server.
please find the attached screenshot
![myddleware](https://github.com/Myddleware/myddleware/assets/95737622/70e54c14-dff6-41bd-b416-f4b4670f32b7)

Regards,
Mushood

**Comment by Myddleware** [comment]
Hi @mushoodmujeeb05 ,
You can find our documentation here : https://myddleware.github.io/myddleware/#/?id=install-myddleware
Hope it will help.
Have a nice weekend.

**Comment by CamillePMyddleware** [comment]
Hello,
We take the liberty to close this problem, however if you encounter a bug equal or similar to this one do not hesitate to reopen the problem. 
Thanks.
