### ISSUE TITLE
where to save the rule? is there any button to save?

### ISSUE THREAD

**Issue by mushoodmujeeb05** [Myddleware/myddleware#1022]
I want to create a rule for that purpose first i add on "source side" mysql db and then on "target side" i add another mysql db. But after adding these i am unable to find save the rule. Is there any button ?

**Comment by Myddleware** [comment]
Hi @mushoodmujeeb05 ,
Could add a screenshots to help us to sera what is the issue? Thanks

**Comment by mushoodmujeeb05** [comment]
these are the 2 screenshots. I have added mysql (source) and mysql other db to (target). it says "new connector added"
but still i dont able to find the save button. Please find the attached screenshots:
![prod_mysql1](https://github.com/Myddleware/myddleware/assets/95737622/5e65d4f9-93d3-4a72-8ad2-a84a9f05de98)
![qa_mysql2](https://github.com/Myddleware/myddleware/assets/95737622/575297c0-8b68-4163-bca7-410af056c5de)

**Comment by mushoodmujeeb05** [comment]
please guide me in this regard. Thanks

**Comment by CamillePMyddleware** [comment]
Hi @mushoodmujeeb05 , I see that you already have your connectors. All you need to do is choose the source and target connectors for your environment, then select the modules and configure your fields. For a better understanding of the application, I recommend checking out our documentation where you'll find all the information you need to create and use your rule. https://myddleware.github.io/myddleware/#/basic_usage

Thanks

**Comment by mushoodmujeeb05** [comment]
What should i do nexxt? here find an attached screenshot:
![Uploading rule connector.jpg…]()

**Comment by mushoodmujeeb05** [comment]
What should i do nexxt? here find an attached screenshot:
![rule connector](https://github.com/Myddleware/myddleware/assets/95737622/a76b9433-7ba3-4504-a003-2924c1e375be)

**Comment by CamillePMyddleware** [comment]
Hi @mushoodmujeeb05, 

It's possible that you forgot to execute the "yarn install" or "yarn build" command. Could you please confirm if you have completed this step? Additionally, could you let me know if you can see the Myddleware logo in your application when you connect? If you have already run the "yarn" command and are still experiencing issues, could you check for any errors in the console and share them with us? 

Thanks

**Comment by mushoodmujeeb05** [comment]
here is the screenshot. I think I am not seeing it's logo:

![logo myddleware](https://github.com/Myddleware/myddleware/assets/95737622/3f61f4a1-44c1-4168-a7db-f43cea0608e8)

**Comment by mushoodmujeeb05** [comment]
yarn install and yarn build already done. as shown in the screenshots below:
![yarn build](https://github.com/Myddleware/myddleware/assets/95737622/fa79ca60-286e-45a4-9ec4-cd528d9bc5ab)
![yarn install](https://github.com/Myddleware/myddleware/assets/95737622/d8917100-0e81-49ec-b63c-d1af92ae3a45)

**Comment by mushoodmujeeb05** [comment]
but myddleware "favicon" is shown. please find the attached screenshot:
![top logo](https://github.com/Myddleware/myddleware/assets/95737622/40fce976-298f-4739-8692-4e1a3a7d5960)

**Comment by Myddleware** [comment]
Hi @mushoodmujeeb05 ,
Could you open the directory myddleware/public with a terminal and excecute this command : 
`rsync -Rr ./build/ ./build/`

It will create a copy of the build folder into the build folder. Does it change something ?

**Comment by mushoodmujeeb05** [comment]
ok let me do it

**Comment by mushoodmujeeb05** [comment]
yes by running this command (rsync -Rr ./build/ ./build/) I see logo of myddleware.  what should I do next? 
As shown in screenshot below:
![myddleware logo](https://github.com/Myddleware/myddleware/assets/95737622/080f48f2-c52a-436d-a1a6-dae510a41242)

**Comment by Myddleware** [comment]
Hi @mushoodmujeeb05 , you can try to create a rule. 
Have a nice day

**Comment by mushoodmujeeb05** [comment]
Hi,
It worked but when I add source (mysql) and target (mysql) it showed me a blue dot which moves to and fro but it did not guide me to the other steps likes modules etc. Please guide me in this regard.
I am adding a screenshot.

![prod to qa connection](https://github.com/Myddleware/myddleware/assets/95737622/5431533f-8626-449e-b0a4-185b87801260)

**Comment by CamillePMyddleware** [comment]
Hello mushoodmujeeb05, 
Have you tested your connector? A faulty connection can prevent the configuration process of a rule. I also recommend clearing your browser cache. This can resolve issues related to the interface. Finally, it would be helpful for us to review your error logs to precisely determine the cause of this problem.

Thanks and have a nice day.

**Comment by mushoodmujeeb05** [comment]
connector list as shown in the screenshot.
in the meanwhile i am clearing my browser cache.
![connector list](https://github.com/Myddleware/myddleware/assets/95737622/63d3741f-20ac-4219-8f62-1ab0df42bff8)

**Comment by mushoodmujeeb05** [comment]
I have opened in incognito mode in the web browser, but still black dot (source side) and blue dot (target side) moves to and fro and not showing or moves to next step may be it will be modules. please check the attached screenshot:
![maping connectors](https://github.com/Myddleware/myddleware/assets/95737622/bc4a0609-5bcc-4061-8384-0a22d4fee740)

**Comment by mushoodmujeeb05** [comment]
i have checked and tested my connectors it requires vpn connection first. so is this the issue? vpn issue?

**Comment by mushoodmujeeb05** [comment]
can you reply me? I am stuck

**Comment by mushoodmujeeb05** [comment]
reply the above messages

**Comment by Myddleware** [comment]
Hi @mushoodmujeeb05 , could you try to create you connector and a rule using our demo version (option 2 in our website : https://www.myddleware.com) 
Then don't forget to remove the rule and connector as this environment is public. 
If you have the same problem in our demo environment, it means that the issue could be the VPN. If there is no issue on our demon environment, then it means the issue comes from your environment.

**Comment by CamillePMyddleware** [comment]
Hello,
We take the liberty to close this problem, however if you encounter a bug equal or similar to this one do not hesitate to reopen the problem. 
Thanks.
