### ISSUE TITLE
Unwanted redirection on the On/Off button in the detailed view of a rule

### ISSUE THREAD

**Issue by CamillePMyddleware** [Myddleware/myddleware#1025]
By clicking on the On/Off button in the detailed view of a rule, it leads to an unexpected redirection to 'update_description'. 'updateDescription' is the function used to modify the description of a rule.

![image](https://github.com/Myddleware/myddleware/assets/95077335/626af09e-a9f6-4415-ac3e-e0f3af836080)

**Comment by AlexMyddleware** [comment]
corrected in 3.3.3
