### ISSUE TITLE
question reinstallation of myddleware

### ISSUE THREAD

**Issue by Alexandre17220** [Myddleware/myddleware#103]
Hi, 
Because I have much problem with my installation of myddleware, I have reinstalled, deleted all directory middleware and database, reinstall the last version and reconfigure my connector and rule.
I use it for Prestashop -> SuiteCRM and 
![image](https://user-images.githubusercontent.com/7665521/41022260-3eccffa6-6969-11e8-9415-d6225c10c4f0.png)

All my customers have been inserted by the first installation.
But I have error with the rule "addresses" :
![image](https://user-images.githubusercontent.com/7665521/41022309-66c1e954-6969-11e8-88ab-b6709db9fbd9.png)
Why ?
Thanks,

**Comment by Alexandre17220** [comment]
I see this 
![image](https://user-images.githubusercontent.com/7665521/41022720-b710df5e-696a-11e8-86c4-c8753cef8f64.png)

**Comment by Myddleware** [comment]
Hi Alexandre,
Myddleware search the customer 60 762 in the rule customer (in Myddleware) to retrieve the SuiteCRM customer ID. Then Myddleware will be able to send this address to the right customer.
Your problem is the customer 60 762 isn't in the rule customer because it is only in your first installation.

Here is my advise : make sure the duplicate field "email" is active in your customer rule : 
![image](https://user-images.githubusercontent.com/11330301/41023067-a2591e0e-696b-11e8-894e-903e8a7e388f.png)
Then set the reference date of you customer rule far in the past : 
![image](https://user-images.githubusercontent.com/11330301/41023305-5989a4d6-696c-11e8-8220-aaaced40ddc5.png)

Then Myddleware will read again all your customers from Prestashop and check if this customer already exists in SuiteCRM by searching the email, If the customer exist in SuiteCRM, Myddleware will store the SuiteCRM ID and will be able to link other data to it (like address).

Does it help ?

**Comment by Alexandre17220** [comment]
I have already this :
![image](https://user-images.githubusercontent.com/7665521/41024012-4a9558c4-696e-11e8-941c-71264b9ece3a.png)
and a date in 1970 when I reinstall myddleware.
Myddleware have synchronize all the night my 262 000 customers but some transfers rule address don't ok:
1000 closed
1000 error
there isn't error for rule customer

**Comment by Alexandre17220** [comment]
why there is this ?
![image](https://user-images.githubusercontent.com/7665521/41024336-42c9db14-696f-11e8-8cb8-5b9810abcfa0.png)

**Comment by Alexandre17220** [comment]
the exact number of error and closed fron the tule address 👍 
![image](https://user-images.githubusercontent.com/7665521/41024526-c6ea68dc-696f-11e8-930b-1d5c67a9c99f.png)

**Comment by Myddleware** [comment]
Alright.
Could you search the data transfer with the source ID 60762 in the rule customer : 
![image](https://user-images.githubusercontent.com/11330301/41025014-19438004-6971-11e8-8864-b5d80b0c7ace.png)
Do you find one ? If yes what is its status ?
Thanks.

**Comment by Alexandre17220** [comment]
![image](https://user-images.githubusercontent.com/7665521/41025509-561114d2-6972-11e8-92a0-bdd4c51ccfaa.png)

**Comment by Myddleware** [comment]
This is very weird thant you don't have the customer 60762 in the rule customer.
Could you just try to reread the customer 60762 with the rule customer. To do that we have a new command in version 2.3.4 : readrecord. From your Myddleware root directory, could you run this command : php app/console myddleware:readrecord ID_of_your_rule_customer id 60762

Is the data transfert for the customer 60762 created ? 
Thanks.

**Comment by Alexandre17220** [comment]
![image](https://user-images.githubusercontent.com/7665521/41029422-e6360c80-697b-11e8-9a81-e0703655fd79.png)

**Comment by Myddleware** [comment]
Could you add the id of you rule Customer between readrecord and id ? Thanks.

**Comment by Alexandre17220** [comment]
![image](https://user-images.githubusercontent.com/7665521/41031596-509e09a6-6981-11e8-8f0c-f5e2d7da677b.png)

**Comment by Myddleware** [comment]
OK so could you search again the data transfer with the source ID 60762 in the rule customer ?
If it exists could you reload the address data transfer in error ?
Thanks.

**Comment by Alexandre17220** [comment]
after reload:
![image](https://user-images.githubusercontent.com/7665521/41031892-276868d2-6982-11e8-85dc-1c131fa7b514.png)

![image](https://user-images.githubusercontent.com/7665521/41031910-3618b38c-6982-11e8-975f-cb2036b9b86d.png)

**Comment by Alexandre17220** [comment]
I make it twice

**Comment by Alexandre17220** [comment]
strange it's not the same Id source

**Comment by Myddleware** [comment]
Alexandre, 
Your address data transfer isn't the one you give me at the beginning of this discussion. The cirstomer ID here is 53503 not 60762. Coud you reload the address data transfer with the customer 60762 ? 
Thanks.

**Comment by Alexandre17220** [comment]
I don't understand:
1> I clic transfers/list, I input source id 60762 and I click filter
![image](https://user-images.githubusercontent.com/7665521/41032311-38c30fc8-6983-11e8-9867-1e4649dd6f18.png)

**Comment by Alexandre17220** [comment]
I find, :
I have make this command :
php app/console myddleware:readrecord 5b165b65f17b1 id 53503
and reload the data transfert in error
now the data transfert it's ok

**Comment by Alexandre17220** [comment]
So how to find and reload all the transfert mistake in rule customer ? and how to resolve this bug?

**Comment by Myddleware** [comment]
Hi Alexandre, you can search by source content. Myddleware will search every data transfert with 60762 in their content. So you will be able to find the address data transfer with id customer = 60762.

**Comment by Alexandre17220** [comment]
Ok, I found it, reload it and now it's ok
So, how to identify all customer don't created and relaunch the system ?
And why some customer aren't created?
![image](https://user-images.githubusercontent.com/7665521/41035962-a79696da-698e-11e8-9dab-172641cb701e.png)

**Comment by Alexandre17220** [comment]
I find something all customers haven't been transfered from my prestashop to suitecrm !?! why the synchroall don't synchronize all ??

**Comment by Alexandre17220** [comment]
I have disable all rules except customers.
change the date to 1970, and relaunche synchroall via cron table 
*/1 * * * * cd /home/vhosts/default/docs/liaison; php app/console myddleware:synchro ALL  --env=background  > /dev/null 2>&1

There is a method to synchronize more quickly?

**Comment by Myddleware** [comment]
Good idea.
You can change  ALL by the ID of your rule and it will launch only your rule.
Other way to synchronize only specific customers, you can use the commande readrecord by adding all customer_id you need to send separated by comma. Here an example : 
php app/console myddleware:readrecord 5b165b65f17b1 id 53503,53504,53505,53506

About the customer missing. Could you tell me if you have imported you data in Prestashop and if a lot of customer have the same modified date ?

**Comment by Alexandre17220** [comment]
> About the customer missing. Could you tell me if you have imported you data in Prestashop and if a lot of customer have the same modified date ?
Yes, maybe there are the same date modified, you don't use this date to know somthing..don't afraid me

**Comment by Myddleware** [comment]
I don't understand your question sorry.
It could be a bug during reading data from Prestashop when a lot of customers have the same modified date.
We will analyse it and try to reproduce the case. If we get the bug we will fixe it in the next version.

**Comment by Alexandre17220** [comment]
in 
"src/Myddleware/RegleBundle/Solutions/prestashop.php"
line 401 function read_last
how is built his param ?

**Comment by Myddleware** [comment]
Myddleware sort data to avoid missing data. Then we keep the last modified or created date date as a reference date. And next time the program run it will start from this date.

But I have checked the code again and I should'nt be a bug.

We will see what your last acton will done. If some customer are still missing. 
It could also be a problem in your database, if customer has no modified date for example.

**Comment by Alexandre17220** [comment]
ok "je vais allumer un cierge"
I have verified in my Prestashop table ps_customer no record without date_upd
suspence

**Comment by Myddleware** [comment]
Bonjour Alexandre, 
So you speak fnench too ;). If 17220 is a postal code, I live not too far from you ;)
Please let us know if customers have been read properly.

There should not be a bug on the read function of Prestashop. We have currently a big project with Prestashop, we have transfered more than 2 000 000 data without missing any customer.

**Comment by Alexandre17220** [comment]
Hi,
yes my post code is now 17000 :)
where do you live you?

**Comment by Myddleware** [comment]
Hi, one of my place is in Charente, north of Angoulême. But I studied 4 years in La Rochelle, very nice city ;)

**Comment by Alexandre17220** [comment]
So, The operation is terminated.
In prstashop I have 260 000 customers when I make this request (rule id of customer is 5b165b65f17b1 I use the model for prestashop include in myddleware) :
`SELECT * FROM `Document` WHERE `rule_id` LIKE '5b165b65f17b1'`
I found  177 000 records..
why ?

**Comment by Alexandre17220** [comment]
Now .. I Try with product...
I delete all my products in SuiteCRM
In prestashop I have 4150.
I use the rule include in Myddleware... and in suiteCRM myddleware create 417products.

**Comment by Myddleware** [comment]
Hi Alexandre,
This is difficult to say. We will need more analys to find the problem.
I advise you to get the detail of all missing partners (possible to do it with Excel) and see if they have something specific. If there date created/modified is in the right format, if these data are later than the reference date you choose.
Maybe there is something wrong in these customers. Did you import them or have they been created directly in Prestashop ?
During your first Myddleware installation, have they been all read by Myddleware ?
Thanks.

**Comment by Alexandre17220** [comment]
during the first installation all have been read.
Myddleware save somme information in suitecrm database ? or all are save in the database myddleware ?

**Comment by Myddleware** [comment]
OK. All is saved in Myddleware database.
So could you analys the customers no read by Myddleware and try to find the origin of the error ?  
Thanks.

**Comment by Alexandre17220** [comment]
I go to analyse product , much fast

**Comment by Alexandre17220** [comment]
I found something for some product, when I delete product in suitecrm the product isn't delete, just deleted=1 and invisible.
So when mydlleware search the id find it... Is it possible to configure myddleware for put delete=0 for product ??

**Comment by Alexandre17220** [comment]
I edit my rule to put deleted to 0..wait and see, I go to analyse customers

**Comment by Alexandre17220** [comment]
For customers :
in prestashop
id : 31490
customer name ABCDEFGH
If I search in suitecrm.contacts I found id : 1000b464-94e4-48cf-24df-59b6f40075a7
If I search in myddleware on his id :
SELECT * FROM `Document` WHERE `rule_id` LIKE '5b165b6679736' AND `source_id` LIKE '31490'
I found this :
![image](https://user-images.githubusercontent.com/7665521/41150586-b074e67c-6b0e-11e8-9e99-c0c5dbb0ec61.png)
Why ? the contact in suitecrm id 8aa8035b-4e5f-b27b-8de0-59a819b5d9ce haven't the same mail..

**Comment by Myddleware** [comment]
If I remember everything, you case was specific and we have fixed you problem directly.
Contact us if you have any other issue.
Have a nice day,
Stéphane
