### ISSUE TITLE
Wrong display of formula popup in case of long value in a dropdownlist

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#1033]
When a value in a list is too long, the formula popup is too large : 
![image](https://github.com/Myddleware/myddleware/assets/11330301/65ff7992-d06a-4c40-befc-691e1d06e037)

![image](https://github.com/Myddleware/myddleware/assets/11330301/4df73be5-a112-4dae-b19c-1d220997b699)

**Comment by AlexMyddleware** [comment]
fixed in 3.3.3
