### ISSUE TITLE
bug transfert list - wrong list rule

### ISSUE THREAD

**Issue by Alexandre17220** [Myddleware/myddleware#104]
Hi,
I have this rules :
![image](https://user-images.githubusercontent.com/7665521/41229924-1a7b99b4-6d7e-11e8-8c0e-5521b1d40e44.png)

and now in transfert list :
![image](https://user-images.githubusercontent.com/7665521/41229932-27bf15f6-6d7e-11e8-8f81-50792fcdd110.png)

thanks

**Comment by Myddleware** [comment]
Hi Alexandre,
Thanks for your feedback. I see that you run 2 times the same template so tere is a conflict in the rule names. We will work on it to fix it for the next release.
Until we fix the problem, you can change the names (fields name and name_slug) of the rules in the database, table Rule. It should fixe this bug.

**Comment by Alexandre17220** [comment]
ok thanks, for information my rule have thame names because I use the default templates selection
ps: I send you some mail about my problem , do you receive them?

**Comment by Myddleware** [comment]
Hi Alexandre.
Yes we will fix this bug in the next release.
PS : No I didn't receive your messages. As I can't add my email here, could you just send us a message via our website on this page : http://www.myddleware.com/contact-us
Thanks.

**Comment by CamillePMyddleware** [comment]
Hi, I archive this problem, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be. 
Thanks
