### ISSUE TITLE
Move button "Stop all the tasks"

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#1042]
We need to move the button as shown on the screenshot and rename the button "Stop active tasks" : 
![image](https://github.com/Myddleware/myddleware/assets/11330301/36bbe882-dd55-4443-aa50-bdc128c13ff2)

**Comment by AlexMyddleware** [comment]
fixed in 3.3.4

**Comment by Myddleware** [comment]
Hi @AlexMyddleware , thanks for adding the button in detail list view. However, could you remove it from the menu ? Thanks.

**Comment by AlexMyddleware** [comment]
will be addressed in next release
