### ISSUE TITLE
clean installation myddleware

### ISSUE THREAD

**Issue by Alexandre17220** [Myddleware/myddleware#105]
Hi,
I want to clean my installation of myddleware
can I delete all data in document ,documentdata, job, and log ?
I want symply keep my rule and connector

Thnaks,

**Comment by Myddleware** [comment]
Hi Alexandre,
Yes, you can definetely delete all data in these tables. However I advise you to keep a backup of the table document to keep the correspondence of the IDs of your source and target solutions.
Have a nice day.
