### ISSUE TITLE
Access denied when logging into middleware.

### ISSUE THREAD

**Issue by hcdangan** [Myddleware/myddleware#106]
Hi. I am getting an error when trying to login at my installed myddleware. Here is the error:

An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO) ( 1 )

I am wondering why root@localhost is being used when I specified a different user during the myddleware installation. It always assume I am logging in as root@localhost regardless of which login ID I use in the login form.

My Myddleware is currently hosted at HostGator.

**Comment by Myddleware** [comment]
Hi,
Could you check the parameters in the file myddleware\app\config\parameters.yml : 
    database_driver: pdo_mysql    => has to be pdo_mysql
    database_host: localhost  => it is generaly localhost if Myddleware runs on the same server than MySQL
    database_port: '' => it is generaly empty if Myddleware runs on the same server than MySQL
    database_name: xxxxxxx => your database name
    database_user: xxxxxxx => your MySQL user
    database_password: xxxxxxx => your MySQL password

Are these parameters OK ? If not, could you change them, empty the directory myddleware\app\cache and try to connect again ?

**Comment by hcdangan** [comment]
Ther parameters seem to be okay. I even tested these using a simple PHP page and it was able to connect properly...

parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: ''
    database_name: payment
    database_user: payment
    database_password: DummyPassword
    secret: 780b63a01867d377a9cab6e992b21166
    myddleware_support: 0
    param:
        mode: front_office
    extension_allowed:
        - xml
        - wsdl
    myd_version: 2.3.4
    block_install: 1

You can try it here:

http://myddleware.cpdportal.ph/web/

Regardless of what you type in the login form. It still tries to connect with root@localhost

**Comment by Myddleware** [comment]
Alright.

Could you check if you database have been created properly, you should have 20 tables and 1 row in the table users : 
![image](https://user-images.githubusercontent.com/11330301/42511953-96b6b45a-8453-11e8-9d6a-1abf376a5d02.png)

If everything os OK, could you give us you MySQL version ?
Thanks.

**Comment by hcdangan** [comment]
There are no tables in the database. This is strange because the installation was successful.

Here is my version of MySQL:


Variable_name | Value 
innodb_version | 5.6.39-83.1
protocol_version | 10
slave_type_conversions |  
tls_version | TLSv1.1,TLSv1.2
version | 5.6.39-83.1
version_comment | Percona Server (GPL), Release 83.1, Revision da5a1...
version_compile_machine | x86_64
version_compile_os | Linux

**Comment by Myddleware** [comment]
Thanks.

Could you follow this tutorial : https://myddleware.github.io/myddleware/#/?id=install-myddleware

It will help you installing Myddleware via linux command.

You will see these command which should generate the tables: 
php app/console doctrine:schema:update --force --env=background
php app/console doctrine:fixtures:load --append --env=background

Could you tell us if it works ? Thanks.

**Comment by dawoodjee** [comment]
```
root@scw-email:/var/www/html/myddleware.zeroinvoice.com# php app/console doctrine:schema:update --force --env=background
Could not open input file: app/console
root@scw-email:/var/www/html/myddleware.zeroinvoice.com# ls app
AppCache.php  AppKernel.php  autoload.php  config  htaccess  phpunit.xml.dist  Resources
```

**Comment by dawoodjee** [comment]
I also have a login problem. No web-based errors or notifications. Myddleware is just returning to the login page

**Comment by Myddleware** [comment]
Hi @dawoodjee ,
We have upgraded symfony (Myddleware 's framework) version. The path isn't "app/console" anymore but "php bin/console". The documentation is updated so you can follow it : https://myddleware.github.io/myddleware/#/?id=install-myddleware

Have a nice day.

**Comment by dawoodjee** [comment]
Thanks @Myddleware 

I used this command-line installation method. is there a better way I can see the errors?

**Comment by Myddleware** [comment]
You can also check the logs in myddleware\var\logs\prod.log

**Comment by dawoodjee** [comment]
The logs are not giving anything relevant

```
[2019-08-26 15:35:17] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /web"" at /var/www/html/myddleware.zeroin$
[2019-08-26 15:37:16] console.ERROR: Error thrown while running command "fos:user:create support 'support@xxxx.co.zm' 'xxxxxxx@#' -e prod". Message: "An exception occurred while executing '$
[2019-08-26 15:51:46] app.ERROR: Exception occurred while flushing email queue: Expected response code 220 but got code "", with message "" [] []
[2019-08-26 15:52:14] app.ERROR: Exception occurred while flushing email queue: Expected response code 220 but got code "", with message "" [] []
```

The user creation exception was because I ran another create user with the same email.

I'll try removing Myddleware files and database then reinstalling

**Comment by Myddleware** [comment]
You have just re opeened a closed issue.

If you have the same problem than hcdangan (can't connect to Myddleware because of database empty) please click on reopen and add comment to tell us how you have installed Myddleware, if you had some errors...
If your database isn't empty, we assume that your Myddleware installation is OK, in this case could you open a new issue and explain your problem.
Thanks.

**Comment by dawoodjee** [comment]
Alight. Thank you
