### ISSUE TITLE
Optional fields required on connector creation view

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#1069]
When we create a Moodle connector, there are 2 optional fields.
Unfortunately we can't save or test the connecteor if we don't fill them : 
![image](https://github.com/Myddleware/myddleware/assets/11330301/311f1ce6-8187-4fc3-8bef-b9fc92bc8986)

I thing we shouldn't have any requiered field in this view.

**Comment by raulcaparida** [comment]
any update on this because I'm also having the same concern.

**Comment by Myddleware** [comment]
Hi @raulcaparida ,
You can put a space in these fields for now. It will be fixed in the next version.
Best regards.

**Comment by Myddleware** [comment]
@AlexMyddleware

**Comment by AlexMyddleware** [comment]
fixed, will be added in next release !

**Comment by AlexMyddleware** [comment]
will close in 
https://github.com/Myddleware/myddleware/pull/1147

**Comment by AlexMyddleware** [comment]
i close this issue because the solution was merged
