### ISSUE TITLE
Issues with Hubspot createdate field

### ISSUE THREAD

**Issue by Travelopia-robwalker** [Myddleware/myddleware#107]
Hi, 

When we set up a rule to import from HubSpot to a local MySQL DB, we manage to get through the rule setup screens and the on the simulation tab the test data button successfully shows one result:

hubspot
Source
 booking_ref ( Empty content )
 country ( Empty content )
 createdate ( 1526573033537 )
 email ( coolrobot@hubspot.com )
 firstname ( Cool )
 hs_email_optout_4898329 ( Empty content )
 lifecyclestage ( lead )
 lastname ( Robot (Sample Contact) )

Target
 booking_reference  Empty content
 country  Empty content
 created_date  1526573033537
 email  coolrobot@hubspot.com
 firstname  Cool
 gdpr_opt_in  Empty content
 lifecycle_stage  lead
 surname  Robot (Sample Contact)

However, after saving and going to the Parameters tab, with any date of reference date (i.e. 2018-01-01) I always get 0 results in the simulation. 

Most of the data I am trying to import is of May 2018 (1526573033537). Could it be the unix timestamp that is causing the issue? 

Thank you

**Comment by Myddleware** [comment]
Hi,
We have fixed few bugs on Hubspot connector. Could you try to replace the file "<myddleware_root>\src\Myddleware\RegleBundle\Solutions\hubspot.php" by the file attached (once you have extracted it).

[hubspot.zip](https://github.com/Myddleware/myddleware/files/2253496/hubspot.zip)

Could you tell me if it works now. Thanks.
Best regards,
Stéphane
