### ISSUE TITLE
Failed to modify a document in error + error 500

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#1076]
When I try to modify a document in error, I double click on a value and I get a 500 error. A job is also created with an empty comment. 
At least a part of the issue is here : https://github.com/Myddleware/myddleware/blob/c57b98c3cb89ee648178d3b4625cbe66fed09e9b/src/Controller/FluxController.php#L778
If the comment is emty we shouldn't generate any job with the comment.

The job name "notification" should be replace by "New comment"

**Comment by AlexMyddleware** [comment]
fixed in https://github.com/Myddleware/myddleware/pull/1138 because comment feature was removed
