### ISSUE TITLE
Prestashop Error : Notice: Undefined index: language 

### ISSUE THREAD

**Issue by Likeandfeel** [Myddleware/myddleware#108]
Hi Team

i have problem with prestashop 1.6.1.20 for transfer to 2 plateform running with ame version 1.6.1.20 with Middleware version 2.3.4

Source plateform dont use specific product language and same for destination 

For customer synchro its ok
For product no alway i get same message 

Error : Notice: Undefined index: language 
src/Myddleware/RegleBundle/Solutions/prestashop.php Line : ( 899 )Failed to send document. Status : Error_sending

some one have same issue, and have found solution ?
Thanks in advance

**Comment by Myddleware** [comment]
Hi,
Thanks for contacting us.
For product module, Myddleware need the language to update the description in the right language. When we create a rule with product we can choose the language in the last tab : 
![image](https://user-images.githubusercontent.com/11330301/44526858-88f0bc80-a6e5-11e8-8db6-48c8fb466b4e.png)

Could you show us what you get in this dropdown list. Is it empty or are you able to select a language ?

Thanks.
Stéphane

**Comment by Likeandfeel** [comment]
Hi 

Thanks for the answer :)

For these 2 websites i dont have this option as you can see on screenshoot. For both webservice is open in all right for Product and language (2nd screenshoot) 

![capture d ecran 2018-08-23 a 19 06 00](https://user-images.githubusercontent.com/23337598/44540631-b9e1e900-a707-11e8-83e6-2095f61b3a9a.png)

![capture d ecran 2018-08-23 a 19 09 48](https://user-images.githubusercontent.com/23337598/44540783-4e4c4b80-a708-11e8-81f1-f93d0dde8d08.png)

thanks for all 
bests regards

**Comment by Myddleware** [comment]
Hi, 
Maybe the language list function doesn't work with Prestashop 1.6 as it is a feature we have added with Prestashop 1.7.

Let's try a workaround. Could you add an entry in your Myddleware database, table ruleparam. 
![image](https://user-images.githubusercontent.com/11330301/44590907-890fbb80-a7bc-11e8-8fc8-6fef6de22ef2.png)

Please add your rule_id, name = language and value = the id of the language you want to send. You can see the language id in your table <prefix>_lang in your Prestashop database : 
![image](https://user-images.githubusercontent.com/11330301/44591422-fcfe9380-a7bd-11e8-9335-9adac96b1364.png)

Then try to rerun your rule. Does it work ? 
Best regards,
Stéphane

**Comment by Likeandfeel** [comment]
Hi

Its working in manual, but each time we create or modify new rule we must add on this table for its working.
Other thing i get for automatic update this error message : 

**_Error : Please check your data.This call to PrestaShop Web Services failed and returned an HTTP status of 500. That means: Internal Server Error. 
src/Myddleware/RegleBundle/Solutions/prestashop.php Line : ( 940 )Failed to send document. Status : Error_sending_**

I have make test from other source version shop and its true with 1.7 we get Language, but same message that i put up

Thanks for all :)

**Comment by Myddleware** [comment]
Hi,
Thanks for your feedback.

The language parameter is required only for the module product so you shouldn't have to add the parameter language for rules which send data to other modules.

About the other problem, could you open another issue and add a screenshot of your data transfert in error please ? Thanks.

Best regards.
