### ISSUE TITLE
Display content of table cron_job_result

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#1082]
It would be great if we could display the content of the table cron_job_result with, at least, the possibility to order the result for each column. 
It could be diplayed at the bottom of this page : /myddleware/public/rule/jobscheduler/crontab_list
Or it could be a new page that could be reach by a button on the crontab page.

**Comment by AlexMyddleware** [comment]
![image](https://github.com/Myddleware/myddleware/assets/106162060/86fd9300-bd55-4216-a3bc-d0e5d149302d)
