### ISSUE TITLE
Error installing Myddleware

### ISSUE THREAD

**Issue by Sebas82** [Myddleware/myddleware#109]
Hello,
I'm trying to install myddleware on a web server and when I insert all the config information through the installMyddleware.php file, the following error is reported:

"Failed: The command "php .../myddleware/app/../vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Resources/bin/build_bootstrap.php" failed. Exit Code: 255(Unknown error)
Output: ================ Error Output: ================ PHP Parse error: syntax error, unexpected '[' in .../myddleware/vendor/illuminate/support/helpers.php on line 346"

I've been looking for a solution but I didn't find a related solution for this error. I'm not sure about the the error coulbe be related to any configuration with web server. 
Could any one help me, please?
Many thanks.

**Comment by Alexandre17220** [comment]
Hi,
Can you specify your server version ?
mysql (mariadb) version?
php version (mode fpm or not ?) ?
linux Distribution version?
Thanks,

**Comment by Sebas82** [comment]
Hello, thanks for your reply:

server version: CentOS 6.9
Mysql: 5.7.19
PHP: 5.3.3 OS, 7.0.31 Hosting

Yesterday I realized the server and hosting PHP version are different. I've tried to check which version of PHP is  took by Myddleware, but I don't know how to check that.

Thanks.

**Comment by Alexandre17220** [comment]
Put a phpinfo in a script php and open the page

**Comment by Sebas82** [comment]
Thanks! It is working with 7.0.31 PHP version.

**Comment by Alexandre17220** [comment]
nice have a good day

**Comment by Sebas82** [comment]
Thanks ... but I still have the same error.

**Comment by Alexandre17220** [comment]
do you respect this requirements : 
"
Please have a look at the Symfony2 requirements to install Myddleware : http://symfony.com/doc/2.8/reference/requirements.html

Myddleware uses Doctrine so you will need to have the PDO driver installed for the database server you intend using.

Make sure that only_full_group_by isn’t in the MySQL option sql_mode.
"

**Comment by Myddleware** [comment]
Thanks Alexandre for your help.

Sebas82, could you try to refresh boostrap cache with this command : 
`php vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Resources/bin/build_bootstrap.php`

Then try to install again. If it doesn't work, could you try the installation via command. It is an isnatllation step by step so you will be able to tell us in which step you get the error : 
https://myddleware.github.io/myddleware/#/?id=install-myddleware

Hope it will help you.

**Comment by Sebas82** [comment]
Alexandre, I can confirm I respect all the requirements.
Ok, I'm gonna start the installation via command and get back to you with more news.

Thanks!

**Comment by Sebas82** [comment]
Solved! The problem was the installing code was trying to use the OS PHP version (5.3.3), and I've forced to use the PHP 7 version. I saw that in the first check in the command installation.

Thanks for your help!

**Comment by Myddleware** [comment]
Thank you very much for your feedback.
Have a nice day.
