### ISSUE TITLE
is it possible to delete useless document and log lines ?

### ISSUE THREAD

**Issue by Alexandre17220** [Myddleware/myddleware#110]
Hi,
is it possible to delete useless document and log lines ?

My database : 
![image](https://user-images.githubusercontent.com/7665521/44839556-63146c00-ac3f-11e8-9595-1265fb7cdecc.png)

My crontab with cleardata line:
![image](https://user-images.githubusercontent.com/7665521/44839606-850dee80-ac3f-11e8-9e62-f9ef7875d87e.png)

Thanks,

**Comment by Myddleware** [comment]
Hi Alexandre,
The documentation of the clear data job is here : https://myddleware.github.io/myddleware/#/cron_jobs?id=data-clearing
Did you log are older than 7 days and you data older that the expired delay you have set in your rule ?
If yes, could you try to run the job manually without adding > /dev/null 2 >$1 ? You will see in the command windows if there is an error.

Hope it will help you.

**Comment by Alexandre17220** [comment]
60 days configured for all rules,

I think all are ok, but can I delete more log ? and document data ? with edit "deleting data" for All my rule, can I put 7 days ?

no error command : 
 1687 rows deleted in the table DocumentData for the rule Addresses. 2730 rows deleted in the table Log for the rule Addresses. 1918 rows deleted in the table DocumentData for the rule Customers. 3850 rows deleted in the table Log for the rule Customers. 3075 rows deleted in the table DocumentData for the rule Orders. 6360 rows deleted in the table Log for the rule Orders. 56 rows deleted in the table DocumentData for the rule Product categories. 95 rows deleted in the table Log for the rule Product categories. 45 rows deleted in the table DocumentData for the rule Product categories parent. 75 rows deleted in the table Log for the rule Product categories parent. 482626 rows deleted in the table DocumentData for the rule Products. 725619 rows deleted in the table Log for the rule Products. 1893 rows deleted in the table Job.

**Comment by Myddleware** [comment]
Alright,
Yes you can edit your rules and change the number of day. Then you can run again the cleardata program. 

Just let you know that no data will be deleted in the table Documents, Ids are stored there and Myddleware needs it to work properly.

You could change the number of day for log by changing the attribut nbDayClearJob in the class myddleware\src\Myddleware\RegleBundle\Classes\job.php
The best way to do it is to redifine the class Job in the folder Custom
Let me know if you need help.
