### ISSUE TITLE
History pagination error when too much data

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#1102]
Hi, 

We get this error when we have a lot of history document : 
![image](https://github.com/Myddleware/myddleware/assets/11330301/d5893d97-728e-40fd-8d3d-0f0d39bc1d29)

There is no more error if I comment this line : 
https://github.com/Myddleware/myddleware/blob/c57b98c3cb89ee648178d3b4625cbe66fed09e9b/templates/Flux/view/view.html.twig#L574

After adding comment, if I open the document I see a lot of page for history : 
![image](https://github.com/Myddleware/myddleware/assets/11330301/0b29e575-67cd-4436-94ec-cc71dce257c9)

![image](https://github.com/Myddleware/myddleware/assets/11330301/7384342d-61fa-45af-825d-93c7f5aea401)

**Comment by Myddleware** [comment]
I add to also comment this line : https://github.com/Myddleware/myddleware/blob/c57b98c3cb89ee648178d3b4625cbe66fed09e9b/templates/Flux/view/view.html.twig#L490

**Comment by AlexMyddleware** [comment]
@Myddleware  after various fixes for the pagination, i tested with 1000 history docs and got no issue, i think my fixes could have solved this problem

![image](https://github.com/Myddleware/myddleware/assets/106162060/e17c7a11-5e43-4a79-8729-cdb7133a7403)

**Comment by Myddleware** [comment]
Thanks @AlexMyddleware , that's perfect.
