### ISSUE TITLE
Filter labels

### ISSUE THREAD

**Issue by RomanFaure** [Myddleware/myddleware#1105]
On the version 3.3.4a the labels for the actions of the filtrer is wrong 
![Capture d'écran 2023-12-08 110020](https://github.com/Myddleware/myddleware/assets/97444658/61a3713a-b929-43a6-ac2f-2de3be7e7012)
"Another filed" and "Choose another field"

**Comment by Myddleware** [comment]
Display by default : Rule name / Source ID / Target ID / Global status

**Comment by AlexMyddleware** [comment]
![image](https://github.com/Myddleware/myddleware/assets/106162060/3c115c2a-cafe-4649-a06b-65ccf37f5a3e)

**Comment by AlexMyddleware** [comment]
solved in 3.4.0
