### ISSUE TITLE
Connector test connection loading forever

### ISSUE THREAD

**Issue by JiahuiLuData** [Myddleware/myddleware#1112]
Hi team,

I tried to create a new connector, but when I filled in the credentials of SuiteCRM (I have tested the login is correct) and click test, the test runs forever. I tried to test the connectors I already have (they are now correctly running), but they all have the same issue now. I have tried to clear all cache using "php bin/console cache:clear -e background" but in vain. Can you suggest how to fix that?

<img width="380" alt="image" src="https://github.com/Myddleware/myddleware/assets/91266642/d7194d7e-12fa-4521-bd6d-7948e2dfcf24">

Thanks,
Jiahui

**Comment by AlexMyddleware** [comment]
hi @JiahuiLuData , can you give us more detail about your environment ? Is it on your local machine ? do you have some logs ? if it is a local environment, you might want to use xdebug, if you don't know how it works I can explain how to install it.

**Comment by AlexMyddleware** [comment]
also could you please tell us what version of suitecrm and what version of myddleware did you install

**Comment by JiahuiLuData** [comment]
Hi Alex,

It is held on a centos7 Linux server. The version of suitecrm is Version 7.12.14 and the myddleware is version 3.2.0a. I have the var/log/prod.log said:

[2024-01-31 00:56:29] php.INFO: User Deprecated: Since api-platform/core 2.7: Use "ApiPlatform\Metadata\Resource\Factory\ResourceMetadataCollectionFactoryInterface" instead of "ApiPlatform\Core\Metadata\Resource\Factory\ResourceMetadataFactoryInterface". {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since api-platform/core 2.7: Use \"ApiPlatform\\Metadata\\Resource\\Factory\\ResourceMetadataCollectionFactoryInterface\" instead of \"ApiPlatform\\Core\\Metadata\\Resource\\Factory\\ResourceMetadataFactoryInterface\". at /home/default/html/myddleware/vendor/symfony/deprecation-contracts/function.php:25)"} []
[2024-01-31 00:56:29] app.ERROR: Please check url [] []
[2024-01-31 00:56:29] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []

Hope the information is useful. Looking forward to hearing back from you!

Jiahui

**Comment by AlexMyddleware** [comment]
if you're ok with editing your code, first of all it's going to be a bit more difficult if you're on a linux server, since we can't use xdebug easily, but you can echo / print / log variables. If you're certain about your credentials, then you need to go to the 
src/Solutions/suitecrm.php to the login function. 
At around line 124 we assign the url used for the connection, and this is where it might go wrong. 

![image](https://github.com/Myddleware/myddleware/assets/106162060/8819f4e8-4006-4abb-b21e-21d0bbc3e141)
You can print / log the variable $this->paramConnexion['url'] and if it looks correct according to your suitecrm instance, then we move on to the next debugging step but first tell me what you get.

**Comment by Myddleware** [comment]
@JiahuiLuData , could you make a quick test to see if the REST API of your suiteCRM's instance is available.
Could you add this `/service/v4_1/rest.php` at the end of your SuiteCRM root URL. You should have a page like this : 
![image](https://github.com/Myddleware/myddleware/assets/11330301/11ab489e-40d6-4ca2-87dd-ead2ba4ed3c9)

Please let us know what you get. Thanks.

**Comment by JiahuiLuData** [comment]
Hi Alex,

I fixed the problem. It was related to the suitecrm suite guard. Thanks you!

Jiahui

**Comment by Myddleware** [comment]
Perfect @JiahuiLuData . Thanks for your feedback.
