### ISSUE TITLE
Manage crontab menu

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#1114]
We have to remove the old scheduler link in the menu and rename crontab to Scheduler : 
![image](https://github.com/Myddleware/myddleware/assets/11330301/278bdb8e-9fe4-4c14-a6fd-4eb7ed05184c)

**Comment by AlexMyddleware** [comment]
![image](https://github.com/Myddleware/myddleware/assets/106162060/f4f932a2-e4e5-4aca-892d-609cbd3d2548)
