### ISSUE TITLE
Create an alert when a rule is blocked by its limit

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#1118]
Myddleware should alert the admin when a rule is blocked because its limit. When we receive the error : 
`All records read have the same reference date in rule XXXX. Myddleware cannot guarantee that all data will be read. Job interrupted. Please increase the number of data read by changing the limit attribute in job and rule classes.`

**Comment by AlexMyddleware** [comment]
will be closed in 

https://github.com/Myddleware/myddleware/pull/1147

**Comment by AlexMyddleware** [comment]
closed because solution was merged
