### ISSUE TITLE
Crontab view : force several lines if command too long

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#1119]
If the command is too long on crontab view, we should diplay several lines and the command column should,'t be too wide like this : 
![image](https://github.com/Myddleware/myddleware/assets/11330301/356fe995-f4b6-468f-97f7-975d4c7c61af)

**Comment by AlexMyddleware** [comment]
fixed in https://github.com/Myddleware/myddleware/pull/1138
