### ISSUE TITLE
Filter view : align command

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#1120]
The display of the column for the tab view filter should be aligned.

And if we add a filter and if we don't click on the "+" button, then the filter should be save. In the case below, if we don't click on the "+" button the filter on "type_id" isn't saved. 

![image](https://github.com/Myddleware/myddleware/assets/11330301/ef1c6480-7a24-407d-bc79-08f02c755b5c)

**Comment by AlexMyddleware** [comment]
fixed +, now need to align

**Comment by AlexMyddleware** [comment]
fixed with https://github.com/Myddleware/myddleware/pull/1147/commits/4005ba8c2c0782e9bd373cf4e754e584f003cb9c
