### ISSUE TITLE
Cannot create rule template: "kernel.root_dir" must be defined

### ISSUE THREAD

**Issue by JiahuiLuData** [Myddleware/myddleware#1131]
Hi team,

I am creating a new rule template for a new Myddleware instance. I am trying to run the php bin/console myddleware:generateTemplate command but got the following error:

Failed to generate template template1 : Error : The parameter "kernel.root_dir" must be defined. /var/www/html/myddleware/var/cache/background/ContainerVxsxZIf/App_KernelBackgroundContainer.php Line : ( 7632 )

I am in the Versions:

Myddleware=3.3.0b
Ubuntu = 22.04.1
PHP = 8.1.27
Node.js = 20.11.1
Composer = 2.7.1
Yarn = 1.22.22
Symfony = 5.8.12

Could you please suggest what can be the part that we should take a look at?
Thanks,
Jiahui

**Comment by Myddleware** [comment]
Hi @JiahuiLuData , 
We can't reproduce this issue, le template generation work on our side. 
Could you check you have the permission to write into the cache ?
Have a nice day.

**Comment by JiahuiLuData** [comment]
Hi @Myddleware,
I have run chown -R www-data:www-data /var/www/html/myddleware so the permission should be good. And also tried to clear the cache first and run the permission command but still not working. Might that be because of some compatibility issues with my Symfony version or something? Did you try the same system setting as I had above?

Thanks,
Jiahui

**Comment by Myddleware** [comment]
Hi @JiahuiLuData ,
I haven't exactly the same configuration but it is still Myddleware 3.3. 
Could you tell me if other commands works, like synchro command ? I would like toknow if it is a global error or just for template generation.
Thanks.

**Comment by JiahuiLuData** [comment]
Hi @Myddleware,

Thanks for the reply, I have reinstalled the latest Myddleware 3.3.4a and the generate template worked. I am going to close this issue.

**Comment by Myddleware** [comment]
Thanks @JiahuiLuData  for your feedback.
