### ISSUE TITLE
Wrong insert when we double clic on a constant 

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#1139]
When we double clic on a constant, it should insert `"constant"` and not `constant(`
![image](https://github.com/Myddleware/myddleware/assets/11330301/34e210e9-84f5-4c75-89f7-54b12d5af865)

Could you also translate the function.category.constant ?
Thanks.

**Comment by AlexMyddleware** [comment]
@Myddleware I sent you a video, tell me what you think !
