### ISSUE TITLE
Question: Failed Install Process in Azure Environment

### ISSUE THREAD

**Issue by SunDownGroup** [Myddleware/myddleware#114]
Hello,

Getting a timeout when configuring a new myddleware instance in an azure environment connecting to a MySQL server.  Seems to not be able to login to the server as there are no tables being created and there are no errors other than the timeout being reported.

Thanks.

**Comment by Myddleware** [comment]
Hi,
Could you give us more detail about the error : When does it happen ? When you try to login ? When you try to install ? Have you finished the installation ? Do you have Myddleware table in your database ? 
It will help us to help you. Thanks.
Have a nice day.

**Comment by SunDownGroup** [comment]
Resolved the issue.  Had to go through and do it via command line.  The setup wizard kept timing out.
