### ISSUE TITLE
Enhancement Requsest: Cobot Connector

### ISSUE THREAD

**Issue by SunDownGroup** [Myddleware/myddleware#116]
Cobot is an industry leading coworking management system with a very large user base.  There is already and integration with Cobot and Zapier.

API documentation is available at:
https://www.cobot.me/api-docs

**Comment by Myddleware** [comment]
Hi, 
Very interesting. I guess you would like to connect Cobot to Myddleware.

If you are a developper we can help you to develop it. To start, here is a tutorial to guide you : https://myddleware.github.io/myddleware/#/dev_guide
Then we will definitely help you if you decide to develop it by yourself, please let us know.

However, if you want we develop it for you before, please contact us privately via our contact form on our website http://www.myddleware.com.

Thanks.
