### ISSUE TITLE
Send notification when this message appears : "All records read have the same reference date in rule" 

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#1161]
An email should be sent to the admin each time the message "All records read have the same reference date in rule....." is generated.

**Comment by Myddleware** [comment]
Alert too when a rule is locked for too much time.

**Comment by AlexMyddleware** [comment]
@Myddleware  you might want to check these commits

https://github.com/Myddleware/myddleware/commit/b77b7f70bc75b8febd3ead30ff3658c90f797be5
https://github.com/Myddleware/myddleware/commit/e73f5b16bce94647b1990e3a5241649aebe405c6
https://github.com/Myddleware/myddleware/commit/5e12f9621c169559387d166dc0c6ee8ff51efde6

they answer your issue of "all records have the same reference rule". I'll see what i can do about the locked rule

**Comment by AlexMyddleware** [comment]
@LucieMyddleware  we need to identify what has been done and what needs to be done in order to make a nice jira ticket

**Comment by AlexMyddleware** [comment]
@LucieMyddleware  je close car le code est deja mis donc c'est ok

**Comment by AlexMyddleware** [comment]
done
