### ISSUE TITLE
Workflow generate document : wrong field list

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#1197]
We should have only the field of the rule selected when we create or update a workflow action generateDocument : 
![image](https://github.com/user-attachments/assets/09a67ada-3c52-4d47-ad3a-36bea59b9af7)

Maybe it would be easier to pu the rule list before the field list.

**Comment by AlexMyddleware** [comment]
now the field depends on the selected rule, if no rule is selected, then we have no options, and we only have the fields of the selected rule and no other rule

![image](https://github.com/user-attachments/assets/d7dd313e-1e42-4f50-a47a-38474458bad9)

![image](https://github.com/user-attachments/assets/e07739c8-03b2-4005-bf10-e070dca04d12)
