### ISSUE TITLE
Workflow generate document : Set id by default 

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#1198]
The default value for this field should be "id". It should be added in the field list : 
![image](https://github.com/user-attachments/assets/e38d4e7d-4c96-4c47-87c4-082c7156286e)

**Comment by AlexMyddleware** [comment]
added, when we select generate document in the creation of a new action , the value becomes id

![image](https://github.com/user-attachments/assets/9d36dacc-f7c9-42b8-aee0-c9fae694b71f)
