### ISSUE TITLE
Problem with MySQL as a target

### ISSUE THREAD

**Issue by zbyles** [Myddleware/myddleware#1199]
Hi,

I’m trying to establish a connection between Moodle (source) and MySQL (target). I need to export a few pieces of information about courses - name, category, and summary. My Moodle is a university e-learning system with a large number of records (around 2700 courses for now). I successfully generated connectors and a rule, but when I run the rule, only a few records are synchronized. Specifically, I got 5 records during the first run (yesterday). Then I reran the rule several times, and now I have 16 records. Is this normal, or could I have missed something in the configuration?

I wanted to test the configuration on the same Myddleware installation but using a different Moodle (with a much smaller dataset – only about 20 courses) and a different database. In this case, connectors were generated successfully, and the “simple simulation” during rule creation was OK. However, when I start the rule, I get nothing - the document list is empty.

Here are the details of my systems:
First case:
Server: Ubuntu Server with Apache2, MariaDB v.15.1, and PHP 8.1.
Moodle version: 3.3+ on another server (same local network).
Database: Connection with the database is on localhost.

Second case:
Same Myddleware installation.
Moodle version: 3.4+ on another server and another database (MariaDB 15.1) – both on an external network.

In both cases, I see a few errors and warnings in the application logs (attached). However, there are no errors in the database logs on either server. Additionally, the Apache2 error logs contain the following recurring entries:

Array\n(\n    [champs] => Myddleware_element_id[=]id;kategoria%20kursu[=]categoryid;nazwa%20kursu[=]fullname;opis%20kursu[=]summary;\n    [formules] => \n    [params] => Array\n        (\n            [0] => Array\n                (\n                    [name] => targetFieldId\n                    [value] => nazwa%20kursu\n                )\n\n            [1] => Array\n                (\n                    [name] => mode\n                    [value] => 0\n                )\n\n            [2] => Array\n                (\n                    [name] => regleId\n                    [value] => 0\n                )\n\n        )\n\n)\n, referer: https://ankiety.ujd.edu.pl/connect/public/rule/create/step3

WARNING   [php] Warning: Undefined array key "categoryname" ["exception" => ErrorException { …}]

Could this be related to the issue? Any suggestions on what might be going wrong, or areas I should investigate further?

Best regards,
Zbyszek

[prod.log](https://github.com/user-attachments/files/17160807/prod.log)

**Comment by Myddleware** [comment]
Hi @zbyles ,
Thanks for using Myddleware. 
You should probabkly change the reference date of your rule to force Myddleware to read data from the past. Here is more info about the rule parameters.
https://myddleware.github.io/myddleware/#/basic_usage?id=rule-parameters 

Please let me know if it helps.

**Comment by zbyles** [comment]
Yes... Sorry - it was so simply and I've just missed this setting. Now it works as axpected
And talking about errors in my logs - since everything is working I don't have to worry about them?
Greetings
Zbyszek

**Comment by Myddleware** [comment]
Great. 
About the second issue, difficult to say without access to your Myddleware 's instance. 
Let's try ;). 
Could you tell me if you have mapped the field categoryname, if yes could you show me a screenshop of your mapping ? 
Thanks.

**Comment by zbyles** [comment]
Yes - I've mapped categoryname, but it is always empty. Every course in our Moodle is in category and no matter what course I choose - I always have categoryname empty. I'm sending screen from simple simulation. Fields colours and summary in this case should be empty - it is OK. But this course has a category

<img width="1397" alt="Zrzut ekranu 2024-09-27 o 11 15 37" src="https://github.com/user-attachments/assets/74db882a-d548-43e6-9193-59cb97bf1d7c">

**Comment by Myddleware** [comment]
Thanks @zbyles . 
We will try to reproduce and fix it if we have the same error. 
We 'll keep you posted.

**Comment by zbyles** [comment]
Hi
Any progress/suggestions on this issue?

**Comment by Myddleware** [comment]
Hi @zbyles ,
It is a very busy time as we prepare a new main Myddleware version that will be launched in a few weeks.
I will do my best to manage it next week.
I 'll keep you posted.

**Comment by zbyles** [comment]
Hi,
Thank you for the update. Perhaps the upcoming version will resolve this issue, which would save the need for further adjustments in the current one. Looking forward to hearing more soon.

**Comment by Myddleware** [comment]
Hi @zbyles , 
The field categoryname isn't returned by the webservice core_course_get_courses, only the field categoryid. It is the reason why Myddleware can't returned it. Sorry it is a mistake on our part, the field categoryname shouldn't be in Myddleware for the module course. We will remove it.
So you can only use the field catagoryid. 
Please contact us directly if you want us to do a specific development for this field.

**Comment by AlexMyddleware** [comment]
removed category name in metadata for the course module, will be in 3.4.0a

https://github.com/Myddleware/myddleware/commit/c37cdcaa015e023c8863acb882f20967c7ba9c04

@zbyles if you want to get the issue fixed immediately, you can reproduce the commit above in your environment.
