### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by IANCROCKER1967** [Myddleware/myddleware#121]
Hi 

I am Trying install on my server and receive the following error when trying to finalise install.

Many thanks

[ERROR] 
Failed: The command "php /var/www/vhosts/plaskettnutritioncollege.com/httpdocs/myddleware/app/../vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Resources/bin/build_bootstrap.php" failed. Exit Code: 255(Unknown error) Working directory: /var/www/vhosts/plaskettnutritioncollege.com/httpdocs/myddleware/web Output: ================ Error Output: ================ PHP Parse error: syntax error, unexpected '[' in /var/www/vhosts/plaskettnutritioncollege.com/httpdocs/myddleware/vendor/illuminate/support/helpers.php on line 346

**Comment by Myddleware** [comment]
Hi, 
Thanks for you interest in Myddleware. 

Could you try to install Myddleware via command by following this tutorial : https://myddleware.github.io/myddleware/#/?id=install-myddleware

Please let us know if you could install Myddleware. Thanks.
Stéphane
