### ISSUE TITLE
Failed to run the task

### ISSUE THREAD

**Issue by Raks-simple** [Myddleware/myddleware#1218]
Description:
I am creating rules to get my Facebook forms in Vtiger

Steps to reproduce:
1. When I click on any option to avoid duplicate registrations, I get a notice telling me to fill out mandatory fields.
2. If I don't select any restrictions to avoid duplicates, it lets me save the rule.
3. Once the rule is saved, I click on Rule de rule and I get the error "Failed to run the task".
4. I have already reviewed all the fields and I don't see any errors.
5. I checked the hidden fields in the system to see if any of them were required at the time but none of them are or were required.
6. I couldn't find the fault.

Expected behavior:
That can run the rule and get the records in the Vtiger Contacts module. I hope you can tell me what could be happening and how to fix it. I hadn't had a problem with other accounts.

Actual behavior:
I get the error "Failed to run the task"

![image](https://github.com/user-attachments/assets/34e9d382-c261-4c70-8ba7-8cc2f29f7c02)

Setup Information:
Myddleware v2.5.5
Vtiger 7.4

Additional context
Attach images

1. When I click on any option to avoid duplicate registrations, I get a notice telling me to fill out mandatory fields.

![image](https://github.com/user-attachments/assets/6d12663e-10b3-4169-90dc-f5d811417166)

2. If I don't select any restrictions to avoid duplicates, it lets me save the rule.

![image](https://github.com/user-attachments/assets/358b95f2-9571-4b77-881b-366a67e6af92)

3. Correct simulation

![image](https://github.com/user-attachments/assets/78791fff-3d2b-4d34-83f4-1254b6862c21)

4. Variables

![image](https://github.com/user-attachments/assets/e14b5978-4ef2-46d1-8469-1fa5184b44e4)

5. Mapping:

![image](https://github.com/user-attachments/assets/49849627-678a-4cb2-a696-7bc4d2b6d1cf)

**Comment by rulotec** [comment]
Just to complete the report of my colleague, we are using myddleware 2.5.5 (as far as we know the facebook connector was deprecated and that's why we don't use the last version).

How can we get more debug information about what the error is?

**Comment by rulotec** [comment]
Ok, we got to the point where we found  out that the error happens in `src/Myddleware/RegleBundle/Classes/rule.php` on line 947

![image](https://github.com/user-attachments/assets/737bef7a-4fd8-4af6-9bc2-a342860d9653)

If we run the the command on line 941 directly from the command line:

`php /var/www/html/myddleware/src/Myddleware/RegleBundle/Classes/../../../../bin/console myddleware:synchro ALL --env=prod > /var/www/html/myddleware/var/cache/prod/myddleware/job/6721263ee9b5f.txt &`

![image](https://github.com/user-attachments/assets/a02fc490-04f0-4573-a943-1e0605aac962)

the transfers actually work. why is it not working when the command gets executed by the php script?

**Comment by Myddleware** [comment]
Hi @rulotec ,
Thanks for you investigations. 
Could you check if your web user has the right to write in the <myddleware root>var/cache/prod directory. If yes, could you also check the directory <myddleware root>var/cache/prod/myddleware ?
Thanks.

**Comment by rulotec** [comment]
So, the problem was that the "exec" function was disabled in `php.ini`. I didn't think that could be the case because I erroneously thought that a fatal error would occur. However php (7.4 in this case) only issues a warning message (which was not visible due to php configurration) and exec returns "null".

**Comment by rulotec** [comment]
I don't know what the current version of myddleware does, but it would be nice to have something that checks `exec` is not disabled and make the error more explicit.

**Comment by Myddleware** [comment]
Hi @rulotec,
That's a great idea. 
@AlexMyddleware , could you check if we can easily add an exception if exec command (executed in ruleManager class) is disabled ? 
Thanks.

**Comment by AlexMyddleware** [comment]
added an exception for the exec

https://github.com/Myddleware/myddleware/commit/d743229655f311da3eaed227ff9d9cb18b9bc186

![image](https://github.com/user-attachments/assets/04988ccd-6f44-4bfe-bfa0-cfb1bcf51ddf)
I tested it by adding the exec to disable_functions in php.ini, @rulotec I supposed that is how you did it as well ?

![image](https://github.com/user-attachments/assets/aa2e7460-f029-4d86-a5cd-ee68388df98a)

@rulotec it will be in the next release but if you want to get the changes immediately for your own environment feel free to copy-paste the code in the commit above.

**Comment by rulotec** [comment]
I'd love to get the latest version. But as far as I know, there is no facebook connector anymore. Thats why we use 2.5

**Comment by Myddleware** [comment]
Yes you are right. We will probably make it compatible to the latest version this year. However, we develop first what our client needs. I hope you understand.

**Comment by rulotec** [comment]
I totally understand! We use the same approach ;)
