### ISSUE TITLE
Salesforce-Moodle fields mapping not working

### ISSUE THREAD

**Issue by dagleich** [Myddleware/myddleware#124]
Hi there,

I have an issue with the fields mapping between Salesforce and Moodle.
When I try to map fields between whatever Modules are available in the Rule creation menu, it breaks down with the error message: "Alerte: Source module connection error":
![salesforce-moodle-myddleware_issue](https://user-images.githubusercontent.com/25120276/47169214-36a5d380-d303-11e8-9ffc-a0c514600993.png)
In the file "./myddleware/var/logs/prod.log" it only says "[2018-10-18 17:53:07] app.ERROR: Error unknown.  [] []".
Setting up the Moodle and Salesforce connectors worked great.
Did I miss something during the installation?

Thanks,
Daniel

**Comment by Myddleware** [comment]
Hi Daniel,
Could you test each connectors : Salesforce and Moodle in the connector editview ? Does the test successuf for both connectors ? If yes could you save them and try to create a rule again ?

Could you give us your Myddleware version (you can find it in the footer) ? Thanks.
  
We will have a look to this error message, it should have more information ;)
Best regards,
Stéphane

**Comment by dagleich** [comment]
Hi Stéphane,
Yes, I tested each connector in the editview again and each test was successful:
![salesforce_connector-success](https://user-images.githubusercontent.com/25120276/47199473-119c7980-d372-11e8-90ef-29ecc93f81e7.png)
![moodle_connector-success](https://user-images.githubusercontent.com/25120276/47199585-8ff91b80-d372-11e8-81ad-70ec32419567.png)
Afterwards, I tried again to create a rule and got the same error.
I have version 2.4.0d installed, the version that was automatically downloaded after filling out the form at http://www.myddleware.com/solution/download.
Thanks for looking into that.
Daniel

**Comment by Myddleware** [comment]
Hi Daniel,
We have created a rule between Salesforce and Moodle and everything work well on our Myddleware.

We have fixed the message displayed on Myddleware, it should give more information now. However, we will lauch the version with this fix only next week (monday or tuesday depending on the test result).
If you want this fix before, you can download and replace this file on your Myddleware : https://github.com/Myddleware/myddleware/blob/Release-2.4.1/src/Myddleware/RegleBundle/Controller/DefaultController.php

Once you have this new file, can you test again and tell us what is the error message ? Thanks.
Have a nice day,
Stéphane

**Comment by dagleich** [comment]
Hi Stéphane,
I replaced the file _DefaultController.php_ and got now the following message for the exact same scenario as before:

>  Alerte: Target module connection error Error unknown. 

The logfile _prod.log_ reports the same message as before:

> [2018-10-19 14:06:29] app.ERROR: Error unknown.  [] [] 

Is there anything else I could try?
Thanks,
Daniel

**Comment by Myddleware** [comment]
Hi Daniel,
So we know now that the problem doesn't come from Salesforce but it comes from Moodle (target module). 
The error come from the Moodle function login called from the default controller line 1291. 
Could you debug with us ? If yes could you add this in the line 54 of Moodle file (<myddleware_root>\src\Myddleware\RegleBundle\Solutions\moodle.php)  :
`$this->logger->error('DEBUG : '.print_r($response,true));`

You should have this :  
![image](https://user-images.githubusercontent.com/11330301/47218438-bf5f5680-d379-11e8-80f8-1ad1b2e56258.png)

Then could you have a look to your log, you should have 2 lines (1 for the connection when you select your connector et one when you validate the rule). I have this : 
![image](https://user-images.githubusercontent.com/11330301/47218577-43194300-d37a-11e8-916a-beadde47630c.png)

Could you show us what you have ? 
Thanks.
Stéphane

**Comment by dagleich** [comment]
Hi Stephane,
here is what the log says:
![myddleware_logfile](https://user-images.githubusercontent.com/25120276/47221848-c0ae7480-d3b5-11e8-9a81-ddc166ec6006.png)
Is something wrong with the Moodle installation?
Thanks,
Daniel

**Comment by dagleich** [comment]
By the way, the URL to my Moodle server looks like this: https://moodle.MYDOMAINNAME.de

**Comment by Myddleware** [comment]
Hum, it seems that your Myddleware isn't really connected to Moodle. 

You could make a test to see if your token is valid. PLease copy this URL and change the url and the token:  
YOU_MOODLE_URL/webservice/rest/server.php?wstoken=YOUR_TOKEN&wsfunction=core_webservice_get_site_info&moodlewsrestformat=json  

Do you get a result like : 
{"sitename":"Myddleware","username":"myddleware","firstname":"Myddleware","lastname":"Myddleware","fullname":"Myddleware Myddleware","lang":"en","userid":4,"site[...............................................]usermaxuploadfilesize":134217728}

Thanks.
Stéphane

**Comment by dagleich** [comment]
Hi Stéphane,
yes, that works fine. I got the following result:
`{"sitename":"Moodle - Daniel Gleich","username":"MYUSERNAME","firstname":"Daniel","lastname":"Gleich","fullname":"Daniel Gleich","lang":"de","userid":3,"siteurl":"https:\/\/moodle.MYDOMAINNAME.de","userpictureurl":"https:\/\/moodle.MYDOMAINNAME.de\/pluginfile.php\/1304\/user\/icon\/adaptable\/f1?rev=9423","functions":[{"name":"core_course_create_courses","version":"2018051700"},{"name":"core_course_get_categories","version":"2018051700"},{"name":"core_group_add_group_members","version":"2018051700"},{"name":"core_group_create_groups","version":"2018051700"},{"name":"core_user_create_users","version":"2018051700"},{"name":"core_user_get_users","version":"2018051700"},{"name":"core_user_update_users","version":"2018051700"},{"name":"core_webservice_get_site_info","version":"2018051700"},{"name":"enrol_manual_enrol_users","version":"2018051400"},{"name":"enrol_manual_unenrol_users","version":"2018051400"},{"name":"local_myddleware_get_users_completion","version":"2016111800"},{"name":"local_myddleware_get_users_last_access","version":"2016111800"}],"downloadfiles":0,"uploadfiles":0,"release":"3.5 (Build: 20180517)","version":"2018051700","mobilecssurl":"","advancedfeatures":[{"name":"usecomments","value":1},{"name":"usetags","value":1},{"name":"enablenotes","value":1},{"name":"messaging","value":1},{"name":"enableblogs","value":1},{"name":"enablecompletion","value":1},{"name":"enablebadges","value":1},{"name":"mnet_dispatcher_mode","value":0}],"usercanmanageownfiles":true,"userquota":0,"usermaxuploadfilesize":-1,"userhomepage":1,"siteid":1,"sitecalendartype":"gregorian","usercalendartype":"gregorian"}`

Thanks,
Daniel

**Comment by Myddleware** [comment]
Hi Daniel,
So the token is valid, thanks.  There is a bug but we can't reproduce it and we would definitely fix it.

If you don't mind, could you contact us directly via this page http://www.myddleware.com/contact-us and we will see how we can organize en debug together. Thanks.

Have a nice day
Stéphane

**Comment by Myddleware** [comment]
Hi Daniel,
It seems that we have a bug on the Mailchimp connector as we could have space added after the token. in the URL We wil check the controller.
But by adding trim function here, it should work : 
![image](https://user-images.githubusercontent.com/11330301/47323305-4128db80-d629-11e8-9eef-bbf526c49a82.png)

Could you check if it works ? 
Thanks.

Stéphane

**Comment by dagleich** [comment]
Dear Stéphane,
yes, now it works wonderfully.
Thank you so much!
Daniel
