### ISSUE TITLE
Transfering new user from Salesforce to Moodle

### ISSUE THREAD

**Issue by dagleich** [Myddleware/myddleware#127]
Hi,

I'm trying to transfer a contact from Salesforce to Moodle, where the data should be used to create a new user. I created an additional field in Salesforce for the custom Moodle username. In a first attempt, I also created a custom field for the Moodle to transfer this from Salesforce to Moodle as well. When that transfer failed, I thought it might be connected to the password. So I decided to let Moodle create a password. My rule then looked like this:
![myddleware_rule](https://user-images.githubusercontent.com/25120276/47376436-e360c600-d6f2-11e8-9ef3-cf57b4cbad7f.png)
However, I always get the following error:
![myddleware_transfererror](https://user-images.githubusercontent.com/25120276/47376561-39356e00-d6f3-11e8-8b53-cb1d52170706.png)
Creating this Moodle user with only this information manually on the Moodle platform works without any problems.
Did I miss anything when creating the rule?
Thanks,
Daniel

**Comment by Myddleware** [comment]
Hi Daniel,

Sorry, this is the same erro than issue #124 . You have a space on the token for creation. The bug will be fixe for the next release (v2.4.1). You can find the file here : https://github.com/Myddleware/myddleware/blob/release-2.4.1/src/Myddleware/RegleBundle/Solutions/moodle.php

Have a nice day
Stéphane

**Comment by dagleich** [comment]
Hi Stéphane,
thank you so much.
Now it works like a charm.
Daniel
