### ISSUE TITLE
Passing an Array to the Formula field

### ISSUE THREAD

**Issue by codrotech** [Myddleware/myddleware#131]
Is it possible to pass an Array or Dictionary Array or json to the formula to a submodule field?

Thanks

**Comment by Myddleware** [comment]
Hi Codrotech,
We could add a function like json_encode or json_decode in the formula popup : 
![image](https://user-images.githubusercontent.com/11330301/48583382-5a0d6f80-e8fd-11e8-9c58-6dcb36ffbdd1.png)

 However could you give us more detail about what you would like to do ? 
Thanks.

**Comment by codrotech** [comment]
Thanks for your answer.

I'm trying to sync PrestaShop with ERPNext (Target) using : 
Module : product (Presta) and Module Item (ErpNext)
Item Module form Erpnext as a Field Attributes which take a json dictionary as below:
{
	"item_code": "TNT-TEST3",
	"item_name": "TNT NAME",
	"item_group": "Generic",
	"has_variants": 1,
	"attributes": [{
		"attribute": "Colour"
	}, {
		"attribute": "Size"
	}]
}

This POST Method creates an Item which has two variants.
With mydlleware rule I can pass all field but 'attributes' 

Thanks
Maurizio

**Comment by chdecultot** [comment]
Hi @codrotech,

You need to create a main rule and a child rule linked to this main rule.

Your main rule could look like:
![image](https://user-images.githubusercontent.com/4903591/48659410-d369a700-ea50-11e8-9c13-931d3a5335c8.png)


Then you link the two using the "Relations" module of Myddleware:
![image](https://user-images.githubusercontent.com/4903591/48659384-5dfdd680-ea50-11e8-8c7b-b53cf93b0ca7.png)


Just be aware that with ERPNext you will need to create two separate rules: one for item templates and one for item variants.

**Comment by codrotech** [comment]
Hello,

has_variants take 1 or 0 as a BIT type,   and "attributes" field takes the list or dictionary , when you do POST Methods ( Creating an item template )  it takes care of creating "Item Variant Attributes" Record.
