### ISSUE TITLE
Is ERPNext v10 supported?

### ISSUE THREAD

**Issue by backendoadmin** [Myddleware/myddleware#132]
Helo,

first of all thank you for your effort, myddleware is awsome. 

I have a mysql based website on www and we installed myddleware to an another subdomain. And we also have an ERPNext v10 on a different machine. When I try to create connection the bulb is yellow, not greet. I'd like to know myddleware supports ERPNext v10 or you developed for the upcoming v11 version only?

thank you for your help

**Comment by Myddleware** [comment]
Hi Muvuk,

Sorry for the delay of my answer. I confirm that Myddleware is compatible withe ERPNext v10 and v11. So you should be able to connect to your ERPNext.

Please can you give us more detail about the error your get, a screenshot would be perfect ? Thanks.

Best regards,
Stéphane

**Comment by backendoadmin** [comment]
Dear Stéphane,

Sorry for the delay, I wanted  new setup before I answer. So right now we have a Myddleware setup at a webhosting provider (without ssh access) And we have a freshly installed v11 ERPNext on a different VPS. 

(we removed our v10 config)

but we still cannot connet to ERPNext from Myddleware. 

There is no error messages, but the light bulb isnt green. 

you can see here:
https://prnt.sc/lp1u65

Do you have any idea? Thank you

**Comment by Myddleware** [comment]
Hi Muvuk,

Maybe I didn't understand you problem because I see the green light on your screenshot.  

Does the problem happen when you click on "test" or when you click on "Save the connection" ? 

Best regards,
Stéphane

**Comment by backendoadmin** [comment]
Light bulb is yellow/gold not green, but maybe it's also good. 

The problem is, when I make another test or save (with password) on this screen, it shows there is a problem for a short time. And then disappear that error message. 

https://prnt.sc/lp4emo

**Comment by Myddleware** [comment]
Ho Sorry Muvuk,
We have forgotten you. Could you tell me if the connector you use has been edited. To be sure could you try by creating a new one.
I say that because we have a bug with the connector modification (cot creation) in version 2.4.1. It will be fixed in version 2.4.2.
