### ISSUE TITLE
Invalid Parameter Error sending

### ISSUE THREAD

**Issue by Musong1** [Myddleware/myddleware#134]
Hi,
I try to connect SuteCrm With Moodle. 
I got an error when transfering. Error says "Invalid parameter: a wrong value for a parameter has detected. The transfer could not continue. Faled to send document. Status: Error_sending
What am I doing wrong?
![pic 1](https://user-images.githubusercontent.com/31029891/49796998-78b92780-fd3e-11e8-9a81-ad30214c113d.png)
![pic 2](https://user-images.githubusercontent.com/31029891/49797030-8ff81500-fd3e-11e8-9e44-c26707a99d81.png)
![pic 3](https://user-images.githubusercontent.com/31029891/49797952-465cf980-fd41-11e8-8075-ca732bf695f3.JPG)

**Comment by Myddleware** [comment]
Hi,
Could you have a look to this topic and see if it fixes your problem, my first answer should help you : https://github.com/Myddleware/myddleware/issues/60

For example, I see on your data transfer that you didn't set any password. Your problem could come from there. 
 
Best regards

**Comment by Musong1** [comment]
Hi,
Thanks for quick answer:-)
I new to this so I might ask dum questions. But do you mean that I should map like this. I use mail as many parameters. So Moodle will create user and password from email.

Br 
Hans
![pic4](https://user-images.githubusercontent.com/31029891/49809366-03118380-fd5f-11e8-9d86-812f7cc2231c.JPG)

**Comment by Myddleware** [comment]
Hi,
I don't know if the email is a valid password regaring your Moodle configuration.
But could you just try to create a user manually in Moodle with the data you want to send using Myddleware. You will see if the data you send are correct. Then you can delete the user in Moodle and try to create it using Myddleware. 
I hope I am clear.

Have a nice day,
Stéphane

**Comment by Musong1** [comment]
Hi,
I did as you told me. But no luck. Still same error.
I try to do reverse and sync moodle to suite. It is suppose just to be 2 records to be able to get. Or is it something wrong with the moodle settings? se pic

Br 
Hans
![pic 4](https://user-images.githubusercontent.com/31029891/49929420-c2327f80-fec2-11e8-91ce-bdf98a5a5892.JPG)

**Comment by Myddleware** [comment]
Hi Hans,
Sorry, you can't do reverse as Myddleware can read only completion and last access data from Moodle. We are thinking about improving Moodle connector but it is not easy as Moodle API is made more for mobile app than synchronization tool.
Here is what Myddleware can do today : http://www.myddleware.com/solution/connected-applications?view=project&id=14:moodle

But we would be really happy to help you to create a user to Moodle via Myddleware.
Could you give us an example of data you want to send to Moodle and we will try in our side. 

Thanks.

**Comment by Musong1** [comment]
Hi,
I see, no problem, I am glad that you thinking of it:-)
I want to send for a start.
Firstname. lastname, email, username, password, Suite contactID to be Moodle userID. 
That would be great!
Thanks for outstanding service.

Br
Hans

**Comment by Myddleware** [comment]
Hi,
OK, do not send contact_id in user_id. The Moodle user ID will be generated automatically and Myddleware will keep the correspondance between the contact_ID and the user_IDs if you want to send other data linked to the user.
Could you change your field mapping by removing the contact_id ? 

Please let us know if it works. Thanks.
Stéphane
