### ISSUE TITLE
Unable to Create a Rule for MYSQL Source

### ISSUE THREAD

**Issue by jbdot** [Myddleware/myddleware#135]
Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\myddleware\src\Myddleware\RegleBundle\Form\ConnectorType.php on line 26

Notice: Undefined index: solution in C:\xampp\htdocs\myddleware\src\Myddleware\RegleBundle\Service\SessionService.php on line 59

Warning: in_array() expects parameter 2 to be array, null given in C:\xampp\htdocs\myddleware\src\Myddleware\RegleBundle\Controller\ConnectorController.php on line 349
Oops! An Error Occurred
The server returned a "500 Internal Server Error".

**Comment by Myddleware** [comment]
Hi,
Could you show us how and when this error happens ? Some screenshots would be wonderful.
Thanks.

**Comment by jbdot** [comment]
Error happens when i try to simulate my transfer, as well as running a rule

**Comment by Myddleware** [comment]
OK, we will need more detail about the 500 internal Server error. 

Could you have a look to the error in the log (myddleware/var/logs/prod.log) or just use the dev environment which will give you the error detail. To use the dev environment, please change app.php to app_dev.php in your url. 

Then could you give me the error detail ? 
Thanks.

**Comment by jbdot** [comment]
This happens on PHP 7.2

**Comment by Myddleware** [comment]
Hi,
I don't think that you problem comes from php 7.2 as we have a lot of Myddleware running on php 7.2.
Could you give me the error detail ?
Thanks.
