### ISSUE TITLE
ERPNext v12 - Failed to get the field list

### ISSUE THREAD

**Issue by tkapias** [Myddleware/myddleware#136]
Thank you very much for this tool, I am currently trying to use it for the first time and I spend 2 days on this problem : 

Context : Trying to connect Prestashop en ERPNext.

ERPNext is behind Nginx with an Administrator user account.
- ERPNext: v12.x.x-develop () (develop)
- Frappe Framework: v12.x.x-develop () (develop)

I can add the connector but when I create a rule the field for ERPNext side is empty and gray. Myddleware logs say this : 

`[2018-12-12 15:46:14] app.ERROR: No data in the module Customer Group. Failed to get the field list. /var/www/myddleware/src/Myddleware/RegleBundle/Solutions/erpnext.php 186 [] []`

In Nginx I see the GET : 

`xxx.xxx.xxx.xxx - - [12/Dec/2018:15:46:14 +0700] "GET //api/method/frappe.client.get_list?doctype=DocField&parent=Customer%20Group&fields=*&filters={%22parent%22:%22Customer%20Group%22}&limit_page_length=500 HTTP/1.1" 403 7406 "-" "-" "-" "erpnext.xxx.xxx" sn="erpnext.xxx.xxxx" rt=0.650 ua="127.0.0.1:8000" us="403" ut="0.652" ul="7406" cs=-`

I don't see permission errors in ERPnext. Do you have an idea ?

**Comment by Myddleware** [comment]
Hi tkapias,
Thank you for your interest in Myddleware. 

Do you have empty fields for all the modules or just "Customer group" ? 
I have tried in our ERPnext and we get all the fields for Customer group module : 
![image](https://user-images.githubusercontent.com/11330301/49896610-2e14d980-fe2a-11e8-8dce-d5395065fea1.png)

However, I see that you use the API v12, but for now, Myddleware is only compatible V10 and V11, we haven't test Myddleware in V12 yet. Could you try with ERP API v11 ?

Thanks.

**Comment by tkapias** [comment]
It's the same for every other modules that I tried.

I'll install a v11 somewhere else and I'll tell you.

**Comment by Myddleware** [comment]
Yes please, let us know. Thanks.

**Comment by dawoodjee** [comment]
You have to enable developer mode in ERPNext then Edit the DocType. Customising the DocType doesnt cut it.

**Comment by Myddleware** [comment]
Bug fixed in version 2.5.0 #226

**Comment by sezanzeb** [comment]
> You have to enable developer mode in ERPNext then Edit the DocType. Customising the DocType doesnt cut it.

Beware that this may cause problems when upgrading erpnext afaik, since it would change the contents of the frappe/erpnext app directories and theremore might cause merge conflicts when pulling in a new version.
