### ISSUE TITLE
Cancel child document when parent is cancelled

### ISSUE THREAD

**Issue by chdecultot** [Myddleware/myddleware#137]
Hi,

Currently when a parent document is manually cancelled, its child documents stay open.

It would be nice if these child documents could be automatically cancelled as well.

Thank you!

**Comment by Myddleware** [comment]
Hi chdecultot,
You are right. We will develop this in the next release (v2.4.2).
Thanks for you feedback.

**Comment by Myddleware** [comment]
Fixed in Myddleware 2.5.0 #226
