### ISSUE TITLE
Prestashop Modules Not Available (Fixed) | HTTP status of 500 (Fixed) | not getting to the mapping page

### ISSUE THREAD

**Issue by Khaled4** [Myddleware/myddleware#138]
Greetings. I have to congratulate you on an amazing product. It looks amazing. Well done.
However, I need your help in solving an issue I have with the Prestashop connector. None of the Modules display even though I selected everything I possibly can when configuring the Prestashop webservice.
See the image please

![myddleware ecommerce crm integration fail](https://user-images.githubusercontent.com/15167986/50069891-72ff8e00-01e5-11e9-83c8-0ef649eac659.jpg)

Further, when I confirm the rule, I get the following error that customer module is not available?
See the image please:

![myddleware ecommerce ecampus integration fail](https://user-images.githubusercontent.com/15167986/50070082-21a3ce80-01e6-11e9-997c-a8e54d5322c5.jpg)

Note that I am able to see all configured modules in SuiteCRM and in MOODLE but not Prestashop.
My prestashop is version 1.6 and I have not enabled the CGI mode for PHP as in your tutorial I noticed that you kept it off.

**Comment by Khaled4** [comment]
OK, I gave it a shot and tried with the CGI mode for PHP enabled and now I have all the modules to choose from. I wanted to experiment first so I chose your default template which had 4 rules defined.
I enabled all 4 and now I have this on each of them:

Error : Call failed This call to PrestaShop Web Services failed and returned an HTTP status of 500. That means: Internal Server Error. /app/src/Myddleware/RegleBundle/Solutions/prestashop.php Line : ( 742 )Error : Call failed

Further on checking the error log file I found this:
[17-Dec-2018 10:40:15] [PHP Warning #2] preg_match(): Compilation failed: invalid range in character class at offset 10 (/public_html/.../classes/webservice/WebserviceRequest.php, line 1635)

Help!!

**Comment by Khaled4** [comment]
I enabled Dev mode and now I do not get any error but I am not able to go to the mapping page.
This is what the progress showed me on the other tab:

![myddleware ecommerce ecampus integration fail 2](https://user-images.githubusercontent.com/15167986/50086547-de158880-0216-11e9-8884-36775694c2b1.jpg)

**Comment by Myddleware** [comment]
Hi Khaled,
Thank for all your messages. I see that you could manage the main part of your problems. 
The dev mode don't use cache so maybe you problem with the production mode is the cahce. Could you clear it by removing the director var/cache/prod

About you mappinh page error, could you show me which error do you get ? Thanks.

**Comment by Khaled4** [comment]
Thank you for your response. I am not getting an error! But the flow just stops. Nothing happens further.
I am testing the connectors on your cloud.
But on my Prestashop, where do I remove the director var/cache/prod from?

**Comment by Myddleware** [comment]
Thanks.
Sorry I wasn't clear, I spoke about Myddleware cache, so it is in myddleware/cache/prod.
Have a nice day.

**Comment by Khaled4** [comment]
But where is  myddleware/cache/prod ? 
One more thing, Has the php version got anything to do with it?
I am using PHP5.2 for Prestashop but PHP7.1 for MOODLE

**Comment by Myddleware** [comment]
Oups myddleware/var/cache/prod
No worry for the php version of your other application, there is no link with Myddleware configuration.

**Comment by Khaled4** [comment]
Yes, but how do I reach this location myddleware/var/cache/prod ? I do not have access!

**Comment by Myddleware** [comment]
Alright, 
You are maybe on the Cloud ? If yes you don't have to refresh the cache, no worries. I was thinking you spoke about your local installation.

**Comment by Khaled4** [comment]
I am testing the connectors on your cloud.
So what do you think is the solution?
Where am I going wrong?
and must I put back the Dev mod to False?

**Comment by Myddleware** [comment]
Sorry, I don't really follow you now.
So you are using Myddleware in the Cloud if I am right. Could you tell me what error you have ? If this error isn't linked to this issue "Prestashop Modules Not Available (Fixed) | HTTP status of 500 (Fixed) | not getting to the mapping page", could you close this issue and create a new one ? Thanks.

**Comment by Khaled4** [comment]
It is related to "not getting to the mapping page"

**Comment by Myddleware** [comment]
Sorry, I have mixed 2 issues in my head ;(
Could you give me the URL of your Myddleware cloud instance with the new password if you have changed it ? Could you send it by direct message via our contact page : http://www.myddleware.com/contact-us

Thanks, then I will have a look in your Myddleware instance. Thanks.

**Comment by Myddleware** [comment]
Hi Khaleb, 

I can access to the mapping page : 
![image](https://user-images.githubusercontent.com/11330301/50110986-08187c00-0212-11e9-8160-28466147a50d.png)

To reach this page, you can open a rule and click on "Edit the rule".

Please let me know if I didn't understand your problem.
