### ISSUE TITLE
Issue creating connector to Sage CRM

### ISSUE THREAD

**Issue by mikedbcomp** [Myddleware/myddleware#139]
I downloaded and installed a copy of your software to test integrating Moodle and Sage CRM.
I have successfully linked to Moodle and have followed your help guide on how to connect to Sage CRM however when I click Test on the connector is just sits there and looks like it is constantly trying to connect.

FYI - your instructions are for the Cloud based version of Sage CRM whereas I am using a locally installed copy of SageCRM - the SOAP web services in both should however be exactly the same.

Was wondering if you could guide me towards any log files that might help me as I can't seem to find any info on log files. I can see a warning in the apache error log when I try to create the connection but other than that I can't find any obvious problem.

**Comment by Myddleware** [comment]
Hi Mike,
Thanks for you interest in Myddleware.

Could you tell me if your wsdl file is copied in the directory : myddleware\src\Myddleware\RegleBundle\Custom\Solutions\sagecrm\wsdl

If not, could you make sure the web server can write in the directory : myddleware\src\Myddleware\RegleBundle\Custom ? If the directory Custom doesn’t exist, could you create it ?

Thanks.

**Comment by mikedbcomp** [comment]
Hi - yes the file does get copied to that folder - I can see mutliple copies of the file in there from each time I tested the connection.

Cheers,
Mike

**Comment by Myddleware** [comment]
Hi Mike,
We can reproduce your error. We will work on it today.
I 'll keep you updated.
Best regards.

**Comment by mikedbcomp** [comment]
Ok great thank you

**Comment by Myddleware** [comment]
Hi Mike,

I guess soap extension for php isn't installed on your server. Could you install it ?  

Coul you also make these 2 modifications on the file myddleware\src\Myddleware\RegleBundle\Solutions\sagecrm.php

![image](https://user-images.githubusercontent.com/11330301/51205175-a7956100-18db-11e9-8162-a1114ffca28f.png)

Please let me know if it solves your problem. Thanks.

**Comment by mikedbcomp** [comment]
Hi,

Below changes seem to have worked thank you.

Cheers,
Mike
