### ISSUE TITLE
Connect Microsoft SQL via database connector

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#14]
I got it set up and trying to connect to MS SQL - it is saying driver not found. Do you have the syntax to specify the MS SQL driver? do I need to install it for PDO?

**Comment by Myddleware** [comment]
Hi,
The driver for Microsoft SQL should be sqlsrv
Could you tell me if it is working and we will update the tutorial ? Thanks.

**Comment by Myddleware** [comment]
That is what I was trying - do I need to install this library for PDO? do you have recommendation for best driver for mssql for PDO?

**Comment by Myddleware** [comment]
Alright, yes you need to enable the php module PDO. This page should help you : http://php.net/manual/en/pdo.installation.php

Could you tell me if it is working ?

**Comment by Myddleware** [comment]
Looks like I will need to configure and use ODBC as MSSQL doesn't look to be supported anymore. I am not 100% sure on that, but I will let you know what I find. Would odbc be the driver in this case?

**Comment by Myddleware** [comment]
Thank you very much for your research. 
I guess the driver would be odbc:MSSQLServer but you can try odbc alone too.

**Comment by rrichardsmn** [comment]
I am trying to use this as a guide, but still running into issues - I would appreciate it if you could try to setup and see if it will work before I spend too much more time on trying to setup.  http://php.net/manual/en/ref.pdo-odbc.php

**Comment by Myddleware** [comment]
We will make some tests with Microsoft SQL and tell you how you can set up it.
We come back to you this tuesday maximum.
Best regards.

**Comment by rrichardsmn** [comment]
this is another source that looks promising.  https://coderwall.com/p/21uxeq/connecting-to-a-mssql-server-database-with-php-on-ubuntu-debian

**Comment by Myddleware** [comment]
Hi rrichardsmn,

The driver you have to use is dblib. Make sure the driver pdo dblib is installed. See php info here 
![pdo_dblib](https://cloud.githubusercontent.com/assets/11330301/21813449/2e2a45d6-d74e-11e6-9e1f-7abfcbfa720e.png) 

However, we have to adapt the database connector in Myddleware to be fully compatible with Microsoft SQL. The new connector will be available next week in the version 2.1.1 of Myddleware. Hope that's ok for you.

Best regards.

**Comment by rrichardsmn** [comment]
Can't get dblib to load in phpinfo.  I have tried reinstalling the extensions and have added to php.ini, but still not loading.  At this point, I have another option for moving the data that may be simpler.  I appreciate your help and attempts to get this working for me.

**Comment by Myddleware** [comment]
Hi,
You shouldn't have to add something in php.ini. You have just to install the package php5-sybase (example with Ubuntu : apt-get install php5-sybase) and restart apache.

That is fine if you have another solution. Thank you very much for your contribution, we are sure that it will help a lot of people.
Have a nice evening.

**Comment by rrichardsmn** [comment]
I did the install and restarted apache, but no luck showing in phpinfo

I can try to connect from middleware connector, but don't know driver.  

Thanks
Ryan

**Comment by Myddleware** [comment]
Hi,
If you are still interested to install the dblib, could you give me the version of your php (by the way, if you use php7, the command for Ubuntu is apt install php7.0-sybase).
Could you tell me what is you OS ? 
Best regards.

**Comment by rrichardsmn** [comment]
we are using Ubuntu and php 5.6 - sybase is installed.  At this point, I am going to try pulling data locally instead.  I appreciate the help and if you want me to try anything else, I would be happy to.

**Comment by Myddleware** [comment]
Hi,
Could you try to follow the steps on this page : https://gist.github.com/joecampo/acd1e5881aee08bd8959
They use this command : sudo apt-get install php5-sybase freetds-common libsybdb5 

For information, we will launch Myddleware 2.1.1 tomorrow.
Best regards,

**Comment by Myddleware** [comment]
The connector Microsoft SQL is available in Myddleware 2.1.1 #18
