### ISSUE TITLE
Missing Moodle Modules

### ISSUE THREAD

**Issue by mikedbcomp** [Myddleware/myddleware#140]
Hi,

I have setup a Moodle connector as per the instructions in the Connector tutorial.
If I browse to...
http://mymoodleurl/moodle/webservice/rest/server.php?wstoken=mytoken&wsfunction=core_webservice_get_site_info&moodlewsrestformat=json
...I can see all of the web service functions listed.
I am trying to setup a rule to send User data from Moodle into SageCRM.
During my rule setup the choose module dropdown for my Moodle Connector only lists the functions that are added via the Myddlware plugin which I installed and none of functions I manually added as per the guide.
See below screengrab:
![2019-01-17 16_19_21-myddleware _ creation of a rule](https://user-images.githubusercontent.com/46717136/51332572-e5c58880-1a73-11e9-9d23-32cc13bc0865.png)

I'm guessing I have missed something simple but can't find what it is.

Cheers,
Mike

**Comment by Myddleware** [comment]
Hi Mike,
It is normal to have only 2 modules when you select Moodle in source solution. Here is the documentation : http://www.myddleware.com/solution/connected-applications?view=project&id=14:moodle

However, it won't be very difficult to add user module in source solution. However, as Moodle API function doesn't fit perfectly for sync tool like Myddleware, we will be able to read only new user, not user modified. 

We can develop in Myddleware or tell you how to develop it if you are a developer. You can contact us diretly about that if you  want.

Best regards.

**Comment by Myddleware** [comment]
Hi Mark,
With the new version of Moodle plugin (version 1.1) and the lastest version of Myddleware (2.4.1c) #149 , you will be able to read more data from Moodle (Courses, users, enrolments and completion) : 
![image](https://user-images.githubusercontent.com/11330301/53963249-4b70e100-40c3-11e9-99ae-3f3a918f06d4.png)

 Best regards
