### ISSUE TITLE
[PRESTASHOP] many product with the same datetime

### ISSUE THREAD

**Issue by Alexandre17220** [Myddleware/myddleware#141]
Hi,
I have a question, I have connected Prestashop to SuiteCRM with your excellent solution.
But I want force update of all my product in SuiteCRM, so I have edited the rule and change the date in past.
But now the operation is stopped : 
![image](https://user-images.githubusercontent.com/7665521/51392685-1837ba00-1b36-11e9-9889-4327be2000c5.png)
When I search in table in Prestashop I see ps_product.date_upd= "2018-10-11 11:21:47"
count 60...
Is there problem when two or more products have exactly the same date_upd ?

Thanks,

**Comment by Alexandre17220** [comment]
No problem, in fact I wait and Myddleware  continue to synchronize all

**Comment by Myddleware** [comment]
Great, thanks for your feedback.
Have a nice day,
Stéphane
