### ISSUE TITLE
bidirectional rule - problem target_id deleted

### ISSUE THREAD

**Issue by Alexandre17220** [Myddleware/myddleware#142]
Hi,

I have SuiteCRM and Prestashop
I synchronize products from Prestashop to SuiteCRM and SuiteCRM to Prestashop.
For example : 
rule "PS to SCRM" create one product in SCRM at 2018-09-07 07:54:16
my customer delete this product in Prestashop one day later....
and my customer edit this product in SCRM one more day later
so the rule try to send it to PS but error...
I have actually more 54 000 try for the same product ID, 
how to configure Myddleware to cancel automatically transfert if data doesn't exist in Prestashop ?

Thanks,

**Comment by Myddleware** [comment]
Hi Alexandre, 
You mean that there is 54 000 try for one data transfer or 54 000 data transfer in error ?

If it is only one data transfer you can just cancel it and Myddleware won't try to rerun it.

If you have 54 000 data transfer in error and you want to automatically cancel this data transfer in case of specific condition, you can create a file document.php in the directory myddleware\src\Myddleware\RegleBundle\Custom\Classes

It will redifine the standard classe document. Add ths code in this file :
```

<?php
namespace Myddleware\RegleBundle\Classes;

use Symfony\Bridge\Monolog\Logger; 
use Symfony\Component\DependencyInjection\ContainerInterface as Container;
use Doctrine\DBAL\Connection; 
use Myddleware\RegleBundle\Encryption\encryption as enCrypt;

use Myddleware\RegleBundle\Classes\rule as ruleMyddleware; 


class document extends documentcore {

	protected function beforeStatusChange($new_status) {
		if (
				!empty($this->document_data['rule_id'])
			AND	$this->document_data['rule_id'] == '5924xxxxxxxe6f' // Your rule id
		) {
			if (strpos($this->message, '<a part of your error message>') !== false) {
				$new_status = 'Cancel';
				$this->message .= '<Add error message and whrite why you cancel this document>. The document is canceled. '; 
			}	
		}
		return $new_status;
	}
}

```
Please change the rule id and the error messages and Myddleware should automatically cancel your data transfer when it runs it and meets your conditions.

Please let me know if it helps. Thanks.
Stéphane

**Comment by Alexandre17220** [comment]
Hi, 54 000 for the same product.
I try your solution,thanks 
have a nice day
