### ISSUE TITLE
prestashop 1.7.3.3 - probleme date_upd product

### ISSUE THREAD

**Issue by Alexandre17220** [Myddleware/myddleware#143]
Hi,

I have found a problem in myddleware but after analyse the problem come from prestashop...
The rule Product (rule in documentation for prestashop) use a date for reference.

Myddleware use Prestashop Webservice to get product list.
But I don't know why when Myddleware or my own php make this request : 
$xml = $webService->get(array('resource' => 'products&date=1', 'display'  => "[name,price,code_zone,wholesale_price,description,reference,id_category_default,id_category_default,id,date_upd,date_add]",
"filter[date_upd]" => "[2018-12-03 16:40:48,9999-12-31 00:00:00]","sort" => "[date_upd_ASC]"));
I have : 
 the first product have date_upd = 2018-09-04 14:35:17...﻿?!?

Do you have the same problem whith your connector ???

Thanks a Lot,
Ps: I know there isn't bug in myddleware , but you must have the same problem with prestashop, maybe this depend of prestashop version??

**Comment by Myddleware** [comment]
Hi ALexandre,

Thanks for this feedback. We will have a look into this. I will keep you posted next week.

Have a nice day,
Stéphane

**Comment by Myddleware** [comment]
Hi ALexandre,

I have tested with Prestashop 1.7.0.0 with these parameters and I get only expected result (date_upd > 2017-01-20 19:33:06 ) : 
Array
(
    [limit] => 101
    [resource] => products&date=1
    [display] => [name,price,wholesale_price,description,reference,id_category_default,id_category_default,id,date_upd,date_add]
    [filter[date_upd]] => [2017-01-20 19:33:06,9999-12-31 00:00:00]
    [sort] => [date_upd_ASC]
)

So this issue comes probably from Prestahop 1.7.3.

Thanks for your feedback.
Stéphane

**Comment by Alexandre17220** [comment]
Thanks Stéphane for your feedback.
Prestashop is very buggy solution, the worst open-source solution I saw.
Have a nice day
