### ISSUE TITLE
Hubspot API key not connecting

### ISSUE THREAD

**Issue by Jasonlbotelho** [Myddleware/myddleware#148]
When I go to create a connection and enter the API key into the appropriate field and click the test feature it returns this:

Connection failed : Failed to connect but no error returned by Hubspot. 

Any help would be greatly appreciated.

**Comment by Myddleware** [comment]
Hi,
Thanks for your interest in Myddleware. 

Could you send this URL in your browser (replace <API KEY> by your api key) : 
https://api.hubapi.com/properties/v1/contacts/properties?hapikey=<API KEY>

You should get something like that : 
![image](https://user-images.githubusercontent.com/11330301/53098663-863b1c80-34fa-11e9-9f4c-744d2081f1d1.png)

Could you tell me if you have it in your borwser ?
Thanks.

**Comment by Jasonlbotelho** [comment]
This is a snippet of what I have:

Raw Data:

![capture](https://user-images.githubusercontent.com/44562750/53132304-34a78780-3524-11e9-81b5-04e51cc8c74c.PNG)

Do you need any more information? 

Thanks,
Jason

**Comment by Myddleware** [comment]
Thanks, so your token is OK. Maybe a server problem. Is curl installed on your server ? 
Could you send the same URL from your server command prompt with curl ? Here is what I get : 
![image](https://user-images.githubusercontent.com/11330301/53190731-99281c80-35e0-11e9-831c-e31efbf782f1.png)
Please let me know what you get ? 
Thanks.

**Comment by Jasonlbotelho** [comment]
This is what I get when I run the command:

![tempsnip](https://user-images.githubusercontent.com/44562750/53221541-b24fbe00-361e-11e9-8bfc-0ab2f7d7bf36.png)

Could I have improperly configured my server?

![capture](https://user-images.githubusercontent.com/44562750/53221654-428e0300-361f-11e9-9e95-436607bed3bc.PNG)

**Comment by Myddleware** [comment]
Hi, 
This is really weird as your server seems to be well configured. So let's debug Myddleware ;)

Could you add these 2 lines after line 82 in the file myddleware\src\Myddleware\RegleBundle\Solutions\hubspot.php
```
$this->logger->error('DEBUG Hubspot connector URL: '.$this->url . 'properties/' . $this->version . '/contacts/properties?hapikey=' . $this->paramConnexion['apikey']);			
$this->logger->error('DEBUG Hubspot connector RESULT : '.print_r($result,true));	
```
![image](https://user-images.githubusercontent.com/11330301/53280152-70da1400-36ed-11e9-8518-c94ec5e222b4.png)

Then could you check your log file myddleware\var\logs\prod.log , I get that : 
![image](https://user-images.githubusercontent.com/11330301/53280277-91ef3480-36ee-11e9-99b9-554b28084250.png)

In your case I guess you have the first line with the URL and the second one should be empty. Could you check that the URL you get is the same that the one you tried in your browser ? No space before ou after the token ? The API key isn't crypted (because the API key is cripted in the Myddleware database) ? Other difference ?

Thanks.

**Comment by Jasonlbotelho** [comment]
**I made the change in the configuration file:** 

![tempsnip](https://user-images.githubusercontent.com/44562750/53283562-47c17f80-36fd-11e9-8219-b579d11d3f18.png)

**Then, I attempted to connect to the API again with no result and got this in the log file:**

![image 1](https://user-images.githubusercontent.com/44562750/53283567-5c9e1300-36fd-11e9-97dc-69a10cc402bb.png)

**It is essentially the same message as the one on the UI. The API key is a match.**

Any further insight would be much appreciated.

-------------------------------------------------------------------------------------------------------

**UI BUG:**

You have an interesting UI bug on your Hubspot connector page, but I don't think it is related to my issue.  I tested this on both Firefox and Chrome.

**1. Right Click + Paste = Doesn't allow me to submit the key when pressing the test button.** 
2. Ctrl-V = Allows me to submit the key when pressing the test button.
3. Manually = Allows me to submit the key when pressing the test button.

**Comment by Myddleware** [comment]
Hi,
So the Key is OK, the server too. Maybe we can check the php configuration. Could you tell me if the CURL extension is enabled in your php ? 
Thanks.

**Comment by Jasonlbotelho** [comment]
Okay, So I didn't have curl enabled. I enabled it and ran another test. 

![capture](https://user-images.githubusercontent.com/44562750/53469530-2c16eb80-3a13-11e9-8a8c-c063f3c1327e.PNG)

![tempsnip](https://user-images.githubusercontent.com/44562750/53469541-320ccc80-3a13-11e9-9196-007efeef4efb.png)

![capture2](https://user-images.githubusercontent.com/44562750/53469543-33d69000-3a13-11e9-9354-0ff1781ea416.PNG)

Can you confirm that it had properly connected based on this information?

Thanks again.

**Comment by Myddleware** [comment]
Hi,
That's great. You are connected to your Hubspot instance. Enjoy Myddleware ;)
Thanks for your feedback.
Stéphane

**Comment by Jasonlbotelho** [comment]
Thank you for your help. Much appreciated.
