### ISSUE TITLE
Access denied when installing

### ISSUE THREAD

**Issue by drewclifton** [Myddleware/myddleware#151]
[ERROR] 
Failed: Can't open the database : SQLSTATE[28000] [1045] Access denied for user 'admin'@'localhost' (using password: YES) 

I attached my install page to see all the info.

Thanks!

PS - I'm also not sure why my installation page looks a bit ugly (missing white background compared to installation guide!)

![Installation Error](https://user-images.githubusercontent.com/33555978/54322326-01e83080-45b2-11e9-9b27-0f896b326151.png)

**Comment by Myddleware** [comment]
Hi,
Could you try to install Myddleware via command by following this tutorial : https://myddleware.github.io/myddleware/#/?id=install-myddleware

Please keep me posted.
Thanks.
Stéphane Faure

**Comment by drewclifton** [comment]
I will take a look at this thanks.

Also, if this problem might be related to a file permissions issue, let it be known that I did **not** edit any of the default file/folder permissions when I uploaded the files to my server. I have created a new issue for this here to verify this: https://github.com/Myddleware/myddleware/issues/152

Thanks
