### ISSUE TITLE
What file/folder permissions are needed for installation?

### ISSUE THREAD

**Issue by drewclifton** [Myddleware/myddleware#152]
In the [1.3. Copying files to web server](http://community.myddleware.com/index.php/installation-guide/#copying-files-to-web-server) section it states:

> Make sure that these permissions are correctly set up :
> 
> The following directories have to be **writable by the web user**
> myddleware/var/cache/
> myddleware/var/logs/
> The following files have to be **writable by the web user** :
> myddleware/app/config/myddleware.yml
> myddleware/app/config/public/parameters_public.yml
> myddleware/app/config/public/parameters_smtp.yml

What is actually meant by "writable by the web user", ie how does this correspond to file permission attributes?

For example, here is what FileZilla shows as default permissions for the folder **myddleware/var/cache/**:

![Screen Shot 2019-03-14 at 8 24 11 PM](https://user-images.githubusercontent.com/33555978/54406584-e3f4fb80-4697-11e9-8e9b-4f8641b74752.png)

Is this correct or what should it be changed to?

Thanks!

**Comment by Myddleware** [comment]
Hi,
Permission 755 for directories and 644 for files are OK if the web user is the owner of these files/directories. If the web user isn't the owner but only belongs to the group, you should set 775 (directories) and 664 (files).
Best regards,
Stéphane

**Comment by drewclifton** [comment]
Thanks - also I just noticed that this file doesn't exist in my file structure:

> myddleware/app/config/myddleware.yml

Does the documentation possibly need updating in this regard? And does this file still exist elsewhere?

Thanks again!

**Comment by Myddleware** [comment]
Oh you are rigth, thanks.

The file is parameters.yml not myddleware.yml.

I have fix the tutorial. Thanks.
Have a nice weekend.
Stéphane
