### ISSUE TITLE
500 Internal Server Error - When creating a connector

### ISSUE THREAD

**Issue by johnpap21** [Myddleware/myddleware#153]
Hello

We are testing using platform.

I am trying to connect Moodle - suiteCRM and get this error.  Mind you, I get it when trying to create connections to anything.

Notice: Undefined index: solution in /app/src/Myddleware/RegleBundle/Service/SessionService.php on line 59

Warning: in_array() expects parameter 2 to be array, null given in /app/src/Myddleware/RegleBundle/Controller/ConnectorController.php on line 349

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please e-mail us at contact@myddleware.com and let us know what you were doing when this error occurred. We will fix it as soon as possible.
You can also log the issue on our Github : Myddleware Github project 

Sorry for any inconvenience caused.

TIA
John

**Comment by Myddleware** [comment]
Hi John,
No problem, we are happy to help.
Please could you provide the logs (Myddleware/var/logs/prod.log) ? Or you can just log to Myddleware with this end of URL : /web/app_dev.php 
You will be on dev environement and see full error log in your browser.We will be happy to have more details about this error.

Thanks.
Stéphane
