### ISSUE TITLE
Unable to create a rule for Moodle course sync

### ISSUE THREAD

**Issue by renehamburger** [Myddleware/myddleware#156]
As mentioned in #155, it does not seem to be possible to create a rule to sync Moodle courses to Hubspot:

> With another rule to sync a Moodle course to Hubspot I didn't even get that far. The simulation yielded no results, but the error message "There is no data in the source server or fields in the target solution", even though there are courses in my Moodle system. I have installed the plugin, even though it shouldn't be necessary for this, and double checked the webservice functions activated for this service. 'core_course_get_courses_by_field' is included, for example.

Our Moodle system contains 4 courses, all of which were modified in the past year:

```
 timemodified
--------------
   1544192657
   1537602856
   1544192384
   1552985684
(4 rows)
```

**Comment by Myddleware** [comment]
Hi Rene,
Hope you had a great weekend. 
Could you debug the simulation process by displaying the moddle response in the file myddleware\src\Myddleware\RegleBundle\Solutions\moodle.php : 
![image](https://user-images.githubusercontent.com/11330301/54957212-74e59580-4f28-11e9-8445-bde93320f5a3.png)
Pleas let me know what you get ? Thanks.
Best regards,
Stéphane

**Comment by renehamburger** [comment]
Ah, here we go: the privacy policy hadn't been confirmed for this user, so Moodle returned an error for trying to access the course through this user!

I accepted the policies manually for this user and now it works.

I couldn't find a to disable the need for agreeing to the policy for the role, so I posted a question about this [here in the Moodle forum](https://moodle.org/mod/forum/discuss.php?d=384354). If that was possible, you could include that in the web service user xml you provide.

**Comment by Myddleware** [comment]
Oh thanks for your feedback. We will update the tutorial.
have a nice day.
