### ISSUE TITLE
Myddleware ErpNext v10 connector no field list

### ISSUE THREAD

**Issue by jaywks** [Myddleware/myddleware#157]
unable to get field list from erpnext connect in myddleware ,any help appreciated.thanks

ERPNext: v10.1.76 (master)
Myddleware v2.4.1c

![erpnext-suitecrm](https://user-images.githubusercontent.com/16625441/54869993-02ef3e00-4dba-11e9-9a6d-b5a8b542b2b0.PNG)

**Comment by Myddleware** [comment]
Hi,
We can reproduce your issue. Sorry for this bug.
We will come back to you with a fix very soon.
Best regards,
Stéphane

**Comment by Myddleware** [comment]
Hi,
chdecultot, one of our partner (and ERPNext contributor), has posted an issue and a fix here : https://github.com/frappe/frappe/pull/7135
Thanks for that chdecultot.
We hope this fix will be accepted quickly and available on the next ERPNext version. However, if you don't use ERPNext in the cloud, you can add this fix manually into your ERPNext instance.
Hope it will help.
Stéphane

**Comment by jaywks** [comment]
thank you

**Comment by jaywks** [comment]
someone suggested below, but i am not knowledgeable enough to understand 

You can use following api:

doctype: <Doctype>
with_parent: 1
cmd: frappe.desk.form.load.getdoctype
It returns fields as well. And this also has access control built in.

**Comment by Myddleware** [comment]
Hi,
Thanks. We are lookking into this. 
We will keep you posted.
Stéphane

**Comment by Myddleware** [comment]
Fixed in version 2.5.0 #226
