### ISSUE TITLE
Prestashop-Moodle template: field fullname not found

### ISSUE THREAD

**Issue by siaotim** [Myddleware/myddleware#158]
Hi there!

First time user of Myddleware, apologies if I missed something obvious. 

I installed Myddleware on Platform.sh. I followed the Connectors guide as best as I could on a fresh Prestashop install (1.6.1.23) and an existing Moodle install (3.3.8) with the latest local_myddleware plugin (1.1). The two Connectors passed 'Test' and were saved.

When I try to create a Rule using the 'Default templates selection', I get the error: **"Field fullname not found in the module courses. Please make sure that you have access to this field."**  I'd guess this is a problem on on the Moodle end, but not sure what the next step might be. Any pointers appreciated!

(I am able to select items using 'Modules selection', but had hoped to use the template to learn how Rules work, especially with so many modules on Prestashop's side!)

Thank you in advance.

![image](https://user-images.githubusercontent.com/48971997/55044205-8300f680-508d-11e9-98c7-9df80b017b0a.png)

![image](https://user-images.githubusercontent.com/48971997/55044268-b9d70c80-508d-11e9-86be-99ebc63a2b71.png)

**Comment by Myddleware** [comment]
Hi,
Thanks for your feedback.
We reproduce this bug so we will be able to fix it quickly. We come back to you very soon. 
Stéphane.

**Comment by Myddleware** [comment]
Hi,
we have fix the bug. You can see the commit here : https://github.com/Myddleware/myddleware/commit/ccad4890b7cf80665fa7e17ae8e697dbeaf50585

We will deply it on the master branch tomorrow. I will let you know when it will be done.

**Comment by Myddleware** [comment]
Hi,
We have deployed the fix on the master branch. 
The easiest way is to create a new platform.sh environnent, you will have the latest Myddleware version.
Contact us if you prefer upgrading your current Myddleware environnement. You will have to add a ssh key on your platform.sh user.
Stephane
