### ISSUE TITLE
Prestashop-Moodle template: how to do the reverse?

### ISSUE THREAD

**Issue by siaotim** [Myddleware/myddleware#161]
This is not a bug report but a question (sorry, couldn't quite figure out how to tag this as such). 

The 'Default templates selection' for Prestashop => Moodle works well (thanks for the quick update after my previous issue) and the 4 generated Rules are helpful for understanding the inner workings of Myddleware.

But my newfound confidence came crashing down when I tried to go the reverse (i.e. Moodle => Prestashop). Say I wanted a Rule that updates Prestashop's Customer's 'notes' field when a user updates his/her 'middlename' in Moodle (See Diagram 1 & 2 below).

1. I presume I'd need another Rule to map an identifier in Moodle (e.g. email) to the customer id in Prestashop? But I don't quite see how I can create this Rule - particularly when there's only one type of Source available on Moodle's side (i.e. 'ID get_users_by_date', c.f. Diagram 3 below).
2. Also, looking at section '6.2 Bidirectional rule' of the Tutorial (https://myddleware.github.io/myddleware/#/basic_usage), Myddleware has an option for 'Bidirectional synchronization' at the 'Confirmation' step for a Rule - this doesn't appear in my usage case. Is it because the combo of Moodle and Prestashop just doesn't offer this? Is this even related to my hope of going from Moodle => Prestashop?

Any pointers appreciated. And thank you so much for Myddleware! 
![GitHub1](https://user-images.githubusercontent.com/48971997/55860125-e1ae9000-5bb6-11e9-9548-b27900a9250d.png)
![GitHub2](https://user-images.githubusercontent.com/48971997/55860126-e1ae9000-5bb6-11e9-8dea-ff8e27ef8d1b.png)
![GitHub3](https://user-images.githubusercontent.com/48971997/55860124-e115f980-5bb6-11e9-92dc-6eb36f70655a.png)

**Comment by Myddleware** [comment]
Hi,
Thank you so much for you feedback and your message with all your explanations and screenshots. This is very helpful.

We have identified the issue, we will prepare a fix and deliver it in the next hotfix version. It will be released by the end if the week.

We will keep you updated.

Have a nice day,
Stephane

**Comment by Myddleware** [comment]
Hi,
We have fixed this issue. So please upgrade your Myddleware instance to the version 2.4.1e. 

You have to upgrade Myddleware plugin into Moodle too. Go to your plugin overview and click on "Install available updates" : 
![image](https://user-images.githubusercontent.com/11330301/56062164-8658db00-5d39-11e9-812a-ec3f240c8119.png)

Please let me know if it works.
Stéphane

**Comment by siaotim** [comment]
Dear Stéphane:

Thank you for the fix.

I tried to upgrade Myddleware (for the 1st time) following section '3 Upgrading Myddleware' (https://myddleware.github.io/myddleware/#/?id=install-myddleware). 

I first tried the 'auto' way with 'php bin/console myddleware:upgrade --env=background', but an error resulted. 

I then tried the 'manual' way - and at step 'php bin/console doctrine:schema:update --force --env=background' I got the same error again (see screen cap below).

tim

![Github03](https://user-images.githubusercontent.com/48971997/56248835-fe822080-60ec-11e9-8421-6fd805c48c6b.png)

**Comment by Myddleware** [comment]
Hi Tim,
Could you tell me what is your PHP version by running the command : PHP -v
Could you also tell me what is your Myddleware version you had before?
Thanks

**Comment by siaotim** [comment]
Hi Stéphane:

Myddleware v2.4.1d running on a clean Ubuntu on AWS, with Myddleware installed as per the installation tutorial (and of course the requisite Apache, MySQL and PHP). 

'php -v' shows:

PHP 7.2.15-0ubuntu0.18.04.2 (cli) (built: Mar 22 2019 17:05:14) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.15-0ubuntu0.18.04.2, Copyright (c) 1999-2018, by Zend Technologies

tim

**Comment by Myddleware** [comment]
Hi Tim,
Could you try to clear your cache by running this command (from you Myddleware root directory) : 
`rm -rf var/cache/*`
Could you then try again ? 
Thanks.
Stéphane

**Comment by siaotim** [comment]
Hi Stéphane:

Unfortunately remove cache didn't do the trick. Same error message about count( ). 

I didn't notice this last time, but there was a (highlighted yellow) warning on the prior step:
`php composer.phar install --no-plugins`
`Package symfony/assetic-bundle is abandoned, you should avoid using it. Use symfony/webpack-encore-pack instead.`

Not sure if this is pertinent. Sorry!


tim

**Comment by Myddleware** [comment]
Thanks for this. 
We will analyse this and come back to you today or tomorrow. 
Have a nice day.

**Comment by Myddleware** [comment]
Hi Tim,
This is an issue on the latest php 7.2 versions. We can reproduce in 7.2.17. 
We 'll do our best to fix it this week. But if you want to make Myddleware work before, you can downgrade you php version to 7.1.
Stéphane

**Comment by Myddleware** [comment]
Hi again Tim,
This is a monolog bug with the php7.2 version. 
You can fix it by applying this fix : https://github.com/partkeepr/PartKeepr/issues/905#issuecomment-416146873
We will upgrade monolog verson to 3.1.2. But it can't be changed in a hotfix version as we have to process all non regression tests. So we will change monolog version in the next Myddleware release.
Stéphane

**Comment by siaotim** [comment]
Hi Stéphane:

Thanks for all the hard work! I shall try the PartKeeper fix, and await the next Myddleware release - I'm afraid my comfort level is only at upgrading, not downgrading, in Linux (but perhaps this is the impetus to branch out!)

I wish I had more technical abilities to offer. Thanks again for Myddleware!

tim

**Comment by siaotim** [comment]
Hi Stéphane:

PartKeeper fix worked, Myddleware upgraded, and new Moodle Source 'ID users' available on the Relation's panel. Yeehaa!

So - please bear with me here as I grapple with this conceptually - **Myddleware needs to somehow map the Moodle ID into a Prestashop ID** to transfer the information from Moodle (say, 'middlename' field) to Prestashop (say, 'company' field). 

1. Hence a Rule is required - correct? 

1. The Rules I created before (or by using the template) are for Prestashop => Moodle, so none of these Rules are useful for Moodle => Prestashop - correct?

1. How do I create this Rule for Myddleware to map Moodle ID to Prestashop ID? 

![image](https://user-images.githubusercontent.com/48971997/56625185-79b07d00-667f-11e9-94a6-a613041bd76b.png)

**Comment by Myddleware** [comment]
Hi Tim,
Thanks for your feedback.

You don't have to set up a relationship to create you "bidirectional" rule. You just have to select your "opposite" rule here : 
![image](https://user-images.githubusercontent.com/11330301/56655767-05340900-6694-11e9-9455-bd60ad22c360.png)
Myddleware will detect the id of the record if it exists in the opposite rule. 
Please let me know if it works. Thanks.
Stéphane

**Comment by siaotim** [comment]
Hi Stéphane:

Sorry for the delay in reporting back. **To recap, I'm trying to go from Moodle => Prestashop**, having succesfully created rules first to go from Prestashop => Moodle.
1. The 'Bidirectional Synchronization' does appear, and the initial Prestashop => Moodle rule is available for selection. **Great!**
2. My screen only has 'Synchronization type' and 'Bidirectional synchronization', not 'Primary key in your source table' and 'Field Date Reference'. I think this is because you are using different sources and targets. **Should be ok me thinks ...**
3. However, running my rule creates the following error. **D'oh! (see screen capture below)**

Potentially a user-side error, and I'll keep fiddling, but thought I'd post it in case its something in the plumbing so to speak.

![image](https://user-images.githubusercontent.com/48971997/57345756-54e3fb80-718f-11e9-900f-50a9e56d673b.png)

**Comment by Myddleware** [comment]
Hi Tim,
This date sould have the format Y-m-d H:i:s : 
![image](https://user-images.githubusercontent.com/11330301/57403359-d82a3f00-71d9-11e9-9ce1-c662e40fd080.png)

Could you give more detail about your rule (module source and target, field mapping, relationship and parameters) ? I will try to reproduce your error.

Thanks.
