### ISSUE TITLE
Moodle "Get Course" Not Loading any fields. Anybody got an idea?

### ISSUE THREAD

**Issue by wikkiboy** [Myddleware/myddleware#164]
I am trying to create a rule in order to get all the courses data from Moodle. Connection goes well as you can see in screenshot 1 attached here but in screenshot 2 you can see that based on "Get Courses" module, no fields show up in screen 2.

Whether if I select "Get Enrolments", I get decent number of fields. Just for your information I already installed the myddleware plugin in moodle and configured it properly.

Thanks for any help!
![Screen-1](https://user-images.githubusercontent.com/4928267/56457639-5643b480-6397-11e9-845c-5711e13ce0af.png)
![Screen-2](https://user-images.githubusercontent.com/4928267/56457641-56dc4b00-6397-11e9-8e79-e8cbedc7ad50.png)

**Comment by Myddleware** [comment]
Hi,
Could you upgrade to the latest version of Myddleware (2.4.1e). The module get_courses_by_date has been replace by the moduke courses in version 2.4.1e  : https://github.com/Myddleware/myddleware/pull/162/commits/951c75e4e17f3ed523717e822024c1a60509d5e7
Please let me know if it solves your problem. 
Thanks.
Stéphane
