### ISSUE TITLE
What is field Myddleware_element_id?

### ISSUE THREAD

**Issue by Wavedancer71** [Myddleware/myddleware#166]
When I'm trying to create a rule between Moodle and MySQL I always get a field that I do not have in my own database table. What is the "Myddleware_element_id"? Should I add it (I already have an id column which is primary)? What should it contain?

![Myddleware](https://user-images.githubusercontent.com/16321788/57523102-5a267f00-7324-11e9-9560-ec1677658075.JPG)

**Comment by Myddleware** [comment]
Hi,
You are right, thanks for your feedbask. 

This field shouldn't be here for thos connector. We will fix this. So please don't map this field..

You cany continue to use the connector without mapping this field. Myddleware updates only fields mapped.

Best regards.
Stéphane

**Comment by Wavedancer71** [comment]
Thanks for your fast reply! I can't continue from this step as it gives me the error "There is no data in the source server or fields in the target solution" in the test. I thought it depended on this extra field. But if it is a bug I will wait for an update.

**Comment by Myddleware** [comment]
The field "Myddeware_element_id" won't cause any bug if you don't map it. So please leave it blank and you connection should work fine.

About you error, could you give me a screenshot of it please ?

Thanks.

**Comment by Wavedancer71** [comment]
Sure!
If I add the following fields (ignoring the "Myddeware_element_id"):

![M1](https://user-images.githubusercontent.com/16321788/57530075-b85c5d80-7336-11e9-8dc7-a71ba0a44f3f.JPG)

Then in the next step, after pushing the Test data-button, it looks like this:

![M2](https://user-images.githubusercontent.com/16321788/57530109-d4f89580-7336-11e9-8cce-f0d3299d393c.JPG)

**Comment by Wavedancer71** [comment]
After checking the content in the source (course database) I realized that the field "ID number" didn't contain any data, so I changed the rule and only used "ID", "Short name" and "Full name", but still I get the same error in the next step. No matter what fields I choose I get the same message ("There is no data...").

**Comment by Myddleware** [comment]
Sorry for the late reply.
In your case, Myddleware will read all courses modified after today - 1 year (1 year is a constant only set for simulation purpose). 
So could you tell me if you have at least a course in Moodle ? If yes has this course been modified for less than a year ? 

For information, when you will run your rule you can choose the reference date you want (more than 1 year in the pst is possible). 

Please let me know if I am not clear.
Stéphane

**Comment by Wavedancer71** [comment]
Yes, I have about 34 courses and they are all modified the last month (I made a migration not long ago). 

How do I choose a different reference date? By formulas?

**Comment by Myddleware** [comment]
Thanks. 
Could you test something ? Could you map only shortname and fullname by removiong mapping on id and courseid. Then select id in the confirmation tab like this : 
![image](https://user-images.githubusercontent.com/11330301/57713597-c95fe400-7640-11e9-836b-7b93f5cd4a90.png)

Then confirm you rule and go to the parameters tab, set a date far in the past (like 2000-01-01 00:00:00), then save this date and click on Simulate transfert : 
![image](https://user-images.githubusercontent.com/11330301/57713836-412e0e80-7641-11e9-81bd-6a6b2bc0e8b2.png)

Mydlware finds 9 courses for me and you should find 34 for you. So Do you have 34 or do you have an error ? Thanks.

**Comment by Wavedancer71** [comment]
I followed your instructions but got an error in the last step:
![Myddleware2](https://user-images.githubusercontent.com/16321788/57908414-30b7a700-7880-11e9-850b-8d5cfbf0550d.JPG)

**Comment by Myddleware** [comment]
OK thanks, it makes sense.

You have an authorization issue in Moodle. Could you follow this tutorial : https://myddleware.github.io/myddleware/#/connectors_credentials?id=moodle

Could you make sure you have imported this role and added it to the Moodle user linked to your Moodle token ? Thanks.
![image](https://user-images.githubusercontent.com/11330301/57930762-c7866280-7884-11e9-814c-352864c4844f.png)

Please let me know if it works.

**Comment by Wavedancer71** [comment]
I have made it working now! I added the Myddleware role into Moodle and added it to my user. I also noticed there was some functions missing when I checked it more thoroughly and added them as well. 

However, I still get the extra field "Myddleware_element_id" when creating a rule, but I just ignore it for now.

**Comment by Wavedancer71** [comment]
I was too fast in my judgement, it is still not working. But the "Simulate Transfers" gives me 34 which is correct. But the rule fails anyway.

![Myddleware3](https://user-images.githubusercontent.com/16321788/58005978-319e4200-7ae7-11e9-910f-ef2a1224d835.JPG)

**Comment by Myddleware** [comment]
Hi,
You have maybe a file right problem.

Could you try to run the task via this comand from Myddleware root directory using putty for example : 
`php bin/console myddleware:synchro <your rule id> --env=background`

Don't forget to set the status of your rule to active.

Please could you send me a screenshot of what you get ? Thanks.

**Comment by Wavedancer71** [comment]
I'm running on a hosted server so I do not think I have access to the console. But I gave it a try:

![Console](https://user-images.githubusercontent.com/16321788/58091510-03456300-7bca-11e9-85c3-8edf20c93dd2.JPG)

**Comment by Myddleware** [comment]
Hi,
You have to run the command from Myddleware root directory. So maybe you should enter in public_html directory via the command "cd public_html". Then you will probably see Myddleware directory. If you see it, go into it (cd myddleware) then run the command.
Hope it will help.
Stéphane

**Comment by Wavedancer71** [comment]
Sorry, didn't understand that. When I changed to Myddleware directory it worked. Now the data are stored in our external database. 
I tried to repeat the step with another data (users), and a new error happens using the GUI tool, now there is a reading issue:
![Myddleware4](https://user-images.githubusercontent.com/16321788/58101003-157dcc00-7bdf-11e9-9f13-10c1d08f3952.JPG)

I tried the console tool again with the new rule id but it also failed:
![Myddleware5](https://user-images.githubusercontent.com/16321788/58101868-a1dcbe80-7be0-11e9-93f9-84b586c46e83.JPG)
By the way, thanks for all the help! You have been very helpful.

**Comment by Myddleware** [comment]
Hi,
Sorry I understand only french and english, could you translate the error for me ? 
And could you tell me which data from Moodle are you trying to read ? User module ?
Thanks.

**Comment by Wavedancer71** [comment]
Of course! The translation should be (from Swedish): "An incorrect value for a response has been detected, the run cannot continue.". 
Yes, I wanted to collect user id, usernames, first name, last name, email, city and country from the user table. We have currently 96 users registered.

**Comment by Myddleware** [comment]
Hi,
Could you try to map only usernames and see if you have the same error. If you don't have the error, could you add fields one by one to try tofind the one which generates the problem ? 
Thanks.

**Comment by Wavedancer71** [comment]
No, if I only choose username the same error shows up. No matter what field I choose I get the same error. 

Just for testing, I tried create other rules for different kind of data and then it seems to work. Only when trying to fetch user data the error appears (module: "Get users"). 

Another question, is it possible to add other modules? Like there does not seem to be a module to fetch the users grades for a particular activity for example.

**Comment by Myddleware** [comment]
OK, could you do a test to check if yor problem is linked to authorization issue.

Could you create anothertoken in Moodle with an admin user. Create another Moodle conector in Myddleware and try to create the same rule with thisnew connector (with the moodle admin token) ? Do you have the same problem ?

Yes it is possible to add new module in Moodle but it requiere 1 or 2 days of development. For instance we will soon add Competency module. So if you want to create this module by yourself (if you are a developer or if a developer works for you) we can help you via this forum. Just create a new issue in this forum. Then you could add your code in Myddleware project as a contributor.
If you wwant we develop it, please contact us directly via this page http://www.myddleware.com/contact-us

Have a nice day

**Comment by Wavedancer71** [comment]
I did create a new token, and made a new connector and tried with a new rule. I only added User ID and Username as fields. When I get to the last step and do **not** change the date, pressing "Simulate Transfers", I actually get 1 estimated transfer (?). Picture proof:

![Myddleware8](https://user-images.githubusercontent.com/16321788/58335643-50336e80-7e42-11e9-9471-af88040f8754.JPG)

If I set another date back in time, like year 2000, I get the same error like before. We have not added any new user today, so why only one estimated transfer? Why doesn't it accept any other dates in history? 

I am a developer but I afraid that I do not have the time (I'm busy teaching). Otherwise it would be very interesting proposal. Maybe in the future.

**Comment by Myddleware** [comment]
Thanks for all of these informations.

We will try to reproduce it on our system. We 'll keep you posted.

**Comment by dawoodjee** [comment]
Please note that this is also showing for MSSQL to **ERPNext**

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue but please do not hesitate to re-open it if needs be.
Thanks.
