### ISSUE TITLE
Is there support for target MysqlDB to store multiple fields as json string?

### ISSUE THREAD

**Issue by amitlimbadia** [Myddleware/myddleware#173]
Suppose in source mysql DB i had 2 fields "**first_name**" & "**last_name**", now i want them to combine and store in target mysql DB  field which is longtext and want to store them as json string. i.e. **{"first_name":"xxx","last_name":"yyy"}** can we do this using formula?

**Comment by Myddleware** [comment]
Hi,
We already use these characters {} as specific characters. So we can't create your formula for now.
However this is a really interesting need. So we will work on the creation of a new formula function to encode/decode json.
I will come back to you about it very soon (next week maximum).

**Comment by Myddleware** [comment]
Hi,
We have found a simple solution for you. We have added the function chr in our hotfix branch : https://github.com/Myddleware/myddleware/commit/e121794b4c4c601227d30e4295a87f72953e282b
 
But if you don't want to wait for the next release, please add the function chr in the table functions :
![image](https://user-images.githubusercontent.com/11330301/58738879-a91c7d00-83d5-11e9-84b1-aa0d449afc62.png)

Then you will be able to create a formula which should looks like this one : chr(123).chr(34)."first_name".chr(34).":".chr(34).{firstname}.chr(34).",".chr(34)."last_name".chr(34).":".chr(34).{lastname}.chr(34).chr(125)

![image](https://user-images.githubusercontent.com/11330301/58739034-47104780-83d6-11e9-9e71-bec9acf572df.png)
Your fields {firstname} and {lastname} may be different than mine.

Here are the result we have with this formula : 
![image](https://user-images.githubusercontent.com/11330301/58739111-a2423a00-83d6-11e9-9b76-5b0ddd26ae0b.png)

Please let us know if it could solve your problem.

Best regards.

**Comment by amitlimbadia** [comment]
Hi

Yes that will also work for now, but if we could add json_encode then it will be good, but let's check with "chr" now. 

Thank you :+1: for your quick reply, will check by adding new function

**Comment by amitlimbadia** [comment]
Yes thank you it worked :+1:

**Comment by sagaraspl** [comment]
Hi @Myddleware ,

I have similar requirement as Amit but I can wait for your next release as you said until next week.  I think this is really interesting as now a days more and more people are using NoSQL and SQL both.

Thanks.

**Comment by Myddleware** [comment]
Hi,
We have just merged the hotfix branch into the master (https://github.com/Myddleware/myddleware/pull/178)
Have a nice day.
