### ISSUE TITLE
Is there support for mysql join multiple one to one tables in source and save data in target in one table?

### ISSUE THREAD

**Issue by amitlimbadia** [Myddleware/myddleware#174]
I have 2 queries

1) Suppose i have 2 tables

**ad** and **business** now **business** have field **ad_id** which references to **ad's** **id** field, so its one to one relationship for ad and business.

Now i want to combine both table's (**ad** & **business**) fields in target's DB table which is **ad**.

Can we do that? let me know is there support for this one or not?

2) Now suppose in one rule i have mapped one field to target's one field, now in second rule i want to append from source to target's same field which is used in rule one. IS it possible?

**Comment by Myddleware** [comment]
Hi,
Yes Myddleware can help you to manage your specific relationships. Could you first have a look into these chapters of this tutorial : https://myddleware.github.io/myddleware/#/basic_usage
![image](https://user-images.githubusercontent.com/11330301/58851220-dd0ad300-865f-11e9-8a33-d3d806212ae6.png)

It should help you to manage your relatiionship. However, as it is a complex process, don't hesitate to contact me again if you have problem to create these relationships.

Have a nice day.

**Comment by amitlimbadia** [comment]
No @Myddleware ,

I want multiple table's field in field mapping screen. Is there support for that?

**Comment by Myddleware** [comment]
If you want to take the data of several tables to send it in one table, you have to create as many rules as there are source tables. So you have several tables as source and one table as target, it is a relationship many to one.

So you create you first rule between your first source table and your target table. Then you create your second rule between your second source table and the same target table, then create a relationship as you can see on the tutorial (many to one relationship).  Your second rule will never create entries in your target table, it will always update existing entries.
And you can do it with a third table... etc

Does that make sense ? 

Best regards
