### ISSUE TITLE
Is there a support for transferring EAV(Entity, Attribute, Value) database structure?

### ISSUE THREAD

**Issue by sagaraspl** [Myddleware/myddleware#175]
Hi @myddleware-dev 

We are trying to perform migration from source database where we have EAV structure in source. So for e.g. in one table I have a column like meta_key & meta_value, meta_key indicates column name of source and meta_value indicates value in source while I want to transfer this meta_key & meta_value as json field in destination table.

**Comment by Myddleware** [comment]
Hi @sagaraspl ,
This is very specific and a custom code will be requiered to meet your need. It will be necessary to redefine few methods in the class myddleware\src\Myddleware\RegleBundle\Solutions\database.php : 

- read=> to change your query and aggreggate all the rows you need for a specific record (I guess your have several row for one record)

- get_module_fields => to add fields in the mapping field tab when you create a rule. 

If think you can do it if you are a developer, but it won't be very easy, sorry.
Let me know if you need help.
best regards,
Stéphane

**Comment by sagaraspl** [comment]
Hi @Myddleware 

Yes I will try to find out solution for it for the classes you have defined, but don't you think now a days many of CMS etc... are using EAV pattern, the good example of it is wordpress.

So isn't that something a needed one now a days? So if you think that it would useful to community and if you can add support for it then it is really useful.

**Comment by Myddleware** [comment]
Thanks for sharing this.

However managing EAV structure in Myddleware isn't plan for now. 

Have a nice day.
