### ISSUE TITLE
Doesn't working with Mariadb 10.2 & Above

### ISSUE THREAD

**Issue by sagaraspl** [Myddleware/myddleware#176]
Hi @Myddleware 

Tool doesn't working for Mariadb 10.2 & Above.

**Comment by Myddleware** [comment]
Hi @sagaraspl ,

Please select MySQL connector, it should work with Mariadb too. 

Please let me know if it works.
Have a nice day.

**Comment by sagaraspl** [comment]
Hi @Myddleware,

Yes thanks for update however I already tried with MySQL connector and it is working fine for MariaDB version < 10.2 however it is giving error for MariaDB version 10.2 & above when running rules.

**Comment by sagaraspl** [comment]
Hi @myddleware-dev 

In MariaDB > 10.2 it is giving following error

Failed to create document (id source : 5d00960d6d8738.87304971): An exception occurred while executing INSERT INTO Document (id, rule_id, date_created, date_modified, created_by, modified_by, source_id, source_date_modified, mode, parent_id) VALUES(5d00960d6d8738.87304971,5d0095db41099,2019-06-12 06:05:01,2019-06-12 06:05:01,1,1,2020,2020,0,): SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: 2020 for column source_date_modified at row 1

**Comment by sagaraspl** [comment]
Hi @Myddleware I have found the issue. It seems it is because in read function of database.php

Original 

```
/ If the reference isn't a valid date (it could be an ID in case there is no date in the table) we set the current date
						    if ((bool)strtotime($value)) {;
								$row['date_modified'] = $value;
							} else {
							    $row['date_modified'] = date('Y-m-d H:i:s');`
							}
```


Suggested

// If the reference isn't a valid date (it could be an ID in case there is no date in the table) we set the current date

```
 if (!is_numeric($value) && (bool)strtotime($value)) {;
								$row['date_modified'] = $value;
							} else {
							    // Chnaged by Sagar
							    $row['date_modified'] = date('Y-m-d H:i:s', mktime(date("H"), date("i"), date("s") + $value));
							}
```
