### ISSUE TITLE
Mysql JSON merge issue

### ISSUE THREAD

**Issue by sagaraspl** [Myddleware/myddleware#180]
Hi @Myddleware,

When using your latest fix for json I have noticed 2 issues. 

1) It is not transforming null values from source when adding it into target json field.
2) When transforming data from more then one source table to same column of destination table it is overwriting json data instead of merging it.

**Comment by Myddleware** [comment]
Hi @sagaraspl ,
Sorry for the delay of our reply. Myddleware don't merge data for now. You have to do a custom development for this. 
About the null value, could you explain with more details your problem and the result you expect with an example ? Thanks.
Have a nice day.
