### ISSUE TITLE
Multithread support

### ISSUE THREAD

**Issue by sagaraspl** [Myddleware/myddleware#181]
Hi @Myddleware 

Is there a support for processing multiple rows in same rule at the same time? Because it is really time taking process if we have large amount of data to transfer and we go sequentially. Something like rabbitmq.

**Comment by Myddleware** [comment]
Hi @sagaraspl ,

Thanks for your feedback.

This is something we plan to develop this year. We plan to allow Myddleware to run on several task in the same time. But it won't be ready before end of this year. 

Best regards.
Stéphane
