### ISSUE TITLE
mydlleware plugin for Moodle

### ISSUE THREAD

**Issue by rickyshe** [Myddleware/myddleware#184]
Hi ,

For the purpose  evaluation process / learning   / being able to evaluate
I installed locally  ( wamp64 - apache 2.4.39 - mysql 5.7.26 - php 7.2.18 )  moodle and myddleware  

After I tried to install myddleware as a  moodle plugins  

The moodle site (  https://localhost/moodle ) response is :
This site can’t be reached
( also admin/index.php or any  other I tried )

 - other apache apps are responding as expected
I tried restarting the wamp services
I tried rename the local (contains myddleware)folder

Thanks,
Ricky.

**Comment by Myddleware** [comment]
Hi Ricky,
Could you have a look to the apache log and copy them here, we will try to find why Moodle isn't responding anymore ? 
Thanks.

**Comment by rickyshe** [comment]
apache_error.log 

[Tue Jun 25 13:48:08.428714 2019] [mpm_winnt:notice] [pid 24620:tid 752] AH00428: Parent: child process 23696 exited with status 255 -- Restarting.
[Tue Jun 25 13:48:08.647412 2019] [mpm_winnt:notice] [pid 24620:tid 752] AH00455: Apache/2.4.39 (Win64) PHP/7.2.18 configured -- resuming normal operations
[Tue Jun 25 13:48:08.647412 2019] [mpm_winnt:notice] [pid 24620:tid 752] AH00456: Apache Lounge VC15 Server built: Mar 28 2019 11:59:33
[Tue Jun 25 13:48:08.647412 2019] [core:notice] [pid 24620:tid 752] AH00094: Command line: 'c:\\wamp64\\bin\\apache\\apache2.4.39\\bin\\httpd.exe -d C:/wamp64/bin/apache/apache2.4.39'
[Tue Jun 25 13:48:08.647412 2019] [mpm_winnt:notice] [pid 24620:tid 752] AH00418: Parent: Created child process 12872
[Tue Jun 25 13:48:09.714038 2019] [mpm_winnt:notice] [pid 12872:tid 148] AH00354: Child: Starting 64 worker threads.
[Tue Jun 25 14:25:00.479847 2019] [mpm_winnt:notice] [pid 24620:tid 752] AH00428: Parent: child process 12872 exited with status 3221225725 -- Restarting.
[Tue Jun 25 14:25:00.589180 2019] [mpm_winnt:notice] [pid 24620:tid 752] AH00455: Apache/2.4.39 (Win64) PHP/7.2.18 configured -- resuming normal operations
[Tue Jun 25 14:25:00.589180 2019] [mpm_winnt:notice] [pid 24620:tid 752] AH00456: Apache Lounge VC15 Server built: Mar 28 2019 11:59:33
[Tue Jun 25 14:25:00.589180 2019] [core:notice] [pid 24620:tid 752] AH00094: Command line: 'c:\\wamp64\\bin\\apache\\apache2.4.39\\bin\\httpd.exe -d C:/wamp64/bin/apache/apache2.4.39'
[Tue Jun 25 14:25:00.593131 2019] [mpm_winnt:notice] [pid 24620:tid 752] AH00418: Parent: Created child process 27428
[Tue Jun 25 14:25:01.124622 2019] [mpm_winnt:notice] [pid 27428:tid 552] AH00354: Child: Starting 64 worker threads.
[Tue Jun 25 14:25:04.271726 2019] [mpm_winnt:notice] [pid 24620:tid 752] AH00428: Parent: child process 27428 exited with status 3221225725 -- Restarting.
[Tue Jun 25 14:25:04.381432 2019] [mpm_winnt:notice] [pid 24620:tid 752] AH00455: Apache/2.4.39 (Win64) PHP/7.2.18 configured -- resuming normal operations
[Tue Jun 25 14:25:04.381432 2019] [mpm_winnt:notice] [pid 24620:tid 752] AH00456: Apache Lounge VC15 Server built: Mar 28 2019 11:59:33
[Tue Jun 25 14:25:04.381432 2019] [core:notice] [pid 24620:tid 752] AH00094: Command line: 'c:\\wamp64\\bin\\apache\\apache2.4.39\\bin\\httpd.exe -d C:/wamp64/bin/apache/apache2.4.39'
[Tue Jun 25 14:25:04.382428 2019] [mpm_winnt:notice] [pid 24620:tid 752] AH00418: Parent: Created child process 25300


repeated many times

**Comment by Myddleware** [comment]
Hi @rickyshe 
Sorry but I see no fatal error, only notice. 
Does Myddleware work properly ? 
Maybe you could try to reinstall Moodle.  Could you check if it works properly without Myddleware plugin ?
Thanks.

**Comment by rickyshe** [comment]
I will reinstall .
 It worked before I tried to install the plugin. The other apache apps works .
Thanks
Ricky

**Comment by rickyshe** [comment]
I tried to reinstall moodle - and used a new DB instance - the result was the same : This site can't be reached .
Then I re-installed on another PC machine 
wamp64 ( same as before )
moodle install
login as admin user
Select : Site Administration , Plugins
Load zip file local_myddleware_moodle37_2019061901.zip
Install plugin
message : Validating local_myddleware  ... ok
Continue button
Button : upgrade moodle databes now
message page : local_myddleware 
Success
Button : Continue

Next page is :   This site can't be reached
The URL is  : http://localhost/moodle/admin/upgradesettings.php?

Could you please help find the root cause, 
Thanks
Ricky

**Comment by rickyshe** [comment]
Thanks for your help,
Found in moodle.org forum discussion regarding "This site can't be .."
Add to httpd.conf 

<IfModule mpm_winnt_module>
   ThreadStackSize 8888888
</IfModule>

Now I am able to login page moodle admin.

Thanks
Ricky.

**Comment by rickyshe** [comment]
https://moodle.org/mod/forum/discuss.php?d=387587

**Comment by Myddleware** [comment]
Thanks for your feedback.
Have a nice day.
