### ISSUE TITLE
SuiteCRM -> Moodle - unique usernames

### ISSUE THREAD

**Issue by berthelemy** [Myddleware/myddleware#185]
Hi there,
I'm able to add users to Moodle from SuiteCRM OK, following the instructions at https://moodle.org/mod/forum/discuss.php?d=365598

But how do you ensure that the usernames are unique? There will be many instances when the {firstname}.{lastname} combination duplicates. As far as I can see now, that just creates an error which stops the processing. I'd like to avoid that if possible, perhaps by adding a counter to the end of the username, but I can't see any way of doing that within Myddleware.

It's looking like my only option is to create the username as a custom field inside SuiteCRM, with the logic there. I was just hoping to avoid modifying the codebase.

Thanks,

Mark

**Comment by Myddleware** [comment]
Hi @berthelemy , 

You have to ways to manage your problem : 

1. You don't want duplicate user : you can use deduplicate field "username" on your rule. By this way, Myddleware will check before creating the user if a user with this username already exists in Moodle. If yes, Myddleware will only update the existing user in Moodle. No duplicate user will be created.
![image](https://user-images.githubusercontent.com/11330301/60497525-4a3c7300-9cb5-11e9-818c-413692c29a26.png)

2. Or you can create duplicate user by changing the username as you proposed.  You can create a field in SuiteCRM and concatenate it (with a formula in the mapping field tab) with the username or just concatenate the creation date of the SuiteCRM record.

Please let me know if it isn't clear.
Stéphane
