### ISSUE TITLE
Creating a rule to update SugarCRM Contacts without Accounts

### ISSUE THREAD

**Issue by rickyshe** [Myddleware/myddleware#186]
Hello,

Thank you very much for your help.

I've been able to set up connectors for Moodle and SugarCRM. ( source : moodle , target : SugarCRM )
The respective connection tests as well.
When I use a rule to create and update data from users to Accounts it works as expected.
New moodle user, is created automaticaly in SugarCRM Accounts. User update in moodle, is updated in SugarCRM.

The problem is :
I would like to have a rule : create and update data from Moodle-users to SugarCRM - Contacts.
The moodle users are students ( not related to business - there are no accounts relation ).

This rule fails.
The error message : 
Error : Error invalidresponse : Invalid response value detected C:\wamp64\www\myddleware\src\Myddleware\RegleBundle\Solutions\moodle.php Line : ( 231 )

This error comes from the read method in moodle.php

Thanks
Ricky.

**Comment by Myddleware** [comment]
Hi @rickyshe ,

If I understand well, you are using the same module in source for both rules (contact and account). If yes, there might be something different. Are your reference date on the same format for both rules ? 
I need to know the difference to have a change to find the solution.

Thanks
Stéphane

**Comment by rickyshe** [comment]
Hi Stéphane,
I was using the users as source in both rules.
I only need the rule for Contacts. 
I would like the students from moodle to be created as Contacts in SugarCRM.
I was using the rule for Accounts only because I could not make it work with Contacts.
Regarding date format : I did not select the date fields when mapping the fields.
Name and email - to make it simple as can be.

Thanks
Ricky.

**Comment by Myddleware** [comment]
Ok but I mean the reference date here : 
![image](https://user-images.githubusercontent.com/11330301/60529164-51d03c00-9cf6-11e9-8c25-530ec55a296f.png)

Because Myddleware use the same function for your rules, it should work the same. So I think about the reference date which is a parameter of the call to Moodle

**Comment by rickyshe** [comment]
When I use the rule :  moodle-users  to sugarcrm-Account
I create a new user in moodle. (I do not set the parameters tab) - I  run the rule. and the new user is created in sugarcrm-Accounts.
Could be that it is using a date parameter for the call to moodle ( datemodified ) .

What should I do to make the rule for sugar-Contacts work the same ?

Thanks very much
Ricky.

**Comment by rickyshe** [comment]
Hi  Stéphane,
I re-installed - and now made new rule Contact ( no rule Accounts )
And it works as expected.
Requires  code changing in document.php method createDocument :

$date_modified = date('Y-m-d H:i:s', mktime(date("H"), date("i"), date("s") + $this->data['date_modified']));

**Comment by Myddleware** [comment]
Thanks for your feedback.
Have a nice day.

**Comment by rickyshe** [comment]
Now when I try to use the parameters tab to set a date - so that all users
records created in moodle - will be created  in Sugar - it does not work

I guess - there is some other date reference in the php code that requires
format fixing.

Thanks,
Ricky.

‫בתאריך יום ד׳, 3 ביולי 2019 ב-18:15 מאת ‪Myddleware‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by Myddleware** [comment]
What is the format of your reference date ?

**Comment by rickyshe** [comment]
Hello
Could you please explain your question ? 
I didn't select any date field when mapping the fields .

Where do I get to choose a format ? a reference date ?

When I "refer to" one rule from the rules list in myddleware,
In the parameters tab - there is a field with title:
Reference (data will be read from this parameter) :
and the value is : 2019-07-03 15:50:47

Is this the date ?

Thanks
Ricky.

**Comment by Myddleware** [comment]
Hi @rickyshe 

Yes I meant the reference in rule parameter's tab. Could you set this date to 2000-01-01 00:00:00

Then Myddleware should read all you users in Moodle. 

If it doesn't work, could you remove your fix in document.php and run it again. 

If it still doens't work, could you tell me what is your Myddleware version (2.4.1i ? )

Please let me know what it your results. Thanks
Stéphane Faure

**Comment by rickyshe** [comment]
Hi ,

When I set the date 2000-01-01 00:00:00 in the parameters tab,
Both with/without fix in document.php , ends with :
Error : Error invalidresponse : Invalid response value detected 
Myddleware version  : myd_version: 2.4.1h

Thanks
Ricky.

**Comment by Myddleware** [comment]
OK, I can reproduce the bug. I come back to you very quickly.

**Comment by Myddleware** [comment]
Hi @rickyshe ,

We have found and fixed the bug in the Myddleware's plugin installed in Moodle. The problem happens because null fileds wasn't allowed for extra name fields. You can see the fix here : https://github.com/Myddleware/moodle-local_myddleware/commit/18a951189f37008beb787231e08b07f0d6e59b39

Install the new version of Myddleware's plugin in Moodle and let me know if your problem is solved.
Thanks.
Stéphane

**Comment by rickyshe** [comment]
Hi Stéphane,

You solved the problem - Thank you!
Thanks so much for your effort.
I really appreciate all your help in getting this done.

With many thanks,
Ricky.
