### ISSUE TITLE
Is it possible to connect two different Moodle servers?

### ISSUE THREAD

**Issue by Kerrilit** [Myddleware/myddleware#190]
I have 2 different Moodle servers. One is main Moodle, another as storage for verified courses. I cant transfer all courses with making backups because number of courses is very huge. Can I make a connection between Moodle`s for automate this process?

**Comment by Myddleware** [comment]
Hi,

Yes you can read all course from one module and copy them to another Moodle instance, but only course header data will be copied, not course content (activities for exemple).

Let me know if you have any other question.

**Comment by Kerrilit** [comment]
Thank you!
