### ISSUE TITLE
Moodle to Salesforce  - transferring enrolments 

### ISSUE THREAD

**Issue by rickyshe** [Myddleware/myddleware#196]
Hello

Thanks very much for your help.
During the process of Integrating Moodle with Salesforce.
After transferring the enrolments from Moodle to Salesforce ( user_id , course_id )
I would like the enrolment page, in Salesforce -  to display the course name .

I created Salesforce objects :
Course :
   moodle_course_name , moodle_course_id

Course enrolment : 
  moodle_user_id , lookup(Course) - field name : moodle_course_id

When I use Salesforce to insert data -  the lookup works ok - the name of the course is displayed.

Using myddleware I create a rule  using :  get enrolments by date
Mapping the fields userid and courseid - to the enrolment object in Salesforce

Trying to transfer using the rule - fails with error :

Array ( [0] => Array ( [statusCode] => MALFORMED_ID [message] => Course name: id value of incorrect type: 2 [fields] => Array ( [0] => course_id__c ) ) ) Failed to send document. Status : Error_sending

I inserted data to courses in Salesforce - there is a course id - with value : 2
I tried to define the course id in Salesforce as number and than as text
The error in both cases is : incorrect type 

Thanks and regards
Ricky.

**Comment by rickyshe** [comment]
I tried data import from csv - learned that lookup can only work with the salesforce id - or the "name"

**Comment by Myddleware** [comment]
Hi @rickyshe ,

If you want to use lookup field in SF, you have to use relationship tab in Myddleware (rule edit view) to link several Myddleware rules. If you map directly the field, you will send Moodle ID in SF. But if ou use relationship, you will send Salesforce ID. 
Here is more detail about how to manage relationship into Myddleware : https://myddleware.github.io/myddleware/#/basic_usage
![image](https://user-images.githubusercontent.com/11330301/61647251-3f21a500-acad-11e9-8fe2-5b1586cd2ad5.png)

Hope it will help.

**Comment by rickyshe** [comment]
Hello Stéphane,

Thanks very much for your reply.

The issue :
Transferring the enrolments from Moodle to Salesforce ( user_id , course_id )
The course_id is a number - I would like the enrolment page, in Salesforce - to display the course name .

Salesforce object Course fields :
Course name ( as the "salesforce name" )
Course id 

In the enrolment Salesforce object - Lookup(Course)
Transferring the enrolments to Salesforce - the course_id can't be matched to find the course object and display the course name.

To solve the issue - the course_id value must be the "salesforce name":

Salesforce object Course fields :
Course id ( as the "salesforce name" )
Course name

Since only the "salesforce name" (or the salesforce id)- can be used to match the salesforce object.

And in the enrolment object in Salesforce - there is one more field using formula to display the Course_r.course_name.

Thanks,
Ricky.

**Comment by Myddleware** [comment]
Hi Ricky,
If you want to link objects in SF, you have to use Myddleware relationships and creat 3 rules : 
 - first rule : transfer Moodle users to salesforce (SF) contact for example
 - second rule : transfer Moodle courses to a SF object (custom object, opportunity...)
 - third rule : transfer Moodle enrolment to a SF oject (custom object, relationship contact-opporutinity...)
In this third rule you will have to create 2 relationships with the first and second rule, something like that (my target field names won't be the same than yours) : 
![image](https://user-images.githubusercontent.com/11330301/61693152-543f1800-ad2f-11e9-86a2-7111779bf78c.png)

Does it help you ?

**Comment by rickyshe** [comment]
Thanks Very much ! Now works great !

**Comment by Myddleware** [comment]
Perfect, thanks for your feedback.

**Comment by rickyshe** [comment]
Hello Stéphane,

Continue the discussion of :  lookup field in SF and   Myddleware relationships
In salesforce I have CourseEnrolments ( course_id, user_id ) as discussed before.
Now I created a new object Activity Completions : 
It is related as -   Master-Detail(CourseEnr) - to CourseEnrolments 

Now when I create a new rule in myddleware - to transfer   activity completions ( get_users_completion )
In the relations tab :

![image](https://user-images.githubusercontent.com/52200359/61777997-9f782a00-ae06-11e9-98ef-2954bafb2ce7.png)

I can select either course_id or user_id - and the records after transfer are attached to one enrollment.

Thanks very much for your time and help
Ricky.

**Comment by Myddleware** [comment]
Hi @rickyshe ,
OK so you want to link activity completion to the CourseEnrolments object, not between the contact and the course in SF.

Are you developper ? Because to do what you want, you will have to add some code in custom files (upgrade safe). You will have to redifine the ID of the enrolment module in Myddleware. This ID will be <user_id>+"_"+<course_id>. You will have also to create a new field in module activity completion in Myddleware which will be also <user_id>+"_"+<course_id>. Then you will be able to link these modules.

This isn't a very difficult develpment but you have to be a developper. If yes I could guide you. Otherwise we could provide the code. In this last case, please contact us directly via our contact page in our website www.myddleware.com 

Thanks.

**Comment by rickyshe** [comment]
Hi,

I am a developer.
There are other tasks that I will have to complete before I get to the decide  regarding changing the code.
This task will wait for next stage.
We will use what we have for now.

Thanks very much,
Ricky.

**Comment by Myddleware** [comment]
No problem, let me know if you need any help.
Have a nice day,
Stéphane
