### ISSUE TITLE
How to Install myddleware on webhosting

### ISSUE THREAD

**Issue by jitendra1405** [Myddleware/myddleware#197]
Hi

I have to install myddleware on my hosting server that is Cpanel how would I achieve that.

**Comment by Myddleware** [comment]
Hi,
You can use these tutorial : https://myddleware.github.io/myddleware/#/?id=install-myddleware
Hope it will help

**Comment by jitendra1405** [comment]
php bin/console cache:clear -e prod this command is not working not giving any error

![Untitled](https://user-images.githubusercontent.com/53037241/61870255-43db9880-aefb-11e9-9ac3-24724295299c.png)

**Comment by jitendra1405** [comment]
Hi All
I am facing this error while installing the myddleware through webhosting
![Untitled](https://user-images.githubusercontent.com/53037241/61871948-c0707600-aeff-11e9-8e83-b05ee7ce9dcf.png)

**Comment by Myddleware** [comment]
I see that you are using php5.6 or you need php 7.1 or 7.2 to run Myddleware.

We will update the requierd condition in the next version.

**Comment by jitendra1405** [comment]
Thanks for the Response that issue is solved but I am facing New problem related with database
![Untitled](https://user-images.githubusercontent.com/53037241/61877193-1f3bec80-af0c-11e9-8b35-5b18490bbb41.png)

**Comment by Myddleware** [comment]
Could you please try to install Myddleware via command with this tutorial : https://myddleware.github.io/myddleware/#/?id=install-myddleware
Let me know if you could install it. 
Thanks.

**Comment by jitendra1405** [comment]
php bin/console doctrine:schema:update -f -e prod
when I execute this command I receive the same error 
![Untitled](https://user-images.githubusercontent.com/53037241/61927132-3a9d0b00-af91-11e9-9f9b-ffc4d24544bd.png)

**Comment by Myddleware** [comment]
Hi @jitendra1405 ,
You have probably an error in the parameters you have set up in the file myddleware\app\config\parameters.yml
Please check these parameters : 
![image](https://user-images.githubusercontent.com/11330301/61934705-41c01b00-af89-11e9-821a-872945774d13.png)
Thanks.

**Comment by jitendra1405** [comment]
Already done the changes still not working

**Comment by Myddleware** [comment]
Plase check first you parameters are right. Try mysql on your server. https://mariadb.com/kb/en/library/mysql-command-line-client/

Something like : mysql --user=user_name --password=your_password db_name
You can add -h with the host if your database isn't localhost (in the same server than your file)

Thanks.

**Comment by jitendra1405** [comment]
Thanks Done
