### ISSUE TITLE
0 is not a correct Rule mode. error when running rule

### ISSUE THREAD

**Issue by dawoodjee** [Myddleware/myddleware#198]
Hello

I'm connecting Unicenta POS to ERPNext. I have defined the connection details but when I try to run the rule it says **0 is not a correct Rule mode.**

`Error : 0 is not a correct Rule mode. C:\xampp\htdocs\myddleware\src\Myddleware\RegleBundle\Solutions\erpnext.php 484`

What could be the issue?

**Comment by Myddleware** [comment]
Hi,

This is really weird as this error come from here line 484 : 
![image](https://user-images.githubusercontent.com/11330301/62329107-3d2dc200-b4b5-11e9-8860-3e7b2dedd605.png)

And we test the "0" at the line 478 so your error shouldn't happen. But it happens ;)

Could you give me more detail about your rule ? A screenshot of the tab "inforations" tab of your rule should be enough. I will try to reproduce it.

Thanks.

**Comment by dawoodjee** [comment]
I think this is because the row I was getting from the database did not have a **datetime** field. All new tables I'm using, I add a **datetime** field on creation atleast. Looking for a way to automate datetime entry for a _modified_ field.

**Comment by dawoodjee** [comment]
Again, I'm sorry I lost this database so I cannot provide a screenshot. I'll do this from now on.

**Comment by Myddleware** [comment]
Ok no problem.

Just let you know that you can create a date fields in MySQL which will be updated each time you modify a record : 
![image](https://user-images.githubusercontent.com/11330301/62451476-a4c26680-b76e-11e9-9e48-0b15bf526987.png)

Have a nice day.

**Comment by kirangaruda** [comment]
> Hi,
> 
> This is really weird as this error come from here line 484 :
> ![image](https://user-images.githubusercontent.com/11330301/62329107-3d2dc200-b4b5-11e9-8860-3e7b2dedd605.png)
> 
> And we test the "0" at the line 478 so your error shouldn't happen. But it happens ;)
> 
> Could you give me more detail about your rule ? A screenshot of the tab "inforations" tab of your rule should be enough. I will try to reproduce it.
> 
> Thanks.

There is a typo Change the variable $RuleMode to $ruleMode. It worked for me
