### ISSUE TITLE
Notice: Undefined index: values in C:\xampp\htdocs\myddleware\src\Myddleware\RegleBundle\Controller\DefaultController.php on line 1210

### ISSUE THREAD

**Issue by dawoodjee** [Myddleware/myddleware#200]
Im creating a new rule for Mysql to ERPNext

The Simulate > Test Data button is giving me the above error. The error is repeated the according to the number variables used.

**Comment by Myddleware** [comment]
OK, when you try to simulate, the read_last function doesn't retrun values even if it return that it could read properly in ERPNext.

I would like to reproduce this error. Could you provide a screenshot of the 'information" tab and the "Mapping of the fields" tab of your rule please ?  

Thanks

**Comment by dawoodjee** [comment]
Thank you for your response. It seems like the issue was because I did not set the some fields were empty for the affected rule.

I'm sorry I cannot reproduce the error after losing my last database due to a Xampp Mysql issue.
