### ISSUE TITLE
What is the right way to format dates in Myddleware?

### ISSUE THREAD

**Issue by dawoodjee** [Myddleware/myddleware#202]
I have tried so many combinations. But I can't seem to get it right. It's either I get an exception or more frequently ends up at **(i)... Please Wait...**

Here is a screenshot of my formula and the resulting exception. Please help!

![date](https://user-images.githubusercontent.com/7912989/62502451-cadc1b00-b7ef-11e9-8852-8493912bcc9a.PNG)

![date2](https://user-images.githubusercontent.com/7912989/62502458-d0d1fc00-b7ef-11e9-9425-342577d6d726.PNG)

Other combinations I've tried:
- changeFormatDate( {Modified},"Y-m-d H:i:s", "Y-m-d" )
- changeFormatDate( {Modified}, "Y-m-d" )
- changeFormatDate( {Modified},"Y-m-d H:i:s" )

**What I want:**
- 2019-08-02
- 2019

**Comment by Myddleware** [comment]
Hi,
Could you try this : changeFormatDate( {Modified},"Y-m-d H:i:s.u", "Y-m-d" )
Does it work ? 
Stéphane

**Comment by dawoodjee** [comment]
Wow, that worked!

How can I use this with `date()` to get the current datetime and format it as I like?

e.g: changeFormatDate( date("Y-m-d") ,"Y-m-d H:i:s.u", "Y" )

**Comment by dawoodjee** [comment]
Got it.
**changeFormatDate( date("Y-m-d") ,"Y-m-d H:i:s.u", "Y" ) takes 3 args:** 
- The input
- Input format
- and required output format

**date() creates the required format according to what is passed**
- date('Y') returns 2019
- date('d-m-Y') returns 06-08-2019, etc

This was helpful https://www.php.net/manual/fr/function.date.php 

Thanks!

**Comment by Myddleware** [comment]
Thanks for your feedback.
