### ISSUE TITLE
[ERROR]  Failed: The command "php../bin//console cache:clear --env=prod"

### ISSUE THREAD

**Issue by celloguerra** [Myddleware/myddleware#203]
I'ḿ trying to install Myddleware but got thie following error:
[ERROR] 
Failed: The command "php /home/piqui083/public_html/ead/myddleware/app/../bin//console cache:clear --env=prod" failed. Exit Code: 255(Unknown error) Working directory: /home/piqui083/public_html/ead/myddleware/web Output: ================ Content-type: text/html 
Parse error: syntax error, unexpected ':' in /home/piqui083/public_html/ead/myddleware/web/installMyddleware.php on line 186
Error Output: ================ 
![AwesomeScreenshot-ead-financieracademy-br-myddleware-web-installMyddleware php-2019-08-06_6_33](https://user-images.githubusercontent.com/86768/62578941-cf004b00-b878-11e9-93ba-247940227039.png)

**Comment by Myddleware** [comment]
Hi,
Could you tell me which php version you use ? 
Thanks.

**Comment by celloguerra** [comment]
We are using PHP 7.1

**Comment by Myddleware** [comment]
Perfact, that's good.
Could you try to  install Myddleware via command by following this tutorial: https://myddleware.github.io/myddleware/#/?id=install-myddleware

Thanks.
