### ISSUE TITLE
What is the best way to host Myddleware when one of the data sources is on a LAN? 

### ISSUE THREAD

**Issue by dawoodjee** [Myddleware/myddleware#206]
For example MS SQL to self-hosted ERPNext solution, with MS SQL being on the LAN and ERPNext on a VPS.

Here are my thoughts so far:

1. Option 1 - LAN Replication
- LAN-first datasource (MS SQL): Installed on LAN
- Myddleware: Installed on LAN syncs to 
- Self-hosted ERPNext datasource: Installed on LAN

   Then replicate the ERPNext instance to the one one the VPS

2. Option 2 - Hybrid
- LAN-first datasource (MS SQL): Installed on LAN and replicated to cloud
- Myddleware: Installed on Cloud and connects both cloud solutions
- Self-hosted ERPNext datasource: Installed on Cloud

3. Or can myddleware detect network conditions and sync only when it can reach both datasources?

**Comment by Myddleware** [comment]
Hi,
Sorry, not sure I understand what you want.

But Myddleware won't test both datasource before sync. Here are the step Myddleware for the sync : 
1. Myddleware connects the source application and read new data. If the datasource isn't available, nothing happens and Myddleware will try again when the sync job will run.
2. Myddleware transfor and chek data read
3. Myddelware connects the target application and send data. If the target application isn't available, Myddleware will set the status "Error sending" to the data transfer in Myddleware. Myddleware will try to send this data transfer again when the job which rerun the errors will run.

Hope I answer your question.

**Comment by dawoodjee** [comment]
Thats helpful. Thank you!
