### ISSUE TITLE
Installation without Root Access

### ISSUE THREAD

**Issue by Inbroch** [Myddleware/myddleware#207]
I have a shared hosting service and use CPanel to manage it. I have worked out the issue to be the lack of access to the php.ini file on the server. If I were to get a copy of the files my host (and very wisely) doesn't allow me to access, and put it into a directory I have access to, am I able to change where the installation is trying to check the "force-cgi-redirect" value and any other surprises I might find along the way given the limitation? Everything else is fine as I'm given the "Your system is fine to run Myddleware" teaser when I boot the installation page.

**Comment by Myddleware** [comment]
Hi @Inbroch ,

Could you try to install Myddleware via a SSH command by following this : https://myddleware.github.io/myddleware/#/?id=install-myddleware

Please, let me know if it works.
