### ISSUE TITLE
Clean install. Can not log into Myddleware

### ISSUE THREAD

**Issue by dawoodjee** [Myddleware/myddleware#208]
I have gone through the command-line installation process on Ubuntu. All done successfully (twice) but cannot login using the web interface. Myddleware does not seem to go further than the login page. No errors are shown.

Here are my installation details:

OS: Ubuntu 18
PHP. 7.2
Webserver: Nginx
Mysql user is root. The whole installation was done using the Ubuntu root user.

Could this be an nginx problem where redirected back to the login page after login?

```
server {
    root /var/www/html/myddleware.xxxxx.com/web;
    server_name myddleware.xxxxx.com;
    #index  index.php index.html index.htm;

    location / {
        # try to serve file directly, fallback to app.php
        try_files $uri /app.php$is_args$args;
    }
    # DEV
    # This rule should only be placed on your development environment
    # In production, don't include this and don't deploy app_dev.php or config.php
    location ~ ^/(app_dev|config)\.php(/|$) {
        fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }
    # PROD
    location ~ ^/app\.php(/|$) {
        fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        internal;
    }

    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/myddleware_error.log;
    access_log /var/log/nginx/myddleware_access.log;

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/myddleware.xxxxx.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/myddleware.xxxxx.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = myddleware.xxxxx.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name myddleware.xxxxx.com;
    listen 80;
    listen [::]:80;
    return 404; # managed by Certbot


}
```

**Comment by Myddleware** [comment]
Could you first check you database, is it created successfully ? If yes could you open the user table et check that the user you have created is present ?

**Comment by dawoodjee** [comment]
MariaDB [myddleware]> select password, username from users;
+------------------------------------------------------------------------------------------+----------+
| password                                                                                 | username |
+------------------------------------------------------------------------------------------+----------+
| egTkBHOx19OzPIwKkGLEEmc6bE1vKfCUpga0I2d0A4SvKrIMMvf1kxxrbRbfa0C9DETSTFUvgpQbopcd9HbroQ== | support  |
+------------------------------------------------------------------------------------------+----------+
1 row in set (0.00 sec)

**Comment by Myddleware** [comment]
That's great.

Could you try to log into Myddleware with the Myddleware dev environement. You just have to add app_dev.php at the end of your URL : http://<path_to_Myddleware_root>/web/app_dev.php

Do you have an error displayed ?

**Comment by dawoodjee** [comment]
(2/2) ContextErrorExceptionWarning: file_put_contents(/var/www/html/myddleware.xxxxx.com/var/cache/dev/appDevDebugProjectContainerDeprecations.log): failed to open stream: No such file or directory
--
in Kernel.php line 642
at Kernel->initializeContainer()in Kernel.php line 135
at Kernel->boot()in Kernel.php line 195
at Kernel->handle(object(Request))in app_dev.php line 19


(1/2) RuntimeExceptionUnable to create the cache directory (/var/www/html/myddleware.xxxxx.com/var/cache/dev)
--
in Kernel.php line 759
at Kernel->buildContainer()in Kernel.php line 636
at Kernel->initializeContainer()in Kernel.php line 135
at Kernel->boot()in Kernel.php line 195
at Kernel->handle(object(Request))in app_dev.php line 19

**Comment by Myddleware** [comment]
OK, your webuser has no right on the log and cache directory. You didn't get the warning during the installation because you have installed with command line (without the web user).
So coudl you give the right to you webuser to write into log and cache directories : 

- myddleware\var\logs

- myddleware\var\cache

Please let me know if it works.

**Comment by dawoodjee** [comment]
Absolutely correct! 

```
sudo chmod -R 755 /var/www/html/myddleware.xxxxx.com
sudo chown -R www-data:www-data /var/www/html/myddleware.xxxxx.com
```

Did the trick. I did the same for my first install so didn't for the second because it had not helped. 

Thanks alot!

**Comment by Myddleware** [comment]
Thanks for your feedback.
