### ISSUE TITLE
Internal server Error - When deleting Connector in 2.4.1

### ISSUE THREAD

**Issue by GaneshKandu** [Myddleware/myddleware#209]
Hi,

I am getting internal server error while deleting Connectors in Myddleware 2.4.1
```
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please e-mail us at contact@myddleware.com and let us know what you were doing when this error occurred. We will fix it as soon as possible.
You can also log the issue on our Github : Myddleware Github project

Sorry for any inconvenience caused.
```
i reproduced same error in demo [link](http://livedemo.myddleware.com/myddleware/web) also

**Comment by Myddleware** [comment]
Hi @GaneshKandu ,

You are right, we will catch this error in the next release. 

The connector you want to remove is probably linked to one of your rule. Please delete your rule first then the connector.

**Comment by GaneshKandu** [comment]
Ok! @Myddleware  deleting rule works
