### ISSUE TITLE
Moodle source connector not transfering to SuiteCRM

### ISSUE THREAD

**Issue by williamwithin** [Myddleware/myddleware#211]
I am unable to get the Moodle source connector to transfer to SuiteCRM. I have installed the plugin, set the role for the user, set up the webservices, custom external service functions and token in Moodle as instructed. 

When setting up the rule, the simulation pulls the first record correctly. When I run the rule, there is no log and no transfers.

Any suggestions on how to troubleshoot this issue?

Also note, I have been able to successfully transfer from MySQL to SuiteCRM with Myddleware.

SuiteCRM version 7.10.9
Moodle version 3.7
Myddleware version v2.4.1l

**Comment by Myddleware** [comment]
Hi @williamwithin ,

Thanks for your interest in Myddleware.

You problem comes probably from the reference date in the rule detail view. Here is more information about this parameter : https://myddleware.github.io/myddleware/#/basic_usage?id=rule-parameters

If you want to read all your data, you have to set a date far in the past.

Please let me know if it works now.

**Comment by williamwithin** [comment]
Thank you for the quick response. Your suggestion resolved my issue.
