### ISSUE TITLE
Problems developing a connector: You have requested a non-existent service

### ISSUE THREAD

**Issue by williamwithin** [Myddleware/myddleware#215]
Hello, I am starting the process of developing a connector based off the moodle connector.

I have been following the developer's guide on your website.

I added the new connector to the Solutions table in the database (active=1, source=1, target=1)

I added the new service to src/Myddleware/RegleBundle/Resources/config/services.yml.

I have copied the relevant moodle files to the new service name (./src/Myddleware/RegleBundle/Solutions/lib/lib_newmoodle.php, ./src/Myddleware/RegleBundle/Solutions/lib/newmoodle, ./src/Myddleware/RegleBundle/Solutions/newmoodle.php,./src/Myddleware/RegleBundle/Resources/public/images/solution/newmoodle.png), changing the class names where needed (s/moodle/newmoodle/).

When I try to create an instance of the new connector, I get this error in the log var/logs/prod.log:

request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "myddleware_rule.newmoodle".

Is there somewhere else that the new service has to be registered before being recognized?
Or do you have any other suggestions to resolve this issue?

Thanks

**Comment by Myddleware** [comment]
Hi @williamwithin ,
Thanks for trying to create a connector. Could you tell me which application you plan to connect ? 
About your problem, firstly let's check if it comes from the cache. 

Could you please use the dev environment URL by changing app.php by app_dev.php in your url? Dev environement don't use the cache.

**Comment by williamwithin** [comment]
For now I am just learning about connectors by copying an existing one. All I have done so far is try to copy the moodle connector.

Using the app_dev.php, the getFieldsLogin connection parameters are now displayed when I choose the new solution (create connector). 

How do I now make it work with the production URL?

Thanks for your help

**Comment by Myddleware** [comment]
To work with the production URL, you just have to clear the cache by running the command you will find here https://symfony.com/doc/3.4/console/usage.html
Or you can just remove the directory var/cache/prod

**Comment by williamwithin** [comment]
Ok I cleared the cache with `php bin/console cache:clear --env=prod` and now my username and password are not working with the production URL!

**Comment by Myddleware** [comment]
If your username and pasword work in dev it should work in production too, all environment use the same database.
Could you just check that your web user can write into the prod cache directory ?
What you can do is just remove the prod directory and try to log again, your web user will create the prod directory and will have the permission to write into it.

**Comment by williamwithin** [comment]
I guess clearing the cache via command line recreated the cache/prod directory with the wrong permissions. I did a `chown` on the prod directory for the web user and it works again!

Thanks again

**Comment by Myddleware** [comment]
Yes it depends the user you use to clear the cache and how your server is configured.
Thanks for your feedback.
