### ISSUE TITLE
How to delete a rule?

### ISSUE THREAD

**Issue by williamwithin** [Myddleware/myddleware#216]
I am trying to delete a rule, but I get this error message:

Failed to delete the rule because data has been successfully sent via this rule.

I would like to delete the rule because I'm not using it any more.

**Comment by Myddleware** [comment]
Yes, you can't remove a rule if there is one data transfer send  using this rule. 

If you want to delete a rule, you have to delete the data transfer first. But it isn't possible in the current Myddleware version, it is available only on our 2.4.2 branch wich will be released next week.
So you can wait for the next release or run queries directly in your database to remove or cancel the data transfer of your rule.

**Comment by williamwithin** [comment]
It's not clear what tables I would be targeting. If you could point me in the right direction I would appreciate it. Thanks!

**Comment by Myddleware** [comment]
The best way is to cancel all documents. 

You have to set 'Cancel' into 2 colums : status and global_status in the table document. Don't forget to filter by rule_id otherwise you will cancel all documents in your database.

**Comment by williamwithin** [comment]
Thanks, that did the trick.
