### ISSUE TITLE
Handle ORACLE database

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#219]
In a new business scenario I need to sync from an ORACLE database, what the best approach to do this?

**Comment by Myddleware** [comment]
Hi,
We already connect MySQL (MariaDB) and MSSQL but not Oracle yet. If you look into the directory myddleware\src\Myddleware\RegleBundle\Solutions, you will see the database class and 2 child classes : mysql and microsoftsql. We have just redefined the database classe to add the specifity of all kind of database.

So to connect Oracle, you have to create a new connector class (oracle) like we have created mysql and microsoftsql classes. Then you have to add the specifities of Oracle in your class.
To create a new connector you can follow this tuto : https://myddleware.github.io/myddleware/#/dev_guide

If you are not a developer or if you don't want to develop it, we can do it for you.
