### ISSUE TITLE
Field mapping with custom profile fields created in moodle

### ISSUE THREAD

**Issue by VirasatSolutions** [Myddleware/myddleware#220]
Hello,
I have created custom profile field in moodle. Now i want to map these fields with salesforce using myddleware but there is no way to get the custom profile fields. Please help...

**Moodle custom profile fields:**
![profile custom fields](https://user-images.githubusercontent.com/46476772/66104170-5f3ae200-e5d5-11e9-9b43-516132d8eb3c.PNG)

**Myddleware allow us to mapping fields with salesforce:**
![screenshot-localhost-2019 10 01-17_41_13](https://user-images.githubusercontent.com/46476772/66104219-80033780-e5d5-11e9-952c-a973b262aff5.png)

**Comment by Myddleware** [comment]
HI,
Myddleware doens't manage custom Moodle fields for now. But we can see that is possible as the function core_user_get_users return custom fields.
If you want these custom fields, it will be necessary to improve Moodle connector into Myddleware. The file to adapt is myddleware\src\Myddleware\RegleBundle\Solutions\moodle.php , method read. 

If you are developer and want to adpat the code, please share what you develop with us. It could be a great contribution to our open source project.
If you want us to adapte the code, please contact us directly using our website, contact form.

Have a nice day.

**Comment by pickettd** [comment]
Hi @Myddleware 

I'm interested in trying to add at least one specific custom profile field for my Moodle (both as a source and a target). My understanding from looking at the code here (src/Myddleware/RegleBundle/Solutions/moodle.php) is that I'm supposed to be able to put the new custom logic in a file called src/Myddleware/RegleBundle/Custom/Solutions/moodle.php but I'm having trouble getting any code I put in that file to load/process properly. I saw in the documentation that this [link to best practices](http://community.myddleware.com/index.php/section/good-practices/) is supposed to describe how to add custom code in an upgrade-safe way but it is an empty article.

Could you provide a template for the file src/Myddleware/RegleBundle/Custom/Solutions/moodle.php ?

I tried putting in the following for the Custom/Solutions/moodle.php file as a first test
```
<?php

class moodle extends moodlecore {
}
```
but got errors that seem to say that the moodle class couldn't be found in the namespace "Myddleware\RegleBundle\Solutions"

Thanks!
-David

**Comment by Myddleware** [comment]
Hi David,
Could you try this : 
```
namespace Myddleware\RegleBundle\Solutions;

use Symfony\Bridge\Monolog\Logger;

// Moodle class enhancement
class moodle extends moodlecore {
	
	
}
```

**Comment by Myddleware** [comment]
You can also redefine the file Solutions/lib/moodle/metadata.php by creating your custim file in Custom/Solutions/lib/moodle/metadata.php'

**Comment by pickettd** [comment]
Thank you @Myddleware and sorry for the slow reply. This advice did work for me! In case it is helpful for anyone else coming to this issue, you are welcome to see my custom files here:

- [My custom Moodle.php file](https://github.com/pickettd/myddleware/blob/master/src/Myddleware/RegleBundle/Custom/Solutions/moodle.php)
- [My custom Moodle metadata.php file](https://github.com/pickettd/myddleware/blob/master/src/Myddleware/RegleBundle/Custom/Solutions/lib/moodle/metadata.php)

In my particular case, I am just learning PHP at the same time as writing this custom code (so please excuse mistakes/mess). I took the approach of detecting that the Moodle customfields parameter was supposed to be part of create/read/update and then currently I hardcoded in the couple of sub-fields that I want to be able to sync (child1_email and child2_email). My use-case is that in my Moodle site, we want to support parents creating a parent-type account and being connected to their children's student-type account using Moodle custom profile fields (and we are syncing these accounts/profiles to/from Salesforce).

**Comment by Myddleware** [comment]
That's great. Thank you for your feedback and the code you shared.
Well done !
