### ISSUE TITLE
Control Panel Error

### ISSUE THREAD

**Issue by luolgon** [Myddleware/myddleware#223]
in my url myddleware/web/app_dev.php/rule/panel/ is reporting the error Table has no columns. The information for my created rules does not appear. How should I solve this problem?

**Comment by Myddleware** [comment]
Hi @luolgon ,
Could you post a screenshot please ? Thanks.

**Comment by luolgon** [comment]
> Hi @luolgon ,
> Could you post a screenshot please ? Thanks.

I managed to solve. Everything is ok now. thanks for listening.

**Comment by Myddleware** [comment]
Great. 
Thanks for telling us.
