### ISSUE TITLE
"1146 Table doesn't exist" après installation réussie.

### ISSUE THREAD

**Issue by tarvathorg** [Myddleware/myddleware#225]
Bonjour !

Après avoir installé myddleware, je reçois un message d'erreur lors de ma tentative de connexion.

An exception occurred while executing 'SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_token AS confirmation_token_9, t0.password_requested_at AS password_requested_at_10, t0.roles AS roles_11, t0.id AS id_12 FROM users t0 WHERE t0.username_canonical = ? LIMIT 1' with params ["clementsanmartin"]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbs205268.users' doesn't exist ( 1 )

Ce problème ressemble à [celui-ci](https://github.com/Myddleware/myddleware/issues/42), traité en décembre 2017

De mon côté, le fichier app/config/parameter.yml renseigne correctement les informations d'accès à la bdd. 

Après malheureusement, je suis novice en code et je ne sais pas comment ni où regarder pour m'assurer que le MySQL user a les bons droits pour créer une table. Ceci dit, la bdd et l'utilisateur ont été créés en même temps et j'imagine que c'est un utilisateur admin... Je suis sur un serveur chez IONOS qui utilise phpmyadmin, je ne crois pas pouvoir accéder au serveur en lignes de commande et je ne vois pas d'onglet "privilèges" ou "utilisateurs" dans l'interface de phpmyadmin. 

NB : Dans le guide d'installation de myddleware, [l'étape 1.3](http://community.myddleware.com/index.php/installation-guide/?lang=fr#copying-files-to-web-server) requière l'accès en écriture à certains dossiers et fichiers. Je les ai paramétrés (664 pour les fichiers et 775 pour les dossiers, comme suggéré par Stephane [ici](https://github.com/Myddleware/myddleware/issues/152#issuecomment-473257022)). Mais j'ai l'impression que cela créer une faille de sécurité, le fichier parameters.yml est entre autres visible de tous. Ne devrais-je pas plutôt bloquer l'accès en lecture au public (660 et 770) ?

Merci pour votre aide !

**Comment by Myddleware** [comment]
Bonjour @tarvathorg ,
Je pense que votre base de données n'a pas été créée. Est-ce que vous pouvez naviguer dans la base de données via phpMyadmin et confirmer que la base de données ne contient pas de table ? 

Pour ce qui est des droits, oui vous pourrez les changer en 660 ensuite en fonction de la configuration du serveur. Mais pour l'instant vous pouvez les laisser comme cela 664 et 775. On va d'abord tenter vous débloquer.
Stéphane

**Comment by tarvathorg** [comment]
Bonjour Stéphane @Myddleware,
Je confirme. J'ai même ce message sur la page "Aucune table n'a été trouvée dans cette base de données."
D'accord pour les droits je les repasse en 664 et 775 pour le moment.

**Comment by Myddleware** [comment]
Bonjour @tarvathorg ,
Si la base de données n'existe pas alors Myddleware ne peut pas fonctionner. Avez-vous suivi ce tutoriel pour installer Myddleware : https://myddleware.github.io/myddleware/#/?id=install-myddleware

Si oui quelle erreur avez-vous rencontré pendant l'installation ? 

Si vous avez un accès ssh à votre serveur, vous pouvez également tenter d'installer Myddleware en utilisant ce tutoriel : https://myddleware.github.io/myddleware/#/?id=setting-up-your-myddleware-environment

Bonne journée.

**Comment by Myddleware** [comment]
En relisant votre post je vois que vous avez suivi le tuto. Quelle erreur avez-vous rencontré alors ?
Merci.

**Comment by tarvathorg** [comment]
Bonjour,

Eh bien, l'installation en elle même a semblé s'être correctement effectuée . J'avais la ligne de confirmation verte "OK votre système est prêt" à laquelle je ne peux plus accéder (apparemment le fichier webinstallmyddleware.php a été supprimé automatiquement). Puis j'ai inscrit comme demandé les informations de la bdd et ai créé un nouvel utilisateur et lors du login j'ai le message d'erreur que je vous ai présenté dans le premier message de ce thread. Voici le screenshot de l'erreur :

![screenshot](https://lecompositeur.com/dl/myddleware-screenshot1.png)

Edit : Je vais tenter l'installation via SSH, j'ai finalement trouvé l'accès au serveur en ligne de commandes.

**Comment by Myddleware** [comment]
Super, tenez moi au courant si vous arrivez à faire l'installation.
Bonne journée

**Comment by tarvathorg** [comment]
Après avoir installé PuTTY et lancé la commande _php bin/symfony_requirements_ sur le serveur, voici ce que j'obtient 
![screenshot2](https://lecompositeur.com/dl/myddleware-screenshot2.png)

Pas fameux donc... j'ai l'impression que ça me renvoi une erreur à cause de _myddleware/_ dans la commande. C'est ça ?

Précisions : 
1. Myddware est installé sur le site distant dans le dossier "myddleware", parce que j'ai d'autres services installés à la racine dans d'autres dossiers. 
2. De plus, il ne m'est possible de me connecter qu'avec l'utilisateur principal qui a forcément accès à la racine (impossible de changer le dossier par défaut pour ne pas avoir besoin d'écrire _myddleware/_).
3. Je ne suis pas reparti de zéro en supprimant tout (j'ai gardé le dossier importé sur le ftp et la bdd en l'état)

**Comment by Myddleware** [comment]
Très bien, pouvez-vous me donner votre version de Myddleware et la version de php sur votre serveur (suffit de faire php -v dans Putty) ?
Merci.

**Comment by tarvathorg** [comment]
Depuis PuTTY : 
PHP 4.4.9 (cgi-fcgi) (built: Aug 29 2019 12:59:15)
Copyright (c) 1997-2008 The PHP Group
Zend Engine v1.3.0, Copyright (c) 1998-2004 Zend Technologies

Mais depuis l'interface d'Ionos : 
version PHP du domaine sync.lecompositeur.com : PHP 7.3
(je crois qu'il est impossible que j'utilise PHP 4.4 étant donné que j'ai créé le sous domaine fin octobre (automatiquement avec la version recommandée d'Ionos : PHP 7.3)

__

Depuis mon historique de téléchargements Chrome : 
http://www.myddleware.com/media/myddleware/2.4.1/myddleware.zip

**Comment by Myddleware** [comment]
Je comprends. En fait la version php utilisé par ton navigateur est la 7.3 et la version utilisé  par php est la 4.4. Mais Myddleware est compatible PHP 7.1 et 7.2.
Donc il faudrait changer ces version ou changer de serveur si vous avez d'autres application sur ce serveur qui ont besoin de php 4.
La version php 7.3 n'est pas exclue sur Myddleware 2.4, on teste que php >= 7.1. Le contrôle est ajouté sur Myddleware 2.5 qui sortira ce mois-ci.

**Comment by tarvathorg** [comment]
D'accord. Je ne peux pas changer la version serveur de php (seul Ionos peut modifier ça et le contact qui m'a reçu m'a indiqué "on utilise la dernière version stable pour serveur"). 

En revanche je viens de downgrader vers la version navigateur 7.2. Est-ce suffisant pour retenter une installation ? Je viens de tenter la commande php bin/symfony_requirements dans PuTTY et toujours ce message d'erreur :

(uiserver):*****:~$ php myddleware/bin/symfony_requirements
X-Powered-By: PHP/4.4.9
Content-type: text/html
<b>Parse error</b>:  syntax error, unexpected T_STRING, expecting ')' in <b>/homepages/4/d478885636/htdocs/myddleware/bin/symfony_requirements</b> on line <b>77</b>



Que devrais-je faire ?

**Comment by Myddleware** [comment]
Bonjour @tarvathorg ,
Désolé pour le délais. Il est necessaire d'avoir une version serveur php compatible car Myddleware utilise souvent les commande en tâche de fond lancées par le serveur.
Il faudrait utiliser un autre serveur ou bien selectionner l'offre Cloud avec 30 jours gratuits de notre partenaire platform.sh (lien sur notre page d'acceuil, votre Myddleware est créé en 2 minutes).
Bonne journée.

**Comment by tarvathorg** [comment]
Bonjour Stéphane @Myddleware ,
Merci pour la précision. J'ai questionné mon conseiller personnel pour comprendre le mode de fontionnement d'Ionos et ai reçu cette réponse :
> "Je vous confirme que les applications installées sur votre espace web utilisent par défaut la version PHP associée au nom de domaine auquel elles sont liées.
> Quant à la version PHP en SSH, elle intervient uniquement si vous exécutez des scripts SHELL, BASH, etc.
> En outre, en SSH vous disposez de plusieurs versions PHP. Il vous suffit pour l'exécution dans une version donnée de la préciser dans la commande (par exemple: php7.0, pour exécuter une commande en PHP 7.0)."

Ce qui implique, si je comprends bien, que l'application myddleware fait bien appel à la version 7.2 installée sur le sous domaine en question. Je me trompe ? Le problème vient-il vraiment de la version php, sachant que d'après mon conseiller le serveur permet d'exécuter des commandes des versions récentes ? Honnêtement, j'ai du mal à comprendre l'incompatibilité..

Merci pour le temps que vous prenez pour ce thread.

**Comment by Myddleware** [comment]
Bonjour @tarvathorg ,

Très bien donc si vous envoyer la commande suivante sur votre serveur
`  php7.2 -v `
Alors vous avez bien une réponse du serveur avec un version de php 7.2.xxx

Dans ce cas, il vous suffit de changer la version de php utilisé par Myddleware dans le fichier de configuration myddleware\app\config\public\parameters_public.yml
Pour cela ajoutez seulement 7.2 derrière php comme cela: 
![image](https://user-images.githubusercontent.com/11330301/68958272-0d889880-07cc-11ea-8ecd-00c8fa924986.png)

N'oubliez pas de vider le cache (vider dossier var/cache)

Myddleware utilisera ensuite la version php7.2 de votre serveur pour toutes les commandes lancées en tâche de fond.

En espérant que cela vous débloquera.
