### ISSUE TITLE
CRON job issue

### ISSUE THREAD

**Issue by NickRedfern** [Myddleware/myddleware#23]
Rules run fine from within the application but when scheduled to run in cron, this error occurs:
PHP Notice:  Undefined index: argv in /home/ghtest/public_html/myddleware/vendor/symfony/symfony/src/Symfony/Component/Console/Input/ArgvInput.php on line 55 PHP Warning:  array_shift() expects parameter 1 to be array, null given in /home/ghtest/public_html/myddleware/vendor/symfony/symfony/src/Symfony/Component/Console/Input/ArgvInput.php on line 59 PHP Warning:  Invalid argument supplied for foreach() in /home/ghtest/public_html/myddleware/vendor/symfony/symfony/src/Symfony/Component/Console/Input/ArgvInput.php on line 281
Status: 500
X-Powered-By: PHP/5.6.30

**Comment by Myddleware** [comment]
Hi Nick,
Could you tell me the version of Myddleware ? You can see it in the footer when you open Myddleware.
Could you show me what is the command you have added in your cron ? Thanks.

Here is an article which could help you : https://myddleware.github.io/myddleware/#/cron_jobs

Have a nice day.

**Comment by NickRedfern** [comment]
Yes, we are using V 2.1.0 and the cron job is 

php www/myddleware/app/console myddleware:synchro ALL  –env background

Thanks

Nick

**Comment by Myddleware** [comment]
Sorry Nick,

I have just seen there is a mistake in the tutorial. There is 2 “-“ before “env=…” not only one. And it would be better to add “=” between “env” and  “background”.

So you command should be : php www/myddleware/app/console myddleware:synchro ALL --env=background

Please, let us know if it works now. Thanks.

**Comment by NickRedfern** [comment]
Unfortunately still getting an error:

PHP Notice:  Undefined index: argv in /home/ghtest/public_html/myddleware/vendor/symfony/symfony/src/Symfony/Component/Console/Input/ArgvInput.php on line 55 PHP Warning:  array_shift() expects parameter 1 to be array, null given in /home/ghtest/public_html/myddleware/vendor/symfony/symfony/src/Symfony/Component/Console/Input/ArgvInput.php on line 59 PHP Warning:  Invalid argument supplied for foreach() in /home/ghtest/public_html/myddleware/vendor/symfony/symfony/src/Symfony/Component/Console/Input/ArgvInput.php on line 281

Status: 500

X-Powered-By: PHP/5.6.30

Content-Type: text/html; charset=UTF-8

**Comment by Myddleware** [comment]
We will find a solution ;)
Could you try to change the “php” command by “php-cli” or “php_cli” ?
So your command should be : 
php-cli www/myddleware/app/console myddleware:synchro ALL --env=background
or
php_cli www/myddleware/app/console myddleware:synchro ALL --env=background

**Comment by NickRedfern** [comment]
We have a solution :) It worked with php-cli 

 

Many Thanks

Nick

**Comment by Myddleware** [comment]
This is great.
Have a nice day.
