### ISSUE TITLE
Upgrading Myddleware

### ISSUE THREAD

**Issue by z3n4j** [Myddleware/myddleware#235]
This is the screen shoot regarding the error whenn upgrading Myddleware.

[root@localhost myddleware]# php bin/console myddleware:upgrade --env=background
PHP Warning:  Module 'PDO' already loaded in Unknown on line 0
PHP Fatal error:  Cannot declare class AppKernel, because the name is already in use in /home/janez/myddleware/myddleware/vendor/white-october/pagerfanta-bundle/TestsProject/app/AppKernel.php on line 24
[root@localhost myddleware]#

**Comment by Myddleware** [comment]
Hi,
COuld you try to run these command : 
`php bin/console cache:clear -e background`
`php composer.phar install --no-plugins`

Then re try the upgrad one : 
`php bin/console myddleware:upgrade --env=background`

**Comment by z3n4j** [comment]
[root@localhost myddleware]# php bin/console cache:clear -e background
PHP Warning:  Module 'PDO' already loaded in Unknown on line 0
Could not open input file: bin/console
[root@localhost myddleware]#

**Comment by z3n4j** [comment]
[root@localhost janez]# php composer.phar install --no-plugins
PHP Warning:  Module 'PDO' already loaded in Unknown on line 0
Do not run Composer as root/super user! See https://getcomposer.org/root for det                                                                                                                                                             ails
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
PHP Warning:  Module 'PDO' already loaded in Unknown on line 0
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
PHP Warning:  Module 'PDO' already loaded in Unknown on line 0

 // Clearing the cache for the dev environment with debug true                                                                                                                                                                               

                                                                                                                                                                                                                                             
 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.                                                                                                                                                                 
                                                                                                                                                                                                                                             

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets
PHP Warning:  Module 'PDO' already loaded in Unknown on line 0

 Trying to install assets as relative symbolic links.

 --- ------------------------------ ------------------
      Bundle                         Method / Error
 --- ------------------------------ ------------------
  ✔   FrameworkBundle                relative symlink
  ✔   WhiteOctoberPagerfantaBundle   relative symlink
  ✔   LoginBundle                    relative symlink
  ✔   RegleBundle                    relative symlink
  ✔   FOSJsRoutingBundle             relative symlink
  ✔   SensioDistributionBundle       relative symlink
 --- ------------------------------ ------------------

                                                                                                                                                                                                                                             
 [OK] All assets were successfully installed.                                                                                                                                                                                                
                                                                                                                                                                                                                                             

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFi                                                                                                                                                             le
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::removeSymfonyStandard                                                                                                                                                             Files

**Comment by z3n4j** [comment]
[root@localhost janez]# php bin/console myddleware:upgrade --env=background
PHP Warning:  Module 'PDO' already loaded in Unknown on line 0
Could not open input file: bin/console

**Comment by Myddleware** [comment]
Hi,
Could you tell me what is your php version ? 
Thanks.

**Comment by z3n4j** [comment]
PHP Version 7.2.25

**Comment by Myddleware** [comment]
Could you try to make a clean installation of Myddleware last version on your server ? Do you have the same error on this clean installation ? 
Thanks.
