### ISSUE TITLE
slow login

### ISSUE THREAD

**Issue by Alexandre17220** [Myddleware/myddleware#239]
Hi all,

I use myddleware to synchronize Prestashop and Suitecrm (customers, orders, products, category)
Myddleware  work since 3 years.
But now when I want to login, myddleware is very very slow, 30minutes to get this screen:
![image](https://user-images.githubusercontent.com/7665521/70617744-9818b800-1c11-11ea-9b1a-7c688473dee8.png)

How to accelerate it ? maybe delete some old data?
database:
![image](https://user-images.githubusercontent.com/7665521/70617720-8b945f80-1c11-11ea-9835-c9ef9a62d337.png)

Thanks,

**Comment by Myddleware** [comment]
Hi @Alexandre17220 ,
Yes you are right, we have a performance issue on the home page when Myddleware has generated more than 2 millions of data transfers. We will work on this to improve these performances.

In the meantime, here is a workaround : you can skip the homepage by using this url when you connect to Myddleware, it will redirect you directly to the data transfer search  : <Myddleware_URL>/rule/flux/list/search-0

Have a nice day.

**Comment by Alexandre17220** [comment]
Hi, this link make 404
I find this :
xxxxx/web/app.php/rule/list/
Thanks for the tip,
