### ISSUE TITLE
[SuiteCRM <-> Prestashop] problem too much element modify in Prestashop

### ISSUE THREAD

**Issue by Alexandre17220** [Myddleware/myddleware#240]
Hi all,
I have a problem, I create a bidirectionnal rule to ling Prestashop and SuiteCRM.
I must only update 6 product's fields :
![image](https://user-images.githubusercontent.com/7665521/70701126-22255700-1ccc-11ea-9a54-42afa0587f99.png)

When I trace webservice call to put date from SuiteCRM in Prestashop I watch this :
All fields are edited! not only my 6 fields.
Why??

![image](https://user-images.githubusercontent.com/7665521/70701387-906a1980-1ccc-11ea-9bf5-7d2c6db6358d.png)

**Comment by Myddleware** [comment]
Yes you are right, we shouldn't send every fields for an update action. 

In the function public function update($param)  in the classe /src/Myddleware/RegleBundle/Solutions/prestashop.php, we should unset the field if it isn't requested. Something like that : 
![image](https://user-images.githubusercontent.com/11330301/70703523-9c57da80-1cd0-11ea-8b5c-b8c86c633647.png)

Could you test it in your instance ? If it works, could you push it in our hotfix branch ? 
Thanks.

**Comment by Alexandre17220** [comment]
Hi,
Sorry but I have disable this rule for more safety.
I cannot test for the moment but I think this unset it's the good solution maybe for all your connector.

**Comment by Myddleware** [comment]
Hi Alexandre, only Presatshop works this way. The other solutions update only mapped fields. 
Let me know if you change the code before our next release. Otherwise we will do the change.
Have a nice day.

**Comment by Myddleware** [comment]
Hi ALexandre,
I have checked again the Prestashop update function and I see it updates only mapped fields. 

Myddleware gets first the record from Prestashop with all its values. Then Myddleware modify only the mapped fields into the Prestashop xml. Finally, Myddleware send the xml to update Prestashop, all fields are in the xml but Myddleware have modified only the mapped ones.
Please let me know if it isn't clear.
