### ISSUE TITLE
Installing Myddleware

### ISSUE THREAD

**Issue by z3n4j** [Myddleware/myddleware#242]
On the page is next error:

Deprecated: Function create_function() is deprecated in /var/www/html/var/SymfonyRequirements.php on line 551

Deprecated: Function create_function() is deprecated in /var/www/html/var/SymfonyRequirements.php on line 700

**Comment by Myddleware** [comment]
Yes create_function is deprecated in php 7.2. We will change this in the next release but it isn't a problem to install Myddleware. It is just a warning.

Thanks for your feedback.
