### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by terhau** [Myddleware/myddleware#243]
Hi, I'm trying to install but I'm running into trouble..
I'm trying to install it on a Ubuntu 18.04 server, but I'm getting this error code when I'm trying to Submit my loging for sql...
Error code:

[ERROR]
Failed: The command "php /var/www/x_x_x_x/public_html/app/../bin//console cache:clear --env=prod" failed. Exit Code: 255(Unknown error) Working directory: /var/www/x_x_x_x/public_html/web Output: ================ Error Output: ================ PHP Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 65536 bytes) in /var/www/x_x_x_x/public_html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 135

**Comment by Myddleware** [comment]
You have reach the php limit or your web server.
Could yo please change the memory_limit value in your php.ini file.  It iseems that your value is set to 2M. You can change it to 128M for example. 
Then don't forget to restart your web service on your server (probably apache or nginx).

**Comment by terhau** [comment]
Hi, I'm sorry for my stupid question.  I had to change the limits for the apach2/php.ini and cli/php.ini file on the wbeserver and the SQL server... Now it's working :)

Thank you for the quick reply.

**Comment by Myddleware** [comment]
No problem, there is no stupid question ;).
Thanks for your feedback.
