### ISSUE TITLE
Moodle, Myddleware and SuiteCRM Integration

### ISSUE THREAD

**Issue by dimpels** [Myddleware/myddleware#244]
Hi

I have done all the steps in preparing Moodle, Myddleware and SuiteCRM for integration, but no data is being sent to SuiteCRM.  What am I doing wrong?

**Comment by dimpels** [comment]
Hi

Please see the errors I am getting.
![errors myddleware](https://user-images.githubusercontent.com/57750761/70943463-a32c7780-2059-11ea-85d6-491ac917bbc4.jpg)

**Comment by Myddleware** [comment]
Hi @dimpels ,
Could you give me more detail about your rule (with screenshot) please ? Thanks.

**Comment by dimpels** [comment]
Hi
Please see attached.
![myddleware test](https://user-images.githubusercontent.com/57750761/70979743-cafff780-20ba-11ea-9bdc-873875457284.jpg)

**Comment by Myddleware** [comment]
Did you change the reference date in the parameters tab ? Myddleware will read all users created or modified after this date. So if this date is today and you don't have user modified or created today, Myddleware won't read any record.
Set this date in the past, far in the past if you want to read all your Moodle users.
Please keep me posted. Thanks.

**Comment by dimpels** [comment]
Ok, Thanks.  I will keep you posted.  Thank you once again for all your support. I really appreciate it.

**Comment by dimpels** [comment]
Hi

I've changed the reference date way back in the past.  Please see the error message I am getting.
![error sending](https://user-images.githubusercontent.com/57750761/70983979-5335cb00-20c2-11ea-84ac-0f51bf73caec.jpg)

**Comment by Myddleware** [comment]
Ok So Myddleware could read data from Moodle. Now the error is because Myddleware can't send the data to SuiteCRM. 
It is weird that you don't have more detail about the error. Could you send me a screenshot of one data transfer ? 
Thanks.

**Comment by dimpels** [comment]
Hi
Please see attached.  Can it be that the fields does not match and I am not creating formulas?
![error myd](https://user-images.githubusercontent.com/57750761/70986196-1ec40e00-20c6-11ea-9167-c00b05e32e07.jpg)

**Comment by Myddleware** [comment]
OK, does this data transfer belong to the rule above (with the screenshot) ? I don't see SuiteCRM field in the target side.
Could you send me a screenshot of the rule "Create courses" ?

**Comment by dimpels** [comment]
Hi 
Please see attached.
![error mydd](https://user-images.githubusercontent.com/57750761/70988722-01de0980-20cb-11ea-83cb-9a151c846c88.jpg)

**Comment by Myddleware** [comment]
You send me a screen shot of rule "Create a course" but your data transfer are linked to the rule "Create courses".
Could you send me a screenshot of the rule "Create courses" ? Thanks.

**Comment by dimpels** [comment]
Sorry about that.  Please find attached.
![create courses](https://user-images.githubusercontent.com/57750761/70990017-5bdfce80-20cd-11ea-90ce-e7006252061d.jpg)

**Comment by Myddleware** [comment]
Thanks.
Could you check you suiteCRM logs to see if something happens when you tried to create a record in your custom module NBD23_Course.
Other question, does the SuiteCRM users (used in Myddleware's connector) has the permission to create/update a record in the NBD23_Course module ?
