### ISSUE TITLE
Transfer error

### ISSUE THREAD

**Issue by z3n4j** [Myddleware/myddleware#245]
Failed to create document (id source : 5df8957d0e7604.42212941): An exception occurred while executing INSERT INTO Document (id, rule_id, date_created, date_modified, created_by, modified_by, source_id, source_date_modified, mode, parent_id) VALUES(5df8957d0e7604.42212941,5df89508485e9,2019-12-17 08:44:45,2019-12-17 08:44:45,1,1,08.4000.15,2019-12-17 09:44:00,0,): SQLSTATE[HY000]: General error: 1364 Field deleted doesnt have a default value /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php Line : ( 103 )Status : Create_KO

**Comment by z3n4j** [comment]
[2019-12-17 08:44:45] app.ERROR: Failed to create document (id source : 5df8957d0e7604.42212941): An exception occurred while executing 'INSERT INTO Document (id, rule_id, date_created, date_modif$

**Comment by z3n4j** [comment]
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please check your log file here : \myddleware\var\logs\prod.log

You can post an issue on Myddleware Github project

Sorry for any inconvenience.

**Comment by z3n4j** [comment]
[2019-12-17 08:45:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getDeleted() on null" at /var/www/html/src/Myddlewa$

**Comment by Myddleware** [comment]
Hi,
We have changethe default value for deleted fields ( #246 ). You can upgrade Myddleware in version 2.5.0e.
To upgrade Myddleware, you can run this command : 
`php bin/console myddleware:upgrade --env=background`

Then you shouldn't get this error anymore.

**Comment by z3n4j** [comment]
HI, I upgrade and now is OK. Thank you.

**Comment by Myddleware** [comment]
Perfect, thank you for your feedback.
