### ISSUE TITLE
What is the "quantity" field in Prestashop products connector?

### ISSUE THREAD

**Issue by z3n4j** [Myddleware/myddleware#248]
![Screen Shot 12-19-19 at 04 00 AM](https://user-images.githubusercontent.com/18057413/71141410-5771fd80-2214-11ea-97b6-7f2adfcc979d.PNG)

**Comment by Myddleware** [comment]
Hi,
Sorry but this is a Prestashop question. Myddleware call a Presatshop webservice function to get Prestashop fields. So you can ask Prestashop team.
However I guess that quantity is the stock quantity.

**Comment by z3n4j** [comment]
Ok. Thanks.
