### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by terhau** [Myddleware/myddleware#249]
Hi, it's me again.
I manage to get the sync running once, but no it will not sync anymore between Prestashop and SuiteCRM. I'm trying to run it, and I have also set up cron jobs for this. But I'm not able to sync anything after the first time. I have also changed the reference date to see if this helps, but no luck.

You can see the error that I'm getting in the log file.
Hope someone can help me with this.

[prod.log](https://github.com/Myddleware/myddleware/files/3991343/prod.log)

**Comment by Myddleware** [comment]
Hi @terhau,
Could you post a screenshot of your tasklist in Myddleware ? You have maybe a task which locks the other tasks.
Thanks

**Comment by terhau** [comment]
Hi, screenshot of my tasklist. I have adjusted the time for the cron jobs on my server.

![Myddelware_001](https://user-images.githubusercontent.com/58954781/71371143-75db4e80-25b0-11ea-8ed3-cef14af6115a.png)

**Comment by Myddleware** [comment]
Sorry @terhau we didn't answer to you. Do you still have the problem ?
