### ISSUE TITLE
Symfony 4 or 5 upgrade

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#250]
Hi Myddleware Staff, I'm worried about the future of Myddleware after Symfony new release. 
What is the plan for the next releases?

**Comment by Myddleware** [comment]
Hi @francescobianco,
Thanks for asking. We have already planned to work on Symfony upgrade for the next Myddleware main version (will be released in June) as the support of Symfony 3 will end in November this year.
Don't hesitate if you have any other questions.
