### ISSUE TITLE
Upgrade issues

### ISSUE THREAD

**Issue by renehamburger** [Myddleware/myddleware#254]
I've been trying to upgrade Myddleware for the first time today after installing it about a year ago, following the [official upgrade guide](http://community.myddleware.com/index.php/installation-guide/#upgrade-myddleware).

When executing `php bin/console myddleware:upgrade --env=background`, I get the error `Error : Failed to update Myddleware. Files are not up-to-date. myddleware/src/Myddleware/RegleBundle/Classes/upgrade.php Line : ( 199 )`.

Following the step-by-step instructions works to the point that the newly generated cache files always reflect the previous version. So even though `app/config/parameters.yml.dist` contains `myd_version: 2.5.1a`, all the files in `var/cache` contain the old version, e.g. `var/cache/background/appBackgroundDebugProjectContainer.xml` has `<parameter key="myd_version">2.4.1c</parameter>`.

@Myddleware, I've also tried out the commands you suggested [here](https://github.com/Myddleware/myddleware/issues/235#issuecomment-557607050).

Any idea what could be going wrong?

**Comment by Myddleware** [comment]
Hi @renehamburger ,

Could you just to remove all the cache (dev, prod and background) by removing the directories : 
 - myddleware\var\cache\background
 - myddleware\var\cache\prod
 - myddleware\var\cache\dev

Then please make sure that all files are updated usign the command : `git pull`
Then please retry the command : `php bin/console myddleware:upgrade --env=background`

Please let me know if it works.

Could you also make sure your server runs with PHP 7.2.x ? Thanks.

**Comment by renehamburger** [comment]
Thanks for the suggestions, @Myddleware.

I did execute `rm -rf var/cache/*` before as per your guide and have done it again. `git pull` was successful as the version number `2.5.1a` in code base demonstrates. `php bin/console myddleware:upgrade --env=background` leads the error message I posted above.

I'm using php 7.2.27 on the command line (and switched from 7.1.33 to 7.2.27 for the website just now, but that should not be significant for this issue).

If there's no simple solution, I'm happy to reinstall it.

**Comment by Myddleware** [comment]
Ok I see. You have followed the step by step instruction successfully. So your Myddleware is up to date. But you are right, the last step is missing in our documentation. You have to change manually the version (myd_version) in the file myddleware\app\config\parameters.yml
Then clear again the cache and you should see the right version in Myddleware.

We will update our documentation.

**Comment by Myddleware** [comment]
Documentation updated. Thanks.
