### ISSUE TITLE
Indentations problems

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#257]
Many files are badly indented by wrong usage of spaces and tabs please, add tools to lint of fix this.
Look this file is badly indented https://github.com/Myddleware/myddleware/blob/master/composer.json

I suggest approaching on StyleCI opensource free service https://styleci.io/

**Comment by Myddleware** [comment]
Thanks for you help @francescobianco 

We have fix the composer.json format in version 2.5.2a and we have fixed the other yml files here : https://github.com/Myddleware/myddleware/commit/ed6b11425432b098c4abbbbd674d14c7a6531b36
