### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by weimiao86** [Myddleware/myddleware#258]
I installed the Myddleware on the server, but failed to login, error log as below:

_An exception occurred while executing 'SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_token AS confirmation_token_9, t0.password_requested_at AS password_requested_at_10, t0.roles AS roles_11, t0.id AS id_12 FROM users t0 WHERE t0.username_canonical = ? LIMIT 1' with params ["qwde"]:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'buildaro_myddle.users' doesn't exist

**And here is the info from the requirement checker:**

Myddleware Requirements Checker
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

> PHP is using the following php.ini file:
/opt/cpanel/ea-php72/root/etc/php.ini

> Checking Myddleware requirements:
..................................W..W.......


[OK]
Your system is ready to run Myddleware


Optional recommendations to improve your setup
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

intl ICU version installed on your system is outdated (4.2.1) and
does not match the ICU data bundled with Symfony (64.2)
> To get the latest internationalization data upgrade the ICU
> system package and the intl PHP extension.
 short_open_tag should be disabled in php.ini
> Set short_open_tag to off in php.ini*.

**Comment by Myddleware** [comment]
Hi @weimiao86 
It seems that the database isn't created. Could you check it ? 
If the installation using web browser doesn't work, please follow this tutorial to installation Myddleware using command shell : https://myddleware.github.io/myddleware/#/?id=install-myddleware
Please keep us posted.

**Comment by weimiao86** [comment]
Yes, using the command shell works, thanks!

**Comment by Myddleware** [comment]
Thanks for your feedback
