### ISSUE TITLE
Platform install failure 

### ISSUE THREAD

**Issue by weimiao86** [Myddleware/myddleware#262]
Found 1 commit

  Building application 'myddleware' (runtime type: php:7.1, tree: a4a74a9)
    Generating runtime configuration.
    
    Moving the application to the output directory
    Prewarming composer cache.
      Pre-downloaded 75 packages referenced in `composer.lock`
    
    Found a `composer.json`, installing dependencies.
      W: Loading composer repositories with package information
      W: Installing dependencies (including require-dev) from lock file
      W: Your requirements could not be resolved to an installable set of packages.
      W: 
      W:   Problem 1
      W:     - Installation request for doctrine/dbal v2.10.1 -> satisfiable by doctrine/dbal[v2.10.1].
      W:     - doctrine/dbal v2.10.1 requires php ^7.2 -> your PHP version (7.1.33) does not satisfy that requirement.
      W:   Problem 2
      W:     - Installation request for doctrine/lexer 1.2.0 -> satisfiable by doctrine/lexer[1.2.0].
      W:     - doctrine/lexer 1.2.0 requires php ^7.2 -> your PHP version (7.1.33) does not satisfy that requirement.
      W:   Problem 3
      W:     - Installation request for symfony/http-client v5.0.3 -> satisfiable by symfony/http-client[v5.0.3].
      W:     - symfony/http-client v5.0.3 requires php ^7.2.5 -> your PHP version (7.1.33) does not satisfy that requirement.
      W:   Problem 4
      W:     - Installation request for symfony/http-client-contracts v2.0.1 -> satisfiable by symfony/http-client-contracts[v2.0.1].
      W:     - symfony/http-client-contracts v2.0.1 requires php ^7.2.5 -> your PHP version (7.1.33) does not satisfy that requirement.
      W:   Problem 5
      W:     - Installation request for symfony/mime v5.0.3 -> satisfiable by symfony/mime[v5.0.3].
      W:     - symfony/mime v5.0.3 requires php ^7.2.5 -> your PHP version (7.1.33) does not satisfy that requirement.
      W:   Problem 6
      W:     - Installation request for symfony/service-contracts v2.0.1 -> satisfiable by symfony/service-contracts[v2.0.1].
      W:     - symfony/service-contracts v2.0.1 requires php ^7.2.5 -> your PHP version (7.1.33) does not satisfy that requirement.
      W:   Problem 7
      W:     - Installation request for doctrine/data-fixtures 1.4.2 -> satisfiable by doctrine/data-fixtures[1.4.2].
      W:     - doctrine/data-fixtures 1.4.2 requires php ^7.2 -> your PHP version (7.1.33) does not satisfy that requirement.
      W:   Problem 8
      W:     - doctrine/lexer 1.2.0 requires php ^7.2 -> your PHP version (7.1.33) does not satisfy that requirement.
      W:     - doctrine/common 2.12.0 requires doctrine/lexer ^1.0 -> satisfiable by doctrine/lexer[1.2.0].
      W:     - Installation request for doctrine/common 2.12.0 -> satisfiable by doctrine/common[2.12.0].
      W: 
    
    E: Error building project: `composer` could not be run.

E: Error: Unable to build application, aborting.

**Comment by francescobianco** [comment]
Current working copy runs into PHP 7.2, try to update your environment. Please share your feedback about it

**Comment by Myddleware** [comment]
Thanks @francescobianco you are right.

Just for information, Myddleware 2.5.1 is only compatible with php7.2. But Myddleware 2.5.2 (released tomorrow) will accept php 7.3 and php 7.4.

**Comment by weimiao86** [comment]
I think this should be indicated in the installation documentation.

> To use Myddleware you need a server

With a web server like apache.
PHP from version 7.1
MYSQL

**Comment by Myddleware** [comment]
Oh you are right. Documentation updated. Thanks.
