### ISSUE TITLE
Need help: Transaction commit failed

### ISSUE THREAD

**Issue by weimiao86** [Myddleware/myddleware#263]
Hi, I am trying to sync my Prestashop user to Moodle and got the error as below, I am not sure if this is caused by Moodle configuration. Please help, thanks!

> Transaction commit failed because the transaction has been marked for rollback only. (/home/buildaro/public_html/myddleware/vendor/doctrine/dbal/lib/Doctrine/DBAL/ConnectionException.php line 12)

**Comment by weimiao86** [comment]
Fixed, the same issue as Creation of the rule MSSQL to Prestashop #241

**Comment by Myddleware** [comment]
Thanks for your feedback. 
This bug is fixed in the new release (2.5.2), so you can change your MySQL variable only_full_group_by or just upgrade Myddleware using this tutorial https://myddleware.github.io/myddleware/#/admin_tasks?id=upgrading-myddleware
