### ISSUE TITLE
MsSql to Prestashop connector new product

### ISSUE THREAD

**Issue by z3n4j** [Myddleware/myddleware#266]
Hi. I have one connector from MsSql to Prestashop. The task work and create a new ID. But i can't see the ne product in prestashop.

**Comment by Myddleware** [comment]
Hi @z3n4j ,
Could you add a screenshot of your rule (field mapping) and we will try to reproduce your problem ?
Thanks.

**Comment by z3n4j** [comment]
![Screen Shot 02-24-20 at 07 10 PM 003](https://user-images.githubusercontent.com/18057413/75178936-5213c080-5739-11ea-8fc7-6d0a07293c2f.PNG)
![Screen Shot 02-24-20 at 07 10 PM 002](https://user-images.githubusercontent.com/18057413/75178938-53dd8400-5739-11ea-9d14-1bd2fcf587ff.PNG)
![Screen Shot 02-24-20 at 07 10 PM 001](https://user-images.githubusercontent.com/18057413/75178939-54761a80-5739-11ea-9107-475b926fa181.PNG)
![Screen Shot 02-24-20 at 07 10 PM](https://user-images.githubusercontent.com/18057413/75178941-54761a80-5739-11ea-8f9e-fa2248723c4f.PNG)
![Screen Shot 02-24-20 at 07 09 PM](https://user-images.githubusercontent.com/18057413/75178943-550eb100-5739-11ea-9d43-4abc6ce871ef.PNG)

**Comment by Myddleware** [comment]
Hi @z3n4j ,
I have created a rule to create a product in Prestashop and the product is displayed in the product catalog. 
Here is the fields I have mapped : 
![image](https://user-images.githubusercontent.com/11330301/75257341-1afae900-57e5-11ea-974f-a08b7daea575.png)

I see that you didn't map the field "state". Maybe this is the problem ?  

Could you also tried to open your product in Prestashop by opening a product, then change the id in the URL : 
![image](https://user-images.githubusercontent.com/11330301/75257536-6614fc00-57e5-11ea-96e6-1f55aa7b3dc6.png)

Does you product appear ?

**Comment by z3n4j** [comment]
I see the new products in products table in db of prestashop. But i don't see it in back office products.

**Comment by z3n4j** [comment]
Hi.
I have solved the problem. When myddleware creates the product, it inserts the category in the products table, but category 0 remains in the category_produtc table. Having a filter on the back office products page, it didn't show them to me.

**Comment by Myddleware** [comment]
Thanks for your feedback.

Maybe you should set a default value corresponding do the id of a Prestashop category in this field : 
![image](https://user-images.githubusercontent.com/11330301/75659225-eb773100-5c69-11ea-9852-eab949c74bfd.png)

**Comment by z3n4j** [comment]
I have a value in id_category_default, but it update product table. In the category_product table the value dont'change and remain 0. 
Than you for your feedback.

**Comment by Myddleware** [comment]
Yes this field change only the default category in the product table and doesn't change the table category_product.
We would have to develop a specific call to update the table category_product

**Comment by z3n4j** [comment]
In Prestahop 1.6 worked ok. In Prestashop 1.7.6.3 change only in product table.

**Comment by Myddleware** [comment]
We have added modules into Prestashop connector. 

You will be able to create categories and association products - categories in the next hotfix version : 
![image](https://user-images.githubusercontent.com/11330301/75728587-8dd5f980-5ce8-11ea-9d37-c75138c21ad8.png)

**Comment by Myddleware** [comment]
Done in version 2.5.3a : #272
