### ISSUE TITLE
Can't cancel transfers

### ISSUE THREAD

**Issue by weimiao86** [Myddleware/myddleware#267]
I activated the prestashop to moodle template rules, but all failed, then I want to edit or delete these rules, it shows

> Failed to delete the rule because there is at least one data transfer not deleted on this rule. Remove these transfers to be able to delete this rule.

Then I tried to cancel those transfers, and it shows

> Failed to run the job.

So I am stuck there, now I start to doubt does this tool really work?

**Comment by Myddleware** [comment]
Yes it definitely works.
You have probably a task not closed due to an error. So please, could you open you task list. You should have a task not closed, open it and stop it.
Then you will be able to cancel your data transfers and edit your rules.
