### ISSUE TITLE
[Question] How to skip the existing users while sync the Prestashop users to Moodle

### ISSUE THREAD

**Issue by weimiao86** [Myddleware/myddleware#269]
Hi

I got the following error while sync a Prestashop user to Moodle because the user already exists.

> invalidparameter : Invalid parameter value detectedFailed to send document. Status : Error_sending

It is not an issue for me to fail to import the existing user. But this error blocks me when I want to edit my rules, so how can we skip the existing users without reporting errors?

Thanks!

**Comment by Myddleware** [comment]
Hi @weimiao86 

Please, cancel first your data transfer in error first and you will be able to edit your rule.

Then, go to your confirmation tab when you edit your rule and select one of these 2 fields : 
![image](https://user-images.githubusercontent.com/11330301/75658712-12813300-5c69-11ea-8880-92b407c544d5.png)

Myddleware will wheck if the user already exist and will update it (not create it) if the user already exists.
Please let me know if it solves your problem.
