### ISSUE TITLE
Myddleware version 2.5.3a

### ISSUE THREAD

**Issue by z3n4j** [Myddleware/myddleware#273]
Hi. I update myddleware to last version.
When I start rule I get the following error (MsSql to Prestashop - The products) if I select duplicate ean or reference or nothing:

Failed to create Job : An exception occurred while executing 'INSERT INTO Job (id, begin, status, param, manual, api) VALUES ('5e636b2d0f9098.03604257', '2020-03-07 09:36:45', 'Start', 'Synchro : terpin_shop', '1', '')':

**Comment by Myddleware** [comment]
Hi @z3n4j ,

We can't reproduce this issue. Maybe it is linked to the MySQL configuration. Could you try to set 0 value to the attribute api in the classe <myddleware>\src\Myddleware\RegleBundle\Classes\job.php. Please just add "= 0"here : 
![image](https://user-images.githubusercontent.com/11330301/76144561-130f3480-6082-11ea-8055-c6520974a5d0.png)

Could you tell me if it has solved your issue. If yes, we will add this fix to the hotfix branch.

Thanks.

**Comment by Myddleware** [comment]
I gound a way to reproduce it.
I 'll keep you posted very soon.

**Comment by Myddleware** [comment]
We have released the hotfix version 2.5.3b (https://github.com/Myddleware/myddleware/pull/274) 

Could you upgrade Myddleware. If you still have the issue, could you check that the api column is in your table Job ? Thanks.

**Comment by z3n4j** [comment]
Hi. I can't upgrade Myddleware. 
I get this error:

Failed to create Job : An exception occurred while executing 'INSERT INTO Job (id, begin, status, param, manual, api) VALUES ('5e6484b71bcff5.88375102', '2020-03-08 05:37:59', 'Start', 'upgrade', '0', '')':

SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'api' at row 1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php Line : ( 106 )Failed to create the Job in the database
[janez@localhost html]$

I have the colum api in Job table.
![Screen Shot 03-08-20 at 06 57 AM](https://user-images.githubusercontent.com/18057413/76157552-94120e80-610a-11ea-822c-40949f814a44.PNG)

If I set 0 value to the attribute api in the classe \src\Myddleware\RegleBundle\Classes\job.php
and try to upgrade i get this error:

Error : The command "git pull origin master" failed.

Exit Code: 1(General error)

Working directory: /var/www/html

Output:
================
Updating eddc59b..0db74c4


Error Output:
================
From https://github.com/Myddleware/myddleware
 * branch            master     -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
        src/Myddleware/RegleBundle/Classes/job.php
Please, commit your changes or stash them before you can merge.
Aborting
 /var/www/html/src/Myddleware/RegleBundle/Classes/upgrade.php Line : ( 175 )

**Comment by Myddleware** [comment]
Hi @z3n4j ,

Could you first run this command directly : git pull origin master
If you still have your conflict with job file, please delete this file and run again the git pull command. This job file will be created again.

Then you should be able to upgrade Myddleware.
Please keep me posted.

**Comment by z3n4j** [comment]
Hi. 

I run command: git pull origin master

Error:

From https://github.com/Myddleware/myddleware
 * branch            master     -> FETCH_HEAD
Updating eddc59b..0db74c4
error: Your local changes to the following files would be overwritten by merge:
        src/Myddleware/RegleBundle/Classes/job.php
Please, commit your changes or stash them before you can merge.
Aborting

I deleted file job.php

I run command: git pull origin master

An then the command: php bin/console myddleware:upgrade --env=background

Myddleware update correctly.

And the rule work good. It found reference.

**Comment by Myddleware** [comment]
Great news.
Thanks for your feedback.
