### ISSUE TITLE
Massive delete of error

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#275]
I'm trying do delete all error queue, but I cant' find a way to do in a massive way.
It seems that I can select only all record from 1 page (20) and not all the list.

I suggest that after you click on check that select all records from page, a clickable link SELECT ALL (N) appear and so you can select all record to send to massive action.

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,

Thanks for your suggestion. We will work on it. 

However today you have 2 options : 

- If you have just a few hundreds of data transfer to cancel, you can increase the number of data transfer in the result list (change parameter pager in file app\config\public\parameters_public and clear the cache). Then you will be able to cancel more data transfer

- Second option, we have a command to remove or cancel all document for a rule (we didn’t create the button in Myddleware UI yet) : 
-  => To cancel: `php bin/console myddleware:massaction cancel rule <your rule id> -e background`
-  => To remove: `php bin/console myddleware:massaction remove rule <your rule id> -e background`
-  => You can add Y after <your rule id> if you want to cancel/remove all data transfers even the transfers successfully sent, not only the ones open or in error. So I advise you to not put the Y except if you really know what you are doing.

The command is here https://github.com/Myddleware/myddleware/blob/master/src/Myddleware/RegleBundle/Command/massActionCommand.php
