### ISSUE TITLE
Filter in rules

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#276]
Hi,
I think in rules could be usefull have condition "IT'S NOT EMPTY". Or I can get same result with other rules?

**Comment by Myddleware** [comment]
Hi Simone,
It is possible to do this by selecting the filter "different from" (we will change the translation to "Not equal to") and leaving the field empty like this : 
![image](https://user-images.githubusercontent.com/11330301/76230118-8603e100-6223-11ea-86e0-22e2dd362ed0.png)

Sorry this is not clear at all. 
Thanks for the question.
