### ISSUE TITLE
Available quantities Prestashop

### ISSUE THREAD

**Issue by z3n4j** [Myddleware/myddleware#278]
Hi.

I created a rule form MsSQL to Prestashop, to update the quantities in prestashop.

In source table and target table i link "quantity".

In source table i have SKU(reference),  but in target table i have only id_product. And i can't link.

Maybe do you have some solution?

**Comment by Myddleware** [comment]
Could you show me more detail with some screenshotabout what you want to do ?
I need to see the detail view (only the main view when you open a rule) of the rule you want to link. I guess it is a "product" rule.
I need also to see the edit view of your "quantity" rule : map field tab and relationship tab.
Thanks.

**Comment by z3n4j** [comment]
This is my rule from MsSql to Prestashop for some field and the description in italian language. 
This work fine with last update for duplicates.
![Screen Shot 03-12-20 at 11 00 AM](https://user-images.githubusercontent.com/18057413/76509968-1ecb7400-6451-11ea-9662-f89d41517853.PNG)

**Comment by z3n4j** [comment]
This is my rule from MsSql to Prestashop for description in slovenian language.
This work fine.
![Screen Shot 03-12-20 at 11 00 AM 001](https://user-images.githubusercontent.com/18057413/76510038-3c004280-6451-11ea-84fa-e8c4876d2f72.PNG)

**Comment by z3n4j** [comment]
This is the rule for quantities. But in source i have the "reference(Codice)" but in target i have only id_products.
![Screen Shot 03-12-20 at 11 01 AM](https://user-images.githubusercontent.com/18057413/76510178-7a95fd00-6451-11ea-8b6b-cda08517ab89.PNG)

**Comment by Myddleware** [comment]
Thanks for the screeshot but these are not the ones I need ;). Sorry I wasn't clear. 
So I need to know what field you use as the reference in your "product" rule : 
![image](https://user-images.githubusercontent.com/11330301/76511111-f47ab600-6452-11ea-9826-7f661bc9d82e.png)

Then I need to see your relationship tab for your quantity table, please open the dropdown list like this : 
![image](https://user-images.githubusercontent.com/11330301/76511771-e24d4780-6453-11ea-8692-4791e03681fa.png)

Thanks.

**Comment by z3n4j** [comment]
![Screen Shot 03-12-20 at 11 37 AM](https://user-images.githubusercontent.com/18057413/76513163-26414c00-6456-11ea-8b56-7be587ba749b.PNG)

**Comment by z3n4j** [comment]
![Screen Shot 03-12-20 at 11 39 AM](https://user-images.githubusercontent.com/18057413/76513449-9c45b300-6456-11ea-91ed-2fb12fa529ad.PNG)

**Comment by z3n4j** [comment]
![Screen Shot 03-12-20 at 11 39 AM 001](https://user-images.githubusercontent.com/18057413/76513468-a23b9400-6456-11ea-948e-b556847be714.PNG)

**Comment by Myddleware** [comment]
OK so you should have to add manually (in the code) the field "codice" as a reference. Then you will see this field in your relationship tab and you will be able to map it with you product rule and the field product_id. 

But instead of adding this field manually, we will enhance a little bit this connector to add automatically in the relationship tab, the list of fields used as reference in other rules (codice in your case).

We have another fix in ERPNext that we will release today, so we will add this fix too. I 'll let you know when it is done today.

**Comment by z3n4j** [comment]
Super. Thank you very much.

**Comment by Myddleware** [comment]
We have merged the hotfix branch : #282 
You can upgrade Myddleware in version 2.5.3d and try again.
