### ISSUE TITLE
Failed to get field list for Sales Order from ERPNext v12

### ISSUE THREAD

**Issue by ophl55** [Myddleware/myddleware#279]
Hi. I'm also trying to connect Prestashop and ERPNext v12. 

**Problem**:
I don't see any fields for Sales Order. Other Doc Types like Customer and Address are working.

prod.log gives the following output:
`app.ERROR: No data in the module Sales Order. Failed to get the field list. /var/www/html/myddleware/src/Myddleware/RegleBundle/Solutions/erpnext.php 191 [] []`

Do you have any ideas why it is failing?

**Comment by Myddleware** [comment]
Hi,
We have reproduced this issue. We are working on it. We 'll keep you posted.

**Comment by Myddleware** [comment]
We have found the bug : https://github.com/Myddleware/myddleware/commit/9fa366615f0085effd6b85961da461b4ad21e126 .
We will release the hotfix version today. We will keep you posted.

**Comment by Myddleware** [comment]
We have merged the hotfix branch : #282 
You can upgrade Myddleware in version 2.5.3d and try again.
