### ISSUE TITLE
[v2.5.3b] Uncaught Exception: column not found 

### ISSUE THREAD

**Issue by ophl55** [Myddleware/myddleware#280]
ERPNext v12 Connector
Prestashop Connector

### Problem
Added a rule yesterday and saved it. Today I wanted to edit the rule but received Error 500.

prod.log gives the following output:

`request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT t0.id AS id_1, t0.rule_id AS rule_id_2, t0.field_name_source AS field_name_source_3, t0.field_name_target AS field_name_target_4, t0.field_id AS field_id_5, t0.parent AS parent_6, t0.deleted AS deleted_7 FROM RuleRelationShip t0 WHERE t0.rule_id = ?' with params ["5e67e28fdf32c"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.deleted' in 'field list'" at /var/www/html/myddleware/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 60 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'SELECT t0.id AS id_1, t0.rule_id AS rule_id_2, t0.field_name_source AS field_name_source_3, t0.field_name_target AS field_name_target_4, t0.field_id AS field_id_5, t0.parent AS parent_6, t0.deleted AS deleted_7 FROM RuleRelationShip t0 WHERE t0.rule_id = ?' with params [\"5e67e28fdf32c\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.deleted' in 'field list' at /var/www/html/myddleware/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:60, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.deleted' in 'field list' at /var/www/html/myddleware/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.deleted' in 'field list' at /var/www/html/myddleware/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)"} []`

**Comment by Myddleware** [comment]
Could you check that the field deleted is missiong in your table ? If yes, could you run this command to update your table structure : `php bin/console doctrine:schema:update -f -e prod`
