### ISSUE TITLE
Edit rule empty v2.5.3d

### ISSUE THREAD

**Issue by z3n4j** [Myddleware/myddleware#283]
Hi I updatet myddleware to the last version v2.5.3d.

But if I want to edit the rule the rule is empty. If I Refer to the form ther is all the data of the ruel. If I execute the rule all work fine.
![Screen Shot 03-13-20 at 07 20 AM](https://user-images.githubusercontent.com/18057413/76595418-dae17900-64fb-11ea-90a6-08e7db83f2d1.PNG)
![Screen Shot 03-13-20 at 07 20 AM 001](https://user-images.githubusercontent.com/18057413/76595421-dddc6980-64fb-11ea-8245-983c14a6d9d0.PNG)
![Screen Shot 03-13-20 at 07 20 AM 002](https://user-images.githubusercontent.com/18057413/76595427-e2a11d80-64fb-11ea-81bd-c5a5d44db051.PNG)
![Screen Shot 03-13-20 at 07 20 AM 003](https://user-images.githubusercontent.com/18057413/76595434-e5037780-64fb-11ea-8507-55c6265f48f1.PNG)

**Comment by Myddleware** [comment]
Hi @z3n4j 
Could you show us what you have in your log (var/logs/prod.log) ?
Thanks.

**Comment by z3n4j** [comment]
[prod.log](https://github.com/Myddleware/myddleware/files/4328710/prod.log)

**Comment by z3n4j** [comment]
Hi. I tried to create a new rule to update categries for products in prestashop. Source MsSQL target Prestashop. 

I get the error under. Maybe is this connected to the empty rules?

Alerte: An unexpected error has occured on the fields mapping : An exception occurred while executing 'SELECT value FROM ruleparam WHERE ruleparam.name = 'fieldId' AND ruleparam.rule_id in ('5df89508485e9','5e523b4697015','5e5a23a00f296')': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'myddleware.ruleparam' doesn't exist (/var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 42)

**Comment by Myddleware** [comment]
Hi @z3n4j ,
Could you open your database and show me the name of your table "ruleparam'. Do you have some capital letters ? 
Thanks.

**Comment by z3n4j** [comment]
![Screen Shot 03-13-20 at 11 10 AM](https://user-images.githubusercontent.com/18057413/76611806-5e5e9280-651b-11ea-916a-d1fb585f0748.PNG)

**Comment by z3n4j** [comment]
![Screen Shot 03-13-20 at 11 13 AM](https://user-images.githubusercontent.com/18057413/76611928-949c1200-651b-11ea-93c5-bfc82f687c91.PNG)

**Comment by Myddleware** [comment]
OK the problem is here. 
I 'll come back to you today about it.

**Comment by Myddleware** [comment]
We have fixed the issue #284 
Could you upgrade Myddleware and try again ?
