### ISSUE TITLE
Issues Syncing with Moodle and SuiteCRM

### ISSUE THREAD

**Issue by chcpr** [Myddleware/myddleware#285]
Hello all, 
Thanks for taking the time to help me out. 
I'm sure my issue something I've foolishly overlooked but I've been stuck for a few days with this. I'm fairly new to coding anything other than HTML/CSS to please bear with me!

I have myddleware installed and have created connectors for SuiteCRM and Moodle. It seems like it should be working, there are no error messages and CRON is running every 5 minutes but nothing is being transferred. 

The moodle user has all the necessary permissions and I can't replicate an error when trying to add a user with the same information being provided by Suite CRM. 

I've attached some screenshots that may answer some queries but thank you ever so much for helping! 

![Screenshot 2020-03-14 at 23 20 56](https://user-images.githubusercontent.com/62191097/76692182-da0b2d00-664a-11ea-894c-de2c1578b3a7.png)
![Screenshot 2020-03-14 at 23 20 50](https://user-images.githubusercontent.com/62191097/76692184-dc6d8700-664a-11ea-826d-b0c1f2aa8553.png)
![Screenshot 2020-03-14 at 23 20 46](https://user-images.githubusercontent.com/62191097/76692185-dd061d80-664a-11ea-95cc-4e25f09c10b2.png)
![Screenshot 2020-03-14 at 23 20 41](https://user-images.githubusercontent.com/62191097/76692186-dd061d80-664a-11ea-8ed8-e93b3ce8538b.png)
![Screenshot 2020-03-14 at 23 20 16](https://user-images.githubusercontent.com/62191097/76692187-dd9eb400-664a-11ea-861c-38165dc90748.png)
![Screenshot 2020-03-14 at 23 20 05](https://user-images.githubusercontent.com/62191097/76692188-de374a80-664a-11ea-9bf6-ade48abf5073.png)

**Comment by chcpr** [comment]
I said it would be something stupid!
I'd disabled curl!

**Comment by Myddleware** [comment]
Thanks @chcpr 
We don't work the weekend, it is the reason I answer only today.
There is no stupid question ;) . Thanks for your feedback.
We hope that Myddleware will meet all your needs.
