### ISSUE TITLE
Prestashop quantities

### ISSUE THREAD

**Issue by z3n4j** [Myddleware/myddleware#286]
Hi. Here is my rule. What i made wrong. I get one error.
![Screen Shot 03-15-20 at 12 01 PM](https://user-images.githubusercontent.com/18057413/76700184-62261c80-66b5-11ea-87a3-3983d7c673b0.PNG)
![Screen Shot 03-15-20 at 12 02 PM](https://user-images.githubusercontent.com/18057413/76700188-6eaa7500-66b5-11ea-8fec-56f97a07ff25.PNG)
![Screen Shot 03-15-20 at 12 02 PM 001](https://user-images.githubusercontent.com/18057413/76700192-736f2900-66b5-11ea-8445-d5f6e1263823.PNG)
![Screen Shot 03-15-20 at 12 02 PM 002](https://user-images.githubusercontent.com/18057413/76700195-7bc76400-66b5-11ea-8bbb-c16a0e02deeb.PNG)
![Screen Shot 03-15-20 at 12 03 PM](https://user-images.githubusercontent.com/18057413/76700198-841f9f00-66b5-11ea-93f5-d21137164919.PNG)
![Screen Shot 03-15-20 at 12 03 PM 001](https://user-images.githubusercontent.com/18057413/76700200-88e45300-66b5-11ea-9860-3a703167f1f9.PNG)

**Comment by Myddleware** [comment]
Hi @z3n4j ,
Could you show me what you have in your data transfer log : open the data transfer (last screenshot) and go to the bottom, then create another screenshot with the error you get.
Thanks.

**Comment by z3n4j** [comment]
![Screen Shot 03-16-20 at 06 48 PM](https://user-images.githubusercontent.com/18057413/76786210-1eb3d700-67b7-11ea-8477-8542de87c7f5.PNG)
![Screen Shot 03-16-20 at 06 49 PM](https://user-images.githubusercontent.com/18057413/76786219-22475e00-67b7-11ea-93ea-e23ca243ced7.PNG)
![Screen Shot 03-16-20 at 06 49 PM 001](https://user-images.githubusercontent.com/18057413/76786224-24a9b800-67b7-11ea-9c67-2b913f635d99.PNG)

**Comment by Myddleware** [comment]
Hi @z3n4j ,
Could you make sure you have the Prestashop token has access to module "stock_availables" in Prestashop ? 
Thanks.

**Comment by z3n4j** [comment]
![Screen Shot 03-17-20 at 09 05 AM](https://user-images.githubusercontent.com/18057413/76835121-b3a5e700-682e-11ea-8b45-8165b5aa1db4.PNG)
![Screen Shot 03-17-20 at 09 05 AM 001](https://user-images.githubusercontent.com/18057413/76835125-b6084100-682e-11ea-820f-53964e8a699f.PNG)

**Comment by Myddleware** [comment]
Thanks. 
The POST function is maybe not allowed by the server where Prestashop is installed. Is that the first data you tried to POST in Prestashop using Myddleware ? Maybe you have just used the GET methode to read data until now.

**Comment by z3n4j** [comment]
Hi. I have two rules who send data for products to the same prestashop. It means thath POST is enabled?

**Comment by Myddleware** [comment]
Yes, so it is OK on your server.
I can reproduce the problem. This module "Stock available" can't be created into Prestashop but only updated. So only PUT method is allowed. But the stock id is requiered to send a PUT and you don't have the stock ID. 
We use this module for only one project and we have a custom code to get the stock id before sending the quantity available.
I come back to you with a solution, without custom code hopefully .

**Comment by Myddleware** [comment]
Hi @z3n4j 
We found the solution to update the stock in Prestashop without adding custom code. Here are the steps to follow : 
 - Apply this fix on files prestashop.php and document.php (we plan to merge the hotfix branch into master next week, so if you want the fix now, please copy the content of these files from the hotfix branch and paste it manually into your Myddleware instance). Here is the commit : https://github.com/Myddleware/myddleware/commit/71817ad95ad86f60e4193c53710dd8708a91c49b
 - Then create a rule to find the Prestashop stock id using your product id. This rule has to read your product in your source application, get the product id of your target application (using the Myddleware relationship with your product rule) and search the stock id into Prestashop. Here is what you have to do : 
    => Create a rule using your product module in your source application and stock_availables as target module : 
![image](https://user-images.githubusercontent.com/11330301/76989398-8c423d80-6946-11ea-9585-9de4bed67c4a.png)

    => Map any field with id_product in the field tab and set "dummy" or whatever you want. It will be overriden by the relationship tab. It is a workaround to allow search duplicate with product_id : 
![image](https://user-images.githubusercontent.com/11330301/76989534-cf041580-6946-11ea-9aef-5f73f7d3a4e6.png)

    => Map the product_id in the relationship tab (Myddleware will set the Prestashop product id which will be used to get the stock_id) : 
![image](https://user-images.githubusercontent.com/11330301/76989697-0d013980-6947-11ea-9fdb-680566744284.png)

    => In the confirmation tab, select id_product and "Retrieving existing data only" : 
![image](https://user-images.githubusercontent.com/11330301/76989801-3621ca00-6947-11ea-99a0-29f0a1676491.png)

With this rule you will have a correspondance between your product in the source application and the stock available in Pretsashop.


 - Then create the second rule which will update the quantity in Prestashop : 
    => Use the same modules than the previous rule
    => Map the quantity field
    => Create the relationship between your source product field and the stock available id (this will always generate a data transfer with type Update, method PUT, because we send a stock available record with the id of this stock available) : 
![image](https://user-images.githubusercontent.com/11330301/76990230-e98abe80-6947-11ea-8059-f18f668ad6ed.png)
    
    => Validate your rule

Please let meknow if it works for you.

**Comment by z3n4j** [comment]
hi. Thanks for the reply. I tried to change the file but I probably missed something. Could you please pass me both files, or I will wait for the new version.

**Comment by Myddleware** [comment]
No problem, here are the files, you can copy and paste the code :
https://raw.githubusercontent.com/Myddleware/myddleware/71817ad95ad86f60e4193c53710dd8708a91c49b/src/Myddleware/RegleBundle/Classes/document.php
https://raw.githubusercontent.com/Myddleware/myddleware/71817ad95ad86f60e4193c53710dd8708a91c49b/src/Myddleware/RegleBundle/Solutions/prestashop.php

Please let me know if it works.

**Comment by z3n4j** [comment]
Hi. I create one rule to find id_product. Under is the screen shoot. I think it works well.

**Comment by z3n4j** [comment]
![Screen Shot 03-19-20 at 01 21 PM](https://user-images.githubusercontent.com/18057413/77068346-b3504c00-69e6-11ea-892d-3ecedf8d8c96.PNG)
![Screen Shot 03-19-20 at 01 21 PM 001](https://user-images.githubusercontent.com/18057413/77068349-b5b2a600-69e6-11ea-92ec-06e128863604.PNG)
![Screen Shot 03-19-20 at 01 21 PM 002](https://user-images.githubusercontent.com/18057413/77068354-b8150000-69e6-11ea-916a-99d9cda0f4df.PNG)
![Screen Shot 03-19-20 at 01 21 PM 003](https://user-images.githubusercontent.com/18057413/77068361-bcd9b400-69e6-11ea-8803-eafa1e58b280.PNG)
![Screen Shot 03-19-20 at 01 22 PM](https://user-images.githubusercontent.com/18057413/77068367-bfd4a480-69e6-11ea-901a-82a7108ece0f.PNG)
![Screen Shot 03-19-20 at 01 22 PM 001](https://user-images.githubusercontent.com/18057413/77068375-c400c200-69e6-11ea-99dc-cdf868d49cac.PNG)
![Screen Shot 03-19-20 at 01 23 PM](https://user-images.githubusercontent.com/18057413/77068380-c7944900-69e6-11ea-898b-101bbcd2cab8.PNG)
![Screen Shot 03-19-20 at 01 23 PM 001](https://user-images.githubusercontent.com/18057413/77068384-cb27d000-69e6-11ea-8f13-be4d7f24fc02.PNG)

**Comment by z3n4j** [comment]
Then i create a rule for update stock in prestashop. It works. write the stock in the right place but change the id_product in the table. Under the screen shoot.

**Comment by z3n4j** [comment]
![Screen Shot 03-19-20 at 01 23 PM 002](https://user-images.githubusercontent.com/18057413/77068618-3671a200-69e7-11ea-8252-ffa8f3a73d57.PNG)
![Screen Shot 03-19-20 at 01 33 PM](https://user-images.githubusercontent.com/18057413/77068623-37a2cf00-69e7-11ea-8e05-bc13446c04d3.PNG)
![Screen Shot 03-19-20 at 01 32 PM 003](https://user-images.githubusercontent.com/18057413/77068627-37a2cf00-69e7-11ea-9c02-59c1da884927.PNG)
![Screen Shot 03-19-20 at 01 32 PM 002](https://user-images.githubusercontent.com/18057413/77068630-383b6580-69e7-11ea-8066-20b9cae7d481.PNG)
![Screen Shot 03-19-20 at 01 32 PM 001](https://user-images.githubusercontent.com/18057413/77068635-38d3fc00-69e7-11ea-92db-baadd58b99b6.PNG)
![Screen Shot 03-19-20 at 01 32 PM](https://user-images.githubusercontent.com/18057413/77068637-38d3fc00-69e7-11ea-834e-030b594ea46c.PNG)
![Screen Shot 03-19-20 at 01 31 PM](https://user-images.githubusercontent.com/18057413/77068641-396c9280-69e7-11ea-809e-dfc6e9289c4f.PNG)
![Screen Shot 03-19-20 at 01 24 PM](https://user-images.githubusercontent.com/18057413/77068646-3a052900-69e7-11ea-9049-7a6602272494.PNG)

**Comment by z3n4j** [comment]
![Screen Shot 03-19-20 at 01 23 PM 002](https://user-images.githubusercontent.com/18057413/77068700-4be6cc00-69e7-11ea-8ac0-7e6e5318cfc0.PNG)
![Screen Shot 03-19-20 at 01 24 PM](https://user-images.githubusercontent.com/18057413/77068706-4ee1bc80-69e7-11ea-93bb-40cdd5a30fe2.PNG)
![Screen Shot 03-19-20 at 01 31 PM](https://user-images.githubusercontent.com/18057413/77068714-52754380-69e7-11ea-95f8-bc3699fc98fd.PNG)
![Screen Shot 03-19-20 at 01 32 PM](https://user-images.githubusercontent.com/18057413/77068723-55703400-69e7-11ea-92fc-477676972b53.PNG)
![Screen Shot 03-19-20 at 01 32 PM 001](https://user-images.githubusercontent.com/18057413/77068731-586b2480-69e7-11ea-9560-2a482f07379f.PNG)
![Screen Shot 03-19-20 at 01 32 PM 002](https://user-images.githubusercontent.com/18057413/77068736-5b661500-69e7-11ea-990f-eae9d39fa328.PNG)
![Screen Shot 03-19-20 at 01 32 PM 003](https://user-images.githubusercontent.com/18057413/77068741-5dc86f00-69e7-11ea-88c5-5c6e037cd896.PNG)
![Screen Shot 03-19-20 at 01 33 PM](https://user-images.githubusercontent.com/18057413/77068749-61f48c80-69e7-11ea-8ac1-88a55c1fa358.PNG)

**Comment by z3n4j** [comment]
Reads in History the correct id_product but rewrites wrong id_product in target.

What i have made wrong?

**Comment by Myddleware** [comment]
Hi @z3n4j ,
The relationship in your second rule is not correct. You should link ID stock_availables not id_product : 
![image](https://user-images.githubusercontent.com/11330301/77069581-f8757d80-69e8-11ea-85a6-347d1d328399.png)
Keep me posted please.

**Comment by z3n4j** [comment]
Thank you.
Now it seems that it works. Can I choose the order of atomatic execution of the rules.

**Comment by Myddleware** [comment]
Great !
Could you open another issue for your second question ? Thanks.

**Comment by z3n4j** [comment]
Ok. Tahnk you very much.
