### ISSUE TITLE
Job scheduler

### ISSUE THREAD

**Issue by z3n4j** [Myddleware/myddleware#288]
Hi. Can I select the order of executing of the rules?

**Comment by Myddleware** [comment]
Hi.
The rule execution order is automacaly calculated depending on the relationship in all your rules. The parent rules runs first then the child rules...
This execution order is set in the table ruleorder, you can change it. However this table is refreshed each time you edit a rule.

But if you just want to run some rule more often than other rules, you can change Myddleware scheduer and set up the execution of your rule one by one. 
![image](https://user-images.githubusercontent.com/11330301/77078483-ed294e80-69f6-11ea-89e4-9ba44fab2aef.png)
Documentation about the scheduler : https://myddleware.github.io/myddleware/#/cron_jobs

If Myddleware scheduler doesn't meet your needs, you can run the rules one by one using linux cron. Use synchro Myddleware command : 
`php bin/console myddleware:synchro <your rule id> --env=background `

Hope it answers your question.

**Comment by z3n4j** [comment]
Ok. Thanks.
