### ISSUE TITLE
Unknown error when installing Myddleware

### ISSUE THREAD

**Issue by sohungry-roma** [Myddleware/myddleware#292]
Hi,
I was about to install myddleware, but after submitting all necessary data for "database access" and "myddleware user" I get the following error message.

> [ERROR]
> Failed: The command "php /websites/myddleware/bin/console cache:clear --env=prod" failed. Exit Code: 255(Unknown error) Working directory: /websites/myddleware/myddleware/web Output: ================ X-Powered-By: PHP/4.4.9 Content-type: text/html
> Parse error: syntax error, unexpected T_STRING, expecting ')' in /websites/myddleware/web/installMyddleware.php on line 174
> Error Output: ================ 

I guess some settings are wrong, but there I cannot identify them due to the unknown error. DOes someone have an idea?

The Server is running with PHP Version 7.3.6 and standard settings. We never had problems like ths before when installing software.

Best regards
Robert

**Comment by Myddleware** [comment]
Hi @sohungry-roma ,
We will try to reproduce this issue this week, meanwhile you can try to install myddlware using shell commands : https://myddleware.github.io/myddleware/#/?id=install-myddleware
We 'll keep you posted.

**Comment by slemo** [comment]
I have the same error. See below. Any update?

I tried using Shell for the install, but I get the same error there as well. There seems to be something wrong with the code. 

[ERROR]
Failed: The command "php /home/user/sebsite/myddleware/app/../bin//console cache:clear --env=prod" failed. Exit Code: 255(Unknown error) Working directory: /home/user/sebsite/myddleware/web Output: ================ Error Output: ================ PHP Warning: Module 'fileinfo' already loaded in Unknown on line 0 PHP Parse error: syntax error, unexpected ':', expecting ';' or '{' in /home/user/sebsite/myddleware/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 50

**Comment by Myddleware** [comment]
Hi @slemo ,
Could you tell me what php version you are using ? 
Thanks.

**Comment by slemo** [comment]
Sure. I am using php 7.2.

**Comment by Myddleware** [comment]
Thanks, could you also run this command (from Myddleware root directory) and send us a screenshot of what you get : 
`php bin/symfony_requirements`
Thanks.

**Comment by slemo** [comment]
Hello there, here is the screenshot. I just blanked out the user name and website URL.

![image](https://user-images.githubusercontent.com/9007606/80982772-60452380-8df1-11ea-8c79-c477eb964143.png)

**Comment by Myddleware** [comment]
I think your command uses php version 5.6 (see the path of your php.ini file). Could you make sure you use php7.2 or highter ? Thanks.
Please keep me updated

**Comment by slemo** [comment]
Thank you identifying that. I will work to try again with a different php version through the command line. However, I did try through the web browser with PHP 7.2 and got the same error. See the screenshot below. 

![image](https://user-images.githubusercontent.com/9007606/80988409-1c561c80-8df9-11ea-9d4c-ee1bce337013.png)

**Comment by Myddleware** [comment]
Thanks. 
Some actions use php command during the installation, even the web installation. This is something we have to change. So you php version 5.6 is called even in the installation via the browser.

In your case, you should check if you can change your php version. Depending of you host services (check their documentation), you will have to set up an htaccess in Myddleware folder to change the php version. Sometime, you will have to change the php command, using for example php72. 

In this last case, please change the parameter php to php72 (depending your host service)  "php - executable" in the file myddleware\app\config\public\parameters_public.php. Then clear the cache et restart the installation. 

Please let me know if it works.

**Comment by slemo** [comment]
Thank you for your support. I have now updated the shell command PHP version to 7.2. You can see the outcome on the first screenshot below. However, when I start to run the install commands on the installation page here: https://myddleware.github.io/myddleware/#/?id=install-myddleware, I consistently get the error shown on the second screenshot. That error shows for every command starting with this one: "php bin/console cache:clear -e prod". Can you help?

![image](https://user-images.githubusercontent.com/9007606/81090190-f85f0d80-8ec2-11ea-9c10-fb5e4fa920f7.png)


![image](https://user-images.githubusercontent.com/9007606/81090463-64417600-8ec3-11ea-9e84-9aa140e503d8.png)

**Comment by Myddleware** [comment]
Thanks for your answer. 
I see that your password has a star "*" in it. Could you change the password by removing this star please ? 
Please let me know if it works.  In this case, we will have to fix this bug.

**Comment by slemo** [comment]
That did it. Thank you. I have now successfully installed myddleware. I'll let you know if I have any issues using the tool. I do want to thank you so much for the initiative to put this out there. Highly needed.

**Comment by Myddleware** [comment]
Thank you for your feedback. We will work on this.
Have a nice day.

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue, this will be taken into account in Myddleware 4, but do not hesitate to re-open it if needs be.
thanks.
