### ISSUE TITLE
sync when no date reference field

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#293]
Hi,
suppose I have a table to sync without a data reference to check last update. Suppose I want to update every day all records. Is it possible?
What I have to set in fieldDateRef?

**Comment by Myddleware** [comment]
Hi Simone,
You will have to redefine the class of your solution. 
I have redefined the MySQL class but you can apply what I have done for any other application. 

Create the file  src\Myddleware\RegleBundle\Custom\Solutions\mysql.php and add this code : 
```
<?php

namespace Myddleware\RegleBundle\Solutions;

//Custom class
class mysql extends mysqlcore {
	
	// Redifine read function
	public function read($param) {
		$result = parent::read($param);
		// Change reference date for a specific rule
		if ($param['rule']['id'] == 'you_rule_id') {
			$result['date_ref'] = '2000-01-01 00:00:00';
		}	
		return $result;
	}
}
```
So each time Myddleware will read data using your rule, this code will redefined the reference date to 01/01/2000.
Please let me know if it helps.
Stéphane

**Comment by simonetravaglini** [comment]
Hi why not move at frontend this option? :)

**Comment by Myddleware** [comment]
Yes you are right, maybe we could add an option, "sync all data for every run".
I 'll keep you posted.
