### ISSUE TITLE
Data transformation if data empty broke

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#296]
Hi,
I'm using a data transformation formula
changeFormatDate( {DATADINASCITA}, "d-M-Y", "d-m-y" )
It works but if {DATADINASCITA} is empty rules give error when processing.
How I can manage this situation? In rules I can use IF not empty ?

**Comment by Myddleware** [comment]
Hi Simone,
Could you try something like this : 
`({DATADINASCITA} == "" ? "" : changeFormatDate( {DATADINASCITA}, "d-M-Y", "d-m-y" ))`
Please let me know if it works. Thanks.

**Comment by simonetravaglini** [comment]
It works thanks!
