### ISSUE TITLE
Prestashop 1.7.6.4 Connector

### ISSUE THREAD

**Issue by Labyrinth-00** [Myddleware/myddleware#299]
Hi. I have enabled the webservice in my prestashop site and tested it by going to https://urlofsite/api/&ws_key=*apikey* and it works there but when I go to create the connector in the middleware panel I get Bad auth key.  What could I do to get this working? I saw someone mention that they enabled CGI mode and it worked.  Is CGI mode for PHP required?

**Comment by Labyrinth-00** [comment]
I got the issue resolved be adding 

  | RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

in .htaccess

**Comment by Myddleware** [comment]
Oh yeah that's perfect. I was about to answer you today.
Thanks you very much for your feedbacK

**Comment by Labyrinth-00** [comment]
sorry i have to come back to this but the connector is saying bad auth key again and I can't solve this issue.  I've tried generating a new key, disabling and reenabling the webservice, verified the rewrite mod works and tried enabling prestashop cgi mode for php...also updated my prestashop to version 1.7.6.7 to see if that would help 

this is what i have in the conf

DocumentRoot /var/www/myddleware/web/

        <Directory /var/www/myddleware/web>
                AllowOverride All
                Require all granted
                Allow from all
        </Directory>
    Alias myddleware /var/www/

Also this line is still in the .htaccess

RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

I'm not sure what else to do, please assist,  thanks

**Comment by Myddleware** [comment]
Hi @Labyrinth-00 ,
Did you try to test you API key with your browser : 
 - Go to this URL http://your prestashop root url/api/
 - Add you apikey in field "username" in the popup 
 - Leave the password empty
Do you see a big xml file ? Could you send us a screenshot of what you have ?
Thanks.

**Comment by Labyrinth-00** [comment]
Hi, using https://url/api/ give the pop up but entering the api key in the username field does not work, it continues to through the pop up window for the credentials. It would work if I use https://url/api/&ws_key=api_key then I can see the xml file

**Comment by Labyrinth-00** [comment]
screenshot of https://url/api/&ws_key=api_key

![image](https://user-images.githubusercontent.com/62351641/87160143-80c9a800-c290-11ea-88e4-23db574e7c83.png)

**Comment by Myddleware** [comment]
I think you will need to talk with Prestashop expert on their forum, and ask them why the xml doesn't appear after your the popup validation. 
You problem seems to be on Prestashop side.
Please let me know what they say. Thanks.

**Comment by Labyrinth-00** [comment]
Thanks, will do.

**Comment by Labyrinth-00** [comment]
Hey, seems like I may have placed the below code in the wrong .htaccess file.  So instead of editing the htaccess where myddleware is installed I placed it in the htaccess on the prestashop host and I got a successful test!

RewriteCond %{HTTP:Authorization} ^(.*)

RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]

I did find this info in the prestashop forums. Thanks

**Comment by Myddleware** [comment]
Thanks for you feedback.
