### ISSUE TITLE
Add email as a duplicate field criteria for record creation in Vtiger CRM

### ISSUE THREAD

**Issue by rulotec** [Myddleware/myddleware#300]
When creating a rule, in the last step, you can specify fields to avoid duplicates:

![image](https://user-images.githubusercontent.com/36896420/79792785-20703d80-8315-11ea-94c2-4e41fa5c8d9b.png)

In the case of Vtiger, when creating Leads or Contacts, it would be very helpful to have email as an option. Avoiding duplicates by Lastname is not really a good option for large databases.

**Comment by Myddleware** [comment]
Hi @rulotec , 
We 'll work on it this week. We 'll keep you posted.

**Comment by rulotec** [comment]
Great, thanks!

**Comment by Myddleware** [comment]
Hi @rulotec ,
Here is the commit with the fix : https://github.com/Myddleware/myddleware/commit/37b2dfaa3bd3a6939ecda44b31ca446063680933
But we won't merge the hotfix branch to the master today, we will do it next week. However, if you want the fix today, you can just remplace the $FieldsDuplicate attribut in your file as we have done it on the commit : 
![image](https://user-images.githubusercontent.com/11330301/80240131-aa940b00-8661-11ea-8b1c-8c2d1e3c06d4.png)
Have a nice weekend.

**Comment by rulotec** [comment]
Awesome! Thanks!
