### ISSUE TITLE
show fieldlabels instead of fieldnames in Vtiger fields mapping

### ISSUE THREAD

**Issue by rulotec** [Myddleware/myddleware#301]
When you are in the mapping step of creating a new rule for vtiger as a target application, you see fieldnames like this:

![image](https://user-images.githubusercontent.com/36896420/79793329-fe2aef80-8315-11ea-8638-7ee984a0f026.png)

You can see fields like `cf_1028` which refer to "custom fields" (therefore the cf_ prefix) added to Vtiger by users (as opposed to already existing fields). In Vtiger there are "fieldnames" and "fieldlabels". I think it would be better to display the "fieldlabels" so that a user without code knowledge of Vtiger doesn't get confused by those names.

**Comment by Myddleware** [comment]
Hi @rulotec , 
We 'll work on it this week. We 'll keep you posted.

**Comment by Myddleware** [comment]
Sorry we couldn't work on it this week. We 'll do our best to work on this next week.
We 'll keep you posted.

**Comment by AlexMyddleware** [comment]
was resolved in later update.
