### ISSUE TITLE
How to change myddleware path after installation has been completed

### ISSUE THREAD

**Issue by rulotec** [Myddleware/myddleware#303]
I would like to move my myddleware's installation directory. This is because right now I have everything under the www public directory:

![image](https://user-images.githubusercontent.com/36896420/80054211-38e28280-84e4-11ea-893b-748e067363ff.png)

I suppose that only the "web" directory should be public (reachable by a browser) and not the rest of the directories.

What is the proper way of doing this and where should the application's path be changed?

**Comment by Myddleware** [comment]
HI @rulotec ,
You can set the directory rights to 755 and your file rights to 644 (or 775 and 664 depending on your server configuration).
Then the following directories have to be writable by the web user
•	myddleware/var/cache/
•	myddleware/var/logs/
The following files have to be writable by the web user :
•	myddleware/app/config/parameters.yml
•	myddleware/app/config/public/parameters_public.yml
•	myddleware/app/config/public/parameters_smtp.yml

Hope it helps.

**Comment by rulotec** [comment]
Thanks for the tips.

One more question in this regard. I just renamed the root folder say from `myddleware` to `myddleware2` but the app doesn't work on the new path. Is there a config file where I would need to change in order for the app to work with the new path?

**Comment by Myddleware** [comment]
Hi @rulotec ,
Could you clear the cache directory and try again ? Because there is no config file with the installation directory of Myddleware. So it should work.

**Comment by rulotec** [comment]
Thanks, it worked!
