### ISSUE TITLE
Ftp Connecteur

### ISSUE THREAD

**Issue by kent2206** [Myddleware/myddleware#304]
Bonjour
il m'est impossible de connecter mon SFTP Ionos 
 Connection failed : Please enable extension ssh2. Help here : http://php.net/manual/fr/ssh2.installation.php
Avez vous deja pu configurer sur Ionos Linux herbergement ?
Merci

**Comment by Myddleware** [comment]
Bonjour @kent2206 ,
En effet k'extension ssh2 est requise pour connecter Myddleware à un serveur SFTP. S'il n'est pas possible d'activer cette extension depuis le back office de Ionos, il faudrait contacter leur support pour leur demander comment activer cette extension.
Tenez moi au courant.

**Comment by kent2206** [comment]
Bonjour,

Effectivement il n'est pas possible chez Ionos
J'ai donc installé Myddleware sur mon Xampp avec un serveur SFTP sur FreeFTPd

La connexion se fait bien mais se déconnecte aussitôt 
04-28-2020 10:50:16 IP 192.168.X.X SFTP admin connected
04-28-2020 10:50:16 IP 192.168.X.X SFTP admin disconnected

PS: En me connectant par Filezilla tout est OK

Avez vous une idée ?

Cordialement,

**Comment by Myddleware** [comment]
Bonjour @kent2206 ,
Pouvez-vous me dire sur quel processus vous êtes : création de connecteur, création de règle, lancement de règle, autre ? 
Qu'est ce que vous obtenez dans Myddleware également ? 
Le fait que cela se déconnecte n'est pas forcément un problème tant que Myddleware a fini son action.

**Comment by kent2206** [comment]
Ça bloque sur la création 
La connexion se fait bien mais le test ne se valide pas 
Pas de visualisation du dossier 
Le test passe avec test.rebex.net:22

J’ai essayer avec d’autres serveurs sftp toujours le même résultat 
Tout est ok avec un client classique 

Merci pour votre aide

**Comment by Myddleware** [comment]
Le dossier sur lequel vous pointez contient-il au moins un autre dossier. En effet Myddleware va considérer tous les dossier comme des modules. Donc si le dossier sur lequel vous faites pointer Myddleware n'as pas de sous-dossier alors cela peut poser problème.
Pouvez-vous me dire ce qu'il en est ? 
Merci.

**Comment by kent2206** [comment]
Bonjour,

En changeant de SFTP et avec le sous dossier c'est ok
Parcontre le fichier CSV ne se charge pas 

`Warning: fopen(): Unable to open ssh2.sftp://805/XXX/XXX/30/XXX/htdocs/XXX/XXX/testcontrats2.csv on remote host in C:\xampp\htdocs\myddleware\src\Myddleware\RegleBundle\Solutions\file.php on line 149`

Comment doit être formater le CSV ?

Cordialement,

**Comment by Myddleware** [comment]
Bonjour,
Le csv doit être en ut8 et séparé par des ";" mais cela peut être redéfini. Le problème ici est en amont du formatage même du fichier. En effet Myddleware n'arrive pas à ouvrir votre fichier. 
Pouvez-vous vérifier que votre fichier est accessible par le user que vous utilisez pour vous connecter à votre serveur ?

**Comment by kent2206** [comment]
Bonjour,
J'ai trouver la solution 
`$fileName = trim($this->paramConnexion['directory'].'/'.$module.$file);`

paramConnexion['directory'] = au chemin absolu en remplacement par le chemin relatif tout est ok
Je l'ai codé en dur 
`$fileName = trim('/vtiger/testimport'.'/'.$module.$file);`

j'ai modifier également les lignes  271 et 366

Cependant j'ai un dernière erreur
`File : /vtiger/testimport/contrats/testcontrats2.csv : Error : File is rejected because the id of the line 2 is empty C:\xampp\htdocs\myddleware\src\Myddleware\RegleBundle\Solutions\file.php Line : ( 626 )`

**Comment by Myddleware** [comment]
Super, merci pour votre retour.

Pour la 2ème erreur, l'id qui est la référence de vos enregistrements dans le fichier est vide (au moins à la ligne 2). Il faut donc que vous sélectionniez dans la règle de Myddleware le champ correspondant à l'id de vos enregistrements  :
![image](https://user-images.githubusercontent.com/11330301/80807252-f5aba200-8bbc-11ea-90a5-8be562f082c6.png)

Si vous n'avez pas d'id dans votre fichier, vous pouvez sélectionner "generated by Myddleware", mais dans ce cas Myddleware ne fera que des création de données. En effet il ne sera pas possible pour Myddleware de faire des mise à jour si vous envoyez plusieurs fois le même enregistrement dans vos fichiers puisqu'il n'aura pas de référence.
Il ne sera pas non plus possible de lier d'autres règles à cette règle puisqu'il n'y aura pas de référence connues.
N'hésitez pas si je ne suis pas clair.

**Comment by kent2206** [comment]
Bonjour,

Effectivement tout est Ok
Il me manque à trouver comment récupérer l'userID 19X.. pour le champs Assigned_to

Merci pour votre aide

**Comment by Myddleware** [comment]
Merci pour votre retour @kent2206
 
Pouvez-vous ouvrir un autre fil de discussion au sujet  de la récupération de userID 19X pour le champs Assigned_to puisqu'il s'agit d'un nouveau sujet ? Merci.
