### ISSUE TITLE
Job scheduler error

### ISSUE THREAD

**Issue by z3n4j** [Myddleware/myddleware#305]
Myddleware  v2.5.4b

Hi. 

Job scheduler give me this error. If exexute all rules manuali it work.

Failed to create documents : Notice: Undefined index: values /var/www/html/src/Myddleware/RegleBundle/Classes/rule.php Line : ( 306 )Failed to create documents : Notice: Undefined index: values /var/www/html/src/Myddleware/RegleBundle/Classes/rule.php Line : ( 306 )Failed to create documents : Notice: Undefined index: values /var/www/html/src/Myddleware/RegleBundle/Classes/rule.php Line : ( 306 )Failed to create documents : Notice: Undefined index: values /var/www/html/src/Myddleware/RegleBundle/Classes/rule.php Line : ( 306 )

**Comment by Myddleware** [comment]
Hi @z3n4j ,
Could you run your rule one by one in background task to see the one which generates this error. It is also possible that all rules generate this erro.
To run a rule, please run this command in your prompt (like putty) from your Myddleware root directory: 
`php app/console myddleware:synchro ALL --env=background`
Please let me know if you have the error. 
If yes, please could you run this command to know which php version is used when a task runs in background : 
`php -v`

**Comment by z3n4j** [comment]
PHP 7.2.28 (cli) (built: Feb 18 2020 11:07:04) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.28, Copyright (c) 1999-2018, by Zend Technologies

**Comment by z3n4j** [comment]
sudo php app/console myddleware:synchro ALL --env=background
Could not open input file: app/console

**Comment by z3n4j** [comment]
php bin/console myddleware:synchro terpin_shop_opis_IT --env=background
1;5ea910446de681.41435480
terpin_shop_opis_IT
Read data for rule : terpin_shop_opis_IT
terpin_shop_opis_IT : Create documents.
terpin_shop_opis_IT : Number of documents created : 343
0;Failed to create documents : Notice: Undefined index: values /var/www/html/src/Myddleware/RegleBundle/Classes/rule.php Line : ( 306 )

**Comment by z3n4j** [comment]
php bin/console myddleware:synchro terpin_shop_opis_slo --env=background
1;5ea910800f1072.46934720
terpin_shop_opis_slo
Read data for rule : terpin_shop_opis_slo
terpin_shop_opis_slo : Create documents.
terpin_shop_opis_slo : Number of documents created : 343
0;Failed to create documents : Notice: Undefined index: values /var/www/html/src/Myddleware/RegleBundle/Classes/rule.php Line : ( 306 )

**Comment by z3n4j** [comment]
php bin/console myddleware:synchro terpin_shop_find_id_product --env=background
1;5ea9109fc995a1.27293533
terpin_shop_find_id_product
Read data for rule : terpin_shop_find_id_product
terpin_shop_find_id_product : Create documents.
terpin_shop_find_id_product : Number of documents created : 343
0;Failed to create documents : Notice: Undefined index: values /var/www/html/src/Myddleware/RegleBundle/Classes/rule.php Line : ( 306 )

**Comment by z3n4j** [comment]
php bin/console myddleware:synchro terpin_shop_quantities --env=background
1;5ea910bfcc8d77.73382406
terpin_shop_quantities
Read data for rule : terpin_shop_quantities
terpin_shop_quantities : Create documents.
terpin_shop_quantities : Number of documents created : 343
0;Failed to create documents : Notice: Undefined index: values /var/www/html/src/Myddleware/RegleBundle/Classes/rule.php Line : ( 306 )

**Comment by z3n4j** [comment]
I have 4 rules and all generate the error.

**Comment by Myddleware** [comment]
What is your source application ? Prestashop ? What is the module you read from your source application ? 
Could you add this before the return result in the method read of your class (if Prestashop : \myddleware\src\Myddleware\RegleBundle\Solutions\prestashop.php) : 
`print_r($result);`
![image](https://user-images.githubusercontent.com/11330301/80572670-f696d500-89fe-11ea-9c33-4692e4159f24.png)
What do you get  ?

**Comment by z3n4j** [comment]
My source application is MsSql, Target is Prestashop.

**Comment by Myddleware** [comment]
So could you add the print_r in the file \myddleware\src\Myddleware\RegleBundle\Solutions\database.php
![image](https://user-images.githubusercontent.com/11330301/80609436-58bffc00-8a38-11ea-8938-296657a6d0f8.png)

Please could you show me the result.

**Comment by Myddleware** [comment]
Ah yes and could you also add this line : 
![image](https://user-images.githubusercontent.com/11330301/80609639-a0df1e80-8a38-11ea-9384-80223a6db583.png)

It will display the query sent to your database.

**Comment by z3n4j** [comment]
Hi. I add the two line in database.php

**Comment by z3n4j** [comment]
![Screen Shot 05-15-20 at 07 34 AM 001](https://user-images.githubusercontent.com/18057413/82015273-afefde80-967e-11ea-97ce-54f6b49a167f.PNG)

**Comment by z3n4j** [comment]
![Screen Shot 05-15-20 at 07 34 AM](https://user-images.githubusercontent.com/18057413/82015294-b5e5bf80-967e-11ea-8f62-b4ffc72ab172.PNG)

**Comment by z3n4j** [comment]
The error is the same:

Failed to create documents : Notice: Undefined index: values /var/www/html/src/Myddleware/RegleBundle/Classes/rule.php Line : ( 306 )Failed to create documents : Notice: Undefined index: values /var/www/html/src/Myddleware/RegleBundle/Classes/rule.php Line : ( 306 )

**Comment by z3n4j** [comment]
![Screen Shot 05-15-20 at 07 34 AM 002](https://user-images.githubusercontent.com/18057413/82015360-dd3c8c80-967e-11ea-9aff-7eea33896bc3.PNG)

**Comment by Myddleware** [comment]
Hi @z3n4j ,
Yes, the error is definitely the same as the lines I have asked you to add are juste here to get more info from the error.
Could you just run the rule from a shell prompt ? And show me, using a screenshot,  what you get as the result, the SQL query should be display.
Thanks.

**Comment by z3n4j** [comment]
[janez@localhost html]$ php bin/console myddleware:synchro terpin_shop_opis_IT -                                                                                                                     -env=background
1;5ebe5e57bd3887.10289499
terpin_shop_opis_IT
Read data for rule : terpin_shop_opis_IT
terpin_shop_opis_IT : Create documents.
SELECT [Prezzo], [Flag_VetrinaWeb], [Flag_ArticoliWeb], [Profondita], [Descrizio                                                                                                                     neEstesaIT], [Codice], [Barcode], [Altezza], [CodiceIVA], [DescrRegFiscali], [De                                                                                                                     scrizione], [UnitaMisura], [Peso], [Larghezza], [Data_Modifica] FROM [WEB_ARTICO                                                                                                                     LI_PRESTASHOP] WHERE [Data_Modifica] > '2020-05-13 18:51:00' ORDER BY [Data_Modi                                                                                                                     fica] ASC OFFSET 0 ROWS FETCH NEXT 101 ROWS ONLY
Array
(
)
terpin_shop_opis_IT : Number of documents created : 0
[janez@localhost html]$ php bin/console myddleware:synchro terpin_shop_opis_slo --env=background
1;5ebe5e71d40e49.44090826
terpin_shop_opis_slo
Read data for rule : terpin_shop_opis_slo
terpin_shop_opis_slo : Create documents.
SELECT [Flag_VetrinaWeb], [Flag_ArticoliWeb], [DescrizioneEstesaSL], [Codice], [DescrizioneBreveSL], [Data_Modifica] FROM [WEB_ARTICOLI_PRESTASHOP] WHERE [Data_Modifica] > '2020-05-13 18:51:00' ORDER BY [Data_Modifica] ASC OFFSET 0 ROWS FETCH NEXT 101 ROWS ONLY
Array
(
)
terpin_shop_opis_slo : Number of documents created : 0
[janez@localhost html]$ php bin/console myddleware:synchro terpin_shop_find_id_product --env=background
1;5ebe5e7b353da9.61619828
terpin_shop_find_id_product
Read data for rule : terpin_shop_find_id_product
terpin_shop_find_id_product : Create documents.
SELECT [Codice], [Flag_ArticoliWeb], [Data_Modifica_Articoli_Contabile] FROM [WEB_ARTICOLI_PRESTASHOP] WHERE [Data_Modifica_Articoli_Contabile] > '2020-05-14 23:44:00' ORDER BY [Data_Modifica_Articoli_Contabile] ASC OFFSET 0 ROWS FETCH NEXT 101 ROWS ONLY
Array
(
)
terpin_shop_find_id_product : Number of documents created : 0
[janez@localhost html]$ php bin/console myddleware:synchro terpin_shop_quantities --env=background
1;5ebe5e8ae76ea5.17255396
terpin_shop_quantities
Read data for rule : terpin_shop_quantities
terpin_shop_quantities : Create documents.
SELECT [Flag_ArticoliWeb], [Esistenza], [Codice], [Data_Modifica_Articoli_Contabile] FROM [WEB_ARTICOLI_PRESTASHOP] WHERE [Data_Modifica_Articoli_Contabile] > '2020-05-14 23:44:00' ORDER BY [Data_Modifica_Articoli_Contabile] ASC OFFSET 0 ROWS FETCH NEXT 101 ROWS ONLY
Array
(
)
terpin_shop_quantities : Number of documents created : 0

**Comment by z3n4j** [comment]
But now it work.

**Comment by z3n4j** [comment]
![Screen Shot 05-15-20 at 11 22 AM](https://user-images.githubusercontent.com/18057413/82034392-66af8700-969e-11ea-9c52-e9aaac01320b.PNG)

**Comment by z3n4j** [comment]
![Screen Shot 05-15-20 at 11 23 AM](https://user-images.githubusercontent.com/18057413/82034408-6c0cd180-969e-11ea-81ff-85013132a469.PNG)

**Comment by Myddleware** [comment]
Did you change something on your rule ?

**Comment by z3n4j** [comment]
No. Now the error restart.:

[janez@localhost html]$ php bin/console myddleware:synchro terpin_shop_find_id_p                                                                                                                                                             roduct --env=background
1;5ebe7078023ed3.91228924
terpin_shop_find_id_product
Read data for rule : terpin_shop_find_id_product
terpin_shop_find_id_product : Create documents.
SELECT [Codice], [Flag_ArticoliWeb], [Data_Modifica_Articoli_Contabile] FROM [WE                                                                                                                                                             B_ARTICOLI_PRESTASHOP] WHERE [Data_Modifica_Articoli_Contabile] > '2020-05-14 23                                                                                                                                                             :44:00' ORDER BY [Data_Modifica_Articoli_Contabile] ASC OFFSET 0 ROWS FETCH NEXT                                                                                                                                                              101 ROWS ONLY
Array
(
    [count] => 11
    [error] => Error : Notice: Undefined index: deletion /var/www/html/src/Myddl                                                                                                                                                             eware/RegleBundle/Solutions/database.php Line : ( 418 )
)
terpin_shop_find_id_product : Number of documents created : 11
0;Failed to create documents : Notice: Undefined index: values /var/www/html/src                                                                                                                                                             /Myddleware/RegleBundle/Classes/rule.php Line : ( 306 )
[janez@localhost html]$ php bin/console myddleware:synchro terpin_shop_quantities --env=background
1;5ebe70854285c1.27777683
terpin_shop_quantities
Read data for rule : terpin_shop_quantities
terpin_shop_quantities : Create documents.
SELECT [Flag_ArticoliWeb], [Esistenza], [Codice], [Data_Modifica_Articoli_Contabile] FROM [WEB_ARTICOLI_PRESTASHOP] WHERE [Data_Modifica_Articoli_Contabile] > '2020-05-14 23:44:00' ORDER BY [Data_Modifica_Articoli_Contabile] ASC OFFSET 0 ROWS FETCH NEXT 101 ROWS ONLY
Array
(
    [count] => 11
    [error] => Error : Notice: Undefined index: deletion /var/www/html/src/Myddleware/RegleBundle/Solutions/database.php Line : ( 418 )
)
terpin_shop_quantities : Number of documents created : 11
0;Failed to create documents : Notice: Undefined index: values /var/www/html/src/Myddleware/RegleBundle/Classes/rule.php Line : ( 306 )
[janez@localhost html]$ php bin/console myddleware:synchro terpin_shop_opis_slo --env=background
1;5ebe70a0890cb9.75873515
terpin_shop_opis_slo
Read data for rule : terpin_shop_opis_slo
terpin_shop_opis_slo : Create documents.
SELECT [Flag_VetrinaWeb], [Flag_ArticoliWeb], [DescrizioneEstesaSL], [Codice], [DescrizioneBreveSL], [Data_Modifica] FROM [WEB_ARTICOLI_PRESTASHOP] WHERE [Data_Modifica] > '2020-05-13 18:51:00' ORDER BY [Data_Modifica] ASC OFFSET 0 ROWS FETCH NEXT 101 ROWS ONLY
Array
(
)
terpin_shop_opis_slo : Number of documents created : 0
[janez@localhost html]$ php bin/console myddleware:synchro terpin_shop_opis_IT - -env=background

In FileLocator.php line 44:

  The file "/var/www/html/app/config/config_nv=background.yml" does not exist.


[janez@localhost html]$ php bin/console myddleware:synchro terpin_shop_opis_IT - -env=background

In FileLocator.php line 44:

  The file "/var/www/html/app/config/config_nv=background.yml" does not exist.


[janez@localhost html]$

**Comment by z3n4j** [comment]
But if I Execute all runs from the browser It rework normal for some time and then the error return.

**Comment by z3n4j** [comment]
![Screen Shot 05-15-20 at 12 42 PM](https://user-images.githubusercontent.com/18057413/82042148-b2b3f900-96a9-11ea-8db6-73eeb44a0f1f.PNG)

**Comment by Myddleware** [comment]
Thanks.

For the 2 last error with "In FileLocator.php line 44:", I guess the problem is that you have a space between your 2 "-" in _opis_IT - -env=bac

The other problem seems to happen because of this query : 
`SELECT [Flag_ArticoliWeb], [Esistenza], [Codice], [Data_Modifica_Articoli_Contabile] FROM [WEB_ARTICOLI_PRESTASHOP] WHERE [Data_Modifica_Articoli_Contabile] > '2020-05-14 23:44:00' ORDER BY [Data_Modifica_Articoli_Contabile] ASC OFFSET 0 ROWS FETCH NEXT 101 ROWS ONLY`

Could you run it directly form your database and send me a screenshot of the result ? You should get at least 11 records.
Thanks.

**Comment by z3n4j** [comment]
The last 2 error the problem was the space.

**Comment by z3n4j** [comment]
![Screen Shot 05-15-20 at 05 01 PM](https://user-images.githubusercontent.com/18057413/82064949-b8233a80-96cd-11ea-889b-487d3b79d69a.PNG)

**Comment by z3n4j** [comment]
The translation of the error is:
Msg 242, Level 16, State 3, Line 1
Converting a varchar data type to smalldatetime generated a value outside the range of allowed values.

**Comment by z3n4j** [comment]
If i cancel the line WHERE:
![Screen Shot 05-15-20 at 05 03 PM](https://user-images.githubusercontent.com/18057413/82065114-f587c800-96cd-11ea-8df4-eeef47679f84.PNG)

**Comment by Myddleware** [comment]
Hi @z3n4j ,

The problem seems to be the Data_Modifica_Articoli_Contabile field type.

Is that possible that you convert the field Data_Modifica_Articoli_Contabile to a datetime field ? 

Otherwise, maybe you could create another field in your database (datetime type) and create a trigger to copie Data_Modifica_Articoli_Contabile content into this field each time this table is modified.  Then you use this new field as the reference in your Myddleware rule.

**Comment by z3n4j** [comment]
Hi. I check. Data_Modifica_Articoli_Contabile is smalldatatime field.  Is this the problem?

**Comment by Myddleware** [comment]
I guess it is the problem. Is that possible to convert it to a standard datetime field ?

**Comment by z3n4j** [comment]
Hi. I convert the data field in datetime (2020-04-06 23:12:05.000), But now myddleware rules don't find nothing to sincronize.

**Comment by z3n4j** [comment]
![image](https://user-images.githubusercontent.com/18057413/83868522-4e75d980-a72b-11ea-8987-7d867070466e.png)

**Comment by Myddleware** [comment]
Hi @z3n4j ,
Could you open a new issue for this topic ? In this new issue, could you also tell us what is the source module of your rule ? 
Thanks.

**Comment by Myddleware** [comment]
Do you have data in June for this table in your database ?
