### ISSUE TITLE
Formula 

### ISSUE THREAD

**Issue by z3n4j** [Myddleware/myddleware#307]
Hi. I have this formula. 

replace(" ","-", lower( {DescrRegFiscali}))

How I add to replace other caracters.

/ replace in -
" replace in -
$ replace in -

**Comment by Myddleware** [comment]
Hi @z3n4j ,
You can use array to change several characters and chr function for special characters (ascii code).
Something like that should meet your needs : 
`replace(array(chr(47), chr(34), chr(36) ," "), "-", lower( {DescrRegFiscali}))`

Could you tell me if it works ? Thanks.

**Comment by z3n4j** [comment]
Thank you. It works.
