### ISSUE TITLE
Magento 2.3.4 orders sync to Erpnext v12

### ISSUE THREAD

**Issue by ghost** [Myddleware/myddleware#308]
Trying to synchronize orders from magento 2 with erpnext using modules. Sales orders module in magento to Sales Invoice module in erpnext. I seem to map all the fields but it doesn't seem to work. Will keep trying. Meanwhile, is it possible to update the myddleware with the template for such sync? Any help would be greatly appreciated!

**Comment by Myddleware** [comment]
Hi @EstebanAorta 
Could you check your reference date in your rule, more info about it here : https://myddleware.github.io/myddleware/#/basic_usage?id=rule-parameters

You have to set up this date in the past if you want to read all orders. Then could you try to restart your rule. 

If it doesn't work, could you post a screenshot to show us what's the problem ? Thanks.

**Comment by ghost** [comment]
I do put the date in the past. Simulate transfer seems to work as expected. But when I run the rule I still get an error. Here is an error. 

![](https://raw.githubusercontent.com/EstebanAorta/images/master/transfer_error.gif)

Thank you!

**Comment by Myddleware** [comment]
Hi @EstebanAorta,
Could you post a screenshot of your data transfer content ? Thanks.

**Comment by ghost** [comment]
Here is what I have


![](https://raw.githubusercontent.com/EstebanAorta/images/master/cont1.jpg)

![](https://raw.githubusercontent.com/EstebanAorta/images/master/cont2.jpg)

Thanks.

**Comment by Myddleware** [comment]
Thanks. We will try to reproduce you issue today or tomorrow. 
I will keep you posted.

**Comment by Myddleware** [comment]
Hi @EstebanAorta ,

I see in you screenshot that you send the order to the customer 490 which is the same than Prestashop id. You should use the relationship to use the ERPNext ID for your customer. But firts you have to create a rule to send your Prestashop Customers to ERPNext.
You ca have a look to this tutorial : https://myddleware.github.io/myddleware/#/basic_usage

It is an example between Prestashop (E-commerce) et SuiteCRM (CRM) so it looks like you case.

Please try it and let me know if you could do what you want.
Thanks.

**Comment by Myddleware** [comment]
We can also reproduce the issue, so we are working on it to provide a fix as soon as possible.

**Comment by ghost** [comment]
I'm sending orders from Magento 2 to Erpnext. Does the Prestashop tutorial still apply?

Thank you!

**Comment by Myddleware** [comment]
You can follow the same steps by adapting the rule to your applications. Create first a rule for your customers then a rule for your orders which has to be linked to your customer rule. 
We will keep you updated about the bug with ERPNext connector.

**Comment by ghost** [comment]
Unfortunately, this doesn't work. I can't send customers from Magento to Erpnext as there are no customers created after transaction. Just the sales invoice. And sending the invoices result in above mentioned error. Please let me know once you get a chance to look into this. Thank you for your time!

**Comment by Myddleware** [comment]
Hi @EstebanAorta ,
Creating the customer rule first is the right way to sync Prestashop to ERPNext.
However, we still have the bug when it comes to create records in ERPNext. We will do our best to find the fix this today or tomorrow.
We will keep you posted.

**Comment by ghost** [comment]
Thank you for the effort!

**Comment by Myddleware** [comment]
Hi @EstebanAorta ,
Did you install ERPNExt with the Oracle's Virtual Box image ? 
Thanks.

**Comment by Myddleware** [comment]
Hi @EstebanAorta,
Could you change your ERPNext file like we did on this commit : https://github.com/Myddleware/myddleware/commit/0e3cee5b1f31d3cd2204ccf39fe7d86fc3ab5b81

Replace this (line 548) in the file src/Myddleware/RegleBundle/Solutions/erpnext.php : 
`return json_decode($response);`
By : 
```
$result = json_decode($response);
// If result not a json, we send the result as it has been return (used for 301 error for example)
if (empty($result)) {
	$result = $response;
}
return $result;
```
Then could you try again to create a record to ERPNext using Myddleware. You will still have an error but you should have more detail.
On our side we have the error : 
```
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
Do you have the same error ?

**Comment by Myddleware** [comment]
Hi @EstebanAorta ,
We have fixed the issue (if you had the same error than us). Could you upgrade you Myddleware and check again ?
A reminder to upgrade Myddleware, use the command : 
`php bin/console myddleware:upgrade --env=background`
More info here : https://myddleware.github.io/myddleware/#/admin_tasks?id=upgrading-myddleware
