### ISSUE TITLE
Can't delete rule.

### ISSUE THREAD

**Issue by ghost** [Myddleware/myddleware#309]
When I try to delete a rule it errors with: 
**Failed to delete the rule because there is at least one data transfer not deleted on this rule. Remove these transfers to be able to delete this rule.** 

But all transfers have status: **Cancel** 

What am I missing? 

Thank you!

**Comment by Myddleware** [comment]
Hi @EstebanAorta ,

Cancelling data transfer isn't enought to delete a rule, it is enought to edit the rule.

if you want to delete a rule you have to delete all data transfers of this rule. There is no button to do this action in Myddleware yet (it will be done soon).

For now, you have to run this command : 
`php bin/console myddleware:massaction remove rule <your rule id> Y --env=background 
`
Please let me know if it works. Thanks.

**Comment by Myddleware** [comment]
The documentation for this command is here : https://myddleware.github.io/myddleware/#/api?id=apimass_action

**Comment by ghost** [comment]
It worked. Thank you!
