### ISSUE TITLE
MSSQL little issue when columname have spaces

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#310]
Hi,
if columname have spaces then name is converted in a string without spaces, the rule crash and also if I try to edit rule I get error becouse columname it's not recognized.

**Comment by Myddleware** [comment]
Hi @simonetravaglini,
Thanks for this.
We will have a look into this. I will keep you posted this week.

**Comment by Myddleware** [comment]
Hi @simonetravaglini 
You can upgrade your Myddleware to version 2.5.4c, Your bug is fixed.
Have a nice day.
