### ISSUE TITLE
NGINX on php7.4 Installation

### ISSUE THREAD

**Issue by riaansteenberg** [Myddleware/myddleware#312]
Hi there,

I have installed Myddleware on a standard Ubuntu 18.04 virtual machine with Nginx and php7.4 fpm. Other sites work and database works. 

Everything checks out and installs and all steps went fine. Scripts confirm that all installation requirements are met. After installation the site comes up but when clicking on login button it remains "dead". No progress to next screen. No seeming submission of login details and no progression to next screen.  

Accessing with Chrome browser if that makes a difference. 

I was wondering if anyone else has experienced this and if there is any guidance on how to proceed.  

Thanks,

Riaan

**Comment by Myddleware** [comment]
Hi @riaansteenberg ,
Thanks for your message. Sorry but Myddleware si compatible php 7.2 and 7.3 but the check is done on php version > 7.2. So the check is OK for php 7.4 but we don't have tested Myddleware with php7.4 yet. 
We will check the compatibility with php7.4 and come back to you.

**Comment by CamillePMyddleware** [comment]
Hi, I archive this problem, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be. 
Thanks
