### ISSUE TITLE
Job scheduler datetime field tipe

### ISSUE THREAD

**Issue by z3n4j** [Myddleware/myddleware#317]
Hi I changed the data tipe from smalldate (because i get one error (#305)) to date. Bu now the rules don't sincronize nothing. I have every day new item to sincronize.

**Comment by Myddleware** [comment]
Hi @z3n4j 
Could you do again what you have done on the issue https://github.com/Myddleware/myddleware/issues/305

Put these lines ino your database.php file 
https://github.com/Myddleware/myddleware/issues/305#issuecomment-621256556
https://github.com/Myddleware/myddleware/issues/305#issuecomment-621257523

Then run the query into you database and change the datetime format until you get a result. Then we will see how to make Myddleware work.
Thanks.
