### ISSUE TITLE
MSSQL connector issue with date 

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#318]
Hi guys,
we faced following issue. 
In MSSQL connector seems an issue, when check data query is:

SELECT [Name], [Email], [Code], [PMEmail], [IsAreaMgr], [PID], [LastUpdateDate] FROM [SalesPersons] WHERE [LastUpdateDate] > '2020-06-15 00:00:00' ORDER BY [LastUpdateDate] ASC OFFSET 0 ROWS FETCH NEXT 1000 ROWS ONLY

But seems that
[LastUpdateDate] > '2020-06-15 00:00:00'
Shuold be
[LastUpdateDate] > '20200615'

**Comment by Myddleware** [comment]
Hi Simone,
Could you tell me what is the type of your field ? Is it a interger, a char , a date a datetime ... ?
Thanks.

**Comment by simonetravaglini** [comment]
Hi,
datetime

**Comment by Myddleware** [comment]
Alright, so you should have time inside your date and 20200615 shoulddn't be enought. Exept if you run this rule just 1 time per day otherwise you will read several time the same record.
Could you show me how this date is stored in your database with a screenshot ?
Thanks

**Comment by simonetravaglini** [comment]
![image](https://user-images.githubusercontent.com/6990139/84862581-b6a1b500-b073-11ea-98f6-a81e6af6e77d.png)
AAAA-MM-GG HH:MM:SS.mmm

If you need to send only date it's ok AAAAMMGG

**Comment by Myddleware** [comment]
Hi @simonetravaglini 

We could try to change the date format before the SQL query is sent to MSSQL

Could you create the file \myddleware\src\Myddleware\RegleBundle\Custom\Solutions\microsoftsql.php and add this code : 
```
<?php

namespace Myddleware\RegleBundle\Solutions;

//Custom class
class mysql extends microsoftsqlcore {
	
	// Redifine read function
	public function read($param) {
		// Redefine reference date format (add milliseconds)
		$date = new \DateTime($param['date_ref']);
		$param['date_ref'] = $date->format('Y-m-d H:i:s.v');
		// Call standard read function
		$result = parent::read($param);
	}
}
```
 If you display $requestSQL at line 391 in the file \myddleware\src\Myddleware\RegleBundle\Solutions\database.php : 
![image](https://user-images.githubusercontent.com/11330301/84875001-ad214880-b085-11ea-94c4-949024e1b001.png)

If you simulate your rule, you should see you query with milliseconds : 
![image](https://user-images.githubusercontent.com/11330301/84875146-dc37ba00-b085-11ea-9738-cf4ca1699549.png)

Could you tell me if it fixes your problem ? 
Thanks.

**Comment by simonetravaglini** [comment]
Hi we will check and let you know, thanks for support!

**Comment by francescobianco** [comment]
@Myddleware @simonetravaglini please take care about class override on top example we have:

```php
//Custom class
class mysql extends microsoftsqlcore {
.
```
instead of (the right solution)
```php
//Custom class
class microsoftsql extends microsoftsqlcore {
.
```

**Comment by Myddleware** [comment]
Hi @francescobianco ,

Yes you are right. I have tested it in mysql and forgot to change all the names in my post.

Thanks.

**Comment by simonetravaglini** [comment]
@francescobianco can you please also give other fix connected to missing return ?

**Comment by francescobianco** [comment]
@Myddleware @simonetravaglini please take care about read(.) method must end with a RETURN statement

```php
<?php

namespace Myddleware\RegleBundle\Solutions;

//Custom class
class mysql extends microsoftsqlcore {
	
	// Redifine read function
	public function read($param) {
		// Redefine reference date format (add milliseconds)
		$date = new \DateTime($param['date_ref']);
		$param['date_ref'] = $date->format('Y-m-d H:i:s.v');
		// Call standard read function
		$result = parent::read($param);
		return $result;       
	}
}
```

**Comment by Myddleware** [comment]
Oh yes your are right. When I have coded it, I have just checked that result was correct by diplaying it in debug. But I forgot to return it ;)
Thanks.
I still see mysql in your code so the right coee should be :
```
<?php

namespace Myddleware\RegleBundle\Solutions;

//Custom class
class microsoftsql extends microsoftsqlcore {
	
	// Redifine read function
	public function read($param) {
		// Redefine reference date format (add milliseconds)
		$date = new \DateTime($param['date_ref']);
		$param['date_ref'] = $date->format('Y-m-d H:i:s.v');
		// Call standard read function
		$result = parent::read($param);
		return $result;       
	}
}
```
Team work ;)

**Comment by simonetravaglini** [comment]
Hi we faced still a big issue.
Seems that date_ref is considered inverted, in example if I set
![image](https://user-images.githubusercontent.com/6990139/87553829-ae10be80-c6b3-11ea-892f-a50f69bdd516.png)
I get this error:
![image](https://user-images.githubusercontent.com/6990139/87553884-be289e00-c6b3-11ea-9956-ae5d839e483a.png)
Becouse date is considered something like 07-13-2020 and not 13-07-2020.

**Comment by francescobianco** [comment]
@Myddleware is seems similar to this https://stackoverflow.com/questions/19924236/query-comparing-dates-in-sql

Does make sense add date manipulation ad QUERY level eg. https://github.com/Myddleware/myddleware/blob/master/src/Myddleware/RegleBundle/Solutions/database.php#L390
?

**Comment by Myddleware** [comment]
Hi @francescobianco ,
What is your database date format ? Maybe you could just change the line 
`$date->format('Y-m-d H:i:s.v'); `
to
`$date->format('Y-d-m H:i:s.v');`
What do you think ?
