### ISSUE TITLE
Orders from Magento 2 to Erpnext

### ISSUE THREAD

**Issue by ghost** [Myddleware/myddleware#322]
Is there any way you could update the software with the template for transferring the orders from Magento 2 to erpnext? I can't seem to make it work on my own. Errors each time. This would be greatly appreciated!

Thank you!

**Comment by Myddleware** [comment]
Hi @EstebanAorta ,
We could help you to make your rules working. Then, we could help you to generate the template and you could share it as a contributor.
I propose that you could explain what you have done (all your rules) and the error you have. Thne we will help you to fix your rules.
Thanks.
