### ISSUE TITLE
Charts no longer appear

### ISSUE THREAD

**Issue by fosullivan-usam** [Myddleware/myddleware#323]
I recently noticed that none of the charts on the homepage render.

The browser console shows the following error:
Loading failed for the <script> with source “https://www.google.com/uds/?file=visualization&v=1&packages=corechart”.

Then, it shows the following list of errors, four times (one for each of the expected charts):
Uncaught TypeError: google.visualization is undefined
    success https://www.XXXXXX.com/myddleware/web/bundles/regle/js/home.js:32
    j https://www.XXXXXXX.com/myddleware/web/js/dfc36e2.js:2
    fireWith https://www.XXXXXX.com/myddleware/web/js/dfc36e2.js:2
    x https://www.XXXXXX.com/myddleware/web/js/dfc36e2.js:4
    b https://www.XXXXXX.com/myddleware/web/js/dfc36e2.js:4

When I visit the Google URL above, a webpage says:
We're sorry...
... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.

Do you have any ideas of what might be going on here?

**Comment by Myddleware** [comment]
Hi @fosullivan-usam ,
I confirm this issue. We will work on it. I 'll keep you posted.

**Comment by Myddleware** [comment]
Fixed in this commit : https://github.com/Myddleware/myddleware/commit/7dbe19e50baea6c79c8c4acd1d9fe802951b908e

**Comment by Myddleware** [comment]
@fosullivan-usam ,
You can upgrade your Myddleware instance in version 2.5.4h.
Please let me know if the home page is back to the normal. Thanks.
Have a nice day.

**Comment by fosullivan-usam** [comment]
I confirm that the upgrade has fixed the issue.
Many thanks.

**Comment by Myddleware** [comment]
Thanks for your feedback @fosullivan-usam
