### ISSUE TITLE
Version on footer

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#325]
After 3 updates of Myddleware version reported on footer still staled to the first one, by looking the file https://github.com/Myddleware/myddleware/blob/master/app/Resources/views/footer.html.twig
I'm not able to debug how it is provided by controller. Could you point me to path from parameters.yml to footer file?

**Comment by Myddleware** [comment]
Hi @francescobianco ,
The version is stored here : <myddleware_root>\app\config\parameters.yml
![image](https://user-images.githubusercontent.com/11330301/87410410-8f80c980-c5c6-11ea-8c4b-e4413db7fe61.png)

You have to clear your cache to see the new version.

Do you use this command to upgrade Myddleware : `php bin/console myddleware:upgrade --env=background ` ?
