### ISSUE TITLE
PHP Version at installation in Plesk

### ISSUE THREAD

**Issue by mirianmpr** [Myddleware/myddleware#326]
Hi all. 
I'm trying to install Myddleware in order to connect Prestashop and Moodle but I have a problem. When I execute the web installer I have an error:
Failed: The command "php /var/www/vhosts/gaiaecocrianza.com/myddleware.gaiaecocrianza.com/app/../bin//console cache:clear --env=prod" failed.
I have a VPS with Plesk, and I'm using PHP 7.2, but, my hosting tell me that I need to execute the command the next way:
/opt/plesk/php/7.2/bin/php bin/console cache:clear --env=prod
because it is needed to specify the php version in the command, by default Plesk is using php 5.6.
How can we do that?
Thank you very much.

**Comment by Myddleware** [comment]
Hi @mirianmpr ,
You can change the php command by modifying the parameter executable (php) in the file <myddleware_root>\app\config\public\parameters_public.yml
![image](https://user-images.githubusercontent.com/11330301/87803575-f5818100-c852-11ea-9fca-c20da7661801.png)

If it still doesn’t work, please clear the case by removing the content of the folder <myddleware_root>\var\cache
