### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by MisterIbe** [Myddleware/myddleware#327]
Bonjour,

Nous recevons depuis quelque temps les messages d'erreur suivants : 

- Règle Stock, id transfert 5efbee2c147243.66593811, le 2020-07-01 02:00:12 : Failed to check document predecessor : The document 5efa9ca7280db7.09254381 is on the same record and is not closed. This document is queued. /home/ibrahimmaalouf/public_html/myddleware/src/Myddleware/RegleBundle/Classes/document.php Line : ( 503 )Status : Predecessor_KO
- Règle Stock, id transfert 5efbee2c15a0b9.88888648, le 2020-07-01 02:00:12 : Failed to check document predecessor : The document 5efa9ca72931a2.25773841 is on the same record and is not closed. This document is queued. /home/ibrahimmaalouf/public_html/myddleware/src/Myddleware/RegleBundle/Classes/document.php Line : ( 503 )Status : Predecessor_KO
- Règle Stock, id transfert 5efa9ca7289f90.57284304, le 2020-07-01 02:00:38 : Failed to retrieve the available stock ID : Failed to find the combination/poduct id in Prestashop using the ean code /home/ibrahimmaalouf/public_html/myddleware/src/Myddleware/RegleBundle/Custom/Classes/document.php Line : ( 109 )Failed to transform document : Failed insert target data in the table DocumentData. /home/ibrahimmaalouf/public_html/myddleware/src/Myddleware/RegleBundle/Classes/document.php Line : ( 1135 )Status : Error_transformed
- Règle Stock, id transfert 5efa9ca72931a2.25773841, le 2020-07-01 02:00:38 : Failed to retrieve the available stock ID : Failed to find the combination/poduct id in Prestashop using the ean code /home/ibrahimmaalouf/public_html/myddleware/src/Myddleware/RegleBundle/Custom/Classes/document.php Line : ( 109 )Failed to transform document : Failed insert target data in the table DocumentData. /home/ibrahimmaalouf/public_html/myddleware/src/Myddleware/RegleBundle/Classes/document.php Line : ( 1135 )Status : Error_transformed
- Règle Stock, id transfert 5efbee2c15a0b9.88888648, le 2020-07-01 02:00:38 : Failed to check document predecessor : The document 5efa9ca72931a2.25773841 is on the same record and is not closed. This document is queued. /home/ibrahimmaalouf/public_html/myddleware/src/Myddleware/RegleBundle/Classes/document.php Line : ( 503 )Status : Predecessor_KO
- Règle Stock, id transfert 5efa9ca7280db7.09254381, le 2020-07-01 02:00:39 : Failed to retrieve the available stock ID : Failed to find the combination/poduct id in Prestashop using the ean code /home/ibrahimmaalouf/public_html/myddleware/src/Myddleware/RegleBundle/Custom/Classes/document.php Line : ( 109 )Failed to transform document : Failed insert target data in the table DocumentData. /home/ibrahimmaalouf/public_html/myddleware/src/Myddleware/RegleBundle/Classes/document.php Line : ( 1135 )Status : Error_transformed
- Règle Stock, id transfert 5efbee2c147243.66593811, le 2020-07-01 02:00:39 : Failed to check document predecessor : The document 5efa9ca7280db7.09254381 is on the same record and is not closed. This document is queued. /home/ibrahimmaalouf/public_html/myddleware/src/Myddleware/RegleBundle/Classes/document.php Line : ( 503 )Status : Predecessor_KO

Nous pensons que ces messages sont dus au fait que nous avons rendu actif 6 nouvelles références dans la base articles MVS , base qui communique par batch avec Middelware qui nous sert d'interface avec notre boutique Ibe Shop hébergée sur prestashop.

Hors ces 6 articles ne doivent pas descendre dans la boutique ( pour l instant car sont commercialisés par d autres circuits que la boutique ) , et cela génère toutes les nuits des messages d erreurs , il faut donc paramétrer Middelware on lui disant que c'est " normal" que ces articles ne sont pas créés dans prestashop et pour cela ne doivent pas redescendre via Middelware , et ainsi cesser de generer des "fausses" alertes qui pourraient cacher d autres alertes plus graves liées au bon fonctionnement du système. 

Sauriez-vous comment procéder ?

Merci !

**Comment by Myddleware** [comment]
Bonjour,
J'imagine que si vous voulez filtrer de nouveaux produits, alors d'anciens produits devaient déjà être filtrés. Pouvez-vous regarder dans l'édition de votre règle, onglet "Filtre", il devrait y avoir des produits filtrés. 
Si c'est le cas, vous pouvez ajouter les nouveaux produits à filtrer. 
Vous pouvez également annuler tous les transferts de données bloqués portant sur ces produits.
Tenez moi au courant.

**Comment by MisterIbe** [comment]
Bonjour,

Merci pour votre réponse ! J’ai bien trouvé la règle ainsi que les produits filtrés, cependant je n’arrive pas à ajouter des produits à filtrer. La règle ne peux pas être éditée car il y a des erreurs dans les transfers que je ne retrouve pas. 

Sauriez vous comment faire ?

Merci !

Rémi Takerkart

**Comment by Myddleware** [comment]
Bonjour Rémi,
En effet il faudrait que vous annuliez tous les transferts de données en erreur sur votre règle avant d'éditer votre règle. 
Pour cela vous pouvez chercher vos transferts de données en erreur comme ceci en indiquant bien la règle en question dans le filtre "Rule" ou "Règle" : 
![image](https://user-images.githubusercontent.com/11330301/88266784-1709bf00-ccd0-11ea-9d69-16e516bdc5c1.png)

Ensuite vous pouvez annuler les transferts de données de façon groupée : 
![image](https://user-images.githubusercontent.com/11330301/88266900-4ddfd500-ccd0-11ea-8708-d09c3e5b5884.png)

Vous pourrez ensuite éditer votre règle.

N'hésitez pas si ce n'est pas clair.

**Comment by MisterIbe** [comment]
Bonjour,

Super, j’ai pu ajouter les références à filtrer ! Je vous tiens au courant si les messages d’erreur continuent à être envoyés.

Merci beaucoup pour votre aide.

Bonne journée,

Rémi Takerkart

**Comment by Myddleware** [comment]
Merci beaucoup pour votre retour.
N'hésitez pas à ré ouvrir cette discussion si le problème n'est pas résolu.
Bonne journée.
