### ISSUE TITLE
Error transformed

### ISSUE THREAD

**Issue by z3n4j** [Myddleware/myddleware#328]
Hi. I have one error in one rule.

I convert the datetime in standard becausa i had problem with job scheduler.

Now the scheduler work. But i get one error in one rule.

**Comment by z3n4j** [comment]
![Screen Shot 07-23-20 at 04 47 PM](https://user-images.githubusercontent.com/18057413/88301850-6d452500-cd05-11ea-8d1f-b9b01ded4545.PNG)

**Comment by z3n4j** [comment]
![Screen Shot 07-23-20 at 04 48 PM](https://user-images.githubusercontent.com/18057413/88301870-73d39c80-cd05-11ea-8464-a2b370e1743c.PNG)

**Comment by z3n4j** [comment]
![Screen Shot 07-23-20 at 04 48 PM 001](https://user-images.githubusercontent.com/18057413/88301892-7a621400-cd05-11ea-97d8-b166e51f7266.PNG)

**Comment by z3n4j** [comment]
![Screen Shot 07-23-20 at 04 48 PM 002](https://user-images.githubusercontent.com/18057413/88301915-7f26c800-cd05-11ea-8773-b452b5bbbec3.PNG)

**Comment by z3n4j** [comment]
![Screen Shot 07-23-20 at 04 49 PM](https://user-images.githubusercontent.com/18057413/88301935-8352e580-cd05-11ea-94fa-46eae6f6e35b.PNG)

**Comment by z3n4j** [comment]
![Screen Shot 07-23-20 at 04 49 PM 001](https://user-images.githubusercontent.com/18057413/88301944-86e66c80-cd05-11ea-84c0-e6749c27beef.PNG)

**Comment by z3n4j** [comment]
![Screen Shot 07-23-20 at 04 49 PM 002](https://user-images.githubusercontent.com/18057413/88301952-8a79f380-cd05-11ea-8c60-0022bef71d5b.PNG)

**Comment by Myddleware** [comment]
Hi @z3n4j ,
Sorry but I don't understand your problem. Could you tell me more about the error you have? 
Thanks.

**Comment by z3n4j** [comment]
Hi. I have one rule wich serch in prestashop the product id. It works but now I get errors. How can i find where is the problem?

**Comment by Myddleware** [comment]
Please, could you give me the detail of the error. You should have it in the log of the data transfer in error. 
Thanks.

**Comment by z3n4j** [comment]
![Screen Shot 07-24-20 at 05 43 PM](https://user-images.githubusercontent.com/18057413/88409473-4bb36e80-cdd5-11ea-8412-222e11302349.PNG)

**Comment by Myddleware** [comment]
Hi @z3n4j ,
You have probably used the word "dummy" in a formula in you rule. Could you change it and try again ?
Have a nice day.

**Comment by z3n4j** [comment]
Hi. I changed the word with another and now work.

Thank you.

**Comment by Myddleware** [comment]
Perfect, thanks for your feedback.
