### ISSUE TITLE
Moodle Integration w ERPNext

### ISSUE THREAD

**Issue by jsaad-novetta** [Myddleware/myddleware#329]
Hello I'm getting the following when try to sync moodle 3.9 with erpnext 12.10.1

ERPNext -->Moodle
Error : 0 is not a correct Rule mode. /opt/bitnami/apache/htdocs/myddleware/src/Myddleware/RegleBundle/Solutions/erpnext.php 490

Moodle-->ERPNext
nothing seems to be coming up or working... no error message

Please help!

**Comment by Myddleware** [comment]
Hi @jysaad ,
Very sorry for my late reply. Yesterday was a busy day.
Could you give me more detail (and screenshot) about your  rule ERPNext -->Moodle ?

Could you also open another issue with more detail avout your rule Moodle-->ERPNext. It seems to be 2 differents issues.

We will be more reactive now :).

**Comment by jsaad-novetta** [comment]
Hello!

Thanks for your reply. Below is what I am experiencing:

In AWS I've installed myddleware on a bitnami-lampstack-7.4.8-0 image

I also have a moodle instance (bitnami-moodle-3.9.0-0) and an erpnext
instancev(bitnami-erpnext-12.10.1-0)
I'm having trouble syncing data though when I test.

I've attached screenshots of what I am choosing for all the screens. I do a
simple mapping of email, firstname, and lastname between the two but it
doesn't seem to work. Am I doing something wrong or do you have any insight
into anything?

Please help!

John

[image: Screen Shot 2020-07-29 at 3.45.56 PM.png]
[image: Screen Shot 2020-07-29 at 3.47.09 PM.png]
[image: Screen Shot 2020-07-29 at 3.47.18 PM.png]
[image: Screen Shot 2020-07-29 at 3.47.55 PM.png]
[image: Screen Shot 2020-07-29 at 3.48.03 PM.png]
[image: Screen Shot 2020-07-29 at 3.49.23 PM.png]

**Comment by Myddleware** [comment]
Hi @jysaad,
OK so when you click on simulation in your rule, your rule can read data from Moodle. So your moodle connector works properly.

Did you try to put your rule reference date in the past. The reference date is set by default to the rule creation date. If no Moodle user has been modified since this date, then Myddleware has nothing to read.

You will find more info about the reference date here : https://myddleware.github.io/myddleware/#/basic_usage?id=rule-parameters
Please, let me know if it has solved your issue.

**Comment by jsaad-novetta** [comment]
That did the trick - thank you!

I was able to successfully sync users from moodle to erpnext
I am having trouble getting grades from moodle into erpnext. Can you
provide any guidance or resources on this topic?

Thanks again!

**Comment by Myddleware** [comment]
Hi @jysaad 
Unfortunately, grade module module hasn't been developped yet. Here is the list of module available by Myddleware to read Moodle data : www.myddleware.com/solution/connected-applications?view=project&id=14:moodle
It has to be developped, Myddleware plugin module and Myddleware moodle connector will have to be enhenced.

**Comment by jsaad-novetta** [comment]
Ohh :(

Is there a timeline for development?
Is there another LMS that works with a CRM that you know of?

**Comment by Myddleware** [comment]
Sorry no timeline for this. 
Contact us directly via our website http://www.myddleware.com/contact-us if you want we develop it for you.
Have a nice day

**Comment by jsaad-novetta** [comment]
Ok I put in a request on the website and look forward to hearing back about
cost and timeline

**Comment by Myddleware** [comment]
Thanks.
We have answered you directly.

**Comment by Myddleware** [comment]
Done in the version 2.4.5g : https://github.com/Myddleware/myddleware/pull/336
