### ISSUE TITLE
Failed to run the task error

### ISSUE THREAD

**Issue by mirianmpr** [Myddleware/myddleware#330]
Hello, 

I've installed Myddleware in order to connect Prestashop and Moodle. I've configured the connectors and they are well tested, and I've created a rule using the default template. I've just only tried the users rule, and when I execute it, the result is the next error: Failed to run the task. 

What is the problem?

Thank you.

**Comment by Myddleware** [comment]
Hi @mirianmpr ,
It could be a right problem on your file.
Could check you log here : <myddleware_root_directory>\var\logs\prod.log ? Do you see an error ? 

Could you also try to run a rule using this command from you Myddleware root directory : 
`php bin/console myddleware:synchro <your rule id> --env=background`
Do you have an error ?

**Comment by mirianmpr** [comment]
I've reviewed the error_log and the result is: 

[Tue Jul 28 18:01:19.975913 2020] mod_fcgid: stderr: PHP Warning:  exec() has been disabled for security reasons in /var/www/vhosts/mydomain.com/myddleware.mydomain.com/src/Myddleware/RegleBundle/Classes/rule.php on line 941, referer: https://myddleware.mydomain.com/web/rule/view/5f15cbc0e59b2

Thank you for your response.

**Comment by Myddleware** [comment]
Hi @mirianmpr ,
OK the exec command is disabled on your server. 
You can try to run the rule using the command I wrote above. Do you have access to a shell prompt to run this kind of command ?

**Comment by mirianmpr** [comment]
Ok, I see.
No, I have no access to the shell prompt, but I can ask the hosting to run the command.

**Comment by Myddleware** [comment]
OK, but are you able to create a scheduled task (cron task) ? 
You could ask them to create the task to run Myddleware scheduler, then you could configure the rules you want to run. Here is more info about Myddleware scheduler : https://myddleware.github.io/myddleware/#/cron_jobs

**Comment by mirianmpr** [comment]
Hi, 
Sorry for the lapsus, I've got a lot of work these days.  
I've tried the console command and this is the result: 
PHP Fatal error:  Uncaught TypeError: Return value of DoctrineCommonAnnotationsAnnotationRegistry::registerLoader() must be an instance of DoctrineCommonAnnotationsvoid, none returned in /mydomain.com/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php:117
Stack trace:
#0 /mydomain.com/app/autoload.php(8): DoctrineCommonAnnotationsAnnotationRegistry::registerLoader(Array)
#1 /mydomain.com/bin/console(13): require('/var/www/vhosts...')
#2 {main}
  thrown in /mydomain.com/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 117
Thank you very much. 
Miriam
EL mar., jul. 28, 2020 a las 18:46, Myddleware  escribió:
 OK, but are you able to create a scheduled task (cron task) ?
 You could ask them to create the task to run Myddleware scheduler, then you could configure the rules you want to run. Here is more info about Myddleware scheduler : https://myddleware.github.io/myddleware/#/cron_jobs

**Comment by Myddleware** [comment]
Hi @mirianmpr 
Could you tell me what is your php version ? Please run this command via the console : `php -v`
Thanks.

**Comment by mirianmpr** [comment]
Hi,My php version is 7.2. I've executed again the command specifying the correct version and the result is 
1;5f2bd9829d0f40.32790258
5f15cbc0e59b2
Read data for rule : 5f15cbc0e59b2
0;Rule 5f15cbc0e59b2 is inactive.
Thank  you. 
Miriam
EL jue., ago. 6, 2020 a las 12:10, Myddleware  escribió:
 Hi @mirianmpr (https://github.com/mirianmpr)
 Could you tell me what is your php version ? Please run this command via the console : php -v
 Thanks.

**Comment by Myddleware** [comment]
Sounds good ;).
Thanks for your feedback.

**Comment by Myddleware** [comment]
You just have to enable your rule now  and run again your command: 
![image](https://user-images.githubusercontent.com/11330301/89521828-80192880-d7e0-11ea-9727-fa0bbf693c67.png)
Have a nice day.

**Comment by mirianmpr** [comment]
But I still have got the same error. 
In the console the response is this: 
1;5f2bdd240fa5e0.62184910
5f15cbc0e59b2
Read data for rule : 5f15cbc0e59b2
5f15cbc0e59b2 : Create documents.
statut New id = 5f2bdd244824d9.98589183  2020-08-06 10:36:20
statut New id = 5f2bdd244dd898.62207792  2020-08-06 10:36:20
statut New id = 5f2bdd244e20b0.47567971  2020-08-06 10:36:20
statut New id = 5f2bdd244e57d1.46955535  2020-08-06 10:36:20
statut New id = 5f2bdd244e9126.82228317  2020-08-06 10:36:20
statut New id = 5f2bdd244ec785.28623471  2020-08-06 10:36:20
statut New id = 5f2bdd244efe11.57993288  2020-08-06 10:36:20
statut New id = 5f2bdd244f3981.90483075  2020-08-06 10:36:20
statut New id = 5f2bdd244f7196.02191252  2020-08-06 10:36:20
statut New id = 5f2bdd244fb490.27673440  2020-08-06 10:36:20
statut New id = 5f2bdd244ff164.11963157  2020-08-06 10:36:20
statut New id = 5f2bdd24503051.60582313  2020-08-06 10:36:20
statut New id = 5f2bdd24507819.30436743  2020-08-06 10:36:20
statut New id = 5f2bdd2450b825.75717742  2020-08-06 10:36:20
statut New id = 5f2bdd2450f967.09078917  2020-08-06 10:36:20
statut New id = 5f2bdd24513655.29344455  2020-08-06 10:36:20
5f15cbc0e59b2 : Number of documents created : 16
statut Filter_OK id = 5f2bdd244824d9.98589183  2020-08-06 10:36:20
statut Filter_OK id = 5f2bdd244dd898.62207792  2020-08-06 10:36:20
statut Filter_OK id = 5f2bdd244e20b0.47567971  2020-08-06 10:36:20
statut Filter_OK id = 5f2bdd244e57d1.46955535  2020-08-06 10:36:20
statut Filter_OK id = 5f2bdd244e9126.82228317  2020-08-06 10:36:20
statut Filter_OK id = 5f2bdd244ec785.28623471  2020-08-06 10:36:20
statut Filter_OK id = 5f2bdd244efe11.57993288  2020-08-06 10:36:20
statut Filter_OK id = 5f2bdd244f3981.90483075  2020-08-06 10:36:20
statut Filter_OK id = 5f2bdd244f7196.02191252  2020-08-06 10:36:20
statut Filter_OK id = 5f2bdd244fb490.27673440  2020-08-06 10:36:20
statut Filter_OK id = 5f2bdd244ff164.11963157  2020-08-06 10:36:20
statut Filter_OK id = 5f2bdd24503051.60582313  2020-08-06 10:36:20
statut Filter_OK id = 5f2bdd24507819.30436743  2020-08-06 10:36:20
statut Filter_OK id = 5f2bdd2450b825.75717742  2020-08-06 10:36:20
statut Filter_OK id = 5f2bdd2450f967.09078917  2020-08-06 10:36:20
statut Filter_OK id = 5f2bdd24513655.29344455  2020-08-06 10:36:20
statut Predecessor_OK id = 5f2bdd244824d9.98589183  2020-08-06 10:36:20
statut Predecessor_OK id = 5f2bdd244dd898.62207792  2020-08-06 10:36:20
statut Predecessor_OK id = 5f2bdd244e20b0.47567971  2020-08-06 10:36:20
statut Predecessor_OK id = 5f2bdd244e57d1.46955535  2020-08-06 10:36:20
statut Predecessor_OK id = 5f2bdd244e9126.82228317  2020-08-06 10:36:20
statut Predecessor_OK id = 5f2bdd244ec785.28623471  2020-08-06 10:36:20
statut Predecessor_OK id = 5f2bdd244efe11.57993288  2020-08-06 10:36:20
statut Predecessor_OK id = 5f2bdd244f3981.90483075  2020-08-06 10:36:20
statut Predecessor_OK id = 5f2bdd244f7196.02191252  2020-08-06 10:36:20
statut Predecessor_OK id = 5f2bdd244fb490.27673440  2020-08-06 10:36:20
statut Predecessor_OK id = 5f2bdd244ff164.11963157  2020-08-06 10:36:20
statut Predecessor_OK id = 5f2bdd24503051.60582313  2020-08-06 10:36:20
statut Predecessor_OK id = 5f2bdd24507819.30436743  2020-08-06 10:36:20
statut Predecessor_OK id = 5f2bdd2450b825.75717742  2020-08-06 10:36:20
statut Predecessor_OK id = 5f2bdd2450f967.09078917  2020-08-06 10:36:20
statut Predecessor_OK id = 5f2bdd24513655.29344455  2020-08-06 10:36:20
statut Relate_OK id = 5f2bdd244824d9.98589183  2020-08-06 10:36:20
statut Relate_OK id = 5f2bdd244dd898.62207792  2020-08-06 10:36:20
statut Relate_OK id = 5f2bdd244e20b0.47567971  2020-08-06 10:36:20
statut Relate_OK id = 5f2bdd244e57d1.46955535  2020-08-06 10:36:20
statut Relate_OK id = 5f2bdd244e9126.82228317  2020-08-06 10:36:20
statut Relate_OK id = 5f2bdd244ec785.28623471  2020-08-06 10:36:20
statut Relate_OK id = 5f2bdd244efe11.57993288  2020-08-06 10:36:20
statut Relate_OK id = 5f2bdd244f3981.90483075  2020-08-06 10:36:20
statut Relate_OK id = 5f2bdd244f7196.02191252  2020-08-06 10:36:20
statut Relate_OK id = 5f2bdd244fb490.27673440  2020-08-06 10:36:20
statut Relate_OK id = 5f2bdd244ff164.11963157  2020-08-06 10:36:20
statut Relate_OK id = 5f2bdd24503051.60582313  2020-08-06 10:36:20
statut Relate_OK id = 5f2bdd24507819.30436743  2020-08-06 10:36:20
statut Relate_OK id = 5f2bdd2450b825.75717742  2020-08-06 10:36:20
statut Relate_OK id = 5f2bdd2450f967.09078917  2020-08-06 10:36:20
statut Relate_OK id = 5f2bdd24513655.29344455  2020-08-06 10:36:20
statut Transformed id = 5f2bdd244824d9.98589183  2020-08-06 10:36:20
statut Transformed id = 5f2bdd244dd898.62207792  2020-08-06 10:36:20
statut Transformed id = 5f2bdd244e20b0.47567971  2020-08-06 10:36:20
statut Transformed id = 5f2bdd244e57d1.46955535  2020-08-06 10:36:20
statut Transformed id = 5f2bdd244e9126.82228317  2020-08-06 10:36:20
statut Transformed id = 5f2bdd244ec785.28623471  2020-08-06 10:36:20
statut Transformed id = 5f2bdd244efe11.57993288  2020-08-06 10:36:20
statut Transformed id = 5f2bdd244f3981.90483075  2020-08-06 10:36:20
statut Transformed id = 5f2bdd244f7196.02191252  2020-08-06 10:36:20
statut Transformed id = 5f2bdd244fb490.27673440  2020-08-06 10:36:20
statut Transformed id = 5f2bdd244ff164.11963157  2020-08-06 10:36:20
statut Transformed id = 5f2bdd24503051.60582313  2020-08-06 10:36:20
statut Transformed id = 5f2bdd24507819.30436743  2020-08-06 10:36:20
statut Transformed id = 5f2bdd2450b825.75717742  2020-08-06 10:36:20
statut Transformed id = 5f2bdd2450f967.09078917  2020-08-06 10:36:20
statut Transformed id = 5f2bdd24513655.29344455  2020-08-06 10:36:20
statut Ready_to_send id = 5f2bdd244824d9.98589183  2020-08-06 10:36:20
statut Ready_to_send id = 5f2bdd244dd898.62207792  2020-08-06 10:36:20
statut Ready_to_send id = 5f2bdd244e20b0.47567971  2020-08-06 10:36:20
statut Ready_to_send id = 5f2bdd244e57d1.46955535  2020-08-06 10:36:20
statut Ready_to_send id = 5f2bdd244e9126.82228317  2020-08-06 10:36:20
statut Ready_to_send id = 5f2bdd244ec785.28623471  2020-08-06 10:36:20
statut Ready_to_send id = 5f2bdd244efe11.57993288  2020-08-06 10:36:20
statut Ready_to_send id = 5f2bdd244f3981.90483075  2020-08-06 10:36:20
statut Ready_to_send id = 5f2bdd244f7196.02191252  2020-08-06 10:36:20
statut Ready_to_send id = 5f2bdd244fb490.27673440  2020-08-06 10:36:20
statut Ready_to_send id = 5f2bdd244ff164.11963157  2020-08-06 10:36:20
statut Ready_to_send id = 5f2bdd24503051.60582313  2020-08-06 10:36:21
statut Ready_to_send id = 5f2bdd24507819.30436743  2020-08-06 10:36:21
statut Ready_to_send id = 5f2bdd2450b825.75717742  2020-08-06 10:36:21
statut Ready_to_send id = 5f2bdd2450f967.09078917  2020-08-06 10:36:21
statut Ready_to_send id = 5f2bdd24513655.29344455  2020-08-06 10:36:21
statut Error_sending id = 5f2bdd244824d9.98589183  2020-08-06 10:36:21
statut Error_sending id = 5f2bdd244dd898.62207792  2020-08-06 10:36:21
statut Error_sending id = 5f2bdd244e20b0.47567971  2020-08-06 10:36:21
statut Error_sending id = 5f2bdd244e57d1.46955535  2020-08-06 10:36:21
statut Error_sending id = 5f2bdd244e9126.82228317  2020-08-06 10:36:21
statut Error_sending id = 5f2bdd244ec785.28623471  2020-08-06 10:36:21
statut Error_sending id = 5f2bdd244f3981.90483075  2020-08-06 10:36:21
statut Error_sending id = 5f2bdd244f7196.02191252  2020-08-06 10:36:21
statut Error_sending id = 5f2bdd244fb490.27673440  2020-08-06 10:36:21
statut Error_sending id = 5f2bdd244ff164.11963157  2020-08-06 10:36:21
statut Error_sending id = 5f2bdd24503051.60582313  2020-08-06 10:36:21
statut Error_sending id = 5f2bdd24507819.30436743  2020-08-06 10:36:21
statut Error_sending id = 5f2bdd2450b825.75717742  2020-08-06 10:36:21
statut Error_sending id = 5f2bdd2450f967.09078917  2020-08-06 10:36:21
statut Error_sending id = 5f2bdd24513655.29344455  2020-08-06 10:36:21
statut Error_sending id = 5f2bdd244efe11.57993288  2020-08-06 10:36:21
Thanks,
Miriam
EL jue., ago. 6, 2020 a las 12:30, Myddleware  escribió:
 You just have to enable your rule now and run again your command:
 (https://user-images.githubusercontent.com/11330301/89521828-80192880-d7e0-11ea-9727-fa0bbf693c67.png)
 Have a nice day.

**Comment by mirianmpr** [comment]
I don't know if you received my message becouse the thread is closed.

**Comment by Myddleware** [comment]
I closed the thread because you task runs properly. The message you have is the detail of the action Myddleware has done. 
Myddleware has read 16 records from your source application and we can see that Myddleware couldn't send it to your target application (error_sending status).
Now you can go into Myddleware UI and open of of these data transfer in error, you will have some logs at the bottom of the page with the error that the target application has returned.
If you don't know how to manage the error, you can open a new thread. 
I close this one because your task isn't in error anymore.
Have a nice day.
