### ISSUE TITLE
Problem with myddleware + moodle integration.

### ISSUE THREAD

**Issue by Inv0k-er** [Myddleware/myddleware#333]
Hello. 

In moodle I created a token from user. 
And when I try to create connector in Myddleware from Moodle and I have a error. 

Connection failed : Error unknown.

![myddleware](https://user-images.githubusercontent.com/42607075/88795759-5baac400-d1c2-11ea-9f8e-b6a367a7013b.PNG)

Myddleware version -  2.1  

in ~ var/logs/prod.log 
I see app.ERROR: Error unknown.  [] []

![logs](https://user-images.githubusercontent.com/42607075/88796390-5a2dcb80-d1c3-11ea-8036-edbe5708c669.png)

**Comment by Myddleware** [comment]
Hi @Inv0k-er ,
Did you follow all step into Moodle : https://docs.moodle.org/20/en/Using_web_services ?

Could you also upgrade Myddleware instance as  version 2.1 is very old ? As it is a big upgrade I advise you to test the upgrade on a copy of your production instance of Myddleware.

**Comment by Inv0k-er** [comment]
Thanks it is help me.

**Comment by Myddleware** [comment]
Thanks for your feedbak.
