### ISSUE TITLE
Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.

### ISSUE THREAD

**Issue by ItsDevMonk** [Myddleware/myddleware#339]
[ERROR]
Failed: The command "php /var/www/html/myddleware/app/../bin//console doctrine:schema:update --force --env=prod" failed. Exit Code: 1(General error) Working directory: /var/www/html/myddleware/web Output: ================ Error Output: ================ In AbstractPlatform.php line 436: Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it. doctrine:schema:update [--complete] [--dump-sql] [-f|--force] [--em [EM]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--]

I got this error while trying to submit the database access and myddleware user. 

Installed on ubuntu 18

copied myddleware directory inside /var/www/html.

I have moodle also there in the same folder  /var/www/html.

**Comment by Myddleware** [comment]
Hi @smartnava ,
Have you created Myddleware database (empty database) and set its parameters in the file /myddleware/app/config/parameters.yml ?
If you plan to install Myddleware using the console, you can follow this tutorial : https://myddleware.github.io/myddleware/#/?id=install-myddleware

**Comment by ItsDevMonk** [comment]
I didn't create a new database. I set the parameters with an existing database in the parameter.yml file.

With new database it is working now. Thank you
