### ISSUE TITLE
Match with existing record

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#340]
Hi, one question.
If I create a rules that sync A with B, in B I set a field as unique identifier. If during first sync a record from A already exist in B (same unique identifier), then record in B is "linked" in myddleware and used in following run? Or is only skipped or created as new record?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
In this case you have to set the B field as duplicate check in the rule edit view : 
![image](https://user-images.githubusercontent.com/11330301/89667023-aa034580-d8db-11ea-9935-4812073de75f.png)

You can redefined the class for your target solution and add this array to add fields available for duplicate check : 
```
protected $FieldsDuplicate = array(	
    '<module1>' => array('field1', 'lfield2'),
    '<module2>' => array('field1'),
    'default' => array('field1'),
 );

```
 
Please let me know if it helps

**Comment by simonetravaglini** [comment]
Hi thanks for answer, suppose that expected behaviour is not skip record, but merge record. The correct way is to set "fields to avoid duplicate"? Based on this fields the behaviour of myddleware is merge or skip?

**Comment by Myddleware** [comment]
It depend of what you select in the field "Synchronization type" : 
![image](https://user-images.githubusercontent.com/11330301/89781087-f1bfe200-db12-11ea-9366-478358348284.png)

If you select "Create and update data", Myddleware will update the existing record (merge). If you select "Create data only", Myddleware will cancel the data transfer (skip).
