### ISSUE TITLE
I can't cancel transfers

### ISSUE THREAD

**Issue by mirianmpr** [Myddleware/myddleware#341]
Hi, 
I want to edit a rule, but it has transfers with errors that I want to delete. When I try to cancel them, I have the next message: Failed to run the job.
When I go to the tasks list I see the tasks ended, I don't see any option to stop them. 
Could you help me, please?
Thanks

![image](https://user-images.githubusercontent.com/68368279/89706333-ec249980-d964-11ea-9df9-900b87d36194.png)

**Comment by Myddleware** [comment]
Hi @mirianmpr 
When you try to cancel data transfers, Myddleware run a job with exec command which isn't allowed by your hoster, if I remember well.
So you can run this command in your console to cancel every data transfers belonging to a specific rule : 
`php bin/console myddleware:massaction cancel rule <your rule id> Y --env=background`

Here you can find more info about this function (the doc show how to launch this function with CURL but you can run it via the console) : https://myddleware.github.io/myddleware/#/api?id=apimass_action

**Comment by mirianmpr** [comment]
Ok, thank you. I cancelled without  problem. But, can I delete this transfers? I see if I try again the rule, I can't use the same data because they have created the documents.

**Comment by Myddleware** [comment]
Hi @mirianmpr ,
You can use the same command and change "cancel" by "remove". It will remove the data transfer of your rule.
Hope it will help.

**Comment by mirianmpr** [comment]
Yes, I used "remove", but they are still there marked as "cancel" and I can't use them again.

**Comment by Myddleware** [comment]
Hi @Myddleware ,
The remove action with the "Y" should remove all the data transfer of your rule. 
Please could you add some details and screenshots to show me which data transfer aren't removed ? 
Thanks.
