### ISSUE TITLE
SuiteCRM password containing ambiguous characters

### ISSUE THREAD

**Issue by fosullivan-usam** [Myddleware/myddleware#342]
When setting up a connector to SuiteCRM, if the password for the username you are using contains any ambiguous characters (e.g., { } [ ] ( ) / \ ' " ` ~ , ; : . < > ), the connector fails the test and you can't save the settings.  When you change the password to use 'normal' characters, it works.  

To recreate, try using https://passwordsgenerator.net/ to generate a 16-character password with ambiguous characters checked.  Use that for the SuiteCRM user, and try logging into SuiteCRM (that will work fine).  Then set up a Myddleware connector to that user, and it will fail.  Furthermore, the error message provides no details as to what went wrong.

**Comment by Myddleware** [comment]
Thanks @fosullivan-usam ,
We will fix this in the next main release.

**Comment by CamillePMyddleware** [comment]
Hi,I am archiving this issue, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be. 
Thanks
