### ISSUE TITLE
Empty relationship fields, even when optional, prevent the record from synchronizing

### ISSUE THREAD

**Issue by fosullivan-usam** [Myddleware/myddleware#343]
Myddleware fails to sync records between two SuiteCRM systems if any of the Relations fields are empty.  

Our system has a custom module with 6 fields that map to fields in other modules.  Two of those fields are optional in the source system; however, we still want to sync those records with the destination system.

**Comment by Myddleware** [comment]
Hi @fosullivan-usam ,
When a relation field is empty, Myddleware shouldn't search the relate record.  Please could you provide  more detail about your error with some screenshot : the detail of a data transfer in error and the detail of your rule (relationship and field mapping tabs) ?
Thanks.

**Comment by fosullivan-usam** [comment]
As you surely expected, the source database did have a value in the field in question.  In this scenario, the Source_ID pointed to a record that no longer exists in the source database, so SuiteCRM showed it as being empty.  A quick look at the raw table showed the culprit which I deleted, and now everything runs smoothly.
Thanks (as usual) for your rapid response.

**Comment by Myddleware** [comment]
Thanks for your feedback.
