### ISSUE TITLE
Error sitepolicynotagreed with Moodle

### ISSUE THREAD

**Issue by mirianmpr** [Myddleware/myddleware#345]
Hi, 
When I try to create the users from Prestashop to Moodle I'm obtaining the error sitepolicynotagreed. I have an optional policy in Moodle, and I don't know how can I pass a value to Moodle in order to avoid this error. 
Thank you.

**Comment by Myddleware** [comment]
Hi @mirianmpr ,
I think you have to change a setting in your Moodle instance. Probaly in this page : Site administration -> Security ->Site policies
Could you tell us if it helps ? 
Thanks.

**Comment by mirianmpr** [comment]
Yes, but the policies are marked as optional, not compulsory. I've tried to deactivate the site policy, but the error persists.

**Comment by mirianmpr** [comment]
I've deactivated all the policy rules and the rule worked! But I don't know why can't I have the rules activated. 

Thank  you.

**Comment by Myddleware** [comment]
Thanks for your feedback. 
Please let us know if you have any other question.
