### ISSUE TITLE
Unable to configure the connectors in myddleware 

### ISSUE THREAD

**Issue by Yuvarajsfcloud** [Myddleware/myddleware#346]
we are integrating Moodle & Salesforce through Myddleware and it was working fine couple of months back. we had a change in salesforce credentials for which I tried to reconfigure the connector and I ended up with the following error . 

**Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please check your log file here : \myddleware\var\logs\prod.log

You can post an issue on Myddleware Github project

Sorry for any inconvenience.**

**Comment by Myddleware** [comment]
No problem,
could you open your log file : \myddleware\var\logs\prod.log
Then regenerate the error in Myddleware.
Then open again your log file and POST the new lines here please.
Thanks.

**Comment by Yuvarajsfcloud** [comment]
[2020-09-03 14:08:01] request.CRITICAL: Uncaught PHP Exception Illuminate\Contracts\Encryption\DecryptException: "The MAC is invalid." at D:\Inetpub\Web\PDC\pdcwebp002vw.state.in.us\myddleware\vendor\illuminate\encryption\Encrypter.php line 148 {"exception":"[object] (Illuminate\\Contracts\\Encryption\\DecryptException(code: 0): The MAC is invalid. at D:\\Inetpub\\Web\\PDC\\pdcwebp002vw.state.in.us\\myddleware\\vendor\\illuminate\\encryption\\Encrypter.php:148)"} []
[2020-09-03 14:08:22] request.CRITICAL: Uncaught PHP Exception Illuminate\Contracts\Encryption\DecryptException: "The MAC is invalid." at D:\Inetpub\Web\PDC\pdcwebp002vw.state.in.us\myddleware\vendor\illuminate\encryption\Encrypter.php line 148 {"exception":"[object] (Illuminate\\Contracts\\Encryption\\DecryptException(code: 0): The MAC is invalid. at D:\\Inetpub\\Web\\PDC\\pdcwebp002vw.state.in.us\\myddleware\\vendor\\illuminate\\encryption\\Encrypter.php:148)"} []

**Comment by Myddleware** [comment]
Hi @Yuvarajsfcloud ,
Did you change the secret in the file \myddleware\app\config\parameters.yml ? Or have you re installed Myddleware and copyied the database to the new Myddleware ? 
Thanks.

**Comment by Yuvarajsfcloud** [comment]
I’m not sure whether something has changed in the recent days.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Myddleware** [comment]
It seems that your secret key has been changed. So Myddleware isn't able anymore to decrypt your Salesforce access.
What is your Myddleware version ?

**Comment by Yuvarajsfcloud** [comment]
v2.5.4b

**Comment by Myddleware** [comment]
Have you recently upgraded Myddleware  ?

**Comment by Yuvarajsfcloud** [comment]
Yes . Now we have a different issue.  we recreated all the rules & connectors and it works when we execute manually. 
we schedule the Synchro (All Rows) with Period 5, but I don't see any task created for the Job Run. There is no trace of the transfers. we need the assistance immediately.

**Comment by Myddleware** [comment]
Hi @Yuvarajsfcloud 
We do our best to be reactive on the forum.  However, I hope you understand that we have to support our client first.
Have you added the Myddleware job in your scheduler on your serveur (crontab if you use a linux server)?

**Comment by Yuvarajsfcloud** [comment]
Yes I do understand . I appreciate your quick response. I scheduled the job through the UI using the Job Schedular available in the top right right corner.

**Comment by Myddleware** [comment]
Cool.
OK but you have to add this task in the scheduler of your server : php bin/console myddleware:jobScheduler --env=background > /dev/null 2>&1
If you have linux, please add this line in your crontab : 
`*/5 * * * * cd <path of myddleware root directory> ; php bin/console myddleware:jobScheduler --env=background > /dev/null 2>&1`

Myddleware scheduler will be launch every 5 minutes and it will run your rules according to your configuration.

More info about Myddleware scheduler here : https://myddleware.github.io/myddleware/#/cron_jobs

Hope it will help.

**Comment by Yuvarajsfcloud** [comment]
Hi Team,

Based on your suggestion , I have used php bin/console myddleware:jobScheduler --env=background to schedule the job on CMD. It ran immediately without any issues. But one of the transfer got failed.

After that the scheduled job didn’t run at all.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Yuvarajsfcloud** [comment]
Hi Team, 

Could you please confirm that the scheduler job stops if any transfer fails and we need to re initiate the scheduler from the CMD again.

**Comment by Myddleware** [comment]
Hi @Yuvarajsfcloud ,
The scheduler doesn't stop if a transfer fails. The only thing that can stop the scheduler is when a job couldn't finish.
Could you open your tak list and check the last job. What is its status ?
Thanks.

**Comment by Yuvarajsfcloud** [comment]
![image](https://user-images.githubusercontent.com/44530191/93298673-4bea4c00-f811-11ea-921c-b967864e97e2.png)
Attached the snapshot of the Task which was executed by Scheduler immediately after we scheduled. and there was no job ran after that. we had to run it manually every time

**Comment by Myddleware** [comment]
OK.
Could you show me how your have created your scheduler task (the crontab if you use linux) ? Thanks.

**Comment by Yuvarajsfcloud** [comment]
![image](https://user-images.githubusercontent.com/44530191/93299089-1c880f00-f812-11ea-90d5-d759cd8c6792.png)

**Comment by Myddleware** [comment]
Your screenshot shows a task running, not the scheduler task. So you have to create a scheduler tack to run Myddleware job automatically.

**Comment by Yuvarajsfcloud** [comment]
I have used php bin/console myddleware:jobScheduler --env=background on the cmd. I believe this is right. Could you please confirm?

**Comment by Myddleware** [comment]
Yes this is right if you want to run a task without opening Myddleware.
However, if you want to run this task automatically, you have to tell windows (I see in your screenshot that your are using Windows) to run your command (the one you run on the cmd) every 5 minutes (or 15 minutes or more... like you want).
Hope it helps.

**Comment by Yuvarajsfcloud** [comment]
Ok . The only thing which we missed to mention is the frequency in the Scheduled Task. How do I modify the command to run every minutes 
php bin/console myddleware:jobScheduler --env=background 

Also how this interferes with the period mentioned in the Job schedular table. Will we end up with conflict sometime?

**Comment by Myddleware** [comment]
Sorry but it isn't just to change the command. You have to create a scheduler task. Here is a video that will probably help you : https://www.youtube.com/watch?v=HAOP0HZeDJg

There is no conflict with the Myddleware scheduler table. You just have to make sure to run your sheduler task with a period lower or equal to the shortest period you have set in Myddleware table.

**Comment by Yuvarajsfcloud** [comment]
Appreciate your help. I will watch and run it accordingly

**Comment by Yuvarajsfcloud** [comment]
Its fixed now. Thanks a lot for helping out
