### ISSUE TITLE
Error when process scheduled

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#347]
Hi,
I've a scheduled process that give error:
![image](https://user-images.githubusercontent.com/6990139/92563685-3eb0e880-f278-11ea-859b-07094eef9d05.png)

Consider that if I run manually process I don't get any error and then if I manually reload transfer than go in status transformed.

Can you help me to understand?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
Could you show me the field mapping tab of your rule ? Could you also show me a data transfer in error (data transfer content with source and target + data transfer log) ? 
Thanks.

**Comment by simonetravaglini** [comment]
here field mapping
![image](https://user-images.githubusercontent.com/6990139/92565182-8a649180-f27a-11ea-9156-fc3464548b33.png)

**Comment by simonetravaglini** [comment]
![image](https://user-images.githubusercontent.com/6990139/92573345-f6002c00-f285-11ea-8b76-db1a59a966bd.png)

**Comment by Myddleware** [comment]
Hi Simone, I see in the creenshot you sent me directly that the date DATADINASCIATA hase the format d/m/Y (19/03/1990). But when I see your formula you try to change the format d-m-Y. 
Could you change your formula and try again ? 
Thanks.
