### ISSUE TITLE
How to "reset" a rule

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#348]
Hi,
suppose I've been a rules correctly set. But not sure if all data in my target are related to rule. So I want delete everythings and force sync like if is first time.
If I delete everythings in target then rules when run will not work correctly. So I suppose I have to "clear" the situation. There is a console command or db query to do that?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
If you want to re sync your data from scratch, yes clear the target application and remove all data trasfer in Myddleware for this rule.
There is a specific command to remove all data transfer in your rule, please have a look to this : https://github.com/Myddleware/myddleware/issues/309#issuecomment-633500529
