### ISSUE TITLE
Message d'erreur 

### ISSUE THREAD

**Issue by MisterIbe** [Myddleware/myddleware#349]
Bonjour,

Nous avons reçu le message d'erreur suivant : 

Here the errors:
- Règle Products to Cirrus, id transfert 5f5c2ba3669085.10276527, le 2020-09-12 02:00:06 : Name:Error_MSG_Field_Required,Failed to send document. Status : Error_sending
- Règle Product list to Cirrus, id transfert 5f5c2bb937e409.38092970, le 2020-09-12 02:00:25 : No data for the field Myddleware_element_id in the rule product_list_to_cirrus. Failed to check document related : Failed to retrieve a related document. No data for the field Myddleware_element_id. There is not record with the ID source 30 in the rule Products to Cirrus. This document is queued. /home/ibrahimmaalouf/public_html/myddleware/src/Myddleware/RegleBundle/Classes/document.php Line : ( 684 )Status : Relate_KO
- Règle Products to Cirrus, id transfert 5f5c2ba3669085.10276527, le 2020-09-12 02:00:28 : Name:Error_MSG_Field_Required,Failed to send document. Status : Error_sending
- Règle Product list to Cirrus, id transfert 5f5c2bb937e409.38092970, le 2020-09-12 02:00:28 : No data for the field Myddleware_element_id in the rule product_list_to_cirrus. Failed to check document related : Failed to retrieve a related document. No data for the field Myddleware_element_id. There is not record with the ID source 30 in the rule Products to Cirrus. This document is queued. /home/ibrahimmaalouf/public_html/myddleware/src/Myddleware/RegleBundle/Classes/document.php Line : ( 684 )Status : Relate_KO

Pourriez-vous nous éclairer sur la cause de ces erreurs ? 

Merci !

**Comment by Myddleware** [comment]
Bonjour @MisterIbe ,
D'après les log des points 1 et 3, un produit n'a pas été créé dans Cirrus Shield car un champ obligatoire doit être vide (règle Products to Cirrus). 

Pour corriger le problème, vous pouvez mettre une données manuellement dans la transfert de données en erreur (statut Error sending) directement dans Myddleware puis relancer le transfert de données.
Cependant la bonne pratique est d'annuler ce transfert de données. Puis corriger le problème dans votre application source afin que ce champ obligatoire (Pour Cirrus Shield) soit renseigné. 

Myddleware viendra alors relire la données qui vient d'être modifiée dans votre système source, l'enverra à Cirrus. Puis vous pourrez relancer le 2ème transfert de données en erreur (Relate_KO) qui pourra être débloqué puisque le premier transfert de données aura été débloqué. 

J'espère que c'est clair, n’hésitez pas à revenir vers moi sinon.
