### ISSUE TITLE
Job historic chart shows oldest data only

### ISSUE THREAD

**Issue by fosullivan-usam** [Myddleware/myddleware#350]
The Job historic chart on the homepage continuously shows the oldest job data in the system.  Presumably, it should show the most recent week.

![Historic Jobs Chart](https://user-images.githubusercontent.com/17993233/93105311-e8c7b080-f67c-11ea-86ab-b42e09864294.jpg)

**Comment by Myddleware** [comment]
Hi @fosullivan-usam ,
You are right, we will work on it. Thanks.
