### ISSUE TITLE
Only Name field available for duplicate check 

### ISSUE THREAD

**Issue by Yuvarajsfcloud** [Myddleware/myddleware#351]
Hi Team, 

we are integrating SF with Moodle . As part of one of our requirement , we need a combination of fields to identify a record as duplicate on SF which should be considered for updated rather than create. 

For Any custom object we use on Myddleware, we only get Name as the duplicate identifier which will not work in our case. Is there anywhere to identify duplicates through other fields. If yes, how to setup ?

**Comment by Myddleware** [comment]
Hi @Yuvarajsfcloud ,
You can redefine the duplicate fields into the SalesForce connector (in Myddleware). 
Please create the file <myddleware_root>\src\Myddleware\RegleBundle\Custom\Solutions\salesforce.php (create the directory Custom if it doesn't exist) and add this code
```
namespace Myddleware\RegleBundle\Solutions;

use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class salesforce extends salesforcecore {

	protected $FieldsDuplicate = array(
								'Contact' => array('Email','LastName'),
								'Lead' => array('Email','LastName'),
								'Account' => array('Email', 'Name'),
								'You_module' => array('Field1', 'Field2', 'Field3'),
								'default' => array('Name')
							  );
		
}
```
Then you can add all the entries you want in this array to add duplicate fields for a module. 
I have added this line as en example : You_module' => array('Field1', 'Field2', 'Field3'),

Hope it helps.

**Comment by Yuvarajsfcloud** [comment]
I have tried your suggestion . Please look my code below 
namespace Myddleware\RegleBundle\Solutions;

use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class salesforce extends salesforcecore {

        protected $FieldsDuplicate = array(
                                             'Contact' => array('Email','LastName'),
                                             'Lead' => array('Email','LastName'),
                                             'Account' => array('Email', 'Name'),
                                             'Product__c' => array(' Product_Code__c', 'Moodle_Course_Id__c'),
                                           ‘Subscription__c' => array('RecordTypeId', 'Product_Course_Id__c', 'Contact__c' 'Product1__c'),
                                              'default' => array('Name')
                                                              );
               
}


I'm getting the below error when I try to edit any rule 
![image](https://user-images.githubusercontent.com/44530191/94276871-71402e00-ff66-11ea-9ec7-03ae1d77f33c.png)

**Comment by Yuvarajsfcloud** [comment]
Hi Team ,

Could you please help out on this ?

**Comment by Myddleware** [comment]
Sorry guys, we don't work the weekend ;)
We will answer today (Europe time zone). Hope it will be fine for you.

**Comment by Myddleware** [comment]
I see that a coma is missing between 'Contact__c' and 'Product1__c'
If you have another error like this, you can check your logs in myddleware\var\logs\prod.log
Have a nice day
