### ISSUE TITLE
Required Fields are currently empty 

### ISSUE THREAD

**Issue by Yuvarajsfcloud** [Myddleware/myddleware#352]
As part of our Salesforce-Moodle integration, we are trying to sync the Subscription__c (Custom Object) in SF with Moodle's get_course_completion_by_date Module . 

Subscription object will already have data and we just need to update the completion date on the Salesforce as per Moodle's data. Duplicate check will be done with a combination of courseId & UserId which we will update in the custom solution. 

After we setup the field mapping and navigate to the final screen(Confirmation) , we cannot choose the duplicate field (Name) as it throws an error " _**some of the required fields are currently empty. You can fill out several source fields towards a target field"**_

According to Salesforce, Only course Id & User Id are required to create any record on Subscription Object. But I tried to map all the fields which is represented as "*" , still no luck .  Attaching the screenshots for your reference  .

![image](https://user-images.githubusercontent.com/44530191/93876341-51093880-fcf4-11ea-8d04-77dabb0b73e9.png)

![image](https://user-images.githubusercontent.com/44530191/93876377-654d3580-fcf4-11ea-8775-4cc983db66f5.png)

**Comment by Myddleware** [comment]
Hi @Yuvarajsfcloud ,
You problem here isn't about the required fields in the Field tab. It is because the name field is selected as duplicate field and not set in the "field" tab. 
Could you just click on "name" in the confirmation tab ? Name won't be in red anymore and you will be able to save.
