### ISSUE TITLE
Issue with old Microsoft sql 

### ISSUE THREAD

**Issue by matteo-opencrmitalia** [Myddleware/myddleware#353]
Hi, old Microsoft sql did not support Offset so myddleware does not work

https://stackoverflow.com/questions/19756839/why-cant-i-query-offset-fetch-query-on-my-sql-server
https://stackoverflow.com/questions/2135418/equivalent-of-limit-and-offset-for-sql-server

**Comment by Myddleware** [comment]
Hi @matteo-opencrmitalia ,
I am sorry but I don't know how I can help. Please let me know.
Thanks.

**Comment by matteo-opencrmitalia** [comment]
I connect sql server and it seem ok 
![image](https://user-images.githubusercontent.com/60502629/94114904-4318fc00-fe49-11ea-91e6-a51bcd724041.png)

so i create rule
![image](https://user-images.githubusercontent.com/60502629/94115124-99863a80-fe49-11ea-8334-c80c53dedce2.png)

But when i try to simulate i get this error
![image](https://user-images.githubusercontent.com/60502629/94115196-ab67dd80-fe49-11ea-8368-c017dbc6a11c.png)

This query did not work on this sql server (SQL Server 2005)

SELECT [RagioneSociale], [LocalitaCliente], [CAPCliente], [StatoCliente], [ProvinciaCliente], [IndirizzoCliente], [EmailCliente], [TelefonoCliente_1], [Tipo cliente], [FIDO], [LinguaCliente], [LinguaDestinoMerce], [CodiceCliente], [CodiceFiscale], [CodiceStatoBloccoCliente], [DescrizioneStatoBloccoCliente], [DestinoMerce], [FaxCliente], [FaxDestinoMerce], [EmailDestinoMerce], [TelefonoCliente_2], [PartitaIva], [LocalitaDestinoMerce], [CAPDestinoMerce], [StatoDestinoMerce], [ProvinciaDestinoMerce], [IndirizzoDestinoMerce], [TelefonoDestinoMerce_1], [TelefonoDestinoMerce_2], [TerminiDiPagamento], [ Valuta], [UltimoAggiornamento] FROM [VIEW_EUROTEX_CRM_Clienti] WHERE [UltimoAggiornamento] > '2020-06-01 00:00:00.000' ORDER BY [UltimoAggiornamento] ASC OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY

I dump DB and move to sql server 2017 and here all work well.

**Comment by Myddleware** [comment]
Thank you very much for your feedback @matteo-opencrmitalia
