### ISSUE TITLE
Apply formula crash if filed is empty

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#354]
Hi guys,
Just applied a formula  to transform a data field. It works, but if fields is empty than I got an error. To avoid this as workaround I set a filter in data field that sync only if contain / (why not adding is empty / is not empty in condition possibility?).
But should be better that if formula is applied on empty field just skip and not give an error...
What do you think about?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
In this case, we use the "if" in your formula : ({your field} =="" ? "" : <your formula>)
Does that make sense ?

**Comment by Myddleware** [comment]
We talk about it here if you need more info : https://myddleware.github.io/myddleware/#/advanced_usage?id=formulae

You can also have a look into the "Ternary Operator" chapter here : https://www.php.net/manual/en/language.operators.comparison.php#language.operators.comparison.ternary
