### ISSUE TITLE
Mass Cancel transfers

### ISSUE THREAD

**Issue by Yuvarajsfcloud** [Myddleware/myddleware#356]
Hi Team , 

we have an integration between Salesforce & Moodle.

Could you please help us with the below queries ? 

I have around 3500 transfers failed for a particular rule . Do we have any solution to mass cancel /reload all the transfers ?

Thanks in Advance

**Comment by Myddleware** [comment]
HI @Yuvarajsfcloud ,
Please could you create 3 posts for your 3 topics. Thanks.

**Comment by Yuvarajsfcloud** [comment]
Yes . I'm doing that

**Comment by Myddleware** [comment]
Good, keep only the first topic for this post. Thanks. We will answer very soon.

**Comment by Myddleware** [comment]
Yes, for example, you can cancel massively all data transfer belonging to a rule . Here is a post that should help you : https://github.com/Myddleware/myddleware/issues/341#issuecomment-671882181

Let me know if you need more help.
