### ISSUE TITLE
Transfers gets stuck in "New" & "Ready to Send" status Intermittently

### ISSUE THREAD

**Issue by Yuvarajsfcloud** [Myddleware/myddleware#358]
In some instances, we need the transfers get stuck at "New" & "Ready to Send" Status  . Only when we reload the transfers, those are getting processed.

**Comment by Myddleware** [comment]
This behavior can happen. It could depend on the solution you use and the limit you have set in your rule. 

For some applications, we can't limit the number of record read. So Myddleware reads more data transfer than the limit set in the rule : 
![image](https://user-images.githubusercontent.com/11330301/94837017-fec2c880-0413-11eb-9d40-942938b7e1ab.png)

In this case Myddleware will read all records from the source application and will create all data transfers with the status "New". Then, Myddleware will process only the next "limit" records. So some of them will stay in an open status (like  "New" & "Ready to Send") and will be processed next time.

You can increase the rule limit if you want to avoid this situation.

Hope it helps.
