### ISSUE TITLE
Moodle with ERPNext integration failing.

### ISSUE THREAD

**Issue by himanshunandan** [Myddleware/myddleware#361]
Hi Admin,

Can I integrate Moodle with ERPnext using Myddleware. I need School (Education) module with fees management.
Kindly suggest.

Regards
Himanshu

**Comment by Myddleware** [comment]
Yes @himanshunandan ,
It is possible to connect Moodle with ERPnext using Myddleware. Here are the list of module Myddleware can read from Moodle : http://www.myddleware.com/solution/connected-applications?view=project&id=14:moodle

We can add more module if you need it.

**Comment by himanshunandan** [comment]
Hi Admin,
I tried creating the integration between Moodle and ERPNext.
I am facing below error while testing .

 "There is no data in the source server or fields in the target solution"
also
Reading Issue: Error : Error accessexception : Access control exception /var/www/html/myddleware/src/Myddleware/RegleBundle/Solutions/moodle.php Line : ( 232 )
![Untitled3](https://user-images.githubusercontent.com/64355057/95650586-21cf3580-0b02-11eb-98c5-4db4bc0cb7f8.png)
![Untitled2](https://user-images.githubusercontent.com/64355057/95650589-2398f900-0b02-11eb-953d-dc8114a2b391.png)
![Untitled1](https://user-images.githubusercontent.com/64355057/95650590-24318f80-0b02-11eb-9bd1-d6fc8a16e21d.png)




I have attached all the screenshots. Kindly help me here.

**Comment by himanshunandan** [comment]
I have not mapped all the fields in form. hope its ok. Also I have imported myddlware user ti my moodle site and gave all the permissions.

**Comment by himanshunandan** [comment]
Kindly suggest here. I am completely stuck.

**Comment by himanshunandan** [comment]
This is solved

**Comment by Myddleware** [comment]
Hi @himanshunandan,
Thanks for telling us this is solved but could you explain in just a few words what the problem was ? 
Thanks in advance.
