### ISSUE TITLE
Incorrect Date Time Value from Moodle to SF

### ISSUE THREAD

**Issue by Yuvarajsfcloud** [Myddleware/myddleware#362]
Hi Team, 

I'm trying to sync Course Completion data from Moodle to Myddleware. I get an incorrect date from the Myddleware to Salesforce. 

Date Time value from Moolde - 1601794506

1601794506
Is equivalent to:
10/04/2020 @ 6:55am (UTC)

Instead of the above date, I'm getting 1970-01-19T12:56:34.000+0000 in the salesforce.

**Comment by Myddleware** [comment]
Hi @Yuvarajsfcloud ,
Yes you have to change the date format. You can use a formula in Myddleware like this : 
`changeFormatDate( {timecompleted}, "U", "Y-m-dTH:i:s")`
![image](https://user-images.githubusercontent.com/11330301/95110547-78bdbf00-073e-11eb-9366-58f7dc3199a9.png)

You should have something like this : 
![image](https://user-images.githubusercontent.com/11330301/95110599-8e32e900-073e-11eb-87ef-d8a0c981ff6d.png)

If the format is still not good, could you please change the one I gave you (Y-m-dTH:i:s) using this documentation https://www.php.net/manual/fr/datetime.format.php

Please let us know if you had to change the format. It would save time to people with the same problem.
Thanks.

**Comment by Yuvarajsfcloud** [comment]
The above time format which you mentioned is not supported in Salesforce. I tried with other formats as well , it didn't work. 
Error : Call failed - 400 [{"message":"Cannot deserialize instance of datetime from VALUE_STRING value 2020-10-04GMT+00000306:55:06 or request may be missing a required field at [line:1, column:70]","errorCode":"JSON_PARSER_ERROR"}]

**Comment by Myddleware** [comment]
Hi @Yuvarajsfcloud ,
The right format is this one : 
`changeFormatDate( {timecompleted},"Y-m-d H:i:s","Y-m-d\TH:i:s.000\Z")`
Please let me know if it works ony your side.

**Comment by Yuvarajsfcloud** [comment]
It doesn't work. formula evaluates to Null value. 

![image](https://user-images.githubusercontent.com/44530191/95216387-9f97f600-080f-11eb-891e-4df3510681a2.png)

**Comment by Myddleware** [comment]
OK the date format of your source isn't the same than me (I have tested it with Prestashop on my side). So for Moodle, it should be this one : 
`changeFormatDate( {timecompleted},"U","Y-m-d\TH:i:s.000\Z")`
