### ISSUE TITLE
Update fails from salesforce to moodle

### ISSUE THREAD

**Issue by Yuvarajsfcloud** [Myddleware/myddleware#363]
Hi Team ,

when records are created newly in salesforce, it syncs successfully to Moodle. But not the updates though same data is used with the update. 
![image](https://user-images.githubusercontent.com/44530191/95173016-c20d1d80-07d5-11eb-8a22-b8ec7569c45f.png)
 
I'm trying to process all the historical records from salesforce to moodle by setting the Reference Date to the past. But it fails. 

![image](https://user-images.githubusercontent.com/44530191/95173147-ee289e80-07d5-11eb-9bfe-21884eb2f6c1.png)

**Comment by Myddleware** [comment]
Hi @Yuvarajsfcloud ,
 Could you try to remove the mapping of auth field  and try again ? Thanks.

**Comment by Yuvarajsfcloud** [comment]
I tried by removing the auth mapping, but still it ends up with error. 

![image](https://user-images.githubusercontent.com/44530191/95341803-4e9e0580-08d4-11eb-83ac-1b2195afdaf5.png)

**Comment by Myddleware** [comment]
I will try to reproduce your issue. I 'll come back to you very soon, probably tomorrow.

**Comment by Myddleware** [comment]
Hi,
I can't reproduce your problem. Could you try to login into Moodle with the user linked to your token (used in Myddleware). Then could you try to modify the user ypattest directly in Moodle. You will see if you have a missing permission. 
Please keep me updated.

**Comment by Yuvarajsfcloud** [comment]
I was able to successfully do that on the Moodle UI. No idea why it is failing on the Myddleware 

Should there be any problem with token used in Myddleware side which doesn't have necessary permission. I validated everything from side and all looks good. 

I would really appreciate if you could get back to me ASAP. 

Thanks in Advance

**Comment by Myddleware** [comment]
We always answer as soon as possible on the forum. However I hope you understand that the support for our client comes first.

You can try to add the "system" role to the Moodle user linked to the token. You will see if it is a permission problem.

**Comment by Yuvarajsfcloud** [comment]
There is no such role called “system” role in our application.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Myddleware** [comment]
This screenshot should help you : 
![image](https://user-images.githubusercontent.com/11330301/95952524-93f09480-0df8-11eb-87c1-6fc514581149.png)

**Comment by Yuvarajsfcloud** [comment]
@Myddleware - We are still hanging with the issue on the update. 

![image](https://user-images.githubusercontent.com/44530191/111509058-58c10b80-8772-11eb-8eed-b3c9a936b26c.png)

Based on the given screenshot, we could identify that createpassword field should not be set when we try to update the user in moodle. 

How do we implement conditional field assignment in the rule ?

**Comment by Myddleware** [comment]
Hi @Yuvarajsfcloud 

Thats's a great idea to be able to create a formula with a type of the document (Update/créate/delete/search) as a variable in the formula. Another thing, we will create a formula function which remve the field. By this way, we coudl create a formula like : if we send an update to Moodle then remove field password. 

But we won't be able to develop ot in the few next weeks as we are busy with Myddleware 3.0.

For now, you can use this solution by creating 2 rules, one to create the record and another one to update : https://github.com/Myddleware/myddleware/issues/467

Hope it will help you.

**Comment by Yuvarajsfcloud** [comment]
we do some existing records in our target system which are not created through the Myddleware. when we create any record in source system which already exist in target , myddleware will try to update by using the email & username. 

If we go with your workaround by creating two rules , one for create & another for update. when the above scenario occurs, the second rule will not find the ID in the first rule as it was not created through that rule itself.

**Comment by Myddleware** [comment]
Hi @Yuvarajsfcloud ,
Yes you are right. In this case I don't see another way than to develop a custom code.

Here is a code that could help (I didn't test it but it should work). It is an upgrade safe code because we redefine Moodle connector properly : 
Create the file myddleware\src\Myddleware\RegleBundle\Custom\Solutions\moodle.php
Then copy this code and replace "your rule id" :
```
namespace Myddleware\RegleBundle\Solutions;

use Symfony\Bridge\Monolog\Logger;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

// Moodle class enhancement
class moodle extends moodlecore {
	
	// Check data before update 
	// Add a throw exeption if error
	protected function checkDataBeforeUpdate($param,$data) {
		// Call standard function
		$data = parent::checkDataBeforeUpdate($param,$data);
		// Remove password field when user is updated
		if (
				$param['rule']['id'] == '<your rule id>'
			AND isset($data['password'])
		) {
			unset($data['password']);
		}	
		return $data;
	}
}
```
Hope it will help you.

**Comment by Yuvarajsfcloud** [comment]
We are facing issue with the above code. please help us out. looks like it is unable to load the class.

[2021-03-22 11:18:15] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "moodle" from namespace "Myddleware\RegleBundle\Solutions". Did you forget a "use" statement for another namespace?" at D:\Inetpub\Web\PDC\pdcwebp002vw.state.in.us\myddleware\var\cache\prod\ContainerXxvgfff\getMyddlewareRule_MoodleService.php line 8 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"moodle\" from namespace \"Myddleware\\RegleBundle\\Solutions\".\nDid you forget a \"use\" statement for another namespace? at D:\\Inetpub\\Web\\PDC\\pdcwebp002vw.state.in.us\\myddleware\\var\\cache\\prod\\ContainerXxvgfff\\getMyddlewareRule_MoodleService.php:8)"}

**Comment by Myddleware** [comment]
Hi @Yuvarajsfcloud ,
Could you try to clear your cache. You can remove the directory D:\Inetpub\Web\PDC\pdcwebp002vw.state.in.us\myddleware\var\cache\prod
Please let me know if it helps.

**Comment by Yuvarajsfcloud** [comment]
It doesn't work. Could you please check & provide us the correct resolution?

**Comment by Myddleware** [comment]
Hi @Yuvarajsfcloud ,
Did you put `<?php` at the very beginning of your file ? 
Have a nice day,

**Comment by Yuvarajsfcloud** [comment]
Thanks for the response. it did resolve the syntax issue. after we update the code & try to do an update. It worked partially. Please help us with the below issues. 

Find below the code we used. 

namespace Myddleware\RegleBundle\Solutions;

use Symfony\Bridge\Monolog\Logger;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

// Moodle class enhancement
class moodle extends moodlecore {
	
	// Check data before update 
	// Add a throw exeption if error
	protected function checkDataBeforeUpdate($param,$data) {
		// Call standard function
		$data = parent::checkDataBeforeUpdate($param,$data);
		// Remove password field when user is updated
		if (
				$param['rule']['id'] == '<your rule id>'
			AND isset($data['createpassword'])
		) {
			unset($data['createpassword']);
		}	
		return $data;
	}
}
**Rule setup for your reference.** 
![image](https://user-images.githubusercontent.com/44530191/113018073-c5d69700-919d-11eb-88bd-e57cd02335e8.png)


Issue 1 # : I believe the above code should impact only the update scenario for Moodle User. but we are getting errors during create .  I see createpassword is removed from the array for create. no idea what has gone wrong. 
![image](https://user-images.githubusercontent.com/44530191/113017691-59f42e80-919d-11eb-9b7b-734d7ec8431f.png)

Issue 2# : Failed for one of the update
dmlwriteexception : Error writing to database (Duplicate entry 1-cwieneke for key mdl_user_mneuse_uix UPDATE mdl_user SET username = ?,auth = ?,firstname = ?,lastname = ?,email = ?,timemodified = ? WHERE id=? [array ( 0 => cwieneke, 1 => manual, 2 => Cara, 3 => Wieneke, 4 => cara@wienekelaw.com, 5 => 1617118339, 6 => 400, )]) Debug : Duplicate entry 1-cwieneke for key mdl_user_mneuse_uix UPDATE mdl_user SET username = ?,auth = ?,firstname = ?,lastname = ?,email = ?,timemodified = ? WHERE id=? [array ( 0 => cwieneke, 1 => manual, 2 => Cara, 3 => Wieneke, 4 => cara@wienekelaw.com, 5 => 1617118339, 6 => 400, )]Failed to send document. Status : Error_sending
--

**Comment by Myddleware** [comment]
Hi @Yuvarajsfcloud ,
Could you create another issue in this forum for the issue 2# please as it is another topic ? Thanks.

About issue#1, this is really weird that the field "createpassword" is missing in your data transfer. Because the code we gave you remove createpassword on the fly just before Myddleware send data to Moodle. This code doesn't remove any data into Myddleware. Are you sure that the screenshot of the data transfer correspond to the screenshot of the rule ?

Thanks.

**Comment by Yuvarajsfcloud** [comment]
Yes . I have double checked it. Please help us out what could have went wrong.

**Comment by Yuvarajsfcloud** [comment]
Additional screenshots for your reference. 

![image](https://user-images.githubusercontent.com/44530191/113161949-7a36f280-925c-11eb-9403-0a8c48163285.png)

Observed something weird . 

Though the transfer is failed, users are getting created at the moodle end. I believe something going wrong in the myddleware. 

Overall functional status

- Update is working without any issues. 
- Create is also working as expected , except the status of the transfer shows as error. 
       -  this will create issues in subsequent transfers as Id of the created user will not be available in myddleware. 
       - Related transfers for this transfer will also fail. 

Please help us find the root cause .

**Comment by Myddleware** [comment]
Hi @Yuvarajsfcloud ,
Yes you 're right, you need the message returned by Moodle to get the Moodle Id of the record created.

Error unknown is an error we add into Myddleware when we get no result from Moodle which isn't normal. It means that something goes wrong into Moodle when you create a user, maybe a fatal error that happened between the user creation in Moodle and the message that should be sent back to Myddleware.

Could you try to create again a user and check  your Moodle logs ? Something should be written into it.  If there is nothing into Moodle log, could you check your webserver (apache or nginx probably) logs as well ? 

Thanks.

**Comment by Yuvarajsfcloud** [comment]
![image](https://user-images.githubusercontent.com/44530191/113265853-3b537c00-92f2-11eb-94b1-83ed30529489.png)
I don't see any errors in the Moodle logs.

**Comment by Myddleware** [comment]
Hi @Yuvarajsfcloud ,
You should have a log somewhere. If the execution was stopped because of fatal error, the log should be on your webserver or your MySQL database. 
Could you check ?
Thanks.

**Comment by Yuvarajsfcloud** [comment]
Before implementing the above custom code, we didn't get any error during user creation. we are unable to find the error logs for it. Please help us .

**Comment by Myddleware** [comment]
Hi @Yuvarajsfcloud ,
Could you comment the code and check you don't have the error ? 
However, if the process is stopped in Moodle it means that an error happens so you should definitely have a error on your web server log. Do you have Apache or Nginx on the server which host Moodle ?

**Comment by Yuvarajsfcloud** [comment]
we just get "Error_Sending" on the logs

**Comment by Myddleware** [comment]
HI @Yuvarajsfcloud ,
This is a log coming from Myddleware I guess. You need to check the web server log (apache or nginx or other) from the server where Moodle is intalled.
Have a nice day.

**Comment by stlgaits** [comment]
Hi, I am archiving this issue but please do not hesitate to re-open it if needs be.
