### ISSUE TITLE
Myddleware login disabled

### ISSUE THREAD

**Issue by himanshunandan** [Myddleware/myddleware#365]
Hi Admin,

I have installed Myddleware on ubuntu 18.04 using Nginx and php 7.4. After installation the "sign in" button is disabled.

I can see below nginx status. I have also attached browser screenshot. kindly help here.

root@localhost:/etc/nginx/sites-available# sudo systemctl status nginx
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-10-09 11:18:53 UTC; 1h 5min ago
     Docs: man:nginx(8)
  Process: 3267 ExecStop=/sbin/start-stop-daemon --quiet --stop --retry QUIT/5 --pidfile /run/nginx.pid (code=exited, status=2)
  Process: 3280 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
  Process: 3268 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
 Main PID: 3281 (nginx)
    Tasks: 4 (limit: 4659)
   CGroup: /system.slice/nginx.service
           ├─3281 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
           ├─3282 nginx: worker process
           ├─3283 nginx: worker process
           └─3284 nginx: cache manager process
![Untitled](https://user-images.githubusercontent.com/64355057/95582835-d3b22780-0a58-11eb-8826-625d974ffc7f.png)

Oct 09 11:18:53 localhost systemd[1]: Starting A high performance web server and a reverse proxy server...
Oct 09 11:18:53 localhost systemd[1]: Started A high performance web server and a reverse proxy server.
root@localhost:/etc/nginx/sites-available#

Also below is by log file 

root@localhost:/etc/nginx/sites-available# tail -20 /var/log/nginx/project_error.log
2020/10/09 11:06:15 [error] 2480#2480: *19 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: Unable to create the cache directory (/var/www/html/myddleware/var/cache/prod)
 in /var/www/html/myddleware/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:765
Stack trace:
#0 /var/www/html/myddleware/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(642): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/html/myddleware/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/html/myddleware/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(195): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/html/myddleware/web/app.php(17): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/html/myddleware/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 765" while reading response header from upstream, client: 103.147.1.182, server: myddleware.ekaway.com, request: "GET /web/app.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "myddleware.ekaway.com"
2020/10/09 11:06:18 [error] 2480#2480: *22 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: Unable to create the cache directory (/var/www/html/myddleware/var/cache/prod)
 in /var/www/html/myddleware/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:765
Stack trace:
#0 /var/www/html/myddleware/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(642): Symfony\Component\HttpKernel\Kernel->buildContainer()
#1 /var/www/html/myddleware/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#2 /var/www/html/myddleware/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(195): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/html/myddleware/web/app.php(17): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#4 {main}
  thrown in /var/www/html/myddleware/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 765" while reading response header from upstream, client: 103.147.1.182, server: myddleware.ekaway.com, request: "GET /web/app.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "myddleware.ekaway.com"
2020/10/09 11:06:40 [error] 2480#2480: *25 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: BASE in /var/www/html/myddleware/web/installMyddleware.php on line 27" while reading response header from upstream, client: 103.147.1.182, server: myddleware.ekaway.com, request: "GET /web/installMyddleware.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "myddleware.ekaway.com"
2020/10/09 11:06:40 [error] 2480#2480: *25 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: myddlewareParameters in /var/www/html/myddleware/web/installMyddleware.php on line 440" while reading upstream, client: 103.147.1.182, server: myddleware.ekaway.com, request: "GET /web/installMyddleware.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "myddleware.ekaway.com"
root@localhost:/etc/nginx/sites-available#

Kindly help here.

Regards
Himanshu

**Comment by himanshunandan** [comment]
To clarify again "Sign In" button is disabled and i cant click on it.

**Comment by Myddleware** [comment]
Hi @himanshunandan ,
It seems that you have no writting permission on the cache and log directories in var directory. Could you change the permission and try again.
Please keep me posted.

**Comment by himanshunandan** [comment]
Hi,
I removed the previous installation and now trying via command line. I am facing below issue while running create database command:

php bin/console doctrine:schema:update -f -e prod


root@localhost:/var/www/html/myddleware#  php bin/console doctrine:schema:update -f -e prod
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql.so' (tried: /usr/lib/php/20190902/pdo_mysql.so (/usr/lib/php/20190902/pdo_mysql.so: undefined symbol: mysqlnd_allocator), /usr/lib/php/20190902/pdo_mysql.so.so (/usr/lib/php/20190902/pdo_mysql.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

In AbstractMySQLDriver.php line 106:

  An exception occurred in driver: could not find driver


In PDOConnection.php line 31:

  could not find driver


In PDOConnection.php line 27:

  could not find driver


doctrine:schema:update [--complete] [--dump-sql] [-f|--force] [--em [EM]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-
debug] [--] <command>
