### ISSUE TITLE
Can't find data in ERPnext

### ISSUE THREAD

**Issue by himanshunandan** [Myddleware/myddleware#366]
Dear Admin,

I have successfully created connection between Moodle and ERPNext.
Now when I am tying to transfer the data (users) from Moodle to ERPNext no data transfer is happening. I cant see it in ERPNext. 
I have around 10 users in Moodle. But 0 records gets populated. 
Kindly help here. I have attached the screenshot.
![Untitled 4png](https://user-images.githubusercontent.com/64355057/95684502-cb501d00-0c0f-11eb-93f8-610f12ea49a7.png)

**Comment by Myddleware** [comment]
Hi @himanshunandan ,
Could you try what I have suggested here : https://github.com/Myddleware/myddleware/issues/329#issuecomment-665925600
Thanks.

**Comment by himanshunandan** [comment]
Dear Admin,

I tried and now I can see attached error. Kindly suggest.
![Untitled1](https://user-images.githubusercontent.com/64355057/95762700-b3d66a00-0ccb-11eb-94d0-a863bd2289aa.png)

**Comment by Myddleware** [comment]
Hi @himanshunandan 
COuld you open this data transfer and show us what is in the log and the content of the data transfer ? Thanks.

**Comment by himanshunandan** [comment]
Dear Admin,
I have attached the screenshot.
![Untitled3](https://user-images.githubusercontent.com/64355057/95767958-36aef300-0cd3-11eb-9c83-0be20c125394.png)
![Untitled2](https://user-images.githubusercontent.com/64355057/95767967-3878b680-0cd3-11eb-9995-3b7c36c788c6.png)

Regards
Himanshu

**Comment by Myddleware** [comment]
Please, open your data transfer, the one in you first screenshot (error_sending) and send us secreenshots with the content of this data transfert.
Thanks.

**Comment by himanshunandan** [comment]
Dear Admin,

I have attached all the screenshots.
![Untitled7](https://user-images.githubusercontent.com/64355057/95769336-5b0bcf00-0cd5-11eb-8301-188d8de3a208.png)
![Untitled6](https://user-images.githubusercontent.com/64355057/95769342-5cd59280-0cd5-11eb-91d5-bc6f784090a9.png)
![Untitled5](https://user-images.githubusercontent.com/64355057/95769347-5d6e2900-0cd5-11eb-8693-538cc09ba82c.jpg)

Regards
Himanshu

**Comment by Myddleware** [comment]
In your first sscreenshot, the end of the log is missing, could you copy the whole log in a post please ? Thanks.

**Comment by himanshunandan** [comment]
Dear Admin,

I have added the log in word file.

Regards
Himanshu
[error.docx](https://github.com/Myddleware/myddleware/files/5366362/error.docx)

**Comment by Myddleware** [comment]
I can see in your log taht you have a problem with email. Could you remove all email from the mapping and see if Myddleware can send the data to ERPNext.
Thanks.

**Comment by himanshunandan** [comment]
Dear Admin,
[error2.docx](https://github.com/Myddleware/myddleware/files/5371792/error2.docx)

I removed and tried. Now I can see attached error.

Regards
Himanshu

**Comment by himanshunandan** [comment]
Sir,

I got resolved. Thanks.

Himanshu

**Comment by Myddleware** [comment]
Thanks for your feedback.
