### ISSUE TITLE
Not able to delete a rule

### ISSUE THREAD

**Issue by himanshunandan** [Myddleware/myddleware#369]
Dear Admin,

i am trying to delete a rule and Myddleware is not allowing me. All transfers are cancelled or send. I have attached the screenshots.
Kindly help here.

Regards
Himanshu
[delete error.docx](https://github.com/Myddleware/myddleware/files/5376185/delete.error.docx)

**Comment by Myddleware** [comment]
If you want to delete a rule, you have to delete all data transfer in this rule first.
To remove all data transfer belonging to a rule, you can run this command in your command prompt :
php bin/console myddleware:massaction remove rule <your rule id> Y --env=background

Here you can find more info about this function (the doc show how to launch this function with CURL but you can run it via the console) : https://myddleware.github.io/myddleware/#/api?id=apimass_action

**Comment by himanshunandan** [comment]
I tried but below error I received in console
root@localhost:/var/www/html/myddleware# php bin/console myddleware:massaction remove rule Y --env=background
5f86b67746be51.71222374
No document found corresponding to the input parameters. No action done in the job massAction.
root@localhost:/var/www/html/myddleware#

**Comment by Myddleware** [comment]
Sorry, I forgot the rule_id. Please add you rule id in the command :
`php bin/console myddleware:massaction remove rule <your rule id> Y --env=background`

**Comment by himanshunandan** [comment]
thanks much for your help. It's perfect.

Regards
Himanshu

**Comment by Myddleware** [comment]
Thanks for you feedback.
