### ISSUE TITLE
erreur entitymanager 

### ISSUE THREAD

**Issue by ogrdiota** [Myddleware/myddleware#372]
Failed to create documents : The EntityManager is closed. /var/www/myddleware/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php Line : ( 144 )

**Comment by Myddleware** [comment]
Hi @ogrdiota ,
Could you show me which command or which button you use to get this error ? 
Thanks.

**Comment by CamillePMyddleware** [comment]
Hi, I archive this issue, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be. 
Thanks
