### ISSUE TITLE
Upgrade to Release 2.5.5b

### ISSUE THREAD

**Issue by z3n4j** [Myddleware/myddleware#374]
Hi. I upgrade myddleware but i get this error:

Error : The process "php composer.phar install --no-plugins" exceeded the timeout of 60 seconds. /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Process/Process.php Line : ( 1330 )

**Comment by Myddleware** [comment]
Hi @z3n4j ,
Depending on the upgrade, the composer install command can take few minutes. 
You have to change the variable max_execution_time in your php.ini file.
Have a nice day

**Comment by z3n4j** [comment]
Hi. I changed the variable max_execution_time.

I run the command:
php bin/console myddleware:upgrade --env=background

But i get this error:

PHP Fatal error:  Uncaught Error: Class 'Doctrine\Common\Annotations\AnnotationRegistry' not found in /var/www/html/app/autoload.php:8
Stack trace:
#0 /var/www/html/bin/console(13): require()
#1 {main}
  thrown in /var/www/html/app/autoload.php on line 8

**Comment by Myddleware** [comment]
What's your php version ? (you can run php -v)

Could you also follow the tutorial to upgrade Myddleware manually : https://myddleware.github.io/myddleware/#/admin_tasks?id=upgrading-myddleware
Please start with the command `git pull`

**Comment by z3n4j** [comment]
PHP 7.2.28 (cli) (built: Feb 18 2020 11:07:04) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.28, Copyright (c) 1999-2018, by Zend Technologies

**Comment by z3n4j** [comment]
Hi. I upgraded manually and it work. Thank you.

**Comment by Myddleware** [comment]
Good news, thanks for your feedback.
