### ISSUE TITLE
Connector SqlServer: 500 Internal Server Error

### ISSUE THREAD

**Issue by yuridebuggers** [Myddleware/myddleware#375]
Hi,

I'm trying to add the Sql Server connector but after entering the parameters and doing the test, i received this error:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please check your log file here : \myddleware\var\logs\prod.log 

Prod.log:

request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getId() on string" at C:\@Condivisa\ApacheWeb\default\src\Myddleware\RegleBundle\Controller\ConnectorController.php line 330 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getId() on string at C:\\@Condivisa\\ApacheWeb\\default\\src\\Myddleware\\RegleBundle\\Controller\\ConnectorController.php:330)"} []
![capture](https://user-images.githubusercontent.com/63705572/97593046-96124000-1a01-11eb-9c7a-db2e85cd7cfe.PNG)

thanks

**Comment by Myddleware** [comment]
Hi @yuridebuggers ,
Could you tell me what is your php version ? 
Thanks.

**Comment by yuridebuggers** [comment]
Of course, my php version is 7.4

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by Myddleware** [comment]
Sorry but Myddleware is only compatible php 7.2 and 7.3.

I agree that we have a bug on the php check version, it is done on php version > 7.2. That's a mistake. 

The next main version will be compatible with php 7.4, we will also upgrade Symfony to version 4.4. 

However, for now, could you try to use Myddleware with a php version 7.2 or 7.3. Thanks.

**Comment by yuridebuggers** [comment]
I downgrade PHP to 7.2 but i have the same error.

![capture](https://user-images.githubusercontent.com/63705572/97671611-dec10c00-1a88-11eb-9a3b-e3617b925806.PNG)

[2020-10-30 07:16:36] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getId() on string" at C:\@Condivisa\ApacheWeb\default\src\Myddleware\RegleBundle\Controller\ConnectorController.php line 330 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getId() on string at C:\\@Condivisa\\ApacheWeb\\default\\src\\Myddleware\\RegleBundle\\Controller\\ConnectorController.php:330)"} []

**Comment by yuridebuggers** [comment]
OK, now it works correctly .

**Comment by Myddleware** [comment]
Thanks for your feedback.
Have a nice day.
