### ISSUE TITLE
Failed to get the task id

### ISSUE THREAD

**Issue by yuridebuggers** [Myddleware/myddleware#377]
i try my first test, it's to run a sync between a MSSQL View and an MSSQL table (tow distinct database)

The connections are working fine, successfully created the rules but getting this message when I try to run it:

"Failed to get the task id".

**Comment by Myddleware** [comment]
OK this is maybe a cache problem with Myddleware UI.
Could you try to run your rule with a command prompt by running this command : 
`php bin/console myddleware:synchro <your rule id> --env=background`
Does it work properly ?

**Comment by yuridebuggers** [comment]
if i try to run my rule with a command prompt, it work correctly. but if i use the web console my rules not worked. why ?

**Comment by stlgaits** [comment]
Hi,

This could potentially be an issue with permissions on your cache folder : 

> <path_to_myddleware>\myddleware\var\cache\prod

Could you please check that Myddleware is allowed to write in this directory ? 

When you run a rule using the web app, Myddleware will try to create a temporary .txt file here : 

> <path_to_myddleware>myddleware\var\cache\prod\myddleware\job

Does your folder contain any of those .txt files ? And if so, do the .txt include a task ID ? 

Let me know if that works.

**Comment by CamillePMyddleware** [comment]
Hi, I archive this issue, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be. 
Thanks
