### ISSUE TITLE
How to manage transcoding table

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#378]
Hi suppose this situation.
I'm in CRM and i need to write in a sql table 2 entity: contact and organization.
The way I found is:
1 - I write sql table with organization -> OK
2 - I write sql table with contact, and i map account_id field of CRM to correspondant field of organization -> OK
This works.
But suppose that in contact sql table I want to write not the CRM ID of organization (account_id), but the name of organization or code of organization or any other field of organization.
There is a way to do that with myddleware?
I hope my question is clear :)

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
I guess your are sending account (form Vtiger for example) to the account table in the first rule.
The you send your contacts to your contact table in the second rule.
I see 2 solutions : 
 - Create a custom code in Myddleware to add account data in your first rule (contact) with a specific webservice call. 
 - Or create a SQL trigger to fill these fields each time the contact is modified in MySQL.

Hope it helps.

**Comment by simonetravaglini** [comment]
Hi it fit with our idea, so we will update vtiger plugin to manage also parent record fields.
Thanks for answer!
