### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by pohodak235** [Myddleware/myddleware#379]
I have problem with installation Myddleware. After clicking on Submit in the first step, an error will be displayed:

**[ERROR]
Failed: The command "php /data/2/f/2fb0803f-65c8-4783-926d-9645e5534cad/automatickekavovary.sk/web/app/../bin//console cache:clear --env=prod" failed. Exit Code: 127(Command not found) Working directory: /data/2/f/2fb0803f-65c8-4783-926d-9645e5534cad/automatickekavovary.sk/web/web Output: ================ Error Output: ================ sh: 1: php: not found**

What now? Thank you.

**Comment by Myddleware** [comment]
Hi  @pohodak235 ,
I guess you have a specific command to run php on your server. It could be php72 or something else. 
If you want to change it, you can modify the file <myddleware>\app\config\public\parameters_public.yml
![image](https://user-images.githubusercontent.com/11330301/98412559-71107380-2078-11eb-831d-a639007afeee.png)

Then clear the cache and the installation should work.
Please keep us posted.

**Comment by RosleStores** [comment]
Hello, I got the same problem with while installing the program.
This is the error I get: 
[ERROR]
Failed: The command "php /var/www/vhosts/boboutik.com/sync.boboutik.com/app/../bin//console cache:clear --env=prod" failed. Exit Code: 127(Command not found) Working directory: /var/www/vhosts/boboutik.com/sync.boboutik.com/web Output: ================ Error Output: ================ sh: php: command not found

**Comment by Myddleware** [comment]
Hi @RosleStores ,
Could you just try the command : php -v
It will tell you if php command is installed on your serveur and if yes, it will give you your php version
Please, keep us posted.

**Comment by CamillePMyddleware** [comment]
Hi, I archive this issue, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be. 
Thanks
