### ISSUE TITLE
Add a input in simutaion view to read a specific record

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#380]
The goal of this topic is to allow users to select a specific record for their rule simulation. 

We have to add an input field here : 
![image](https://user-images.githubusercontent.com/11330301/98846074-e1d7d700-244e-11eb-90fa-e453675a315c.png)

The call to the function read_last in the file \src\Myddleware\RegleBundle\Controller\DefaultController.php line 1167 has to be enhanced with the entry query : 
![image](https://user-images.githubusercontent.com/11330301/98846778-bc979880-244f-11eb-9dc4-701f9743d811.png)

**Comment by AlexMyddleware** [comment]
this feature is present in current version of myddleware
