### ISSUE TITLE
Problem with the installation 

### ISSUE THREAD

**Issue by RosleStores** [Myddleware/myddleware#383]
Hello, I'm unable to install mydlleware. I got the same error, I try to change the executable from PHP to php7 but nothing happens. Please help. I use Plesk. 
This is the error message: 
[ERROR]
Failed: The command "php /var/www/vhosts/boboutik.com/sync.boboutik.com/app/../bin//console cache:clear --env=prod" failed. Exit Code: 127(Command not found) Working directory: /var/www/vhosts/boboutik.com/sync.boboutik.com/web Output: ================ Error Output: ================ sh: php: command not found

**Comment by Myddleware** [comment]
Hi @RosleStores ,
Could you just try the command : php -v
It will tell you if php command is installed on your serveur and if yes, it will give you your php version
Please, keep us posted.

**Comment by RosleStores** [comment]
The PHP version is PHP7.4.12
I change the yml file at this link: boboutik.com / .../ app / config / public / parameters_public.yml
This is the parameter : 
# This file is auto-generated during the composer install
parameters:
    php:
        executable: php7412
    locale: en
    pager: 20
    migration:
        mode: 0
    notification:
        alert_time_limit: 60
    transfer:
        search_limit: 1000
    git_branch: master
    base_uri: null
    email_from: no-reply@myddleware.com
Please help.

**Comment by stlgaits** [comment]
Hi,


could you try removing the numbers after php, like in the following example  :



# This file is auto-generated during the composer install
parameters:
    php:
        executable: php


Please let me know if this works or not.



________________________________
De : Guy Roland Kalou Djollo <notifications@github.com>
Envoyé : mardi 24 novembre 2020 18:39:03
À : Myddleware/myddleware
Cc : Subscribed
Objet : Re: [Myddleware/myddleware] Problem with the installation (#383)


The PHP version is PHP7.4.12
I change the yml file at this link: boboutik.com / .../ app / config / public / parameters_public.yml
This is the parameter :

This file is auto-generated during the composer install

parameters:
php:
executable: php7412
locale: en
pager: 20
migration:
mode: 0
notification:
alert_time_limit: 60
transfer:
search_limit: 1000
git_branch: master
base_uri: null
email_from: no-reply@myddleware.com<mailto:no-reply@myddleware.com>
Please help.

**Comment by stlgaits** [comment]
Oh sorry I just realised it was like that originally, let me look into it further and I will get back to you.



________________________________
De : Estelle Gaits
Envoyé : mercredi 25 novembre 2020 09:33:31
À : Myddleware/myddleware; Myddleware/myddleware
Cc : Subscribed
Objet : RE: [Myddleware/myddleware] Problem with the installation (#383)


Hi,


could you try removing the numbers after php, like in the following example  :



# This file is auto-generated during the composer install
parameters:
    php:
        executable: php


Please let me know if this works or not.



________________________________
De : Guy Roland Kalou Djollo <notifications@github.com>
Envoyé : mardi 24 novembre 2020 18:39:03
À : Myddleware/myddleware
Cc : Subscribed
Objet : Re: [Myddleware/myddleware] Problem with the installation (#383)


The PHP version is PHP7.4.12
I change the yml file at this link: boboutik.com / .../ app / config / public / parameters_public.yml
This is the parameter :

This file is auto-generated during the composer install

parameters:
php:
executable: php7412
locale: en
pager: 20
migration:
mode: 0
notification:
alert_time_limit: 60
transfer:
search_limit: 1000
git_branch: master
base_uri: null
email_from: no-reply@myddleware.com<mailto:no-reply@myddleware.com>
Please help.

**Comment by CamillePMyddleware** [comment]
Hi, I archive this issue, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be. 
Thanks
