### ISSUE TITLE
different beahvior if scheduled

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#386]
Hi we have created a rules with this:
![Clipboard - 4 dicembre 2020 16_03](https://user-images.githubusercontent.com/6990139/101181460-3127b680-364d-11eb-8289-05df77db7751.png)

if we run manually we dont' get error
when rule is run from scheduler we get this error:
![Clipboard - 4 dicembre 2020 16_03-2](https://user-images.githubusercontent.com/6990139/101181369-17866f00-364d-11eb-80f4-1ae4be8452f4.png)
Ideas?

**Comment by Myddleware** [comment]
Hi Simone,
Could you change {RagioneSocialeEstensione}=== NULL by {RagioneSocialeEstensione}== ""
Please, let me know if it works. Thanks.

**Comment by simonetravaglini** [comment]
yes now it works thanks!
