### ISSUE TITLE
List of the transfers

### ISSUE THREAD

**Issue by ghost** [Myddleware/myddleware#39]
When u have just installed myddleware and you click on the menu "list of the transfers", you have this error.

<img width="1244" alt="capture d ecran 2017-06-29 a 22 55 21" src="https://user-images.githubusercontent.com/3073959/27709959-515d0fec-5d1e-11e7-870a-01ee242be4bf.png">

**Comment by ghost** [comment]
Ok it was a bad install on my part.
My user should be promoted on ROLE_ADMIN

```
php app/console fos:user:promote demo ROLE_ADMIN
```
👍

**Comment by Myddleware** [comment]
Hi Karudev,
Yes you 're right. This is a real bug, the non admin user should have access to the transfer 's list. We are following the problem in this issue #32 
Thanks.
