### ISSUE TITLE
login not working 

### ISSUE THREAD

**Issue by dnyt84** [Myddleware/myddleware#392]
Hello,

i did a brand new install and the login is not working.
I get no error just a new login prompt.

When I intentionally use a wrong password I do get a MSG ( Bad credentials)
I use PHP-FPM 7.4.11 with Apache.
I uploaded the latest version available from Github, 2.5.5

How can I troubleshoot this?

Thank you,

Daniel

**Comment by stlgaits** [comment]
Hello, 
I think this could be due to your version of PHP being too high. Could you try downgrading to a PHP 7.3.x version ? 
Let me know if this changed anything for you.

**Comment by dnyt84** [comment]
Its strange, when i open a incognito window I get it to work sometimes.
I will try a lower PHP version.

**Comment by CamillePMyddleware** [comment]
Hi,I am archiving this issue, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be. 
Thanks.

**Comment by AlexMyddleware** [comment]
Hello,

we take the liberty to close this issue, however if you encounter a bug equal or similar to this one do not hesitate to reopen the issue.
Please note that Myddleware is now compatible up to version php 8.

Thanks
