### ISSUE TITLE
 Sending information from different connectors

### ISSUE THREAD

**Issue by Valdderson** [Myddleware/myddleware#393]
Good afternoon, I'd like to use your tool but I have question:

I'm looking to bring information from the Moodle tool, to Hubspot tool. I noticed that sending data is divided by conectors and that each conector has specific field that can be sent.
First question: Can I only send information from one connector at a time or can I send the connector field "x" with the connector field "y"in the same rule?

If I can only send 1 at a time (as it appears to be), how do I make Hubspot understand that a contact within Hubspot needs to receive data from two different rules, from different connectors
Ex: Rule 1: connector "user" /field "name"
Rule 2: connector: "deal"/ field "post-graduation"

In this example how would hubspot understand that the two rules must populate the 1 contact data in the Husbpotsystem if the information is sent separately.

Hugs and Thank you!

**Comment by Myddleware** [comment]
Hi @Valdderson 
Could you have a look to this tutorial : https://myddleware.github.io/myddleware/#/basic_usage? This is a example between Prestashop and SuiteCRM but it will help you to understand how use Myddleware.

You will see that you can create a lot of rules with the same connectors. And if you use the same connectors to send contacts and deals for example, you will be able to link your differents rule. This way Myddleware will be able to find the right Id.

 Please let us know if it isn't clear.

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be. 
Thanks
