### ISSUE TITLE
Cannot find DB during installation. Despite the DB Connection details being correct

### ISSUE THREAD

**Issue by laukokpin** [Myddleware/myddleware#394]
Attached is the screenshot.

Debian 7. Php 7.3
bitnami Moodle image.

![image](https://user-images.githubusercontent.com/26833900/103644250-06ed4f80-4f91-11eb-8c14-201dd62fc625.png)

**Comment by Myddleware** [comment]
Hi @laukokpin ,
Hope you are well today.
I assume you have a problem with your database. Have you created the database myddleware on your server ? If yes, is your database stored on the same server than the one that host your Myddleware files (as you set localhost) ? 
Have a nice day.

**Comment by laukokpin** [comment]
> Hi @laukokpin ,
> Hope you are well today.
> I assume you have a problem with your database. Have you created the database myddleware on your server ? If yes, is your database stored on the same server than the one that host your Myddleware files (as you set localhost) ?
> Have a nice day.

Yes Localhost.

Yes I have created a database and granted the privileges as well as set the password.

Thank You.

**Comment by Myddleware** [comment]
Ok thanks.
Could you try to install Myddleware using the terminal : https://myddleware.github.io/myddleware/#/?id=install-myddleware

Please let us know if it works. Otherwise, could you show us the error with a screenshot please ?

**Comment by CamillePMyddleware** [comment]
Hi,I am archiving this issue, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be. 
Thanks
