### ISSUE TITLE
Moodle Connectors: Role Permission for core_webservice_get_site_info

### ISSUE THREAD

**Issue by laukokpin** [Myddleware/myddleware#395]
I can't find this capability to add to the role. So hence I get the error bellow. 

{
    "exception": "webservice_access_exception",
    "errorcode": "accessexception",
    "message": "Access control exception",
    "debuginfo": "Access to the function core_webservice_get_site_info() is not allowed.\n                     There could be multiple reasons for this:\n                     1. The service linked to the user token does not contain the function.\n                     2. The service is user-restricted and the user is not listed.\n                     3. The service is IP-restricted and the user IP is not listed.\n                     4. The service is time-restricted and the time has expired.\n                     5. The token is time-restricted and the time has expired.\n                     6. The service requires a specific capability which the user does not have.\n                     7. The function is called with username/password (no user token is sent)\n                     and none of the services has the function to allow the user.\n                     These settings can be found in Administration > Site administration\n                     > Plugins > Web services > External services and Manage tokens."
}

**Comment by Myddleware** [comment]
Hi @laukokpin ,

Could you check if you have completed all the steps in this tutorial : https://myddleware.github.io/myddleware/#/connectors_credentials?id=moodle

Hope it will help.
Have a nice day.

**Comment by laukokpin** [comment]
I did go through the steps. 

Can you tell me how to add this specific capability.   core_webservice_get_site_info

**Comment by laukokpin** [comment]
Nvm. I realize I was looking at roles and permissions. Instead of Web service Functions. It works now. Thank you.

**Comment by Myddleware** [comment]
That's perfect.
Thanks for your feedback.
