### ISSUE TITLE
Mautic 3 compatibility

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#396]
Hi guys,
seems that connector in this moment it's not working with mautic 3.0, isn't it?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
You are right, we will work on it to make Myddleware compatible with Mautic3.
We will keep you posted.

**Comment by stlgaits** [comment]
Hello @simonetravaglini ,
this issue should now be fixed and Myddleware is now compatible with Mautic 3 (see this commit : https://github.com/Myddleware/myddleware/commit/4382250cb93f1c98923e5bd2a74bd5c47e57c69a ). However, if using Mautic 3, please ensure that your cache folder (in Mautic) is emptied before creating the Mautic connector. 

Also, in case you need to use a previous version of Mautic, there is a slight change to do in  src/Myddleware/RegleBundle/Solutions/mautic.php line  62 : 

```
//If you have Mautic 2 or lower, you must change this parameter to your version number
	protected $mauticVersion = 3;

```
Hope this helps !
