### ISSUE TITLE
Missing rule_id in $params during Simulation

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#399]
When I click on "Simulate Transfer" many rule get '0' because no `rule_id` in `$param['rule']['id']`

than Custom solution with code like this

```php
public function read($param) {
   if ($param['rule']['id'] == 'you_rule_id') {                        
      $param['date_ref'] = '2000-01-01 00:00:00'; /* The override line */
   }	
   return parent::read($param);
}
```

replay with `0` record

we suggest to introduce something like this

- https://github.com/opencrmitalia-official/myddleware/blob/b425509eec72328f9f6cac0ad65b6407bd2ee964/devops/oldfiles/custom.php#L31
- https://github.com/opencrmitalia-official/myddleware/blob/I737/devops/oldfiles/client.php#L22

**Comment by Myddleware** [comment]
Hi @francescobianco ,

Thanks for this suggestion, very interesting code, thanks. 

The simulation process calls the function read_last') not read() . And this function doesn't need the rule id to work. It will just read one record in the source application : 
https://github.com/Myddleware/myddleware/blob/3df255a3b7ef1b465febd57dad976245bc7532f4/src/Myddleware/RegleBundle/Solutions/microsoftsql.php#L87

So you shouldn't have a problem with the rule id in the simulation process. Please coudl you give us more detail if you still have the problem. thanks.

**Comment by francescobianco** [comment]
Hi @simonetravaglini please follow this

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue but please do not hesitate to re-open it if needs be.
Thanks.
