### ISSUE TITLE
Advice on not-consistent records slot on "Simulate Transfer"

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#400]
We must found useful try a "Simulater Transfer" to configure the right limit number, 
than I'm expect the same behaviour provided here

https://github.com/Myddleware/myddleware/blob/3ad3a8b5be7b97d3634b11342d8a7cb8da64ad38/src/Myddleware/RegleBundle/Classes/rule.php#L507

If the simulation is inconsistent for date_ref

**Comment by Myddleware** [comment]
Hi @francescobianco ,
We are developing a new feature which should resolve this problem. In the next main Myddleware version, you will be able to set an id to read a specific record in the "simulator transfer" tab.
We will keep you updated.

**Comment by francescobianco** [comment]
Hi @simonetravaglini please follow this

**Comment by AlexMyddleware** [comment]
this feature exists in the current myddleware
