### ISSUE TITLE
Error : 0 is not a correct Rule mode. /home/myddleware/public_html/src/Myddleware/RegleBundle/Solutions/erpnext.php 490

### ISSUE THREAD

**Issue by laukokpin** [Myddleware/myddleware#401]
I mapped ERPnext's user to Moodle's users
as well as Erpnext's student to Moodle's Users.

I keep getting this error. Any ideas how to resolve it? Thanks.

**Comment by stlgaits** [comment]
Hello, 

Thank you very much for this. It appears there is a slight bug in our code. We will fix this promptly on the hotfix branch, but meanwhile here is how you can solve this problem : 
Open the file specified :  /home/myddleware/public_html/src/Myddleware/RegleBundle/Solutions/erpnext.php
Then go to line 485, it should look like this : 
![image](https://user-images.githubusercontent.com/74190794/104456656-49beb100-55a9-11eb-8754-baedd067a072.png)
And change $RuleMode to $ruleMode like this : 
![image](https://user-images.githubusercontent.com/74190794/104456767-71157e00-55a9-11eb-8414-abb4107038f6.png)

Once you've made this change, save your file and you should no longer get this error. Let me know whether  this worked or not and we will make sure to fix this bug in the next hotfix.

**Comment by laukokpin** [comment]
Hi,

 I have modified. And do not see their error anymore. Brilliant. And Thank
you.

 However I do not get any transfer whatsoever as per the screenshot bellow.

[image: image.png]


>

**Comment by stlgaits** [comment]
You're welcome ! Could you send the screenshot again ? I can't see it right now unfortunately

**Comment by laukokpin** [comment]
here it is. thanks

![image](https://user-images.githubusercontent.com/26833900/104465734-54039e00-55ef-11eb-89a1-0f36780fd426.png)

**Comment by stlgaits** [comment]
Ok, thank you. Could double checked that you set (and saved) a reference date in the past in the rule parameters ?  

If you don't manually enter a reference date to read from in Myddleware, then the reference date is automatically set to the creation date (so today at midnight) by default.

Here is a link with more detail about this just in case : https://myddleware.github.io/myddleware/#/basic_usage?id=rule-parameters

Let me know if that changed anything.

**Comment by laukokpin** [comment]
It worked.  Thank You.  But now I have error sending. I think it's due to moodle's required field such as password not being sent over.  But that should be for another thread. Thanks!


![image](https://user-images.githubusercontent.com/26833900/104544507-e4c79180-5662-11eb-8cc9-0758696b31e5.png)

**Comment by stlgaits** [comment]
Happy to help !
