### ISSUE TITLE
Wrong Timezone is used in Transfer and Task

### ISSUE THREAD

**Issue by laukokpin** [Myddleware/myddleware#403]
![image](https://user-images.githubusercontent.com/26833900/104574002-85807600-5690-11eb-8bd3-77292d5dad2d.png)
![image](https://user-images.githubusercontent.com/26833900/104574100-9e892700-5690-11eb-9157-c98248062770.png)

But in Rules the correct timezone is used.

![image](https://user-images.githubusercontent.com/26833900/104574164-b19bf700-5690-11eb-94b1-7500b3418004.png)

**Comment by stlgaits** [comment]
Hi,
sorry about this, yes indeed the dates in data transfer are saved as UTC. This is something we need to improve so that the dates are in sync with the user's timezone.

**Comment by AlexMyddleware** [comment]
![image](https://github.com/Myddleware/myddleware/assets/106162060/5f1b2636-d791-4336-ba3c-ad5d6c397ed2)
![image](https://github.com/Myddleware/myddleware/assets/106162060/0b2e09dc-4b09-4b65-b7c1-52b983c50945)
datetime in tasks and document is now in the same format.
