### ISSUE TITLE
Test : send mail failed

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#406]
When we test the email configuration : 
![image](https://user-images.githubusercontent.com/11330301/104777781-93132a00-577c-11eb-86eb-c8a3e1ba38a5.png)

We receive the error : Attempted to call an undefined method named "newInstance" of class "Swift_Message".

**Comment by stlgaits** [comment]
Tested and worked using Google configuration with .env file but this will need to be looked at in more detail, especially as users may not be able to write parameters in .env file themselves.
Google Documentation on configuring SMTP : https://support.google.com/a/answer/176600?hl=en#zippy=%2Cutiliser-le-serveur-smtp-gmail%2Cuse-the-gmail-smtp-server 
If double auth is enabled on Google account, will need to allow 'Less secure Apps' via Google Account.

**Comment by stlgaits** [comment]
Still an issue, currently this is the error displayed.
![image](https://user-images.githubusercontent.com/74190794/121179295-d7a07e80-c85f-11eb-96c2-8deab8cd7ca3.png)

**Comment by stlgaits** [comment]
Fixed. 
Standard Gmail configuration : 
![image](https://user-images.githubusercontent.com/74190794/121202763-d712e280-c875-11eb-8dba-6d24d459784b.png)
or 
![image](https://user-images.githubusercontent.com/74190794/121202815-e2fea480-c875-11eb-9169-5b73e895617a.png)
