### ISSUE TITLE
Connector creation form not properly displayed

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#407]
When we create a connector, teh form isn't visible. Probably a css error : 
![image](https://user-images.githubusercontent.com/11330301/104778043-0026bf80-577d-11eb-9e9b-ce03f664e5c6.png)

**Comment by Myddleware** [comment]
We have the same problem in the data transfer search view : 
![image](https://user-images.githubusercontent.com/11330301/104778525-c4d8c080-577d-11eb-8987-909fe2af3d80.png)

**Comment by stlgaits** [comment]
Fixed https://github.com/Myddleware/myddleware/commit/f0b82edd364b4fd19620a6cc98dd3b16acb7c80b
![image](https://user-images.githubusercontent.com/74190794/106898842-f8f82f00-66f4-11eb-87a4-721c72954738.png)

**Comment by stlgaits** [comment]
![image](https://user-images.githubusercontent.com/74190794/106899932-3c06d200-66f6-11eb-9404-46fbc2913418.png)
Transfers Page
