### ISSUE TITLE
Error when selecting a solution during rule creation

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#408]
When we selec the source and target application, we should be able to select the connector. But we receive an error : 
![image](https://user-images.githubusercontent.com/11330301/104778205-49770f00-577d-11eb-8731-1ef697a7e3d3.png)

**Comment by stlgaits** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/74190794/106904359-63ac6900-66fb-11eb-9397-728471ca2906.png)
