### ISSUE TITLE
Using Myddleware to update existing data in Salesforce with data from MySql DB

### ISSUE THREAD

**Issue by rickyshe** [Myddleware/myddleware#412]
Hello,

We have a Salesforce system with objects we have defined.
Some data is updated automatically using Myddleware, other data is updated manually using csv files.

We are using Myddleware , Moodle connector, updating data in Salesforce.

We are uploading data (not kept in Moodle) from MySql DB.
For this we are using csv files, loaded into Salesforce. 

We want to stop working manually and start working with Myddleware to create an automated process.
We are planning to use Myddleware integration with our local MySql DB.
We want to update existing data in Salesforce with more relevant data from our MySql DB.  
How can we use Myddleware for this purpose?

For example:
We have a contact object with data such as: personal details, employment history, education records etc. 
These, have many lookup data objects, we defined in Salesforce.
We have in our DB only the contact ID in Salesforce.
We do not have the contact related objects (lookup data objects) IDs in Salesforce.
 
Thanks and regards
she codes R&D team

Ricky.

**Comment by Myddleware** [comment]
@rickyshe ,
Could you give us more detail with about your example, one test data would be perfect ? 
Thanks.

**Comment by rickyshe** [comment]
Hello

This is an example :
Moodle - is a source of data   - participants( contact ), courses, enrollments , first two are lookups for the enrollments
MySQl  - is a source of data  - branches - this is a lookup , for each participant, there is a branch
Salesforce - is a target 

Myddleware plugin for Moodle is used to update Salesforce : participants( contact ), courses, enrollments
In order to get the branches data: 
In Salesforce there is a lookup entity : branches which contains a list of branches
In Salesforce each participant has a data field : branch
In order to update that field , extract the participants's  branch data from MYSQL to csv, and upload to Salesforce.

We already have in Salesforce : participants, branches, and which branch every participant belong to.
And we didn't use  Myddleware plugin to update that data.

Now we would like to use Myddleware , 
Whenever there is a new branch, whenever there is a new participants join a branch

Thanks.

**Comment by Myddleware** [comment]
Hi @rickyshe ,
If I have understood well, you have your  Id Salesforce (and other fields like branch) into your MySQL table and you want to update Salesforce automatically. Please let me know if I am wrong.

We have tried to reproduce your case. So we have created a table with 2 fields : Salesforce_id and last_name (your field branch in your example) : 
![image](https://user-images.githubusercontent.com/11330301/106516742-cc1b0080-64d7-11eb-8208-60bc2b479681.png)

Then we have mapped the IdSalesforce with the Myddleware_element_id field which correspond to the ID in the target solution (Salesforce in your case). We have also mapped last_name (branch in your case) : 
![image](https://user-images.githubusercontent.com/11330301/106517139-5feccc80-64d8-11eb-9e44-0c1ad9c168c0.png)

If you do this, Myddleware will automatically generates an update (in case your Id isn't null) using myddleware_element_id as the target ID : 
![image](https://user-images.githubusercontent.com/11330301/106517405-b9ed9200-64d8-11eb-830f-5902a8be2f61.png)

This document has updated Murray to Myrray8 : 
![image](https://user-images.githubusercontent.com/11330301/106517478-d8538d80-64d8-11eb-8523-ce56854a5517.png)

However, when we tried to reproduce your case, we found an issue and we have fixed it. Here is the commit : https://github.com/Myddleware/myddleware/commit/03170f446c88f5df007526035ddec94923a4d26f

You can manually apply this fix or wait for the launch of Myddleware 2.5.7 (tomorrow or on Wednesday).

Hope it helps.

**Comment by rickyshe** [comment]
Hi,
Thanks very much for your help.
Thank You.
