### ISSUE TITLE
Connector list : data not center inside the colum

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#414]
In the connecor list view : the data in the table aren't center : 
![image](https://user-images.githubusercontent.com/11330301/105995537-667ade80-60a9-11eb-9137-fa61edf95ad2.png)

**Comment by stlgaits** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/74190794/106905485-a02c9480-66fc-11eb-9f08-4f7a883521a4.png)
