### ISSUE TITLE
Myddleware is only in french

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#415]
The language of the application is in french even if the language is "en" (parameter locale) in the file \config\packages\public\parameters_public.yml : 
![image](https://user-images.githubusercontent.com/11330301/105995840-d5583780-60a9-11eb-8ecb-1c5ccde59f5a.png)

**Comment by stlgaits** [comment]
![image](https://user-images.githubusercontent.com/74190794/107350928-5102ad00-6aca-11eb-8802-d00da5f7ab8e.png)
![image](https://user-images.githubusercontent.com/74190794/107351309-bf476f80-6aca-11eb-8fc2-7d14965d8bb0.png)
Fixed, locale should now work without using parameters_public.yaml
