### ISSUE TITLE
mssql:  module list fails if too many tables

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#417]
Hi,
we have been connected a Db with 10k tables / viwes.
When we try to select DB we get an empty list:
![image](https://user-images.githubusercontent.com/6990139/106253899-664d2100-6218-11eb-87a2-845786a747b9.png)
Ho to manage this situation?

**Comment by Myddleware** [comment]
Hi Simone,
Could you connect directly to MSSQL with the user used in your MSSQL connector in Myddleware. Then could you run this query : 
`SELECT table_name FROM information_schema.tables WHERE table_catalog = 'your_database';`

Do you get the expected result ? 
Thanks.

**Comment by matteo-opencrmitalia** [comment]
Hi @Myddleware, issue was related to this query: 

https://github.com/Myddleware/myddleware/blob/9deaf79995f41a7383b6530f65d0fce0af35e39c/src/Myddleware/RegleBundle/Solutions/microsoftsql.php#L59

![image](https://user-images.githubusercontent.com/60502629/106293729-a0d1b080-624e-11eb-8311-5841f3c025db.png)


we fix changing like this: 

SELECT table_name FROM INFORMATION_SCHEMA.TABLES

SELECT table_name FROM INFORMATION_SCHEMA.COLUMNS

**Comment by Myddleware** [comment]
Thank  you so much for this fix.
