### ISSUE TITLE
Reading Issue: Error : 0 is not a correct Rule mode. 

### ISSUE THREAD

**Issue by userGitHub75334** [Myddleware/myddleware#418]
I have installed erpNext, prestashop and myddleware for data exchange. Every program for itself works fine. I've transferred customer data from prestashop to erpNext sucessfully.
But now I want to transfer item data from erpNext to prestashop and I got the error message "Reading Issue: Error : 0 is not a correct Rule mode. /var/www/html/myddleware/src/Myddleware/RegleBundle/Solutions/erpnext.php 491".
I've found some information for that issue in the github issue #198 comment, but there is not described the steps to solve the problem.
I would be happy, if somebody can help me.
best regards

**Comment by stlgaits** [comment]
Hello,

please have a look at this thread : https://github.com/Myddleware/myddleware/issues/401 which is linked to this commit https://github.com/Myddleware/myddleware/commit/9deaf79995f41a7383b6530f65d0fce0af35e39c

Kind regards,

Estelle

**Comment by stlgaits** [comment]
By the way, you can simply upgrade your Myddleware version to 2.5.6a by following this tutorial as this bug has been corrected since : https://myddleware.github.io/myddleware/#/admin_tasks?id=upgrading-myddleware

**Comment by userGitHub75334** [comment]
Thank you very much,
the update to the version 2.5.7 has solved the issue. 
Also a lot of thanks for the fast help. 
Best regard
Andreas
