### ISSUE TITLE
templates for the data exchange between erpNext and prestashop

### ISSUE THREAD

**Issue by userGitHub75334** [Myddleware/myddleware#419]
Dear myddleware community,

I've installed erpNext and prestashop. Now I want to configure the data exchange between these systems. I tryed to use the button "default templates selection" and got the message "No template for these solutions, if you want a template, please contact us".
I want to ask you, whether there are templates for the data exchange between erpNext and prestashop in both directions.
I want to transfer data of customers, items, products and orders.

I would be happy, if you can help me.

Best regards
Andreas

**Comment by Myddleware** [comment]
Hi @userGitHub75334 ,
Yes we haven't created any template between erpNext and Prestashop yet. We can help you to create your rules, then we will ask you to generate the template. By this way, you will contribute to our open source project.

Could you give us more detail  about which data you want to send from Prestashop to erpNext, and which data you want to send erpNext to Prestashop ? For example, I guess you want to send orders only from prestashop to erpNext but not from ERPNext to Prestashop, isn't it ?
Do your products have several declinason in Prestashop ? 

Just for information, we could also build the template for you, install it into your Myddleware and support you in your project. In this case, please contact us direclty using our contact page here : http://www.myddleware.com/contact-us

Thanks.

**Comment by kemsko** [comment]
Hi @Myddleware ,
So we can't connect ERPNext and prestashop unless we create the rules, we cant create it using the connector menu? im new on this.

Best Regards.
- David Kemski

**Comment by Myddleware** [comment]
Hi @kemsko,
Yes, you have to create the rule to indicate to Myddleware what data you want to send and how you want to send it.
To  help you to create these rules, you can use this tutorial : https://myddleware.github.io/myddleware/#/basic_usage
It is a tutotial between Prestashop and SuiteCRM (not ERPNext) but it will show you how Myddleware works.
Hope it helps.

**Comment by kemsko** [comment]
definitely helps! thanks!
i have another question, it would be awesome if you can help me.

i'm using the cloud-based Myddleware for testing the connector, and i need to connect PrestaShop and ERPNEXT, but every time that i put the API Key from prestashop to Myddleware and always show me "Connection failed : Bad auth key" message, i followed all the instructions and the key its correct from PrestaShop.
![Capture](https://user-images.githubusercontent.com/77998041/106527053-3fa71880-64ac-11eb-9901-0a58f66887ce.PNG)

**Comment by userGitHub75334** [comment]
> Hi @userGitHub75334 ,
> Yes we haven't created any template between erpNext and Prestashop yet. We can help you to create your rules, then we will ask you to generate the template. By this way, you will contribute to our open source project.
> 
> Could you give us more detail about which data you want to send from Prestashop to erpNext, and which data you want to send erpNext to Prestashop ? For example, I guess you want to send orders only from prestashop to erpNext but not from ERPNext to Prestashop, isn't it ?
> Do your products have several declinason in Prestashop ?
> 
> Just for information, we could also build the template for you, install it into your Myddleware and support you in your project. In this case, please contact us direclty using our contact page here : http://www.myddleware.com/contact-us
> 
> Thanks.

Thanks for your feedback, I will try to build the data exchange with the documentation  you mentioned and will test it in my environment. If it works, I can describe the approach of solution for the community.
best regards
Andreas
