### ISSUE TITLE
empty database tables after successful install

### ISSUE THREAD

**Issue by 604media** [Myddleware/myddleware#42]
I was installing the application and got all good checks and success installed - when i went to login in i got a missing database table error - I looked at my DB and there are no tables??

centos running cpanel - instaled via web installer

![image](https://user-images.githubusercontent.com/64729/27952607-bfd60d12-62bd-11e7-855e-5d26a97cd45e.png)

**Comment by Myddleware** [comment]
Hi,
Thank you for using Myddleware.
Could you have a look into the file app/config/parameter.yml, and check if the database parameters are corrects (database_name, database_user...) ?
Could you give us the detail of the error you have ?
And could you make sure taht the MySQL user you has the right to create table ? 
Thanks.
Have a nice day.

**Comment by Muzzamann** [comment]
I have the same issue, trying UN and PW results in the following....

 An exception occurred while executing 'SELECT t0.username AS username_1, t0.username_canonical AS username_canonical_2, t0.email AS email_3, t0.email_canonical AS email_canonical_4, t0.enabled AS enabled_5, t0.salt AS salt_6, t0.password AS password_7, t0.last_login AS last_login_8, t0.confirmation_token AS confirmation_token_9, t0.password_requested_at AS password_requested_at_10, t0.roles AS roles_11, t0.id AS id_12 FROM users t0 WHERE t0.username_canonical = ? LIMIT 1' with params ["maia"]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'movelife_db.users' doesn't exist ( 2 )

Was the solution above the correct fix?

**Comment by Myddleware** [comment]
Hi Muzzamann,
Can you try to install Myddleware via command ssh : https://myddleware.github.io/myddleware/#/?id=install-myddleware
Could you show me what happens when you run this command : 
php app/console doctrine:schema:update --force --env=prod

Thanks.
Have a nice day.

**Comment by Alexandre17220** [comment]
@ 604media 
think to protect your config file `http://mw.604dev.com/app/config/parameters.yml` is accessible and mysql password is visible..

**Comment by 604media** [comment]
thanks

Kind regards,

Michael

------------------------------
  *michael loveless*
VICE PRESIDENT, OPERATIONS
C: 604 679 9329
O: 604 637 7175 x 602
E: michael@604media.com <+michael@604media.com>
W: 604media.com [image: 604media Design & Function]
Confidentiality Warning: This e-mail contains information intended only for
the use of the individual or entity named above. If the reader of this
e-mail is not the intended recipient or the employee or agent responsible
for delivering it to the intended recipient, any dissemination,
publication, or copying of this e-mail is strictly prohibited. The sender
does not accept any responsibility for any loss, disruption or damage to
your data or computer system that may occur while using data contained in,
or transmitted with, this e-mail.

**Comment by ghost** [comment]
Hi @604media,

You must secure your myddleware, by correcting your virtualhost.
In fact, the virtualhost must be redirect on the web dir of the application.

It's a best pratice on a symfony project.

----
Best Regards
Lead Developer
www.myddleware.com

**Comment by 604media** [comment]
thanks for your support - we will have this done.


Kind regards,

Michael

------------------------------
  *michael loveless*
VICE PRESIDENT, OPERATIONS
C: 604 679 9329
O: 604 637 7175 x 602
E: michael@604media.com <+michael@604media.com>
W: 604media.com [image: 604media Design & Function]
Confidentiality Warning: This e-mail contains information intended only for
the use of the individual or entity named above. If the reader of this
e-mail is not the intended recipient or the employee or agent responsible
for delivering it to the intended recipient, any dissemination,
publication, or copying of this e-mail is strictly prohibited. The sender
does not accept any responsibility for any loss, disruption or damage to
your data or computer system that may occur while using data contained in,
or transmitted with, this e-mail.

**Comment by ghost** [comment]
👍
