### ISSUE TITLE
Homepage's charts aren't displayed anymore

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#420]
Homepage's charts aren't displayed anymore : 
![image](https://user-images.githubusercontent.com/11330301/106523068-e0173000-64e0-11eb-89b0-b972d7701f14.png)

**Comment by stlgaits** [comment]
Fixed : https://github.com/Myddleware/myddleware/commit/3ddec34ab955d7806d12c6ba0282298f4ccdad8c 
![image](https://user-images.githubusercontent.com/74190794/106898712-d239f880-66f4-11eb-9d03-3767bfc61ac4.png)
