### ISSUE TITLE
manage deleted record from DB

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#423]
Suppose we have a Db as source.
A record is cancelled in DB, how to manage deletion with myddleware to a target like CRM?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
Could you tell me how the record is cancelled, is it a flag in your database set to 1 when it is cancelled ? 
I guess your are using Vtiger as a CRM but could you confirm it ? 
Thanks.

**Comment by simonetravaglini** [comment]
It's not a flag, but deep deleted.

**Comment by Myddleware** [comment]
Hi Simone, 
Please update your Myddleware instance to the version 2.5.7a (#433).
Then when you will edit your rule, the new value « Compare source table with Myddleware" will appear in the list « Field with deletion flag" : 
![image](https://user-images.githubusercontent.com/11330301/107767653-97a80f80-6d35-11eb-80bc-722c93085df2.png)

If you choose this value, Myddleware will compare the data already sent by Myddleware in your rule and the data in your source table. If one record doesn’t exist in your source table anymore, Myddleware will genere a data transfer to delete the record in Vtiger.

**Comment by matteo-opencrmitalia** [comment]
@Myddleware try this function on your demo ( http://www.crmconsult.com/livedemo/myddleware/web ) with mysql as source and vtiger as target and i can't use deletion flag. 

![image](https://user-images.githubusercontent.com/60502629/114673841-ead31a00-9d06-11eb-9c9c-6577b5cae466.png)

**Comment by Myddleware** [comment]
Hi @matteo-opencrmitalia ,

We have updated the demo instance. It should be fine now. 

You have to select a solution which allows to read delete data in source, like SuiteCRM or MySQL, if  you want to see the deletion parameter in the rule.

Let me know if you have any proble.
