### ISSUE TITLE
Error : can't run rule from UI 

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#425]
![image](https://user-images.githubusercontent.com/74190794/106908881-ffd86f00-66ff-11eb-808d-61cafb850a76.png)
When you click on 'run the rule', the Error 'undefined offset 1' is triggered and the rule isn't run.

**Comment by Myddleware** [comment]
Button is working now : 
![image](https://user-images.githubusercontent.com/11330301/110049161-94f77380-7d51-11eb-8ef1-a392494b5beb.png)
