### ISSUE TITLE
data exchange between erpNext and prestashop: Error : Please check your data.This call to PrestaShop Web Services failed and returned an HTTP status of 400.

### ISSUE THREAD

**Issue by userGitHub75334** [Myddleware/myddleware#428]
Dear myddleware community,

I've installed erpNext and prestashop. Now I want to transfer item data from erpNext to prestashop. The transferprocess stopped with the error message
"Error : Please check your data. This call to PrestaShop Web Services failed and returned an HTTP status of 400. That means: Bad Request. /var/www/html/myddleware/src/Myddleware/RegleBundle/Solutions/prestashop.php Line : ( 998 )Failed to send document. Status : Error_sending"

I' would be happy if you could help me with an approach of solution.

best regards
Andreas

**Comment by Myddleware** [comment]
Hi Andreas,
Could you post a screenshot of your data transfer in error and tell us which module you want to send to Prestashop (customer, product....) ?  We would like to see what data you want to send to Prestashop. 
Best regards.

**Comment by userGitHub75334** [comment]
Thank you for your quick response.
I've made 2 screenshots. They contain the information you asked for.
I have updated my environment with the newest version 5.1.7 today ca. 22:00.

![error02](https://user-images.githubusercontent.com/78299104/106963381-cd029b00-6740-11eb-8b12-7f45208ce40f.JPG)
The error message of the updated version 5.1.7 is now:
"Error : Please check your data.This call to PrestaShop Web Services failed and returned an HTTP status of 400. That means: Bad Request. /var/www/html/myddleware/src/Myddleware/RegleBundle/Solutions/prestashop.php Line : **( 996 )**Failed to send document. Status : Error_sending"

If you need more information, don't hesitate to contact me.
best regard
Andreas

**Comment by Myddleware** [comment]
Thanks,
I would like the screenshot of the data transfer in error because I would like to send the same data than you to Prestashop and so reproduce the issue.
Could you add your data transfer screenshot ?
Thank you very much

**Comment by userGitHub75334** [comment]
Thank you for your help, 
I hope the screenshots contain the information you need.
![error03](https://user-images.githubusercontent.com/78299104/107006363-4fb34680-6791-11eb-97cc-292154c6b3f3.JPG)
![error04](https://user-images.githubusercontent.com/78299104/107006378-55109100-6791-11eb-8406-ea49a58bcafa.JPG)
best regard
Andreas

**Comment by Myddleware** [comment]
Hi Andreas,
We could reproduce you problem. You haven't mapped the price and it is a required field into Prestahop. You can see the star here to indicate that you should fill this field : 
![image](https://user-images.githubusercontent.com/11330301/107061284-46999800-67d8-11eb-838c-c8826d1704a0.png)

If you haven't any price, you can fixe a default value to 0 using the formula : "0"
![image](https://user-images.githubusercontent.com/11330301/107061374-6466fd00-67d8-11eb-9649-a4f9ecbd6633.png)

Hope it will sove your problem.

**Comment by userGitHub75334** [comment]
Thank you very much,
sorry it was my fault.
I didn't know that the star indicates the key-fields.
I have tested the data transfer with the field "price" like descriped in your solution and it works fine.

You helped me very quickly. Really great support.

Best regard
Andreas

**Comment by Myddleware** [comment]
Hi Andreas,
You couldn't know because there is nothing that explain why there is a star on this target fields.
Thanks for your feedback.
