### ISSUE TITLE
Integration with Moodle and SuiteCRM

### ISSUE THREAD

**Issue by subhankar** [Myddleware/myddleware#430]
We have installed Myddleware to integrate SuiteCRM and Moodle in our organization. The connection has been established successfully. We are trying to push all courses from CRM to Moodle and Students, while any new Course / Student being created. We are unable to achieve this integration through Myddleware. 

We have followed the instruction mentioned here:

https://myddleware.github.io/myddleware/#/connectors_credentials?id=moodle

Could you help us to figure it out.

**Comment by stlgaits** [comment]
Hello,
could you please check for me whether you have selected a reference date in the past (and saved) in this section of your rule : 

![refdate](https://user-images.githubusercontent.com/74190794/107367789-fffdb380-6adf-11eb-8acf-d752ae2e0614.png)
If you save and then click on simulate transfers, it should then tell you the number of estimated transfers for this rule, which should of course be above 0. 

Let me know if this helps.

**Comment by subhankar** [comment]
But parameter is absent when I create / Edit any rule in the system

![Myddleware-Fields](https://user-images.githubusercontent.com/608589/107369891-4ebf4380-6b08-11eb-8f77-ac05f05213e0.png)

**Comment by stlgaits** [comment]
Sorry  I should have been clearer. First you need to save your rule in the confirmation tab. Your rule will then be created. Then, you need to go back to that rule and then click on the parameters tab : 
![image](https://user-images.githubusercontent.com/74190794/107370280-0f323080-6ae3-11eb-8a83-ab9218655915.png)
It is only once your rule is created that you will be able to change the reference date.

**Comment by subhankar** [comment]
Now that rule has been executed. Thanks for your help. But some error occurs 

accessexception : Access control exceptionFailed to send document. Status : Error_sending

![Myddleware-The-task-form-6022911b9c2e38-78081990](https://user-images.githubusercontent.com/608589/107372259-3b61a780-6b0b-11eb-8fa6-5040c07ac251.png)

**Comment by stlgaits** [comment]
I would need to have a look at your data transfer in order to be sure where the problem lies but I think this could be due to your Moodle configuration. Did you import your Moodle role ?  Could you also check that the user that is assigned this token has that role too ? 
Check this out I think it could help you too : https://github.com/Myddleware/myddleware/issues/395

**Comment by subhankar** [comment]
I have assigned Myddleware role to the particular user

![DynLMS-Administration-Users-Permissions-Assign-system-roles](https://user-images.githubusercontent.com/608589/107382268-b5972980-6b15-11eb-92fa-06ae16f182d3.png)

See the error I got 

![Myddleware-Transfer-form-6022a0c93809f7-59665743](https://user-images.githubusercontent.com/608589/107382335-c3e54580-6b15-11eb-9cab-7787e6ed25df.png)

**Comment by stlgaits** [comment]
Ok, are you sure your user is correctly assigned to the token in Moodle? 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/74190794/107383903-bf0e9a80-6af1-11eb-83ce-1fd826dab50d.png)
Also, can you check whether there isn't any missing capabilities on this page ? 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/74190794/107384075-ecf3df00-6af1-11eb-8309-804aff3e72c7.png)

**Comment by subhankar** [comment]
I think yes I configured it 

Manage token screen
![Myddleware-Transfer-form-6022a0c93809f7-59665743](https://user-images.githubusercontent.com/608589/107392082-52aa9000-6b1f-11eb-8fd4-9ac2ec9d55a1.png)

Function added
![DynLMS-Administration-Plugins-Web-services-External-service-functions](https://user-images.githubusercontent.com/608589/107392148-6229d900-6b1f-11eb-98ac-e491f6a84e4e.png)

**Comment by Myddleware** [comment]
OK great. Sounds good.
Could you post a screenshot with the detail of your data transfer (data you are trying to send to Moodle) ? Thanks.

**Comment by subhankar** [comment]
I tried to push a course from CRM to Moodle 

![Myddleware-Transfer-form-6022a9c633bd43-56072167](https://user-images.githubusercontent.com/608589/107393816-37d91b00-6b21-11eb-8082-4044a7843535.png)

**Comment by Myddleware** [comment]
Sorry, not this one. The one that have the status error_sending. 
Thanks.

**Comment by subhankar** [comment]
![Myddleware-Transfer-form-602290ba8e9e97-08707405](https://user-images.githubusercontent.com/608589/107403070-b090a500-6b2a-11eb-8882-bd4244a6f1bd.png)

**Comment by subhankar** [comment]
Any update on how to resolve this issue.

**Comment by Myddleware** [comment]
Hi @subhankar ,
About our support, our clients always come first then we answer forum's question. It is the reason why, sometime, we answer a few hours after a topic is posted.  I am sure that you understand.

Could you test this : could you log into your Moodle instance with the user linked to your token in Moodle. Then try to create a user directly into your Moodle instance (using your browser), use exactly the same data than in your data transfer. It should failed and you will maybe have more detail about the error. Maybe the password is required.
In other word, I ask you to do manually exactly the same thing than you are trying to do with Myddleware. 

Could you try it ? 
Thanks.

**Comment by subhankar** [comment]
I m not able to login using webservice user.

**Comment by Myddleware** [comment]
Hi @subhankar,
Maybe that's the problem. Could you try to set "Manual account" here : 
![image](https://user-images.githubusercontent.com/11330301/107525763-74575600-6bb7-11eb-9621-3e41ab977557.png)

Please keep us updated.

**Comment by subhankar** [comment]
Hi 
I have changed the authentication method to Manual Authentication and able to login. I can create users from new login. Now if I again trying to Run User Creation rule, received **_Error_sending_** Error

**Comment by Myddleware** [comment]
Hi @subhankar ,
When you have created the user in Moodle, did you put exactly the same data than in your Myddleware rule, so only email, firstname and lastname (no username and no password) ?

**Comment by subhankar** [comment]
Seems I have been able to figure out the issue. A couple of mandatory fields were missing in the mapping. Now course list start synchronization. Thanks for your help.

**Comment by Myddleware** [comment]
Good news. Thanks for your feedback. Enjoy Myddleware ;)
