### ISSUE TITLE
Can you explain this scenario?

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#434]
Hi,
after launched a rule I have this result:
![image](https://user-images.githubusercontent.com/6990139/107788067-3e010e80-6d50-11eb-875d-a89a4a9ea60d.png)

Why some record are still open?
In this case we are importing some raw form invoice (from a DB to Vtiger)
Status of these records is:
![image](https://user-images.githubusercontent.com/6990139/107788262-7f91b980-6d50-11eb-8155-d51041712a0c.png)

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
Could you post a screenshop with the data transfer content and its logs ? 
Thanks.

**Comment by simonetravaglini** [comment]
![image](https://user-images.githubusercontent.com/6990139/107788570-da2b1580-6d50-11eb-8673-b8902d9ad6e9.png)

**Comment by simonetravaglini** [comment]
![image](https://user-images.githubusercontent.com/6990139/107788649-f038d600-6d50-11eb-9567-7b4452251183.png)

**Comment by simonetravaglini** [comment]
![image](https://user-images.githubusercontent.com/6990139/107788735-0a72b400-6d51-11eb-9c1a-632cab19eb2f.png)

**Comment by Myddleware** [comment]
Thanks @simonetravaglini ,
What happens if you run it again by clicking on the button "reload the transfer" on the data transfer view ?

**Comment by simonetravaglini** [comment]
![image](https://user-images.githubusercontent.com/6990139/107798905-08aeed80-6d5d-11eb-8b05-7cc976484a46.png)

**Comment by Myddleware** [comment]
You data transfer seems to have the status error_sending. Could you show me the log on your data transfer ? Or does your data transfer still have the status "Ready to send" ?

**Comment by simonetravaglini** [comment]
Is still ready to send...

**Comment by Myddleware** [comment]
OK Simone, you probably have a fatal error. Could you check your logs /var/logs/prod.log (or dev.log if you are using dev environement). Could you try to run it gain and check if there is a new log ? 
Thanks

**Comment by simonetravaglini** [comment]
Seems that was related to a bug in Vtiger connector.
We fixed.
@francescobianco can you release fix?
