### ISSUE TITLE
 rules: mapping fields: documentation about the fields of each module prestashop module and erpNext module

### ISSUE THREAD

**Issue by userGitHub75334** [Myddleware/myddleware#435]
Dear myddleware community,

I've installed erpNext and prestashop. Now I want to transfer sales orders and sale orders detailes from prestashop to erpNext. 
The problem is my try and error method to generate the rules. I get a lot of error messages and I need a lot of time to get little steps with success. So I want to ask, is there a documentation about the field mappings which I could use for that work.
It would be helpful, because the names and the data structure are different and so it is very difficult to map the fields with knowledge. 

I' would be happy if you could help me with a documentation about the fields of each module, in my case prestashop module and erpNext module, which I can use to build the rules purposeful.

It would be great if you can hep me.

best regards
Andreas

**Comment by Myddleware** [comment]
Hi @userGitHub75334,
There is no documentation to create the connection between Prestashop and ERPNext. We have only documentation to create the connectors. 
However, we 'll continue to help you to build the connection via this forum. Once you have built it with our help, we count on you to generate a template (we will show you how to generate it). This template will definitely help other people with the same goal than you.
We remain at your disposal.

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue but please do not hesitate to re-open it if needs be.
Thanks.
