### ISSUE TITLE
Data exchange: prestashop to erpnext: sales order

### ISSUE THREAD

**Issue by userGitHub75334** [Myddleware/myddleware#436]
Dear myddleware community,

I've installed erpNext and prestashop. Now I want to transfer sales orders from prestashop to erpNext.
I got the following error message:

**Traceback (most recent call last): File "/home/pi/frappe-bench/apps/frappe/frappe/app.py", line 64, in application response = frappe.api.handle() File "/home/pi/frappe-bench/apps/frappe/frappe/api.py", line 130, in handle "data": frappe.get_doc(data).insert().as_dict() File "/home/pi/frappe-bench/apps/frappe/frappe/model/document.py", line 230, in insert self.run_before_save_methods() File "/home/pi/frappe-bench/apps/frappe/frappe/model/document.py", line 896, in run_before_save_methods self.run_method("validate") File "/home/pi/frappe-bench/apps/frappe/frappe/model/document.py", line 797, in run_method out = Document.hook(fn)(self, *args, **kwargs) File "/home/pi/frappe-bench/apps/frappe/frappe/model/document.py", line 1073, in composer return composed(self, method, *args, **kwargs) File "/home/pi/frappe-bench/apps/frappe/frappe/model/document.py", line 1056, in runner add_to_return_value(self, fn(self, *args, **kwargs)) File "/home/pi/frappe-bench/apps/frappe/frappe/model/document.py", line 791, in &lt;lambda&gt; fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs) File "/home/pi/frappe-bench/apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 36, in validate super(SalesOrder, self).validate() File "/home/pi/frappe-bench/apps/erpnext/erpnext/controllers/selling_controller.py", line 40, in validate super(SellingController, self).validate() File "/home/pi/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 21, in validate super(StockController, self).validate() File "/home/pi/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 68, in validate self.validate_qty_is_not_zero() File "/home/pi/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 434, in validate_qty_is_not_zero if not item.qty: AttributeError: str object has no attribute qty Failed to send document. Status : Error_sending**

Details:
![image](https://user-images.githubusercontent.com/78299104/107927672-99611580-6f77-11eb-81ef-4b60e97c3c58.png)
![image](https://user-images.githubusercontent.com/78299104/107927816-c9101d80-6f77-11eb-9358-6b58b90679c4.png)

It would be great if you can hep me with an approach of a solution.

best regards
Andreas

**Comment by Myddleware** [comment]
Hi Andreas,

You can't send order into ERPNext without order items. So in your case you have to create a rule between the Prestashop module "Order detail" and the ERPNext module "Items". Keep this rule disable, it will never run by itself.

Then edit again your order rule and, in the relationship tab, you should have a "parent relationship section", below standard relationship. Select you item rule by selecting the order field.

Then when you wil run you rule order, Myddleware will search for all order lines (order details) for the current order, it will create the data transfer for all items and linked them to the order rule. Then Myddleware will merge all these data transfer (order and items) and send it to ERPNExt in one call. 

Please let me know if it helps.

**Comment by userGitHub75334** [comment]
Thank you for your advice and your help.
I think without your help there is no chance of implementing a working solution.
I am a small step further with the definition below.
![image](https://user-images.githubusercontent.com/78299104/108176635-95153380-7102-11eb-9e70-e619379b16b4.png)

The try and error method takes a long time, but Myddleware is a great tool when the settings are correct.
It would be helpful if there was a document showing the key fields and relationships of the Myddleware modules used. With this information we would save time and could set up a well-functioning data exchange solution between Prestashop and erpNext.

I hope I was able to give some of my experience back to the community.
The next step is that I need to find the necessary and appropriate fields between Prestashop and ErpNext. I'm afraid that will take a long time.

Many Thanks
with best regards
Andreas

**Comment by Myddleware** [comment]
Hi @userGitHub75334 ,
Thanks for your feedback. You are right, we have to improve Myddleware's documentation. For now we are working on technical things with the Myddleware's upgrade (framework upgrade to Symfony3 to Symfony4).  But next step will definitely be the documentation.
Could you share you work by generating a template with all you rules once you have finished to configure Myddleware. 

To generate a temmplate, use this command : 
`php bin/console myddleware:generateTemplate <template_name> < descriptionTemplate> <rulesId> --env=background`

 -> template_name has to start by <source solution>_<target solution>_<your name> (for example : prestashop_suitecrm_customers_orders_products)
You can see all the current template here myddleware\src\Myddleware\RegleBundle\Templates

 -> rulesId  has to contain all the rules of the template you want to create separated by coma 

The template file will be generated in the directory myddleware\src\Myddleware\RegleBundle\Templates . Please share it on this topic.

Thanks.
