### ISSUE TITLE
Stop Task button doesn't do anything on Task view log

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#438]
![image](https://user-images.githubusercontent.com/74190794/107948310-f5d22e00-6f93-11eb-98d5-f5b98d750fb9.png)

**Comment by Myddleware** [comment]
Button fixed : 
![image](https://user-images.githubusercontent.com/11330301/108858470-7aecc100-75ec-11eb-950c-d87dcbb8a9b9.png)
