### ISSUE TITLE
urls after installation are broken + create_function() is deprecated

### ISSUE THREAD

**Issue by sezanzeb** [Myddleware/myddleware#439]
![image](https://user-images.githubusercontent.com/28510156/107951713-0933c800-6f99-11eb-84b0-d6ab37da7277.png)

**Comment by stlgaits** [comment]
Hi,

just go back to your folder URL and add /web/app.php and it should redirect you to your app.

Estelle

**Comment by sezanzeb** [comment]
yeah, that leads me to the login page. thanks

**Comment by sezanzeb** [comment]
I also get `Deprecated: Function create_function() is deprecated in /var/www/myddleware/var/SymfonyRequirements.php on line 551` on that page with both apache2 and nginx

with apache2 the url is `http://***.***.***.***/app.php`

**Comment by Myddleware** [comment]
Hi @sezanzeb . Yes there is a deprecated function. We are working on the next main Myddleware version (based on Symfony 4.4), create_function won't be used in this version. 
Thanks for your help.
