### ISSUE TITLE
compatbile HTTPS ? 

### ISSUE THREAD

**Issue by Alexandre17220** [Myddleware/myddleware#44]
Hi All,

I use MyddleWare to connect prestashop 1.6 over http to suitecrm with no problem.
But now, I must make another configuration to connect prestashop 1.7 over HTTPS to suitecrm and I can't create the connector because I have an error "Failed to login to Prestashop : Bad HTTP response".

Can I connect to the Prestashop Webservice with HTTPS ? or the problem is the version of prestashop not supported?

Thanks a lot,

**Comment by Myddleware** [comment]
Hi Alexandre,
Thanks for using Myddleware.

Myddleware supports Prestashop 1.7 so no problem with the version of Prestashop.

Could you check if your Prestashop API is properly enabled by opening the URL https://<your prestashop URL>/api/
You should have a box asking you to put you login and password. Put your API key in the login and leave the password empty, you should get something like that : 
![api_prrestashop](https://user-images.githubusercontent.com/11330301/29554369-214ee0d4-871f-11e7-9858-75308f6c3548.png)

Please let me know if you have this kind of page ? Thanks.

**Comment by Alexandre17220** [comment]
Thanks a lot, the problem is in prestashop..mode CGI not activated..
sorry.
Have a good day,

**Comment by Myddleware** [comment]
No problem Alexandre.
Thanks for your feedback.
Have a good day too.
