### ISSUE TITLE
Prestashop connector error : undefined index language line 810 in prestashop.php

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#441]
![image](https://user-images.githubusercontent.com/74190794/107962513-574fc800-6fa7-11eb-8671-4c2bbab13a7b.png)
Record : 
![image](https://user-images.githubusercontent.com/74190794/107962619-73536980-6fa7-11eb-9014-a013f08aded5.png)

**Comment by Myddleware** [comment]
@EstelleMyddleware could you try again ? 
Thanks.
