### ISSUE TITLE
Add button & input to simulate rule on specific record (like in 2.5.7a)

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#443]
Need to add something similar to this to allow users to simulate a rule on a specific record : 
![image](https://user-images.githubusercontent.com/74190794/107965298-a77c5980-6faa-11eb-819b-5a4bf32b43ca.png)
but instead, there should only be one button, and if the input is left empty then it runs the default simulation

**Comment by Myddleware** [comment]
Buttons have been added : 
![image](https://user-images.githubusercontent.com/11330301/110049266-cd974d00-7d51-11eb-94a0-7b05c2193029.png)
