### ISSUE TITLE
ERROR : Undefined index date_ref in solution.php line 345

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#448]
Transfer in error here : 
![image](https://user-images.githubusercontent.com/74190794/108208545-75453600-7129-11eb-857f-97c430bd6fb1.png)

![image](https://user-images.githubusercontent.com/74190794/108208605-8726d900-7129-11eb-84d4-1b4bbdc2979b.png)

Rule mapping for this transfer : 
![image](https://user-images.githubusercontent.com/74190794/108208677-a160b700-7129-11eb-9627-27fc6528e31e.png)

**Comment by stlgaits** [comment]
![image](https://user-images.githubusercontent.com/74190794/108208854-da992700-7129-11eb-8b77-891d23c28ded.png)

**Comment by Myddleware** [comment]
Search duplicate doesn't generate error anymore : 
![image](https://user-images.githubusercontent.com/11330301/108253111-b35a4e00-7159-11eb-8d8e-64950ce71475.png)
