### ISSUE TITLE
Bug on NotificationManager.php constructor  line 125

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#450]
This was sending a request from constructor. I've commented it as it was causing issues on every single command line (it was loaded and was trying to connect to users table, even when the database isn't connected yet), but it needs to be initialised in a different way here : 

`$this->setEmailAddresses();`

It needs to be replaced by something else.

**Comment by Myddleware** [comment]
Bug fixed, we changed the position of the method setEmailAddresses
