### ISSUE TITLE
User Deprecated: The "Doctrine\Common\Inflector\Inflector::classify" method is deprecated and will be dropped in doctrine/inflector 2.0. Please update to the new Inflector API.

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#451]
This error is triggered when running doctrine:fixtures:load  
![image](https://user-images.githubusercontent.com/74190794/108377886-c413ce00-7204-11eb-870a-813eda181edb.png)

**Comment by stlgaits** [comment]
https://github.com/symfony/symfony/issues/38121

**Comment by Myddleware** [comment]
We have changed the way to create fixtures (see commit https://github.com/Myddleware/myddleware/commit/7d7c22b160cd6c3d2eb8d9a4163152d79b5ab4d3)
