### ISSUE TITLE
PHP 7.4.14 Install Fails

### ISSUE THREAD

**Issue by V0RTX** [Myddleware/myddleware#452]
Fails to install, are there workaround for this.  Other apps depend upon php, not so easy to change versions

**Comment by V0RTX** [comment]
Found a way to download the plugin

**Comment by Myddleware** [comment]
Hi @V0RTX ,
We were about to reply to you.  
Myddleware isn't compatible 2.x php7.4. But let us know how you have done if you found a way to make it works with php 7.4.
Thanks.

For information, we will launch Myddleware 3.0 based on Symfony 4.4  in March. This version will be compatible php7.4 et we do our best to make it compatible with php8 as well.

**Comment by V0RTX** [comment]
@Myddleware 
Hello, thanks for your answer.  
I found the php error with the cli install of Myddleware.  Now I downloaded the Myddleware/Moodle plugin zip file and imported into Moodle without errors so far. 
Not much information around on configuring Myddleware as a plugin in Moodle.   From what I have found so far I am still the process of configuring the parameters in Moodle.  
One thing is that I cannot find the URL for web interface for configuring Myddleware.  
Also still working on the API configuration in Magento. 
Your reply is timely if you can explain to me.  I will really appreciate it.
Maybe as you say I will need to wait for your next release.
I will reopen the case.
Thank you.

**Comment by stlgaits** [comment]
Hello V0RTX,
you've installed Myddleware plugin for Moodle but have you finished installing Myddleware on its own as well? Because the plugin won't be able to work without Myddleware installed.

**Comment by stlgaits** [comment]
By the way Myddleware does not have to be installed on the same server as Moodle. If you want to install it on a different server that is absolutely fine :)

**Comment by V0RTX** [comment]
Ok, I understand.  Didn't realise both are needed.  Well yes in that case, I will need to wait for the next version as at the moment I have just one server.  I'm a startup and don't have the resources to run 2 servers until we grow a bit.
Thanks for your quick response.

**Comment by stlgaits** [comment]
In that case, I think 2 options are available to you for the time being. 

- you can either host Myddleware for less than 10€ a month, for example on PlanetHoster
- or you can host Myddleware locally on your machine, in which case you would either have to execute your rules manually or create a Windows task which will execute Myddleware for you

**Comment by V0RTX** [comment]
Ok, thanks so much.  Yes, I think hosting on my local machine at the moment.  No problem with PlanetHoster or the like, it's just at the moment I'm evaluating Moodle vs Google Workspace.  I'm leaning toward Moodle as I worked with it some years ago and the connection between Magento and Moodle is the attraction.  
Are you able to point me to the resource for hosting on Win10 machine so I can continue the eval?  If it seems what I'm looking for I may move to a hosting site for further eval.
Thanks :)

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue, now myddleware is compatible up to php 8, but do not hesitate to re-open it if needs be.
Thanks.
