### ISSUE TITLE
When Error_Sending, there is not enough info displayed (tested with Prestashop)

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#453]
![image](https://user-images.githubusercontent.com/74190794/108824660-45cb7900-75c2-11eb-9c7e-bbda4695fba8.png)
The error below should be displayed in Myddleware : 
![image](https://user-images.githubusercontent.com/74190794/108824773-67c4fb80-75c2-11eb-8438-adbf3dcf2dc9.png)

**Comment by Myddleware** [comment]
Error is now displayed : 
![image](https://user-images.githubusercontent.com/11330301/109689689-db987280-7b85-11eb-9478-122feac46816.png)
