### ISSUE TITLE
A Fancybox strange problem block me to save rule

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#454]
Fancybox library infers with saving the rules
```
<input class="btn-mydinv" id="validation" type="button" value="Confirm">
```
still no working if I click directly with mouse but if I type this command in developer console it trigger the save procedure

![Workspace 1_030](https://user-images.githubusercontent.com/472171/109284734-76a8e980-7820-11eb-8cf3-00e2b29c6f73.png)

![Workspace 1_031](https://user-images.githubusercontent.com/472171/109284868-a0faa700-7820-11eb-8cfa-afa0834168dc.png)

In this case Fancy triggers the modal and overlay before save, this is the problem

![Workspace 1_032](https://user-images.githubusercontent.com/472171/109285099-edde7d80-7820-11eb-9fdb-3b4246fc9bf9.png)

@EstelleMyddleware @simonetravaglini

**Comment by stlgaits** [comment]
Hello @francescobianco , may I ask what version of Myddleware you are using ? I tried to reproduce the problem in 2.5.7 but couldn't.

**Comment by CamillePMyddleware** [comment]
Hi,  I am archiving  this issue, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be.
Thanks
