### ISSUE TITLE
Strange empty Duplicates field selector

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#455]
We have many rule with strange RED and not clear duplaces field value

![Workspace 1_033](https://user-images.githubusercontent.com/472171/109285998-08652680-7822-11eb-8db8-0811eed9a18c.png)

It not keep the status after save

@simonetravaglini

**Comment by Myddleware** [comment]
Hi @francescobianco ,
Yes your are right, this RED bug is displayed when there is no duplicate field for the application's module selected. 
We will fix this.
Thanks.

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue but please do not hesitate to re-open it if needs be.
Thanks
