### ISSUE TITLE
no template for prestashop <-> suitecrm

### ISSUE THREAD

**Issue by Alexandre17220** [Myddleware/myddleware#46]
Hi,
I haven't nothing when I click on "default template selection".
![image](https://user-images.githubusercontent.com/7665521/29565806-c0d9e7de-8747-11e7-9904-8b0d16ccc42c.png)
Why ? on my test vmware I have : 
![image](https://user-images.githubusercontent.com/7665521/29565837-e7a709dc-8747-11e7-90ac-d522e230508f.png)

Thanks a lot,

**Comment by Alexandre17220** [comment]
same version of mydlleware on the both machine

**Comment by Myddleware** [comment]
Hi Alexandre,
Could you tell me if you have the file prestashop_suitecrm_customers_orders_products.yml in the directory <Myddleware>/src/Myddleware/RegleBundle/Templates ; and if the web user (eg  : www-data) has the right to read this file ? 
Have a nice day.

**Comment by Alexandre17220** [comment]
Hi,
Yes I have it, and permissions are ok (the same of all the directory of your system) 
group : apache
owner : apache
permissions 0775

**Comment by Alexandre17220** [comment]
I have a "https://XXXXX:81/liaison/web/app.php/rule/list/template/" failed to load resource : the server responded with a status of 500 (internal server error)

**Comment by Myddleware** [comment]
This is weird, so let's debug a bit ;)

Could you change the method getTemplates in the file <Myddleware>/src/Myddleware/RegleBundle/Classes/template.php (I have only added the print_r for the debug)

```
public function getTemplates() {
	$templates = '';
	// Read in the directory template, we read files  corresponding to the selected solutions
	foreach (glob($this->templateDir.$this->solutionSourceName.'_'.$this->solutionTarget.'*.yml') as $filename) {
		$template = \Symfony\Component\Yaml\Yaml::parse(file_get_contents($filename));
		$templates[] = $template;
	}
echo '<pre> DEBUG : display template ';		
print_r($templates);		
echo '</pre>';		
	return $templates;
}
```


The can you go back to the rule creation. Do you have this array displayed ?
![template_debug](https://user-images.githubusercontent.com/11330301/29567784-8b478a20-874e-11e7-9806-a2379a263ad7.png)

Thanks.

**Comment by Alexandre17220** [comment]
Hi I haven't the debug test but if I make this :
`public function getTemplates() {
		$templates = '';
		
		// Read in the directory template, we read files  corresponding to the selected solutions
		/*
		foreach (glob($this->templateDir.$this->solutionSourceName.'_'.$this->solutionTarget.'*.yml') as $filename) {
			$template = \Symfony\Component\Yaml\Yaml::parse(file_get_contents($filename));
			$templates[] = $template;
		}
		*/
		echo 'ZZz:'.$this->templateDir;
		echo '<pre> DEBUG : display template ';
		print_r($templates);
		echo '</pre>';
		return $templates;
	}`
I have :"
![image](https://user-images.githubusercontent.com/7665521/29568316-40e1b15c-8750-11e7-930e-980ae9cefe97.png)
"

**Comment by Myddleware** [comment]
OK so the erreur seems to come from the code you put in comment.
Could you tell me what is your php version in this server ? Is this the same version as on the previous server?
Could you log to Myddleware by changing app.php by app_dev.php ? You will maybe have more information about the error 500.

**Comment by Alexandre17220** [comment]
no, I found,
_file_get_contents() make the error._. I debug it, one moment please
php 7, no the two server are different php's version

**Comment by Alexandre17220** [comment]
The problem in comment the solution :
`public function getTemplates() {
		//$templates = '';
		$templates = array();`

**Comment by Myddleware** [comment]
Thanks you very much Alexandre.
You 're right the variable initialisation is different in php7, we need to put the right type. 
I have added the fix in the develop branch, it will be in the next release.
Thanks for your contribution ;)
Have a nice day

**Comment by Alexandre17220** [comment]
no problemo
have a good day
