### ISSUE TITLE
SuiteCRM - Existing records don't sync when a new security group is added (for user of the new security group)

### ISSUE THREAD

**Issue by fosullivan-usam** [Myddleware/myddleware#463]
When using a SuiteCRM connector with a user that is part of a Security Group, if a record (e.g., Account or Contact) existed in SuiteCRM before being added to that Security Group, Myddleware does not sync that record.

How to recreate:
1. Create two Security Groups, one called Existing and one called New.
2. Create a User called Sync-Test that is only part of the group called New.
3. Create a new Account called Test-Account under the Security Group called Existing.
4. Set up and run a rule to synchronize all Accounts using a connector that is logged in as the user Sync-Test.
5. Now add the Test-Account to the Security Group called New.
6. Run the Account sync rule again - it will NOT copy over the Test-Account.
7. If you change any field in the Test-Account (presumably, so the Last Modified Date changes), then the rule WILL copy the Test-Account.

Expected behavior:
Myddleware should recognize that there is a new account available to that user.  Maybe it could run a check at the end, to compare how many Accounts are on each 'side' and notice the new one.

**Comment by Myddleware** [comment]
Hi @fosullivan-usam ,
I see what's your problem. Unfortunately, when you add a security group on an account in SuiteCRM, this account isn't modified. So Myddleware can't detect the modification. Developping the comparaison you wrote would be a specific code only for you and would take several days of work.

I see 2 other solutions : 
 - If the number of account isn't too large, you could set the reference date far in the past for your account's rule once a week for example (or once a day), So Myddleware would read again all accounts available for the specific user. The missing ones would be sent. You could automate this by running a query in your Myddleware database using a command in a crontab.
 - Another solution would be to develop a small workflow in SuiteCRM (logic hook after_relationship_add) to make a dummy change on the account each time a security group is added to an account. With this, Myddleware will read the account with a new group.
Hope it helps.
Have a nice day.

**Comment by fosullivan-usam** [comment]
We took your second suggestion and will let you know if we encounter any other problems.
Thank you!
