### ISSUE TITLE
use myddleware to update prestashop stock ?

### ISSUE THREAD

**Issue by Alexandre17220** [Myddleware/myddleware#47]
Hi all,
I have a question, is it possible to use myddleware for update product's stock in prestashop ?
actually I use it to :
prestashop -> suitecrm (order,customer,product ...)
but I want update prestashop stock when I add product in stock in suitecrm.
Thanks a lot,

**Comment by Myddleware** [comment]
Hi Alexandre,
You can try to add your module (in your case stocks, stock_movements or stock_availables I guess) in the array $authorized in the file myddleware\develop\src\Myddleware\RegleBundle\Solutions\prestashop.php line 167.
For now we have just added the modules we have tested, however the other modules should work too.

If you modify the Prestashop file and it open a new feature, please share with us your modification.
Thanks
