### ISSUE TITLE
When clicking 'reload the document' or 'rerun the same record' message says 'no task ID given'

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#474]
![image](https://user-images.githubusercontent.com/74190794/111280539-42189880-863c-11eb-892b-b558a7b9b02d.png)

**Comment by stlgaits** [comment]
This is what I get when trying to cancel a document in error
`console.ERROR: Error thrown while running command "myddleware:massaction cancel document "6058a64a909321.75720676" Y --env=dev". Message: "Notice: Undefined index: job" {"exception":"[object] (ErrorException(code: 0): Notice: Undefined index: job at ....myddleware\\src\\Command\\MassActionCommand.php:104)","command":"myddleware:massaction cancel document \"6058a64a909321.75720676\" Y --env=dev","message":"Notice: Undefined index: job"} []`

**Comment by stlgaits** [comment]
https://github.com/Myddleware/myddleware/issues/475
https://github.com/Myddleware/myddleware/issues/474
https://github.com/Myddleware/myddleware/issues/486
 These issues are linked

**Comment by stlgaits** [comment]
This issue is still going on, after clicking on rerun / cancel / reload and then on the message above 
![image](https://user-images.githubusercontent.com/74190794/117990867-db62e300-b33d-11eb-8ad5-9d639c84f89b.png)

log :
 [2021-05-12 14:11:45] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "App\Entity\Job object not found by the @ParamConverter annotation." at ........\myddleware\vendor\sensio\framework-extra-bundle\src\Request\ParamConverter\DoctrineParamConverter.php line 107 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): App\\Entity\\Job object not found by the @ParamConverter annotation. at ...........\myddleware\\vendor\\sensio\\framework-extra-bundle\\src\\Request\\ParamConverter\\DoctrineParamConverter.php:107)"} []
![image](https://user-images.githubusercontent.com/74190794/117990705-b1a9bc00-b33d-11eb-97ee-29b591346192.png)

**Comment by Myddleware** [comment]
@EstelleMyddleware , I can't reproduce this issue. These 3 buttons work properly on my side. Could you try again ? 
If you can reproduce, could you give me more detail about the document and its rule ? Thanks.

**Comment by stlgaits** [comment]
@Myddleware it's when you click on 'you just launched a new task' above that the error occurs

**Comment by stlgaits** [comment]
For example, I've generated a Woocommerce to Vtiger  rule using the template provided (so all mapping is from the template).
Some transfers are in error.
Here is a document example, it has the following error :
![image](https://user-images.githubusercontent.com/74190794/119683817-4505e580-be44-11eb-8f04-636510038617.png)
 

> Error: Request Failed! (Syntax Error on line 1: token girdgoj Unexpected COLUMNNAME(girdgoj), expected one of: SEMICOLON)Failed to search duplicate data in the target system. This document is queued. ..........\myddleware\src\Manager\DocumentManager.php Line : ( 939 )Status : Error_checking

When I click on 'run the same record', then on 'you've just launched a new task' above, I get the Symfony error 


Symfony\Component\HttpKernel\Exception\NotFoundHttpException
`App\Entity\Job object not found by the @ParamConverter annotation.`

For further context : 
the job has the following error 
![image](https://user-images.githubusercontent.com/74190794/119684489-d37a6700-be44-11eb-8b14-a75d8f029112.png)
![image](https://user-images.githubusercontent.com/74190794/119685152-687d6000-be45-11eb-8e94-7adb0f630313.png)

And not all transfers were in error on this rule 
![image](https://user-images.githubusercontent.com/74190794/119684893-2bb16900-be45-11eb-9752-6cc578c2c9f8.png)

**Comment by Myddleware** [comment]
@EstelleMyddleware , the error_checking are specific to the application. As we just want to test the button, could click on the button "Reload the document" on a document successfully sent ? If it works then there is no bug on this button anymore.
Then you can create another issue about the bug on this specific template and the child documents.
Thanks.

**Comment by stlgaits** [comment]
I'm not able to reproduce this error anymore so closing this issue.
