### ISSUE TITLE
App\Entity\Job object not found by the @ParamConverter annotation. when clicking on 'see details' after launching a new task

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#475]
![image](https://user-images.githubusercontent.com/74190794/111289767-c4598a80-8645-11eb-8ad6-e7e48efe9ab7.png)
![image](https://user-images.githubusercontent.com/74190794/111289859-dcc9a500-8645-11eb-9239-228530a1fa4b.png)

HTTPNotFoundException is thrown : 
App\Entity\Job object not found by the @ParamConverter annotation.

Previous SQL request log : 
`[2021-03-16 10:54:15] doctrine.DEBUG: SELECT t0.id AS id_1, t0.status AS status_2, t0.param AS param_3, t0.begin AS begin_4, t0.end AS end_5, t0.message AS message_6, t0.open AS open_7, t0.close AS close_8, t0.cancel AS cancel_9, t0.manual AS manual_10, t0.api AS api_11, t0.error AS error_12 FROM job t0 WHERE t0.id = ? ["0;Failed to create the "] []`

**Comment by stlgaits** [comment]
This comes back when changing to 	
`$this->message .= $this->tools->getTranslation(array('messages', 'rule', 'another_task_running')).';'.$job['id'];`
in JobManager.php line 326

**Comment by Myddleware** [comment]
Everything is working properly on my side. Could you test it again ? Thanks.

**Comment by stlgaits** [comment]
Unable to reproduce this bug now. Closing the issue.
