### ISSUE TITLE
doctrine:schema:update --force generates errors by trying to access config table before the DB is actually generated

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#479]
![image](https://user-images.githubusercontent.com/74190794/111485859-483f6f80-8737-11eb-9a02-911eb9ad4e9b.png)
The error is generated both in browser (install/database/connect) and in command line.
The error does not block execution as the database is eventually created, however it generates unnecessary messages which could confuse user.

**Comment by stlgaits** [comment]
Quite similar error occurs on install process with `yarn build` command 
![image](https://user-images.githubusercontent.com/74190794/116095519-c84ae480-a6a8-11eb-8c67-5bae656e15fa.png)

**Comment by stlgaits** [comment]
And on database/connect, still can't check whether config exists without triggering an error (same as first post)
![image](https://user-images.githubusercontent.com/74190794/116096196-5fb03780-a6a9-11eb-91fa-4366e267f3be.png)

![image](https://user-images.githubusercontent.com/74190794/116096091-45765980-a6a9-11eb-994c-57e4d0362162.png)

**Comment by Myddleware** [comment]
@EstelleMyddleware , I have fixed the issue, could you test on your side pease.
Thanks.
