### ISSUE TITLE
problem with session when edit rule

### ISSUE THREAD

**Issue by Alexandre17220** [Myddleware/myddleware#48]
Hi,
I try to create rule on a browser tab and look another on another tab (by editing the rule)...result when I
save the first rule, the second is modified.. certainly session problem.

So, now can I erase, purge my myddleware without reinstall in anoter directory an database ?
Thanks a lot

**Comment by Myddleware** [comment]
Hi Alexandre,
This a known bug and one of our developer is currently working on it. It will be fix in the next version. So, for now, we can't modify 2 rules in the same time.
To purge your myddleware, you can truncate
 - tables documents, documentsData, documentsAudit, Log and Job if you only want to delete data and keeping your rules.
 - tables Rule, RuleAudit, RuleField, RuleFilter, RuleOrder, RuleParam and RuleRelationShip if you want to delete all the rules you have created too
 - tables Connector and ConnectorParam if you want to delete you connectrs as well.
Have a nice day.
