### ISSUE TITLE
How to add orders with product not sync

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#480]
Hi,
how I can manage this situation.
I import orders from a DB to Vtiger. Orders lineitems have products with a product code that is the same of vtiger one. But I don't have a table of products in DB to generate first rule that then I use to link products to lineitems.
There is a smart way to manage this situation?

**Comment by Myddleware** [comment]
Hi Simone,
I see 2 ways to do this : 

1. Create a custom code that get the product id using the product code for all line items before sending the order to Vtiger. You can redefine the funtction checkDataBeforeCreate in Vtiger connector to do that.
2. Create a second rule for product based on your Orders lineitems table in your DB as the source module. The target module would be the product. You will have to add a duplicate field code into this rule (the duplicate field doesn't exist yet but we can add it in a hotfix version). So this rule will read all your Orders lineitems and link them to a Vtiger product based on the product code.  Then, on your first rule that send the orderlines items (the one linked to the order module), add the relationship between the Orders lineitems Id (first field in the list), your second rule and the target field product ID.

Let me know the solution you choose. If it is the second one we will add the code as a duplicate field on the product module.
Have a nice day.

**Comment by simonetravaglini** [comment]
Hi,
in case of second choice, can I do a rule from Vtiger to Vtiger on product or need to do from DB to Vtiger?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
You need a rule DB to Vtiger. Myddleware need the correspondance between each orderline item ID and product Id.

**Comment by simonetravaglini** [comment]
@Myddleware shuold I use:
retrivieng existing data or  create and update? (only update it's not available)

**Comment by Myddleware** [comment]
@simonetravaglini ,
You should use retrieving data as your line item product in your source application shouldn't create any product into your target application.
Have a nice day.
