### ISSUE TITLE
Prestashop connector has a BAD REQUEST issue linked to PrestashopWebservice 

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#482]
Following on initial issue https://github.com/Myddleware/myddleware/issues/466 

https://github.com/Myddleware/myddleware/commit/3f035c087b36a0ec901e98b7baeb3e41491149cf
https://github.com/Myddleware/myddleware/commit/846c0e7441a97cf55de0e57505656440aacadaae

**Comment by Myddleware** [comment]
The problem comes from our Prestashop instance 1.7.7. We have the same issue with Myddleware 2 and no issue with Prestashop 1.7.0 with Myddleware 2 and 3

**Comment by stlgaits** [comment]
Actually, even with 1.7.0, the problem persists. We're able to create rules, but as soon as we run them, we get this error 400 bad request thrown by PrestashopWebservice.php and we're therefore unable to read any data from Prestashop. I've attempted to change this 
![image](https://user-images.githubusercontent.com/74190794/117988024-4f4fbc00-b33b-11eb-9600-3a5b9e4f06d2.png)
to correct this error  
![image](https://user-images.githubusercontent.com/74190794/117988111-65f61300-b33b-11eb-8355-1a7c94fe1407.png)

to the following
![image](https://user-images.githubusercontent.com/74190794/117988155-70181180-b33b-11eb-8c87-64785335363f.png)

on every occurence, but even though I don't get the VSCode error message, the same result occurs (400 Bad Request)
![image](https://user-images.githubusercontent.com/74190794/117988808-0815fb00-b33c-11eb-8725-25e2256c58c3.png)

What is actually very strange is that I never get any records, it's always on 0 despite the fact that I can see multiple records in Prestashop (I've set different dates far in the past with no difference).

**Comment by Myddleware** [comment]
@EstelleMyddleware , good news, it isn't a bug. Prestashop 1.7.7 wasn't working properly because our test server was in php version 7.4 and Prestashop 1.7.7 is compatible PHP 7.1, 7.2 and 7.3, not 7.4. I have changed the php version and Prestashop 1.7.7 is working properly with Myddleware.
