### ISSUE TITLE
Woocommerce simulation returns no results

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#485]
![image](https://user-images.githubusercontent.com/74190794/112009349-96cd7f00-8b26-11eb-9669-2d3e9a444102.png)
There should be at least 3 transfers for my rule Woocommerce Products to Vtiger but I get none, be it when running simple simulation or specific simulation with an ID.

**Comment by Myddleware** [comment]
@EstelleMyddleware , could you test that everything works properly now ? Thanks.
