### ISSUE TITLE
ERROR when clicking 'cancel documents' (for superadmins)

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#486]
![image](https://user-images.githubusercontent.com/74190794/112010058-3ee34800-8b27-11eb-9921-fddee10abc82.png)
And the URL generated is completely wrong (the message is sent instead of the jobID) : 
![image](https://user-images.githubusercontent.com/74190794/112010179-5e7a7080-8b27-11eb-9b79-fe13881ad6ff.png)

**Comment by Myddleware** [comment]
@EstelleMyddleware , it should be fixed now. Could you test ? Thanks.
