### ISSUE TITLE
Manually set LAST RUN to DEFINE time to start in daily RULES

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#488]
Manually set LAST RUN to DEFINE time to start in daily RULES (for JOB)

I require an easy way to set the exact time to start a RULE every day, If I set 1440 is good but LAST  RUN depends by my first manyal execution.

![Clipboard - 25 marzo 2021 15_46](https://user-images.githubusercontent.com/472171/112493507-84e81800-8d82-11eb-9383-a0161e54cbfb.png)

@simonetravaglini

**Comment by Myddleware** [comment]
Hi @francescobianco ,
Sorry I didn't understand what you would like. "Last run" should contain a date ? 

For information, when we need to run a specific rule at a specific time, we set up directly the crontab whith the command : 
`php bin/console myddleware:synchro <your rule id> --env=background`
Maybe it could help.

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be. 
Thanks.
