### ISSUE TITLE
php app/console myddleware:synchro ALL  --env=background don't work

### ISSUE THREAD

**Issue by Alexandre17220** [Myddleware/myddleware#49]
Hi All,

So, I have reinstall mydllware (delete directories, delete database before).
Now when I do
`php app/console myddleware:synchro ALL  --env=background`
I have :
`1;599fda91410c04.58488510` and nothing is transfered
But when I make :
` php app/console myddleware:synchro 599d94e655baa --env=background`
I have :
`1;599fda91410c04.58488510
599d94e655baa
1-599d94e655baa : Synchronisation de la rÃ¨gle : 599d94e655baa
2-599d94e655baa : Create documents.
2-599d94e655baa : Number of documents created : 0
`
Why ? there is cache file in anothers directories ?

Thanks a lot,

**Comment by Alexandre17220** [comment]
before reinstall (reinstall need by a session bug previously ) all work correctly

**Comment by Alexandre17220** [comment]
I find :
function getRules return nothing if you use simply a template and no presonnal rules
because  table "RuleOrder" is empty andthe request  "SELECT name_slug 
							FROM RuleOrder
								INNER JOIN Rule
									ON Rule.id = RuleOrder.rule_id
							WHERE 
									Rule.active = 1
								AND	Rule.deleted = 0
							ORDER BY RuleOrder.order ASC"
return nothnig,
You must create a personnal rule to regenerate the table RuleOrder.

**Comment by Myddleware** [comment]
Hi Alexandre,
You are too fast. Yes I was thinking aout this table RuleOrder. This table is refreshed each time we save a rule. But this refresh doesn't run after a template generation. So we will fix this bug.
A work around would be to simply edit and save a rule. It will init the table RuleOrder.
Is that working for you ? 
Thanks for all your feedback.

**Comment by Alexandre17220** [comment]
I have created a rule and all is back :-)
