### ISSUE TITLE
Scheduled run is slower

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#491]
Hi, if we run same task manually or scheduled we have different result in time need.
Manually we need 1.30h, scheduled 12h

seems that problem is related to transformation
![image](https://user-images.githubusercontent.com/6990139/112856309-efb19000-90af-11eb-9941-4e970242fa29.png)

**Comment by Myddleware** [comment]
Hi @simone, could you tell us how many records has been read for both tasks please ? 
Thanks.

**Comment by simonetravaglini** [comment]
7.000

**Comment by simonetravaglini** [comment]
@Myddleware as said 7000 record every time, and we need to reload all every night.

**Comment by Myddleware** [comment]
Hi @simonetravaglini , 
The function call when a task is executed from Myddleware UI is the same than the one executed by the scheduler. The only difference could be the php.ini (php version) that could be different between the task executed by a cran and a task executed by a browser. But it doesn't explain the different of task duration. 
Do you use a share server that could explain that the server's perfermance could be different during the night and the day ? 

For information, we know that the performance of Myddleware 2.X becomes bad when a task has more than 2 000 data transfer. In Myddleware 3, the performance won't slow down like this. But Myddleware 3 isn't launched yet ;(, we are in our last tests but we will need 2-3 weeks to finish.

**Comment by simonetravaglini** [comment]
@Myddleware hi, server should be not bad and is a dedicated server. We can't understand difference in performance if not related to the fact that are scheduled. I know about myddleware3, but we investigate to try to solve in present version...

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
I have another idea. When you run a task with the scheduler, it execute all active rules, not only one like with a manual execution.
So maybe, other rules has data transfer ready to send that will be added to the 7000 data transfer of your rule. So the task has more data transfer to send with the scheduler task. Even if it is just a few thousands more, it can make a huge difference.

Could you add a screenshot of your Myddleware scheduler : 
![image](https://user-images.githubusercontent.com/11330301/113058596-a09e5480-91ae-11eb-9c26-0313245b5c57.png)

And a screenshot of your linux crontab too. I will tell you what you could configure.
Thanks.

**Comment by simonetravaglini** [comment]
Hi @Myddleware 
we have only this rule active...
We confirm that if launched manually need 1h 30 min, scheduled 12h

**Comment by simonetravaglini** [comment]
![Clipboard - 31 marzo 2021 09_22](https://user-images.githubusercontent.com/6990139/113106102-a6258a00-9202-11eb-895b-8fc9bdcab838.png)

**Comment by Myddleware** [comment]
OK thanks @simonetravaglini ,
Maybe other job (rerun error for example) are running.
If you have only this rule active, could you set actve = false for both synchro job (2 first lines). Then in you crontab could you schedule this task : 
`php bin/console myddleware:synchro <your rule id> --env=background`

Please let me know if the task duration is 1h30 or more.
Thanks.

**Comment by francescobianco** [comment]
@Myddleware @EstelleMyddleware 

Unfortunately, even the execution of the rule placed in the CRONTAB did not have the speed we expected.
It take more than 10hours (for 10000 records)

@simonetravaglini @edoardobozolo

**Comment by Myddleware** [comment]
Hi @francescobianco ,
I am not surprised, performances of Myddleware version 2 becomes very bad after 2000 records read. It won't be the case with Myddleware 3, but this version isn't 100% ready yet.

We could think about another solution using offset as reference . We could set the limit of the rule to 1000 as it s recommanded with Myddleware 2. Then each time the rule runs, we would update the offset value. Then we will set the offset value (stored in the field reference date) to 0 each time the day changes.

Here is the scenario :
 - 1) Myddleware runs at 0:00 pm for example and read the first 1000 records, offset is set to 1000 in the reference date field
 - 2) Five minute after, at 00:05 am, Myddleware will read the record from 1000 (offet) to 2000 from your database, offset is set to 2000 in the reference date field
 -  3) Five minute after, at 00:10 am, Myddleware will read the record the next 1000 records from your database, offset is set to 3000 in the reference date field
 - 4) .... and so on until all records are read. 
 - 5) Then the next day, we will set back offset to 0 so all record will be read again

Please let us know if you want this solution and we will develop the custom code for you next week.
Have a nice day

**Comment by francescobianco** [comment]
@Myddleware It seems a working solution, at this moment we start to put in place this in our system. I hope it close the problem.

**Comment by Myddleware** [comment]
Hi @francescobianco ,
You mean that you are developing this solution ?

**Comment by francescobianco** [comment]
@Myddleware not sorry! I say that I adopting your suggested solution, no custom code or additional code is planned to do for this by my side

**Comment by Myddleware** [comment]
OK @francescobianco ,
We will try to provide a custom code with this solution. It could help other people with the sme problem.
We will come back to you this week.

**Comment by francescobianco** [comment]
@Myddleware very thanks for your support, deeply appreciate, I waiting your updates

**Comment by Myddleware** [comment]
Hi @francescobianco ,
Please upgrade to Myddleware 2.5.7j and create the file <myddleware directory>\src\Myddleware\RegleBundle\Custom\Classes\rule.php, add this code replacing < your rule id> by your rule id
```
<?php

namespace Myddleware\RegleBundle\Classes;

class rule extends rulecore {
		
	protected function readSource() {
		// Change the standard process for a specific rule
		if ($this->ruleId == '<your rule id>') {
			$currentDate = date('Ymd');
			// date_ref fieldformat => date (format Y-m-d) + '_' + offet
			// Get the date and offset from date_ref
			$parameters = explode('_', $this->ruleParams['datereference']);
			if (
					empty($parameters[1])			// If date_ref not properly formatted, we set date_ref far in the pas and offset = 0
				 OR $currentDate > $parameters[0]	// If the day has changed
			) {
				$this->offset = '0';
			} else {
				$this->offset = $parameters[1];	// Set the offset of the previous call
			}
			// Set a date far in the past as this date isn't used to filter data
			$this->ruleParams['datereference'] = '2000-01-01 00:00:00';
		}
		
		// Call standard function that read data
		$readSource = parent::readSource();
		
		// Format the date_ref with the current date and the offset
		if ($this->ruleId == '<your rule id>') {
			$this->dataSource['date_ref'] = $currentDate.'_'.($this->offset + $this->dataSource['count']);
		}
		return $this->dataSource;
	}
}
?>
```
You should have a reference field with this format : 
![image](https://user-images.githubusercontent.com/11330301/115760666-c24fbd80-a3a1-11eb-87ba-2d9f9349b3d8.png)

Please let me know if you have any problem.

**Comment by Myddleware** [comment]
For information, if one day your upgrade your instance to Myddleware 3 (not released yet), here is the code to add in the file \src\Custom\Manager\RuleManager.php : 

```
<?php

namespace App\Manager;

class RuleManager extends rulecore {
	
	protected function readSource() {
		// Change the standard process for a specific rule
		if ($this->ruleId == '<your rule id>') {
			$currentDate = date('Ymd');
			// date_ref fieldformat => date (format Y-m-d) + '_' + offet
			// Get the date and offset from date_ref
			$parameters = explode('_', $this->ruleParams['datereference']);
			if (
					empty($parameters[1])			// If date_ref not properly formatted, we set date_ref far in the pas and offset = 0
				 OR $currentDate > $parameters[0]	// If the day has changed
			) {
				$this->offset = '0';
			} else {
				$this->offset = $parameters[1];	// Set the offset of the previous call
			}
			// Set a date far in the past as this date isn't used to filter data
			$this->ruleParams['datereference'] = '2000-01-01 00:00:00';
		}
		
		// Call standard function that read data
		$readSource = parent::readSource();
		
		// Format the date_ref with the current date and the offset
		if (
				$this->ruleId == '<your rule id>'
			AND !empty($this->dataSource['count'])	
		) {		
			$this->dataSource['date_ref'] = $currentDate.'_'.($this->offset + $this->dataSource['count']);
		}	
		return $this->dataSource;
	}
}

?>
```

**Comment by francescobianco** [comment]
Thanks, @Myddleware , I will keep you updated with our syncronization performance

**Comment by francescobianco** [comment]
@Myddleware 
Unfortunately I bring bad news, despite the use of this new feature, the execution of the job with 11997 records has taken:

From 23/04/2021 at 05:05:33 to 23/04/2021 at 12:47:26

8 hours (2.4 seconds/records) 

our expectation was 3 hours atleast

**Comment by Myddleware** [comment]
Hi @francescobianco ,
Sorry I forgot to tell you to set a rule limit to 1000. So your job will run 12 or 13 times (depending on your records reference date) to read the 11 997 records. 
You can run the job every 5 minutes for example, in this case it should take only 1 hour.
Please keep me updated.

**Comment by simonetravaglini** [comment]
It works well

**Comment by Myddleware** [comment]
Thanks for your feedback @simonetravaglini
