### ISSUE TITLE
Escape is un-implemented

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#492]
In this class database.php the escape function is un-implemente it break any query with strange symbol like " ' " the "quote" symbol.

https://github.com/Myddleware/myddleware/blob/1aee1d7c88269caed104fe3b3e75e24cf9f4e8a9/src/Myddleware/RegleBundle/Solutions/database.php#L721

Our solution in MSSQL DB was symply but it works only for this type of DB
please provide a solution for MYSQL database or any kind of PDO based database

https://github.com/opencrmitalia-official/myddleware/blob/6278dda4c73c3d23452852d090c09e4b64caacaf/src/Myddleware/RegleBundle/Solutions/microsoftsql.php#L81

Thanks!

@simonetravaglini

**Comment by stlgaits** [comment]
Hello @francescobianco ,
I've tried to reproduce this issue with my local MariaDB 10.4.10 & MySQL 8.0.18 and there was no problem for me. Could you give me more details? What version of MySQL are you using? 
TIA
Here's the test transfers I  made : 
![image](https://user-images.githubusercontent.com/74190794/112958112-6b5c1d00-9142-11eb-9b5c-95648e9253a0.png)
![image](https://user-images.githubusercontent.com/74190794/112958200-84fd6480-9142-11eb-9e19-d91f9b42cbf3.png)

**Comment by francescobianco** [comment]
Hi @EstelleMyddleware could you please use MySQL as Target

**Comment by stlgaits** [comment]
Hi Francesco, I tried with MySQL as target and indeed there were problems, so I've taken the escape function from MSSQL and moved it to database.php and was able to transfer to and from MySQL  with special characters and '  '  . See my test below : 
![image](https://user-images.githubusercontent.com/74190794/113161271-83b16200-923e-11eb-9b73-06f28f899a8e.png)

So try with https://github.com/Myddleware/myddleware/pull/494 and hopefully it should now work

**Comment by CamillePMyddleware** [comment]
Hi,  I am archiving  this issue, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be.
Thanks
