### ISSUE TITLE
Problem with formula

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#493]
Hi,
i'm just using this formula:
{CRMCONTO} == "" ? {COD_CLIENTE} : {CRMCONTO}
but I got error 
Error : Invalid formula (failed to retrieve formula) : {CRMCONTO} == "" ? {COD_CLIENTE} : {CRMCONTO} /var/www/html/src/Myddleware/RegleBundle/Classes/document.php Line : ( 1286 )

If I use something like:
{CRMCONTO} == "" ? "hello" : {CRMCONTO}
I get no error.
What's wrong on my first formula?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
Did you add both fields ({COD_CLIENTE} and {CRMCONTO}) in the field list of the formula, like this : 
![image](https://user-images.githubusercontent.com/11330301/112998518-657c3100-916e-11eb-8331-2d903983d0c3.png)

**Comment by simonetravaglini** [comment]
@Myddleware thanks your tips solve the issues
