### ISSUE TITLE
Condition filter: is empty

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#495]
Hi,
could be very usefull hav in filter condition is empty / is not empty.
Why is missing? There is a way to set it with others conditions?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
You can set "is equal to" or "is not equal to" and leave the field on the right empty : 
![image](https://user-images.githubusercontent.com/11330301/113171777-1c001480-9248-11eb-92af-20694bad8a60.png)

It should work as you expect.
Hope it helps
