### ISSUE TITLE
woocommerce special char

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#497]
Hi special char from woocommerce products are transformed
![image](https://user-images.githubusercontent.com/6990139/113305019-e66c3180-9302-11eb-902c-a5066b519d85.png)
in this case - is transformed

**Comment by Myddleware** [comment]
Hi @simonetravaglini ;
I don't see any transformation between these 2 columns in Myddleware. So I guess what you have in your source (Woocommerce) isn't `[....] ONLINE &#8211; Accade[....]`
Could you just tell me what you have in Woocommerce and we will try to reproduce this issue. 
Thanks.

**Comment by simonetravaglini** [comment]
@Myddleware 
we have
Disegno e fumetto ONLINE - Accademia Kids

so &#8211; substitute -

**Comment by Myddleware** [comment]
Thanks @simonetravaglini 

I have tried to reproduce the issue but I can't. I have created a product with your product name : 
![image](https://user-images.githubusercontent.com/11330301/113942964-09ff1280-9802-11eb-89f8-57377ad1a04f.png)

In Myddleware, nothing is replaced in the product name : 
![image](https://user-images.githubusercontent.com/11330301/113943046-2c912b80-9802-11eb-896c-0430ee1e092b.png)

Could you help us to reproduce this issue ? For example, do you have any plugin that allows you to put html code in the produc name ? 
Thanks.

**Comment by simonetravaglini** [comment]
Hi,
I've give a deep look and correct name is:
Disegno base ONLINE – Accademia Kids
seems that – is different from - 
could be this char the problem?

**Comment by Myddleware** [comment]
Hi @simonetravaglini 
We still can't reproduce it : 
![image](https://user-images.githubusercontent.com/11330301/114038075-d95ebd80-9881-11eb-8fc7-6bb2f1f2b0b5.png)
This char seems to not be the problem.
Have a nice day.

**Comment by Myddleware** [comment]
Hi Simone,
Could you add a formula to convert your special characters ? Use the function like this : 
`htmlEntityDecode( {name}, ENT_NOQUOTES)`
![image](https://user-images.githubusercontent.com/11330301/114074808-15574a00-98a5-11eb-8520-c285a47d79a9.png)

Here is the result we get : 
![image](https://user-images.githubusercontent.com/11330301/114074943-3e77da80-98a5-11eb-8a02-6148102716d6.png)

Please let me know if it is OK for you too. Thanks.

**Comment by simonetravaglini** [comment]
thanks we check and let you know, could be a good solution!
