### ISSUE TITLE
Broken image link at rule creation

### ISSUE THREAD

**Issue by rulotec** [Myddleware/myddleware#498]
when you want to create a rule, you see this:

![image](https://user-images.githubusercontent.com/36896420/113809039-e8802700-972c-11eb-856e-d2d865cf7472.png)

If you take a look at the html source for the squares, you'll see this:

![image](https://user-images.githubusercontent.com/36896420/113809065-fc2b8d80-972c-11eb-9c26-0f44fb30372e.png)

I guess it's just a placeholder that's meant to have a src attribute once you select the concrete source, but the browser displays a broken image, which doesn't look nice.

**Comment by stlgaits** [comment]
Hello and thank you for your feedback,  you are right this is simply used to signify that you haven't yet selected a connector, once you do, the appropriate connector's image is displayed with an animation. I am not too sure what it could be replaced with, but if you have any suggestions please don't hesitate :)

**Comment by rulotec** [comment]
I guess you could use an actual image in the src attribute of the img tag. When selecting a source, just replace that src attribute. Another approach would be to use maybe a div instead of a img tag, and replace it once the source is clicked.
