### ISSUE TITLE
Problem in database source without 'date_ref' field

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#499]
We found this problem when try to sync from a MSSQL database table without 'date_ref'

```
Failed to create document (id source : 2682): 
An exception occurred while executing 'INSERT INTO Document (id, rule_id, date_created, date_modified, created_by, 
modified_by, source_id, source_date_modified, mode, type, parent_id) VALUES('606efccab96bb4.80952136','606efcc2dcad3','2021-04-08 12:53:30',
'2021-04-08 12:53:30','1','1','2682','2682','0','','')': 
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2682' for column 'source_date_modified' 
at row 1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php Line : ( 128 )
```
## How to reproduce

Source MSSQL or MySQL
```
CREATE TABLE A_Persone (
    PersonID INT,
    LastName VARCHAR(255),
    FirstName VARCHAR(255),
    Email VARCHAR(255),
    City VARCHAR(255)
);

INSERT INTO A_Persone (PersonID, LastName, FirstName, Email, City) VALUES (2682, 'Rossi', 'Mario', 'mario@rossi.it', 'Milano')
```

Target a Vtiger CRM in Contacts module

Mapped as follow
![Screenshot from 2021-04-08 15-00-45](https://user-images.githubusercontent.com/472171/114031032-40c53f00-987b-11eb-8565-a9d508f69ec3.png)

Confirmation with this
![Screenshot from 2021-04-08 15-01-35](https://user-images.githubusercontent.com/472171/114031149-62bec180-987b-11eb-8b1f-61ffea80899c.png)

## Pay attention to

- Use 'PersonID' as 'date_ref' field, because we no have better alternatives

## Important

The problem could be correlated to the impossibility of casting the value '2682' as a valid date value.

## How the error appear
![Screenshot from 2021-04-08 15-04-57](https://user-images.githubusercontent.com/472171/114031619-d52fa180-987b-11eb-91e0-e80bb8af1026.png)

@simonetravaglini

**Comment by Myddleware** [comment]
Hi @francescobianco ,
Sorry, I forgot your message. Yes it is a case that Myddleware doesn't manage.

Can you create a filed that is automatically updated everytime a record in your table A_Personne is modified : 
`ALTER TABLE `A_Personne` ADD `date_modified` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `date_modified`;`

We have already done that with SuiteCRM and you source application shouldn't be impacted.

And you could use this new field to detect an update in your source application because this field is updated each time you modify a record in this table.

Hope it helps.

**Comment by francescobianco** [comment]
Sorry @Myddleware 
This problem borns because we can't alter the source database adding the missing field.

What's the way when we have a "database source without 'date_ref' field"

@simonetravaglini

**Comment by simonetravaglini** [comment]
another issue related to this topic is that at the end of run the reference data have value of field 
![image](https://user-images.githubusercontent.com/6990139/115007992-e34c7600-9eaa-11eb-836f-dd6b39c6b971.png)

**Comment by Myddleware** [comment]
Hi @simonetravaglini  I undertsand.
We had the case in Prestashop : https://github.com/Myddleware/myddleware/blob/1f3f623c7774f6128aeae9d3b3337d2bcaa46a2b/src/Myddleware/RegleBundle/Solutions/prestashop.php#L694-L708

So what you could do is to force the date_modified for the record like that (upgrade safe method) : 
 - Create the file if it doesn't exist : 
 - Copy this code in the file : \myddleware\src\Myddleware\RegleBundle\Custom\Solutions\mysql.php
```
<?php
namespace Myddleware\RegleBundle\Solutions;

//Custom class
class mysql extends mysqlcore {
	// Redifine read function
	public function read($param) {
		$result = parent::read($param);
		// Change reference date for a specific rule
		if ($param['rule']['id'] == '<your rule id>') {
			$result['date_ref'] = (string)date('Y-m-d H:i:s');
		}	
		return $result;
	}
}
```
Please let me know if it works.

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
We found the bug and we have fixed it : https://github.com/Myddleware/myddleware/commit/629226f070f6c2b5103aa6e13c65fa5ccb72291c

**Comment by Myddleware** [comment]
Please install version 2.5.7h

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue but please do not hesitate to re-open it if needs be.
Thanks.
