### ISSUE TITLE
Mssql error with "00000" and not much more

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#500]
We have some problems with MSSQL database because when it get error show empty message, the only value exposed to the error message is a string with '00000'. As explained here this is a bad behavior of PDO 

- <https://stackoverflow.com/questions/11519966/pdo-sql-state-00000-but-still-error>

The suggested solution is based to the usage of different error handling

```
$this->pdo->setAttribute( PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION );
```

our solution is like this: 
```
$pdoDriverName = $this->pdo->getAttribute(\PDO::ATTR_DRIVER_NAME);
if ($pdoDriverName == 'dblib') {
  $this->pdo->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);
}
$exec = $q->execute();
if ($exec === false) {
  $errorInfo = $this->pdo->errorInfo();
  if (empty($errorInfo[2])) {
    $errorInfo[2] = '['.$pdoDriverName.':'.$exec.'] '.implode(', ', $errorInfo);
  }
  . . . .
```

https://github.com/opencrmitalia-official/myddleware/blob/b20adc047999be70b0db93997ea10ead441858e5/src/Myddleware/RegleBundle/Solutions/database.php#L408

I ask you the following:
- It is possible to switch PDO error handling among the entire solution instead of many pieces of code in spare places?
- Is possible to have a Versions table (reference) in which the base microsoftsql.php works well without any custom fix? (At this time we have customize: date/time processing, usage of lower-case/upper-case reference to INFORMATION_SCHEMA, custom error handling)

@simonetravaglini

**Comment by stlgaits** [comment]
Hello @francescobianco. and thank you very much for this. We will add your custom code to the standard very soon as we think it's a good solution for error handling. 

> Is possible to have a Versions table (reference) in which the base microsoftsql.php works well without any custom fix? (At this time we have customize: date/time processing, usage of lower-case/upper-case reference to INFORMATION_SCHEMA, custom error handling)

For your question about Versions table, I'm not sure I entirely understand what you mean. Could you give me more details & clarification about what you would like to do?

**Comment by francescobianco** [comment]
Sorry, by late response!
We hare looking for an official Database Compatibility Table related to Solutions, something like this

| Database Version        | Compatible           |  Limitations  |
| ------------- |:-------------:| -----:|
| Microsoft SQL 2008    | Yes | no limitation |
| Maria DB 10      |  Yes      |   no limitation |
| Microsoft SQL 2002 | No supported      |   -  |

**Comment by Myddleware** [comment]
Hi @francescobianco , 
@EstelleMyddleware will come back to you about this list.
Have a nice day.

**Comment by stlgaits** [comment]
Hello, 

Database Version | Compatible 
-- | -- 
Microsoft SQL 2008 | No
Microsoft SQL 2012+ | Yes 
Maria DB 10+ | Yes 
MySQL 5.6+  | Yes 

Let me know if you have any questions.

Kind regards
