### ISSUE TITLE
How to set a starting point for sync records

### ISSUE THREAD

**Issue by rulotec** [Myddleware/myddleware#502]
I'm copying fields from facebook to vtiger. I'ed like to be able to only import records created from a specific date onward. Let's say I'm starting today 13 April and I don't want to get records created before today.

In the filters step of the rule creation I can only filter based on the records that exist in my source and I don't have the creation date among those. What can I do?

![image](https://user-images.githubusercontent.com/36896420/114630541-748bd480-9c80-11eb-86a8-c9c97b5c0a6e.png)

**Comment by stlgaits** [comment]
Hello.
Even though your records do not have a creation date field, you can chose the date when you start reading the data from. 

- For this,  you must finish the process of creating the rule and save it. 
- Then, you click on that rule and you go to the parameters tab.
![Capture d’écran 2021-04-14 091253](https://user-images.githubusercontent.com/74190794/114669199-e8ba8c80-9d01-11eb-989b-14de29346621.png)
- There you will be given the option to chose a date to read from so chose your date

![Capture d’écran 2021-04-14 091310](https://user-images.githubusercontent.com/74190794/114669159-dfc9bb00-9d01-11eb-897e-8cd0a8dcf8ef.png)
- Don't forget to click on 'Save'
- Optionally you can click on 'Simulate transfers' to see how many records will be read from that date
- Then go back to 'Information' and click on 'Run the Rule' 

![image](https://user-images.githubusercontent.com/74190794/114669006-b315a380-9d01-11eb-8dfe-da4d80c174c8.png)

If you need more information, please have a look at this section of our tutorial https://myddleware.github.io/myddleware/#/basic_usage?id=rule-details

**Comment by rulotec** [comment]
Thaks a lot!
