### ISSUE TITLE
Deleted record Matrix

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#503]
This matrix is to explore the wide range of possibility to manage deletions of records

| Features | Source Database (discover) | Source Vtiger CRM (discover) | Target Database (apply deletion) | Target Vtiger CRM (apply deletion) |
| --- | --- | --- | --- | --- | 
| Hard Delete | ? | ? | ? | ? |
| Soft Delete with flag | ? | ? | ? | ? |

## Discover 

Discover stands for check if in the source there are deleted records
- Discover in "Hard Delete": Comparing Myddleware memory with source
- Discover in "Soft Delete": Use a field or status flag that define a existing records as deleted

## Apply deletion

Apply deletion stand for remove records from Target
- Apply deletion in "Hard Delete": Remove deeply the record from the target 
- Apply deletion in "Soft Delete": Apply deletion flag or move record in the RecycleBin, record is alive

**Comment by stlgaits** [comment]
Hello here is what is possible or not at the moment

Features | Source Database (discover) | Source Vtiger CRM (discover) | Target Database (apply deletion) | Target Vtiger CRM (apply deletion)
-- | -- | -- | -- | --
Hard Delete | No | No | Yes | Delete function called - don't know if it is hard or soft delete
Soft Delete with flag | Yes | No | Yes | Delete function called - don't know if it is hard or soft delete

**Comment by Myddleware** [comment]
Sorry we have updated the database connector recently

Features | Source Database (discover) | Source Vtiger CRM (discover) | Target Database (apply deletion) | Target Vtiger CRM (apply deletion)
-- | -- | -- | -- | --
Hard Delete | Yes | No | Yes | Delete function called - don't know if it is hard or soft delete
Soft Delete with flag | Yes | No | Yes | Delete function called - don't know if it is hard or soft delete

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue but please do not hesitate to re-open it if needs be.
Thanks.
