### ISSUE TITLE
Filter on a source field not mapped

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#506]
Hi,
frequently I need to filter record of source basing on a field of source that is not mapped.
Becouse not mapped it's not available on filter step.
There is a workaround to manage these situations?

**Comment by Myddleware** [comment]
Hi Simone,
Yes there is a workaround, you can map the field without using it. For example, if I want to filter on "deleted" field without mapping it, you can add it with another field (here last_name) but but only last_name in the formula : 
![image](https://user-images.githubusercontent.com/11330301/114867950-aa9e9500-9df5-11eb-9f0c-ac27f1deb100.png)

The you will be able to filter on deleted field : 
![image](https://user-images.githubusercontent.com/11330301/114868059-cefa7180-9df5-11eb-86fb-7e426727d4eb.png)

Hope it helps.
