### ISSUE TITLE
Massive import of invoice with lineitem 

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#510]
Hi, 
one question.
I've to import >100k invoices from DB to Vtiger
I've 2 separate rule for head and lines
Suppose i schedule every run 1000 record.
For head I think no problem
For inventory line my question is: if I've 50 line in same invoice, and these lines are 25 from 975 to 1000 in one run of scheduler, what will happen? that other 25 lines when run in second run of scheduler delete first 25 lines? Or there is a control to get all lines from same invoices?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
I guess your invoice lines have their own IDs. If yes, Myddeware will never replace a invoice line by another invoice line in Vtiger. The 25 other lines will be read during the next run. 

In the case all your invoice lines have the same reference date, they will always be sent in the same call. In this case, for your example, only 975 lines will be send in the first call, then the 50 lines will be sent during the next call.

Please let me know if I am not clear.

**Comment by simonetravaglini** [comment]
ok seems ok!
