### ISSUE TITLE
Id with special char

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#511]
Hi need an help to understand how to manage this situation.
I import head of orders:
![image](https://user-images.githubusercontent.com/6990139/115362668-10a66600-a1c2-11eb-8e6f-2bd44c90046a.png)
As you can see id code in Db is something like:
0002\A 19\20210416114446\1
then Id of myddleware become:
0002A 19202104161144461

I face the problem when I need to "connect" line with head, becouse line have saved Id of head in this form:
0002\A 19\20210416114446\1 that not match with 0002A 19202104161144461
so I get this error:
No data for the field IDDocumento in the rule isell2crm_righe_ordini. Failed to check document related : Failed to retrieve a related document. No data for the field IDDocumento. There is not record with the ID source 0002\A 19\20210416114446\1 in the rule test testate. This document is queued. /var/www/html/src/Myddleware/RegleBundle/Classes/document.php Line : ( 705 )Status : Relate_KO

Have you an idea how to manage this situation?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
We will try to reproduce this issue and we come back to you.

**Comment by simonetravaglini** [comment]
@Myddleware Hi, did you check? maybe there is a workaround?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
We have reproduce the issue.  We will try to fix it today.
We 'll keep you updated.

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
We have fixed the issue and merge it into master. You can upgrade to Myddleware 2.5.7i.
