### ISSUE TITLE
woocommerce add custom fields

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#512]
Hi,
in woocommerce you show us how to retrieve custom fields from orders:

protected $customFields = array( 'orders' => array('billing_first_name', 'billing_last_name', 'billing_company', 'billing_cf', 'billing_piva', 'sdi', 'pec', 'billing_email', 'billing_phone', 'billing_country', 'billing_address_1', 'billing_address_2', 'billing_pv', 'billing_state', 'billing_postcode'));

If we need to add also in mep_event_attendee how we have to modifiy code?

Thanks

**Comment by stlgaits** [comment]
Hello Simone,
I've modified the code a little bit to allow you to add custom fields to metadata.
With this new code you simply need to create a custom medata file at src/Myddleware/RegleBundle/Custom/Solutions/lib/wordpress/metadata.php
and add the code for your custom field, for example : 
```
<?php 

$moduleFields['mep_event_attendee']['my_custom_field'] = array(
                                                                'label' => 'My custom field', 
                                                                'type' => 'varchar(255)', 
                                                                'type_bdd' => 'varchar(255)', 
                                                                'required' => 0
                                                            );
```
And your custom field should then appear in your mapping : 
![Capture d’écran 2021-04-22 092831](https://user-images.githubusercontent.com/74190794/115673641-25fbcb80-a34d-11eb-9dfd-1cdaf0dc5147.png)

I've pushed these changes to hotfix branch and they should be merged into master branch at the end of the day today.

**Comment by Myddleware** [comment]
@simonetravaglini , if you want to add a custom field, you will need to upgrade myddleware to version 2.5.7i.
Have a nice day.
