### ISSUE TITLE
Myddleware migration to AWS

### ISSUE THREAD

**Issue by Yuvarajsfcloud** [Myddleware/myddleware#513]
Hi Team, 

Currently we have hosted our myddleware on our private server which we are planning to move it to AWS. we would like to migration steps for the same. 

Tried to search across every forum , couldn't get hold of any information. we would like to retain all the history & context from the older server. 

Please provide your suggestion

**Comment by Myddleware** [comment]
Hi @Yuvarajsfcloud,
Myddleware use symfony framework. Please follow these steps : 
 - Copy your Myddleware dorectory to the new server
 - Copy your database if you want to change the location of your database too
 - Change the file <myddleware directory>\app\config\parameters.yml  (parameter to be changed : database_host, database_port, database_name, database_user and database_password)
 - Clear the cache by removing the directories : 
   - <myddleware directory>\var\cache\prod
   - <myddleware directory>\var\cache\background

Please let me know any question.

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue but please do not hesitate to re-open it if needs be.
Thanks.
