### ISSUE TITLE
Invalid usage of the option NEXT in the FETCH statement

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#517]
We have some Microsoft databases with this problem

-----
Reading Issue: Error : SQLSTATE[HY000]: General error: 20018 Invalid usage of the option NEXT in the FETCH statement. [20018] (severity 15)
------

Releaved int simulation

```
SELECT [a], [b] FROM [my_table] ORDER BY [date_ref] ASC OFFSET 0 ROWS FETCH NEXT 100 ROWS ONLY
```

Triggered at `/var/www/html/src/Myddleware/RegleBundle/Solutions/database.php Line : ( 411 )`

It seems a limitation of old Microsoft Database

Any idea about it?

@simonetravaglini

**Comment by Myddleware** [comment]
Hi @francescobianco , 
Are you using SQL Server 2008 or SQL Server 2012 ? 
Thanks.

**Comment by simonetravaglini** [comment]
Hi i'm sure we had this issue with 2008

**Comment by Myddleware** [comment]
Hi @simonetravaglini , 
Yes this kind of query isn't compatible with SQL 2008. However, we could probably redefine some functions in class microsoftsqlcore to make it compatible.

In your query, are you using only the limit parameter ? And the offset alway stays at 0 ? For information, the offset is always equal to 0 except if you have redefined it.

If you confirm that offset is always equal to 0, maybe we could redefine the methods get_query_select_limit_offset and get_query_select_header in the class microsoftsqlcore using the "TOP" command  (create file myddleware\src\Myddleware\RegleBundle\Custom\Solutions\microsoftsqlcore.php to make this modification upgrade safe) . You should have somethinhg like this (not tested) : 
```
class microsoftsqlcore extends database {
	// In SQL 2008, command "OFFSET 0 ROWS FETCH NEXT 100 ROWS ONLY" doesn't work
	protected function get_query_select_limit_offset($param, $method) {
		return null;
	}
	
	// use only TOP with SQL 2008
	protected function get_query_select_header($param, $method) {
		// The limit is managed with TOP if we don't have the offset parameter
		if ($method == 'read_last') {
			return "SELECT TOP 1 ";
		}
		return "SELECT TOP ".$param['limit']." ";
	}
}
```
Hope it will help

**Comment by simonetravaglini** [comment]
Finally we decided to ask customer to update DB.
Anyway maybe @francescobianco can answer to you

**Comment by Myddleware** [comment]
Hi  @simonetravaglini ,
That's a good news. If you are sure that your client will upgrade MSQ 2008 to MSQ 2012, don't waste your time to test this workaround.
Have a nice day.
