### ISSUE TITLE
date_modified hard rewrite without reason

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#518]
In this commit we suspect a problem regarding the missing use of '$value' after che for valid date into 'date_modified' field
https://github.com/Myddleware/myddleware/commit/0787c5b15578af9fca2148a7ef26e613a87bfbe5****

**Comment by Myddleware** [comment]
Hi @francescobianco 
I have added comment into the commit. $value is used line 435 here :  
https://github.com/Myddleware/myddleware/blob/0787c5b15578af9fca2148a7ef26e613a87bfbe5/src/Myddleware/RegleBundle/Solutions/database.php#L435

Please let me know if I am not clear.

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be. 
Thanks.
