### ISSUE TITLE
limit of tasks list stop connexion ?

### ISSUE THREAD

**Issue by Alexandre17220** [Myddleware/myddleware#52]
Hi, 
I haveconfigured my connection between prestashop and suitecrm
When I create manualy a customers in prestashop he is auto-created in suitecrm
and when I create a client in suitecrm he is auto-created in prestashop.
Now  I have maked a big import in prestashop ( 50 000 customers) and I have simply 8852 customers in suite crm.
When I lok tasks, I havbe 1000 tasks, maybe a limit stop connexion ??
in my list of task I have : 
`59b70761a589c5.00631770 	Start 	11/09/2017 22:00:01 	15/09/2017 12:01:53 	0		0 	0 	0		
59b70635801ad6.31267522 	End 	11/09/2017 21:55:01 	11/09/2017 21:55:29 	0		100 	0 	0		
59b705095515f7.79518409 	End 	11/09/2017 21:50:01 	11/09/2017 21:50:28 	0		100 	0 	0		
59b703dd469130.77607383 	End 	11/09/2017 21:45:01 	11/09/2017 21:45:28 	0		100 	0 	0		
59b702b224ac51.10788887 	End 	11/09/2017 21:40:02 	11/09/2017 21:40:29 	0		100 	0 	0		
59b7018621a563.52600699 	End 	11/09/2017 21:35:02 	11/09/2017 21:35:29 	0		100 	0 	0		
59b7005a0a4578.85833117 	End 	11/09/2017 21:30:02 	11/09/2017 21:30:29 	0		100 	0 	0		
59b6ff2e250277.39825900 	End 	11/09/2017 21:25:02 	11/09/2017 21:25:29 	0		100 	0 	0		
59b6fe0212e008.10054240 	End 	11/09/2017 21:20:02 	11/09/2017 21:20:29 	0		100 	0 	0		
59b6fcd6175f76.73848396 	End 	11/09/2017 21:15:02 	11/09/2017 21:15:29 	0		100 	0 	0		
59b6fba9e97075.67126149 	End 	11/09/2017 21:10:01 	11/09/2017 21:10:29 	0		100 	0 	0		
59b6fa7e20ba61.05524696 	End 	11/09/2017 21:05:02 	11/09/2017 21:05:29 	0		100 	0 	0		
59b6f9c94ff4b3.22436666 	End 	11/09/2017 21:02:01 	11/09/2017 21:02:17 	0		0 	0 	100		Array ( [0] =&gt; Transfer id 59b66819538674.90627723 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b668195b0db0.51910628 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b66819628b30.01641519 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b668196a1024.81557220 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b66819719002.99696564 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b66819793f97.47269572 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681980f3e6.40423040 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b668198a4453.28354702 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681991f8d5.03754103 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b66819999b05.73620963 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b66819a13175.82475704 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b66819a8c438.47404142 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b66819b081a6.59611143 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b66819b82a20.06322663 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b66819bfbd10.89066449 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b66819c748c7.60266742 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b66819ced983.55862937 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b66819d66cd4.80904201 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b66819de4eb1.01588341 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b66819e641e7.52154072 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b66819eddce5.86124074 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681a014a73.95286553 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681a08f157.17743760 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681a1088f1.65100557 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681a181828.18720426 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681a1fbf36.67528638 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681a2756d8.37384544 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681a2f06c1.30771304 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681a36a718.06660276 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681a3e3aa1.36997376 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681a45dbc6.44797897 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681a4d81f4.95173494 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681a551ea0.28892566 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681a5cd3b1.00978747 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681a646b50.14253309 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681a6c0c87.20799539 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681a73b186.64015888 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681a7b5db1.49401299 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681a831685.45888518 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681a8abaa9.14604218 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681a926676.72075956 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681a9a1384.59515327 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681aa1b929.66402115 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681aa96c13.53791377 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681ab11aa0.33479910 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681ab8d6f8.67446965 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681ac08b70.30783699 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681ac84050.38899781 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681acff359.83055107 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681ad7a830.42792921 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681adf6c62.85892787 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681ae75591.12875943 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681aef1536.48345381 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681b02a621.48440260 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681b0a6439.18969768 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681b122320.69082472 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681b19e909.94633809 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681b21bf71.59454787 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681b298390.12949225 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681b334b80.74026029 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681b3c9c10.09436867 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681b44a0e8.07506317 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681b4c7080.13814098 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681b543184.28839277 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681b5c03b7.87013728 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681b63d104.15392621 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681b6b9555.45982024 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681b736912.66859360 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681b7b37a0.23026581 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681b8315f8.39026274 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681b8b1223.55766366 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681b92f883.95089031 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681b9adaf7.94589901 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681ba2d798.48842689 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681baaa798.77519346 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681bb2bbd6.98634490 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681bbafb28.35398351 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681bc2dc38.86874855 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681bcacdc0.54980960 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681bd2a144.71453454 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681bda8239.94524646 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681be259f5.87167635 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681bea8f99.26038005 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681bf27c81.33661110 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681c063647.93410396 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681c0e2c47.50891503 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681c160e18.46010515 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681c1df4f3.70821221 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681c25e766.02546890 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681c2ddaa2.03330489 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681c35cd43.25473034 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681c3dc3a3.51654186 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681c45bdd1.33669909 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681c4db9f4.95708288 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681c559b99.65324974 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681c5d9919.17304555 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681c658fc4.57435342 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681c6d7d86.86291348 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681c758225.00916938 : Error, status transfer : Error_checking ) Array ( [0] =&gt; Transfer id 59b6681c7da273.43308622 : Error, status transfer =&gt; Predecessor_KO )
59b6f9521f24c8.96334192 	End 	11/09/2017 21:00:02 	11/09/2017 21:00:29 	0		100 	0 	0		
59b6f8254aa719.19331943 	End 	11/09/2017 20:55:01 	11/09/2017 20:55:28 	0		100 	0 	0		`

thanks a lot for your opinion.

**Comment by Myddleware** [comment]
Hi Alexandre,
Thanks for your feedback.
Could you tell me how many data transfer you have in Myddleware for your rule customer ? I mean the rule with only 8852 customer.
I need to know if the data are missing in Myddleware (so not read from Prestashop) or if these data are just in error in Myddleware (so not sent to SuiteCRM).
In the second case you should have around 50 000 data in Myddleware for this rule. If yes, could you tell me how many data transfert you have for each global status (Open, Cancel, Error, Closed). To do that, you can use the search transfer view in Myddleware.
Thanks.
Have a nice day.

**Comment by Alexandre17220** [comment]
> in Myddleware for your rule customer 
16460 , there isn't all the data from prestashop it's strange

**Comment by Alexandre17220** [comment]
Hi,
after disable the rule suitecrm -> prestashop futur transfert seem to be ok
is it a problem with bidirectional rule ?
Thanks,

**Comment by Myddleware** [comment]
Hi Alexandre,
This is interesting. Could you open a transfer with status "Error_checking" for exemple the data transfer  with id 59b66819538674.90627723. Could you tell me the error you have in the log of the data transfer. You should have more detail.

About the missing data, what reference date did you put for the rule Customer ? Myddleware should have read all data after this date.Was this date far in the past ? For a migration, I usually put 1000-01-01 00:00:00.

Have a nice day,

**Comment by Alexandre17220** [comment]
Hi,

> This is interesting. Could you open a transfer with status "Error_checking" for exemple the data transfer with id 59b66819538674.90627723. Could you tell me the error you have in the log of the data transfer. You should have more detail.

ok : 

![image](https://user-images.githubusercontent.com/7665521/30580165-eb6281e8-9d1b-11e7-8c9e-12b4e51b916a.png)


> About the missing data, what reference date did you put for the rule Customer ? Myddleware should have read all data after this date.Was this date far in the past ? For a migration, I usually put 1000-01-01 00:00:00.
now in my reference there is : 2017-09-18 09:45:44
but If I find the problem I editing this date far in past like you say for synchronize all the data.

Thanks,
Have a nice days,

**Comment by Alexandre17220** [comment]
Ah, I understand,  there is data erased from prestashop when I have tested my import process.. maybe this block the transfert method for the rest.
How to know number of transfert processed and to be processed ?

**Comment by Myddleware** [comment]
Hi Alexandre,
About the status error sending, could you tell me what is the version of your Myddleware?
We have fixed somes problems in the past when it comes to read a specific date from Prestashop. Maybe it is already fixed otherwise we will fix the new problem.

About the migration problem, the Prestashop API don't return customer deleted. Do you know how many customers not deleted you have in Prestashop ? Thanks.

Have a nice day,

**Comment by Alexandre17220** [comment]
myddleware v2.2.3
I have 228068 customers in my prestashop.
> the Prestashop API don't return customer deleted


Ok but maybe there was a delete in prestashop before the connector try to create it in suitecrm.
So, how to know haow many transfert are awaiting ?

**Comment by Myddleware** [comment]
OK Alexandre so you have the latest version. So you can create a new issue to follow the problem of reading date from Prestashop.

We can keep this current issue open to follow your migration problem.

About this migration, if you want to see every awaiting data transfer, you can search the data transfer with the status OPEN and in ERROR.
Just to let you know that we will launch a new version of Myddleware in October with a "migration" mode to improve the performance of Myddleware during the migration process. And because, you have more than 200 000 customers to transfer, I think you will be interested to use this mode.
If you can't wait 1 month, we can support you directly in this migration process. Contact us to contact@myddleware.com if you are interested.
Have a nice day.

**Comment by Alexandre17220** [comment]
Hi,
> About this migration, if you want to see every awaiting data transfer, you can search the data transfer with the status OPEN and in ERROR.

It's strange look that : 
![image](https://user-images.githubusercontent.com/7665521/30632025-e52a3f48-9de6-11e7-93d4-8c1d55c8c795.png)

but myddle continue to create customers, why ?
![image](https://user-images.githubusercontent.com/7665521/30632062-0e7f60d0-9de7-11e7-8b59-80fb2d02c2d2.png)


have a nice days, thanks,

**Comment by Myddleware** [comment]
Hi Alexandre,
Could you search data transfer with global status = closed. You will see all data transfers sent. The first one is the last one sent. You ccan also filter with the rule customer if you have several rules.

If your rule is active, Myddleware keep synchronising data according the cron task you have set up.
Let me know if I'm not clear.
Have a nice day.

**Comment by Alexandre17220** [comment]
ok, I understand all data aren't in myddleware when I import data in prestashop, this go in myddleware according with my Cron by packet of 100 records.

**Comment by Myddleware** [comment]
Yes you 're right.
If you want to increase this limit, you can change it in the class job. The best pratice is to create a file job in the Custom directory. It will be upgrade safe.
I have added the directory Custom here to help you:
[Custom.zip](https://github.com/Myddleware/myddleware/files/1318054/Custom.zip)
It will increase the limit to 500. You can copy this Custom directory in the directory src\Myddleware\RegleBundle\
I advice you to keep a reasonable limit for performance reason.
Have a nice day.

**Comment by Alexandre17220** [comment]
thanks, I go test
