### ISSUE TITLE
Duplicate Rule

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#521]
Just an idea: "It is possible add button that clone an existing rule?"
sometimes it is useful duplicate n-times a rules

**Comment by Myddleware** [comment]
Hi @francescobianco ,
We haven't planned to add this button but you can generate a template with one or several rule then use this template to generate duplicate rules.
You can find more explanations about this command here : https://github.com/Myddleware/myddleware/issues/436#issuecomment-780413924

Hope it helps.

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue, this feature has been added in Myddleware 3, but do not hesitate to re-open it if needs be.
Thanks.
