### ISSUE TITLE
Double condition in filter

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#524]
Hi,
suppose I need to import all record where FIELD 1 = C or FIELD1 = F.
There is a way to manage in one rule? Or I need to create 2 different identical rules one with first condition and another with second condition?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
You should be able to do it using this filter : 
![image](https://user-images.githubusercontent.com/11330301/116976768-dc529f80-acc1-11eb-85e6-c6e194e86df4.png)

Please let me know if it is OK for you. Thanks.

**Comment by Myddleware** [comment]
By th way, thanks for all of your questions. We definitely have to improve our documentation.

**Comment by simonetravaglini** [comment]
Hi seems something not working
I've been set as follow:
![image](https://user-images.githubusercontent.com/6990139/117406080-da305100-af0c-11eb-8c84-fb88cfc9ab60.png)
But result is that skip also if TIPO = F
![image](https://user-images.githubusercontent.com/6990139/117406014-c4bb2700-af0c-11eb-9980-74309e3c4e25.png)

**Comment by Myddleware** [comment]
Oh my bad, sorry. Don't put quote in the filter : 
![image](https://user-images.githubusercontent.com/11330301/117490187-c584a500-af6e-11eb-858f-d77baa88f1d0.png)

Should work properly with this.

**Comment by simonetravaglini** [comment]
it works
