### ISSUE TITLE
Manage class redefinition for custom code purpose

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#525]
We need to be able to redifine a class like the class \src\Manager\RuleManager.php
Today we create the class in Custom directory : \src\Custom\Manager\RuleManager.php
Here a simple example : 
```
<?php
namespace App\Manager;

class RuleManager extends rulecore {
	protected function readSource() {
		// Call standard function that read data
		return parent::readSource();
	}
}
?>
```

But when we try to execute yarn command we have this error : 
![image](https://user-images.githubusercontent.com/11330301/116983491-79b1d180-acca-11eb-99a4-eeb81c4ef2db.png)

We have to change the way we redefine classes, probably using service decoration : https://symfony.com/doc/4.4/service_container/service_decoration.html

**Comment by stlgaits** [comment]
https://github.com/Myddleware/myddleware/commit/ca8338a2e163169a09740f4b16abdd3aedf4ee23

**Comment by Myddleware** [comment]
Lets check this service : https://symfony.com/doc/4.4/service_container/definitions.html

**Comment by stlgaits** [comment]
I've added comments to help declaring custom classes in services_custom.yaml. 
Basically, for each custom class, it must be declared in services_custom.yaml as a decorator of a standard class. 
Here is an example with a custom woocommerce class : 
![image](https://user-images.githubusercontent.com/74190794/120619681-7ee67580-c45c-11eb-8849-80ae951977af.png)

Code is based on https://symfony.com/doc/4.4/service_container/service_decoration.html

This code allows me to implement the following custom class in src/Custom/Solutions/woocommercecustom.php : 
![image](https://user-images.githubusercontent.com/74190794/120620345-2ebbe300-c45d-11eb-9a9e-c6c5cff4fa86.png)
Which in  turn will add the test1/test2/... custom fields to my connector.

I think we should add a link to help tutorial on our website to provide further support / tutorials on how to add custom code using this method.
