### ISSUE TITLE
Massive update of front-end libraries will be needed

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#526]
Need to remove deprecated & abandoned Javascript libraries, update JQuery & Bootstrap etc

**Comment by stlgaits** [comment]
- Removed Boostrap 3
- Added Bootstrap 5
- Added @popperjs
- changes (CSS, JQuery, Twig,...) made to reflect Bootstrap 5 classnames & updates
TODO : 
- go over all install & database setup pages to implement new Bootstrap features & correct CSS bugs
- correct small CSS bugs on Account page

**Comment by stlgaits** [comment]
Made base container wider on all pages to improve readability, especially in tables with error messages and improved layout of homepage graphs 
![image](https://user-images.githubusercontent.com/74190794/127345288-bfe4eaa8-f046-4500-9b16-670964f308e9.png)
![image](https://user-images.githubusercontent.com/74190794/127345321-127ae01a-afec-4cc9-9a92-68f3a07749c1.png)
![image](https://user-images.githubusercontent.com/74190794/127345382-7af82efd-fa34-429a-a73b-a5869aebeefd.png)
![image](https://user-images.githubusercontent.com/74190794/127345443-a2e4dd9f-f064-4ffc-ad69-8ddbc4192fc9.png)

**Comment by stlgaits** [comment]
Changed nav tabs using Bootstrap instead of Jquery UI to make them responsive
![image](https://user-images.githubusercontent.com/74190794/127845169-3c844fe3-693e-48fe-8cd2-6cf3b3bde9f8.png)
![image](https://user-images.githubusercontent.com/74190794/127845410-fa553b86-df80-47b4-b670-30168347eec7.png)

**Comment by Myddleware** [comment]
Perfect, thanks @EstelleMyddleware

**Comment by Myddleware** [comment]
Good job @EstelleMyddleware , thanks.
