### ISSUE TITLE
Activation button doesn't work on rule detail view 

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#529]
When I click on this button, the flag change to ON but the active flag in the database doesn't change :
![image](https://user-images.githubusercontent.com/11330301/117176715-786acc80-add0-11eb-9051-c265d0e70ff3.png)

However, the button on the rule list view works properly : 
![image](https://user-images.githubusercontent.com/11330301/117176834-9b957c00-add0-11eb-80b9-aaf892fc32cd.png)

**Comment by stlgaits** [comment]
Fixed javascript paths.
