### ISSUE TITLE
Upgrade needed on iadvize API (and connector) to be in line with upgraded packages

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#534]
The iadvize REST API is partially deprecated (https://developers.iadvize.com/documentation/graphql-api#graphql-api) and requires abandoned packages (zendframework/zend-hydrator & zendframework/zend-stdlib).
I have removed the iadvize/restapiclient library for now and upgraded packages (replaced zend with laminas). We now need to see how to implement the iadvize API again in the updated context, probably by resorting to their new GraphQL API. Therefore, we need a new library & to update our iadvize connector.
https://github.com/Myddleware/myddleware/commit/ac80183a5c317cbbb34a41673fb28afb771783c9

**Comment by Myddleware** [comment]
Iadvise connector not compatible with Myddleware 3. Connector removed from Myddleware 3. Need to be developped with the new Iadvize API.
https://github.com/Myddleware/myddleware/commit/3482dfc6ea5cb80cee7a0ee94479019e290ec732
