### ISSUE TITLE
SMTP and notification

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#536]
Hi, how are managed email notification in myddleware? 
If setting SMTP then start receving email?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
Yes, if SMTP configuration email is setup, ell Myddleware admin users will receive notification depending on the job scheduler configuration : 
![image](https://user-images.githubusercontent.com/11330301/121643857-98a63f00-ca92-11eb-9697-a05042a5c4ef.png)

With this configuration, you will receive a notification with what Myddleware every day. You will also receive an alert if a synchro job lasts more than 60 minutes.
Have a nice day.
