### ISSUE TITLE
InfoBip with Vtiger

### ISSUE THREAD

**Issue by edsonrodsilva** [Myddleware/myddleware#537]
Hi,
I'm working on building a new connector to integrate InfoBip with Vtiger, does anyone already build something to share?

**Comment by stlgaits** [comment]
Hello, and thank you for your future contributions ! 
We haven't developed anything in relation to InfoBip yet, however, we would be more than happy to help you. In this case, please share your code with us to be able to contribute to our project. 
TIA

**Comment by stlgaits** [comment]
By the way, we're bound to release Myddleware 3, the current code for it is on the upgrade_symfony_4.4.18 branch, which is, as you would've guessed, developed using Symfony 4.4. It is still in development but should be released very soon.
I strongly recommend you make your development based on this branch as we've greatly simplified the way we make new connectors in this version, therefore it would make your life easier to work in this branch. 

https://github.com/Myddleware/myddleware/tree/upgrade_symfony_4.4.18

**Comment by edsonrodsilva** [comment]
Hi, thanks for the infomation.
Pretty good, I'm looking at myddleware 3, looks great.
Great news myddleware 3 is with the Symfony 4.
And of course if what I develop to help, yes I will provide the PR.
Gongratulation for the project, is nice.
Thanks.

**Comment by edsonrodsilva** [comment]
I'm looking at Myddleware 3 for create a new connector in branch upgrade_symfony_4.4.18 It will only be compatible with >= php7.4 ?

**Comment by Myddleware** [comment]
Hi @edsonrodsilva , 
Yes, we will work to make Myddleware3 compatible with php8 too. But for now, it is only compatible with php 7.4.

Our documentation isn't ready for Myddleware 3, so I give you he main steps to create a new connector : 
 - declare the new solution in the file \src\Manager\SolutionManager.php , you can take sugarcrm as an example
 - add you solution in the array $solutionData in the file \src\DataFixtures\LoadSolutionData.php
 - run this doctrine command to update your database (the solution will be added in the table solution) : php bin/console doctrine:schema:update --force
 - Create your solution class in the directory src\Solutions
 - in your solution class, you have several functions to develop. You can use this tutorial to help you, but it is a tutorial based on Myddleware 2 not Myddleware 3 : https://myddleware.github.io/myddleware/#/dev_guide
    -> So please check what is done in other classes, like sugarcrm or suiteCRM to create the same functions
    -> We have simplified the function read, create and update. And the function read_last doesn't exist anymore in Myddleware 3
    -> About read function, please check classes Prestashop or SuiteCRM. The other classes use readData which is the read function for Myddleware 2 and requiered more info to be returned. So it will be easier for your to develop read function, you have just to return the records read in the result array.
    -> About create/update functions, please check class Database. The other classes use createData/upadateData which is the crate/function functions for Myddleware 2 and do more actions (change document status for example). So using create/update function will be easier.
    -> you can see what readData/createData/upadateData functions do in the class src\Solutions\solution. These functions will call your read/create/update functions

I hope it will help you. Please create a new issue if you find any bug in Myddleware 3, it will definitely help us ;)

**Comment by edsonrodsilva** [comment]
Hi, thanks for the valuable tips.
These instructions will help a lot.
:)

**Comment by AlexMyddleware** [comment]
Hello @edsonrodsilva ,

we take the liberty to close this issue.
We are now using Myddleware 3.3.1 with php 8.1.7, and 8.2.0, if you would still like to develop a new connector and need some help feel free to contact me or reopen the issue.

Thanks
