### ISSUE TITLE
BUG : ' massselectall' checkbox on Documents list table doesn't select all documents in error status

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#540]
![image](https://user-images.githubusercontent.com/74190794/123083900-d99e3c00-d420-11eb-8a20-d9766057baad.png)

Triggers the following console error : 
![image](https://user-images.githubusercontent.com/74190794/123083984-f175c000-d420-11eb-8198-ab08d52811e7.png)

**Comment by Myddleware** [comment]
Well done @EstelleMyddleware , thanks.
