### ISSUE TITLE
HttpNotFoundException triggered when filtering documents by Global Status error throw by FluxController.php line 821

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#541]
In Documents list, when selecting the 'Error' filter, once you press 'Filter'
![image](https://user-images.githubusercontent.com/74190794/123116758-78d32b80-d441-11eb-974e-0a1c924b5aa5.png)

, the following HttpNotFoundException is thrown by FluxController.php line 821 : 
![image](https://user-images.githubusercontent.com/74190794/123116603-550fe580-d441-11eb-98fc-f2d402bb6971.png)

**Comment by AlexMyddleware** [comment]
this error is not occuring in modern myddleware
