### ISSUE TITLE
Estimated documents in rule view parameters is higher than the limit 

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#542]
Is this normal behaviour? Isn't the number in simulation supposed to be the same as the limit or lower ?

![image](https://user-images.githubusercontent.com/74190794/123263477-4a188c00-d4f9-11eb-9fa3-164a4d7feb56.png)

@Myddleware

**Comment by stlgaits** [comment]
It seems the limit is not taken into acount anymore and the rule is executed until max number of records is reached.
For context on how to reproduce the issue : 

Source | Target
-- | --
suitecrm | Solution  prestashop
AOS_Products | products


duplicate_fields | name
-- | --

Mapping : 
![image](https://user-images.githubusercontent.com/74190794/123265647-8a790980-d4fb-11eb-8751-c749914ae379.png)


Reference date : 2020-06-24 
Limit : 5
Estimated document (simulation) : 91

Result after rule execution with these parameters : 
![image](https://user-images.githubusercontent.com/74190794/123266061-f491ae80-d4fb-11eb-8da1-8ee746004eda.png)


![image](https://user-images.githubusercontent.com/74190794/123266154-0a9f6f00-d4fc-11eb-8795-781f38f230dc.png)

**Comment by Myddleware** [comment]
Well done @EstelleMyddleware  thanks.

**Comment by stlgaits** [comment]
Partial bugfix for Salesforce, however I am wondering whether this is normal behaviour or not : 

![image](https://user-images.githubusercontent.com/74190794/126140932-64a3a450-6dd9-482a-bcaf-048f69670175.png)

The amount of records returned by the simulation is always 1 lower than actual limit, due to this code in src/Solutions/salesforce.php  line 445 to 456 : 

![image](https://user-images.githubusercontent.com/74190794/126141284-292de91e-b896-4786-b7f0-fb7f193ae183.png)

@Myddleware please let me know your thoughts on this.

**Comment by AlexMyddleware** [comment]
this snippet is no longer present in salesforce.php
