### ISSUE TITLE
NotFoundHttpException thrown when clicking on question mark in filter view in rule creation

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#543]
When creating a rule, if you click on the ? icon
![image](https://user-images.githubusercontent.com/74190794/123599614-163daf00-d7f6-11eb-846e-6329b480ba49.png)
the following error is thrown
![image](https://user-images.githubusercontent.com/74190794/123599341-c7901500-d7f5-11eb-917d-b91e09683c23.png)

**Comment by Myddleware** [comment]
Thanks @EstelleMyddleware
