### ISSUE TITLE
"File" Solution: Different delimiter.

### ISSUE THREAD

**Issue by vtexperts** [Myddleware/myddleware#545]
I configured it to work with a .csv file (comma delimited and fields/columnames enclosed by ""). 

 For example:
"col1","col2"
"val1","val2"

This works, however is there an option to use TAB delimited and without "" ? 
For example:
col1     col2
val1     val2

**Comment by Myddleware** [comment]
Hi @vtexperts ,
In you case, you can redefine the file connector and change the separator.
Could you try to create the file "src\Myddleware\RegleBundle\Custom\Solutions\file.php" , create the directory Custom if it doesn't exist.
Then copy this code in the file : 
```
<?php
namespace Myddleware\RegleBundle\Solutions;

use Symfony\Bridge\Monolog\Logger;
use Myddleware\RegleBundle\Classes\rule as ruleMyddleware;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType; // SugarCRM Myddleware

class file extends filecore {
	Protected $delimiter = '\t';
	Protected $enclosure = '';
}
```
I didn't test the tab character "\t", so could you tell me if it works properly. Thanks.

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be.
Thanks
