### ISSUE TITLE
Magento 2 to ERPnext Undefined Index

### ISSUE THREAD

**Issue by ModeBan** [Myddleware/myddleware#546]
Getting below error for magento 2 customer address module any idea how to fix this?

Notice: Undefined index: items in /app/src/Myddleware/RegleBundle/Solutions/magento.php on line 518

Notice: Undefined index: id in /app/src/Myddleware/RegleBundle/Classes/document.php on line 1325

![image](https://user-images.githubusercontent.com/21164341/126023491-a6fde29c-d5c9-4fe2-a0b3-7f032782b3f7.png)

**Comment by Myddleware** [comment]
Hi @ModeBan ,
We will try to reproduce your issue this week. We 'll come back to you as soon as possible.
Best regards.

**Comment by ModeBan** [comment]
Thanks @Myddleware

The process works but just doesn't display on the frontend.

Theres mention of this in your magento module code.

**Comment by stlgaits** [comment]
Hello @ModeBan , thank you for reporting this. May  I ask what version exactly of Magento 2 you're using?  We've noticed some discrepancies between our connector and the API and currently working on fixing them (in Myddleware 2 & 3). If you want to follow the conversion : https://github.com/Myddleware/myddleware/issues/552

**Comment by ModeBan** [comment]
hey @EstelleMyddleware Its magento 2.4

Could you document how to setup the connector for importing orders/ order items into magento please?

I can't seem to get it to work i dont know how to get the order items to populate in the rule.

**Comment by ModeBan** [comment]
Magento 2 to ERPnext

**Comment by stlgaits** [comment]
Thank you. Currently, Myddleware 2 is not compatible with Magento 2.4. We're currently working on bridging this compatibility gap in Myddleware 3, it should hopefully be done by the end of next week.  Regarding the 'order items' module, it is not yet included in our list of modules, but it will also be part of the development for next week. I will keep you posted.

**Comment by ModeBan** [comment]
The module is there tho under magento as the source. I just don't know how to setup the 2 rules to work with it.

Could you please advise as to how to setup the rule so that the order has the orders lines in it?

Would you have a sample config?

**Comment by Myddleware** [comment]
Hi @ModeBan ,
Yes you are right, OrderItem is developped but we have to make it compatble with Magento 2.4.

If you want to know how to link 2 rules, you can see an example here (it is between Customer and Order but it work the same way between orderItems and Order) : https://myddleware.github.io/myddleware/#/basic_usage?id=rule-details

This example is between SuiteCRM and Prestashop but it works the same way with Magento. So you should create first you rule Order, then create your rule OrderItem and linked it to you rule Order in the tab "Relationships".
We remain at your disposal.
