### ISSUE TITLE
erro na instalação

### ISSUE THREAD

**Issue by joaopaulocz** [Myddleware/myddleware#55]
![erro](https://user-images.githubusercontent.com/34291677/33641217-b9d612ba-da1b-11e7-9b3b-cde832a9bc61.jpg)

**Comment by Myddleware** [comment]
Hi guys,
Could you please explain your problem in english or in french ;) ? Thanks.
However, I see you have an installation problem so maybe you could try to install Myddleware via command. Could you have a look here : https://myddleware.github.io/myddleware/#/?id=install-myddleware
Have a nice day.
