### ISSUE TITLE
Magento 2 fields list needs updating as API fields have changed

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#552]
https://magento.redoc.ly/2.4.2-admin/tag/orders 
The list of fields available for some modules has changed and therefore needs updating in Myddleware metadata.

**Comment by stlgaits** [comment]
I've updated the list of fields available in Myddleware 3 based on Magento 2.4.2. 
However, my test version of Magento is 2.3.6-p1 which doesn't seem to be supported anymore (I don't see it in the API documentation) and therefore I can't test properly whether the new list of fields is accurate at the moment, would need to get a newer version of Magento to be able to try it out (2.3.7 or 2.4.2).
https://magento.redoc.ly/ 
![image](https://user-images.githubusercontent.com/74190794/126332431-33579ce6-c623-4087-8993-73a0f5a920f3.png)

**Comment by ModeBan** [comment]
@EstelleMyddleware I can give you access to a dev environment if you like on Magento ver. 2.4.2-p1

Do you guys have slack or something i can send you the credentials?

**Comment by Myddleware** [comment]
@ModeBan ,
We have just installed the version 2.4.2-p1. We will tell you if we need an environement with more data to test everything properly.
Thanks for your help.
