### ISSUE TITLE
Make the filter field more visible

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#553]
Could you make this field more visible, maybe by adding a border : 
![image](https://user-images.githubusercontent.com/11330301/126818165-7b8effab-3b54-4788-8fff-6d80d1676a4c.png)

Thanks.

**Comment by stlgaits** [comment]
![image](https://user-images.githubusercontent.com/74190794/126954462-1165d3ba-41f2-4d73-a6a3-30a98d283678.png)
