### ISSUE TITLE
ERPNext fields list needs updating 

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#554]
|  Source  |  Target  |  source module  |  target module  |
|  ---  |  ---  |  ---  |  ---  |
|  ERPNext  |  WooCommerce  |  Item  |  Products  |  

Fields mapped : 
![image](https://user-images.githubusercontent.com/74190794/127150846-b8a7d76e-e605-41ae-92b7-ee79b105aed3.png)

The following errors were thrown in simulation with the above configuration : 
- error: "Reading Issue: Error : Notice: Undefined property: stdClass::$attributes  \\src\\Solutions\\erpnext.php 306"
- error: "Reading Issue: Error : Notice: Undefined property: stdClass::$taxes \\src\\Solutions\\erpnext.php 307"

**Comment by EstelleMyddleware** [comment]
![image](https://user-images.githubusercontent.com/74190794/127152594-c129ae19-10fc-4986-a4cf-11d5428b1429.png)
