### ISSUE TITLE
MW3 : Weird visual behaviour

### ISSUE THREAD

**Issue by ModeBan** [Myddleware/myddleware#557]
Hey,

Just noticed that an error is displayed on the task log even tho its going through fine.

![image](https://user-images.githubusercontent.com/21164341/127221979-5ec9dc0b-75cb-47d7-a174-502c9b7289a0.png)

![image](https://user-images.githubusercontent.com/21164341/127222074-e73384cf-6019-46f6-959d-8a5aefbe5c8b.png)

**Comment by Myddleware** [comment]
HI @ModeBan ,
Thanks for your feedback, this is a display bug. @EstelleMyddleware  will fix it next week.
Have a nice day.

**Comment by CamillePMyddleware** [comment]
This has been fixed a while ago, we simply forgot to link a commit to it but the latest MW3 version should not include this bug.
