### ISSUE TITLE
Magento 2 to ERPnext

### ISSUE THREAD

**Issue by ModeBan** [Myddleware/myddleware#559]
Hi,

I'm getting the below error when trying to add Sales Taxes as a child of Sales invoice for magento to erpnext
 
![image](https://user-images.githubusercontent.com/21164341/127583943-e84484a6-cd06-4ef7-b6e1-e276671d8ea0.png)

**Comment by Myddleware** [comment]
Hi @ModeBan ,
childModuleKey is an array we use to define the data format when Myddleware create or update a record into ERPNExt. This array is defined in the file \src\Solutions\erpnext.php : 
![image](https://user-images.githubusercontent.com/11330301/127729077-77194d08-00a5-497b-9805-0f1c2e9a1bd8.png)

When Myddleware merges differents data, like "Sales invoice" and "Item", we need to tell Myddleware what is the key of the array to add the invoice items in the sales order structure, in this example the key is items : 
![image](https://user-images.githubusercontent.com/11330301/127729185-11fa6035-e93d-4e14-b861-675942489030.png)

In your case, if the "Sales taxe" is an item of your "Sales invoice", you should add a entry in the array childModuleKey, something like : 
`'Sales Taxes and Charges' => 'items',`

Please let me know if it works and we will update our ERPNExt connector

**Comment by ModeBan** [comment]
Heya @Myddleware this worked.


How can I submit the field 'docstatus' that's in the Json returnd from the invoices request that's to summit the invoice to make it permanent

**Comment by ModeBan** [comment]
Hey @Myddleware ive added this to the code and it worked,

'Sales Taxes and Charges' => 'taxes',

**Comment by Myddleware** [comment]
Hi @ModeBan ,
Great news, thanks you for your feedback.
@EstelleMyddleware, could you add the line `'Sales Taxes and Charges' => 'taxes',`  in the array childModuleKey and commit it. 
Thanks
