### ISSUE TITLE
Cant Set Posting Date For ERP Next Invoice

### ISSUE THREAD

**Issue by ModeBan** [Myddleware/myddleware#560]
Hi, i can't set the posting date for an erpnext sales invoice.

any ideas?

**Comment by stlgaits** [comment]
hi @ModeBan do you get an error message ? Could you show me your fields mapping & relationships, I would like to try to reproduce your case first.

**Comment by ModeBan** [comment]
Hi @EstelleMyddleware I got it sorted, needed to set set_posting_time to 1

Is there a way to set docstatus in middleware for invoices?

**Comment by stlgaits** [comment]
Hi @ModeBan do you mean the status field in Sales Invoice module ? If so, you can create a formula during field mapping and select one of the following values : 
![image](https://user-images.githubusercontent.com/74190794/128683175-e249ef20-98d7-4ed3-a14b-8b238a5eea8b.png)
![image](https://user-images.githubusercontent.com/74190794/128683348-adb68035-1e1b-418f-841b-87fa59e48ea8.png)
![image](https://user-images.githubusercontent.com/74190794/128683375-c7c84b95-1f67-4dd8-ba04-5132db51012c.png)

If it's not this field then I am not too sure what you're referring to but it might be a read-only ERPNext field. If that's the case I recommend asking on ERPNext forums  https://discuss.erpnext.com/ and please let me know if you find out how you've managed to do it :)

**Comment by ModeBan** [comment]
Hey @EstelleMyddleware 

So that's how you'd submit an invoice?

Can you confirm that it works I wasn't able to get it to submit the invoice.

So I did a rest post request and there is a field called docstatus and it can be 0 or 1 and with 1 being that the invoice is submitted.

Is there a way to achieve this?

**Comment by stlgaits** [comment]
Ha ! 
From what I've gathered, the docstatus part is a description of a field and shouldn't be edited in itself. For example, this is an extract of what I get on a GET request to  ..../api/method/frappe.desk.form.load.getdoctype?doctype=Sales%20Invoice for the fields address_display & contact_person : 
`          {
                    "doctype": "DocField",
                    "name": "e8d2004ac2",
                    "owner": "Administrator",
                    "creation": "2013-05-24 19:29:05",
                    "modified": "2021-01-15 17:55:26.389551",
                    "modified_by": "Administrator",
                    "parent": "Sales Invoice",
                    "parentfield": "fields",
                    "parenttype": "DocType",
                    "idx": 32,
                    "docstatus": 0,
                    "fieldname": "address_display",
                    "label": "Address",
                    "fieldtype": "Small Text",
                    "search_index": 0,
                    "hidden": 0,
                    "set_only_once": 0,
                    "allow_in_quick_entry": 0,
                    "print_hide": 0,
                    "report_hide": 0,
                    "reqd": 0,
                    "bold": 0,
                    "in_global_search": 0,
                    "collapsible": 0,
                    "unique": 0,
                    "no_copy": 0,
                    "allow_on_submit": 0,
                    "show_preview_popup": 0,
                    "permlevel": 0,
                    "ignore_user_permissions": 0,
                    "columns": 0,
                    "in_list_view": 0,
                    "fetch_if_empty": 0,
                    "in_filter": 0,
                    "remember_last_selected_value": 0,
                    "ignore_xss_filter": 0,
                    "print_hide_if_no_value": 0,
                    "allow_bulk_edit": 0,
                    "in_standard_filter": 0,
                    "in_preview": 0,
                    "read_only": 1,
                    "length": 0,
                    "translatable": 0,
                    "search_fields": null,
                    "is_custom_field": null,
                    "linked_document_type": null
                },
  {
                    "doctype": "DocField",
                    "name": "298e7c8e65",
                    "owner": "Administrator",
                    "creation": "2013-05-24 19:29:05",
                    "modified": "2021-01-15 17:55:26.389551",
                    "modified_by": "Administrator",
                    "parent": "Sales Invoice",
                    "parentfield": "fields",
                    "parenttype": "DocType",
                    "idx": 33,
                    "docstatus": 0,
                    "fieldname": "contact_person",
                    "label": "Contact Person",
                    "fieldtype": "Link",
                    "options": "Contact",
                    "search_index": 0,
                    "hidden": 0,
                    "set_only_once": 0,
                    "allow_in_quick_entry": 0,
                    "print_hide": 1,
                    "report_hide": 0,
                    "reqd": 0,
                    "bold": 0,
                    "in_global_search": 1,
                    "collapsible": 0,
                    "unique": 0,
                    "no_copy": 0,
                    "allow_on_submit": 0,
                    "show_preview_popup": 0,
                    "permlevel": 0,
                    "ignore_user_permissions": 0,
                    "columns": 0,
                    "in_list_view": 0,
                    "fetch_if_empty": 0,
                    "in_filter": 0,
                    "remember_last_selected_value": 0,
                    "ignore_xss_filter": 0,
                    "print_hide_if_no_value": 0,
                    "allow_bulk_edit": 0,
                    "in_standard_filter": 0,
                    "in_preview": 0,
                    "read_only": 0,
                    "length": 0,
                    "translatable": 0,
                    "linked_document_type": "Setup",
                    "search_fields": null,
                    "is_custom_field": null
                },`

This docstatus is present on the description for every field so I don't think it's supposed to be modified. 
However I've tried with the following fields mapping from Magento to ERPNext and I get this series of errors from ERPNext, there must be a required field somewhere, you would need to check ERPNext documentation : 
![image](https://user-images.githubusercontent.com/74190794/128692519-c02d91a6-352d-4a48-ae55-3836996966be.png)

![image](https://user-images.githubusercontent.com/74190794/128692470-bf7b09c5-30a6-43a7-a5a8-da90508fb2be.png)
However I'm pretty positive that if you want to send the status "submitted" to ERPNext, you need to do it the way I showed you above with a formula. Let me know if this helps.

**Comment by ModeBan** [comment]
Hi @EstelleMyddleware 

That is not the way to send sumbitted.

the field docstatus needs to be set to 1 when creating the invoice.

Can you add a field for that?

**Comment by stlgaits** [comment]
Hello @ModeBan , could you show me the error message you get from Myddleware as well your fields mapping ? Much appreciated.

**Comment by ModeBan** [comment]
@EstelleMyddleware there is no error thst I can see just the status of the invoice is not set at all in ERPnext.

For that to happen docstatus needs to be set to 1. I've tried to manually by running a post request and creating the invoice via api.

I can send you the fields mapping later today.

**Comment by Myddleware** [comment]
Hi @ModeBan ,
Could you send us what you have post to create you invoice manually with a specific status ? It will definitely help us to adapt our ERPNext connector.
Thanks.

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be.
Thanks
