### ISSUE TITLE
Problem when create template from rule with relationship

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#561]
If I try to create a tempalte with

```
php bin/console myddleware:generateTemplate "newtempl" "My new template" 611148c584xxx --env=background
```

I receive this error

```
Failed to generate template test : Error : Failed to generate relationship for the rule 611148c584xxx /var/www/html/src/Myddleware/RegleBundle/Classes/template.php Line : ( 174 )
```

@simonetravaglini

**Comment by Myddleware** [comment]
Hi @francescobianco ,

I guess your rule 611148c584xxx has a relationship with another rule. If I am right you have 2 ways to solve this problem : 

- Remove the relationship from your rule and generate the template again
- Add the rule linked to the rule 611148c584xxx into the template. You should have something like : 
`php bin/console myddleware:generateTemplate "newtempl" "My new template" 611148c584xxx,<your other rule ID> --env=background`

Hope it helps

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be. 
Thanks.
