### ISSUE TITLE
demo forbidden error

### ISSUE THREAD

**Issue by ingram02** [Myddleware/myddleware#563]
Hi all, 

When I try to create the demo connectors for SuiteCRM and Prestashop, I am getting this error:

**Forbidden
You don't have permission to access this resource.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.**

These are the instructions I am following:

[2.5 Myddleware Demo Instructions.docx](https://github.com/Myddleware/myddleware/files/7031530/2.5.Myddleware.Demo.Instructions.docx)

Any ideas?

Thanks, 
Mel

**Comment by stlgaits** [comment]
Hello, at what step exactly do you get this error ? Could  you send me some screenshots & the exact steps you followed (what data did you input etc) ? This would help me reproduce your issue :)

**Comment by ingram02** [comment]
Hi EstelleMyddleware,

It is when I save the connection. Attached is a zip file of the steps and data I inputted (used demo and demo as user and password).


Best regards,

Mel

________________________________

**Comment by stlgaits** [comment]
Hi @ingram02 , it seems you've responded using your email client so I didn't get the zip file

**Comment by ingram02** [comment]
[DEMO SCREENSHOTS.zip](https://github.com/Myddleware/myddleware/files/7032629/DEMO.SCREENSHOTS.zip)

Oh, sorry. Here you go :)

**Comment by stlgaits** [comment]
@ingram02 ha indeed I got the exact same error, there must be a tiny issue on the server. Let me get back to you once we've fixed it :)

**Comment by Myddleware** [comment]
Hi @ingram02 ,
Sorry for the delay of our intervention. We have fixed the issue, you should be now able to create a connector.
Contact us if you have any other problem.
