### ISSUE TITLE
Change the history document block width

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#564]
Could you change the width of this block : 
![image](https://user-images.githubusercontent.com/11330301/131525338-5a9695fa-472a-4f1a-aa44-b3a18e8317a6.png)

Could you check the other blocks too (child documents, parent documents).
Thanks

**Comment by stlgaits** [comment]
![image](https://user-images.githubusercontent.com/74190794/131629416-cf87f2d8-69c4-4483-baa5-ca9432c85fbd.png)
