### ISSUE TITLE
Allow deletion from target

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#569]
Hi,
sometimes I use deletion funcionality and is very usefull.
But not sure about functionality of 
ALLOW DELETION FROM TARGET APPLICATION
![image](https://user-images.githubusercontent.com/6990139/137914110-e5cca7e0-2edb-4dd5-a302-180bb3ef0f2c.png)
Can you explain better?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
This functionality allow Myddleware to delete a record in target application if the record in the source application has been deleted. Myddleware will be able to deleted only the records it has created.
Please let me know if you have any other question.
