### ISSUE TITLE
cannot save formulas in fields mapping when field names have special characters

### ISSUE THREAD

**Issue by rulotec** [Myddleware/myddleware#573]
I get this error:

![Screenshot from 2021-10-21 19-39-10](https://user-images.githubusercontent.com/36896420/138375321-384d3291-53f7-49d9-9689-aa548642d0db.png)

When using a formula like this one:

![Screenshot from 2021-10-21 19-41-50](https://user-images.githubusercontent.com/36896420/138375469-d1721edb-d617-4da4-8d68-343ab2c57971.png)

The problem is that the fieldname, created by facebook is this one: `¿por_donde_le_gustaría_ser_contactado?`, which is the internal fieldname generated automatically when creating a field for a form. If I take out the `¿?í` characters, then I can save the formula, but, of course, then the field contents are not not retrieved.

**Comment by AlexMyddleware** [comment]
solved in https://github.com/Myddleware/myddleware/pull/1147
