### ISSUE TITLE
records are not retrieved from facbook in the "Simulation" eventhough there are records

### ISSUE THREAD

**Issue by rulotec** [Myddleware/myddleware#574]
When running the test, I get the error: 

> There is no data in the source server or fields in the target solution

![image](https://user-images.githubusercontent.com/36896420/138377867-a61dc233-869d-4f24-abc6-7d1a6db15069.png)

I confirmed there are records in my facebook "Leads Center". What I noticed is that it happens when the records are not recent.

If I choose a campaign that has recent records (from today or yesterday) I do see the record data in the test.

So, is this something that could be fixed? or at least do  you guys know the exact time frame in which records are retrievable? say for example 24 hrs, 5 days... ?

**Comment by stlgaits** [comment]
From top of my head, the simulation reads data from 1 month ago maximum, however bear in mind that if there is an issue with your fields (for example if you put multiple fields in the same target field without a formula), then the message would be there is no data in the source, even though in reality once you run the rule you would get an array to string conversion issue here.
