### ISSUE TITLE
How to create a slot of time for rules.

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#576]
Hi myddleware team,
suppose we have to run a rule every 5 minutes, but... only during night time (ex. from 23.00 to 7.00).
What is in your opinion the best way to manage this situation?

@francescobianco

**Comment by Myddleware** [comment]
Hi @simonetravaglini @francescobianco , 
In your case we use the crontab configuration. In this example, we run Myddleware every minutes the day and every 30 minutes during the night : 
```
* 9-18 * * * /usr/bin/php /var/www/middleware/public/bin/console myddleware:jobScheduler --env=background > /dev/null 2>&1
*/30 * * * * /usr/bin/php /var/www/middleware/public/bin/console myddleware:jobScheduler --env=background > /dev/null 2>&1
```
Hope it helps.

**Comment by simonetravaglini** [comment]
@Myddleware Hi sorry if I was not clear in my request.
Suppose we have 2 rules. One should be load every 5 minutes all day long, the second every 5 minute but only in the night.

**Comment by Myddleware** [comment]
OK, I am afraid that isn't possible using Myddleware scheduler, we have to improve it. 

Here is a workaround. You can disable the synchro command in Myddleware's scheduler : 
![image](https://user-images.githubusercontent.com/11330301/138704297-38c585f5-c6f3-452d-b252-5478675bfff9.png)

And keep the other commands active (rerunerreor, notifcation...)

Then use the crontab to manage synchro command : 
```
*/5 23-7 * * * /usr/bin/php /var/www/middleware/public/bin/console myddleware:synchro <rule id to be executed every 5 mintes the night> --env=background > /dev/null 2>&1
* * * * * /usr/bin/php /var/www/middleware/public/bin/console myddleware:synchro  <rule to be executed every minute> --env=background > /dev/null 2>&1
```
I hope it helps.

**Comment by simonetravaglini** [comment]
ok Thanks it's a good workaround. 
I suggest to add this feature in next release.
@francescobianco

**Comment by Myddleware** [comment]
Thanks @simonetravaglini @francescobianco ,
@EstelleMyddleware could you check if we can add a scheduler bundle like one of these : 
https://github.com/zenstruck/schedule-bundle
https://github.com/j-guyon/CommandSchedulerBundle

Thanks.

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue, this feature has been added in myddleware 3, but do not hesitate to re-open it if needs be.
Thanks.
