### ISSUE TITLE
Synchronizing Prestashop orders with Moodle courses

### ISSUE THREAD

**Issue by egutmartinez** [Myddleware/myddleware#582]
Hi, I'm trying to add automatically new orders of online courses from Prestashop to Moodle course enrolments with myddleware.

I put the same name in both ends but I'm finding that it creates new courses (new id) after the user purchasing on prestashop instead enrol the user to existing moodle courses.

Can someone please let me know any sugeestion to fix the above or let me know about any extended tutorial Prestahop -> Moodle?

**Comment by Myddleware** [comment]
Hi @egutmartinez ,
I guess there is probably a wrong configuration in the rule relationship.
You can use a template we have built for your case. Whe you create a rule, select "Default templte selection" : 
![image](https://user-images.githubusercontent.com/11330301/141451006-60eae5c6-3b2b-49e7-9d99-5c16d060fa5e.png)

It will create 4 rule in your Myddleware : 
 - Prestashop customers => Moodle users
 - Prestashop products => Moodle courses
 - Prestashop orders => Moodle users (rule just used to have the order ID linked to the user ID => required for the next rule. This isn't an easy part and I guess this is where you have an issue)
 - Prestashop order items => Moodle enreolments

Hope it will help you.

**Comment by egutmartinez** [comment]
Yes, I had selected the default template. But maybe I was wrong with any other stuff regarding courses.

The prestashop install we have is just a new testing site where i just add one testing product and I added that product on prestashop using the same name that one of the courses in Moodle. then I thought that if I tried to book that testing product on prestashop it will make the Moodle enrol for that couse in Moodle with the middleware in case it would check that the product name would be the same as any of the moodle courses, but I don't know if the product id would have to match also with something or If I would have to do any kind of products - courses mapping so I make sure that Moodle know what product correspond to any course. 

Do we have to do something like this? or maybe, Would I have to add the Prestashop products (online courses) in other way or following some rules?

Because doing like I did, it is creating a new blank course in Moodle even though the product/course name is moving right.

Thank you in advance

**Comment by Myddleware** [comment]
Hi @egutmartinez ,
Sorry for the delay of our response, weekend + very busy period ;)

Before Myddleware creates a record in the target application (Moodle in your case), it can check if the record already exist. In this case you have to specify the duplicate key. In your case you can check "name" like this : 
![image](https://user-images.githubusercontent.com/11330301/142196048-e71ace9a-32c7-401d-8dfb-5ac7e202bfcb.png)

So Myddleware will check if a Moodle course already exists with the Prestashop product name before creating it.

Please let me know if it helps.

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be. 
Thanks

**Comment by egutmartinez** [comment]
Ok, thank you for letting us know.

 

But unfortunately it wasn’t fixed. So, any advice or support would be great.

 

Best Regards,

 

 

-- 

Eduardo Gutiérrez

***@***.*** ***@***.***>  / +34 653254059

 

 

 

 

 

De: Camille Pichaud ***@***.***> 
Enviado el: jueves, 5 de mayo de 2022 10:01
Para: Myddleware/myddleware ***@***.***>
CC: egutmartinez ***@***.***>; Mention ***@***.***>
Asunto: Re: [Myddleware/myddleware] Synchronizing Prestashop orders with Moodle courses (Issue #582)

 

Hi, I am archiving this issue, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be.
Thanks

**Comment by Myddleware** [comment]
Hi @egutmartinez , 
Did you try to select the name as duplicate key as shown in my last answer ? 
Thanks.

**Comment by AlexMyddleware** [comment]
after some recent testing on upcoming myddleware release with moodle setup, i couldn't reproduce the bug, it was probably fixed, but feel free to reopen this issue if the need arises
