### ISSUE TITLE
Myddleware install on server

### ISSUE THREAD

**Issue by egutmartinez** [Myddleware/myddleware#585]
Hi there, 

I'm trying to install Myddleware on our server with Ubuntu 18.04 and Php 7.4.

In order to meet the requirements I'm trying to install yarn following the instructions on https://yarnpkg.com/getting-started/install

If I ran the command "node -v" on my server I get the following error:

-----------------
Command 'node' not found, but can be installed with:

sudo apt install nodejs
----------------

Shoud I install node first using the above command? Then do?:

sudo corepack enable
sudo yarn init -2

And then everything will be ready to go to the myddleware dierctory and do?:

sudo yarn install
sudo yarn build

Thank you in advance

**Comment by stlgaits** [comment]
Hello @egutmartinez  yes this looks good to me except probably the yarn init -2 command which shouldn't be necessary in this case since it is a command to initialise a brand new project which isn't our case here. Let me know if it worked.

**Comment by egutmartinez** [comment]
Thank you for your help!

I tried but when I ran "sudo yarn build" I get the following error:


yarn run v1.22.15
$ php bin/console fos:js-routing:dump --format=json --target=public/js/fos_js_routes.json && encore production --progress
Dumping exposed routes.

[dir+]  public/js
[file+] public/js/fos_js_routes.json
Running webpack ...

 WARNING  The value passed to setPublicPath() should *usually* start with "/" or be a full URL (http://...). If you're not sure, then you should probably change your public path and make this message disappear.
10% building 0/1 entries 0/0 dependencies 0/0 modulesnode:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/var/www/cervantes.to/public_html/myddleware/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/var/www/cervantes.to/public_html/myddleware/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/var/www/cervantes.to/public_html/myddleware/node_modules/webpack/node_modules/webpack-sources/lib/RawSource.js:77:8)
    at NormalModule._initBuildHash (/var/www/cervantes.to/public_html/myddleware/node_modules/webpack/lib/NormalModule.js:888:17)
    at handleParseResult (/var/www/cervantes.to/public_html/myddleware/node_modules/webpack/lib/NormalModule.js:954:10)
    at /var/www/cervantes.to/public_html/myddleware/node_modules/webpack/lib/NormalModule.js:1048:4
    at processResult (/var/www/cervantes.to/public_html/myddleware/node_modules/webpack/lib/NormalModule.js:763:11)
    at /var/www/cervantes.to/public_html/myddleware/node_modules/webpack/lib/NormalModule.js:827:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.1.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------------------------------

any idea?

**Comment by stlgaits** [comment]
@egutmartinez Ha I believe this is due to the fact that the previous command makes you install Node v17 which is apparently not yet compatible with our version of webpack (this is a Symfony 4.4 project). I had a look at this issue and they seem to suggest several solutions, including downgrading to the LTS version of Node.js to ensure compatibilty, which I think should do the trick : https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported Let me know if this worked.

**Comment by egutmartinez** [comment]
Thank you for that.

I tested it now with the LTS version of Node.js and that "sudo yarn build" command worked fine this time.

But now I went to https://path_to_myddleware/myddleware/public to install and I get the following error 500 page:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.


If I check the apache error log I find the following:

[access_compat:error] [pid 13684] [client MY_IP:64590] AH01797: client denied by server configuration: /var/www/path_to_myddleware/public_html/myddleware/src/

Can you help with this?

**Comment by stlgaits** [comment]
@egutmartinez  Could you check what the last logs in /var/www/path_to_myddleware/public_html/myddleware/var/log/prod.log say ?

**Comment by egutmartinez** [comment]
Well, I cannot find any logs there. The /var/www/path_to_myddleware/public_html/myddleware/var/log/ directory is empty and not exist the prod.log file

**Comment by stlgaits** [comment]
@egutmartinez Ok; could you check that the var/log & var/cache (or simply /var) are writable by the webserver (it should be www-data user if you're using Apache) ?

**Comment by egutmartinez** [comment]
Thank you for that.

I did a "sudo chown -R www-data:" for  the /var directory and it worked. Now I could start with the install from browser.

Bur now I'm finding that the install cannot connet with the database.

I created the database and gave the myddleware user privileges using the following commands:

create database myddleware_db;
create user myddleware_user@localhost identified with mysql_native_password by 'password';
grant all privileges on myddleware_db to myddleware_user@localhost;

And then put the info like you can see on the attached image

![database](https://user-images.githubusercontent.com/94139020/142999731-a13cc446-65d4-40a2-8304-f938fe81d5be.jpg)

Then when click next I get always the following error:

Unknown database. Please make sure your database exists. An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)

But I'm sure the database is fine as for example I can login with the myddleware user using PHPmyadmin and see the blank database.

Any idea?

**Comment by stlgaits** [comment]
@egutmartinez hm you definetely clicked 'Save' before clicking 'Next' ? This is strange as from what I can gather, it attempts to log in using the code from the standard .env file (hence why it says db_user and not myddleware_user like you've written in the input) which means that it didn't create the .env.local file automatically like it should with the info you've typed above.
Could you check one last time by ensuring you clicked Save then Next (might've to type the password again before clicking Next) ?
If that didn't work still, create a .env.local file at the same level as the .env file with the following info written inside :
 
```
DATABASE_URL=”mysql://myddleware_user:your_password@localhost:3307/myddleware_db”
APP_ENV=prod
APP_DEBUG=false
APP_SECRET=ChangeThisSecretToWhatYouWant
```

**Comment by egutmartinez** [comment]
Thank you for that. I did a "sudo chown -R www-data:" for all the /myddleware directory and it worked. Looks like wasn't able to write there.

Now looks like connect to the database, but still I get the following error:

Unknown database. Please make sure your database exists. An exception occurred while executing 'INSERT INTO config (name, value) VALUES (?, ?)' with params ["allow_install", "true"]: SQLSTATE[42000]: Syntax error or access violation: 1142 INSERT command denied to user 'myddleware_user'@'localhost' for table 'config'

Any suggestion?

**Comment by stlgaits** [comment]
@egutmartinez ok, to fix your problem I think the simplest solution would be to follow the rest of the tutorial 'install via command line' here  https://myddleware.github.io/myddleware/#/?id=install-myddleware from 'php bin/console doctrine:schema:update –force' Hopefully it should fix your issue. 

However what I find strange is that this error means that either the web user isn't able to connect to your database (maybe double check your credentials) or that it's unable to write into it / execute commands. 

Normally here it would have executed the following commands : 

```
php bin/console doctrine:schema:update –force 
php bin/console doctrine:fixtures:load –append  
```

which would have populated your database with Myddleware configuration data.

Let me know if the install via command fixes your issue.

**Comment by egutmartinez** [comment]
Well, It finally worked. I had error on the Grant privileges command as I was putting:

grant all privileges on myddleware_db to myddleware_user@localhost;

instead 

grant all privileges on myddleware_db.* to myddleware_user@localhost;

I have just login to the app and I get the following screen that I presumme is the normal one I should get when I didn't still add any information to that.

![myddle](https://user-images.githubusercontent.com/94139020/143011748-4a53dd7f-6e2b-4761-a45e-1503f6fc98ff.jpg)

Thank you so much!

**Comment by stlgaits** [comment]
@egutmartinez Haaa excellent news !!! Yes you can now start using Myddleware and create your first connectors 🥇

**Comment by egutmartinez** [comment]
Well, I'm finding a problem when try to create the first rule.

I have added 2 connectos succesfully then try to create the first rule and when click on "Confirm this rule" it never finish and I see "Please wait" on the button but never finish and not message on prod.log

![rule](https://user-images.githubusercontent.com/94139020/143019468-5ab7c502-332e-4c34-b2ac-31100c12d733.jpg)

Can you help with this?

**Comment by egutmartinez** [comment]
I found some log on the apache error log:

[Tue Nov 23 14:31:41.290730 2021] [php7:notice] [pid 10930] [client 127.0.0.1:35678] [PHP Notice #8] Trying to access array offset on value of type null (/var/www/my_domain/public_html/course/c$
[Tue Nov 23 14:31:41.290818 2021] [php7:notice] [pid 10930] [client 127.0.0.1:35678] [PHP Notice #8] Trying to access array offset on value of type null (/var/www/my_domain/public_html/course/c$
[Tue Nov 23 14:31:41.295392 2021] [php7:notice] [pid 10912] [client my_ip:57946] PHP Notice:  Undefined index: args in /var/www/my_domain/public_html/myddleware/src/Solutions/prestashop$


The "/var/www/my_domain/public_html/course" directory is the place where we have installed the Moodle (target connector).

Any idea or suggestion?

**Comment by stlgaits** [comment]
@egutmartinez hm this might be a bug on our side (in the template), we will try to reproduce your case and will let you know ASAP what we found out.

**Comment by egutmartinez** [comment]
Hi there,


I have just realised that I put a wrong information above as The "/var/www/my_domain/public_html/course" directory is the place where we have installed Prestashop and not Moodle like said before by mistake.

Maybe also It could help If I put all the lines that I can see on the apache error log. Please find it below:

[Thu Nov 25 12:19:20.936421 2021] [php7:notice] [pid 29204] [client 127.0.0.1:52508] [PHP Notice #8] Trying to access array offset on value of type null (/var/www/my_domain/public_html/course/c$
[Thu Nov 25 12:19:20.936471 2021] [php7:notice] [pid 29204] [client 127.0.0.1:52508] [PHP Notice #8] Trying to access array offset on value of type null (/var/www/my_domain/public_html/course/c$
[Thu Nov 25 12:19:20.938960 2021] [php7:notice] [pid 29177] [client my_ip:55567] PHP Notice:  Undefined index: args in /var/www/my_domain/public_html/myddleware/src/Solutions/prestashop$
$/myddleware/src/Solutions/prestashop.php on line 369, referer: https://www.my_domain/myddleware/public/rule/create
[Thu Nov 25 12:19:20.939005 2021] [php7:notice] [pid 29177] [client my_ip:55567] PHP Notice:  Array to string conversion in /var/www/my_domain/public_html/myddleware/src/Solutions/prest$


By other way, Regarding the error on the line 369 of "myddleware/src/Solutions/prestashop.php " I checked that this line belongs to the following code:

} catch (PrestashopWebserviceException $e) {
                // Here we are dealing with errors
                $trace = $e->getTrace();
                if (401 == $trace[0]['args'][0]) {
                    throw new \Exception('Bad auth key');
                }
                throw new \Exception('Call failed '.$e->getTrace());
            }

And so, could be that 401 error informing about some authenticantion problem with the source Prestashop. I have double checked the Webservice API key and it looks fine and even the connector is created also fine without mistake and the connextion test is passed successfully.

Any idea?
