### ISSUE TITLE
Myddleware performance : Execute query on rule not on document

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#588]
For example, the query for rule param (method setRuleParam) can be done on rule level and not document level.

**Comment by AlexMyddleware** [comment]
![image](https://github.com/Myddleware/myddleware/assets/106162060/77951224-6fbd-4284-8a01-a26ecc3f8cfe)
the method ruleParam is present in ruleManager and in document manager, and can be done on rule level and document lever
