### ISSUE TITLE
Deletion issue when record ricreated in source

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#594]
Please give a look at this scenario:
1 - we have a source database and vtiger as target
2 - a record is cancelled in source, the rule manage deletion so in vtiger record is deleted
3 - the record is recreated in source with same ID
4 - when the rule run try to go in update instead of create, so we got error with vtiger api becouse can't find the record

@francescobianco please add info if need

**Comment by francescobianco** [comment]
We have found this on debug:

The line 1677 of file document.php is responsible for the selection of type 'U' instead of type 'C' but we require type 'C' at this stage
https://github.com/Myddleware/myddleware/blob/fa472d42b0252c9328bb63cb71cc1006fa3511fe/src/Myddleware/RegleBundle/Classes/document.php#L1677

```php
if (!empty($result['id'])) {
  $this->targetId = $result['target_id'];
  // If the document found is Cancel, there is only Cancel documents (see query order) so we return C and not U
  // Except if the rule is bidirectional, in this case, a no send document in the opposite rule means that the data really exists in the target application
  if (
		  $result['global_status'] == 'Cancel' 
	  && empty($this->ruleParams['bidirectional'])
  ) {
         // *** IMPORTATN *** WE LOOKING FOR RECREATE THE RECORD ON TARGET WHEN THE RECORD  IS RECREATED ON SOURCE WITH THE SAME SOURCE_ID
	  return 'C';
  } else {
          
	  return 'U';
  }
  }
```

**Comment by Myddleware** [comment]
Hi @simonetravaglini and @francescobianco ,
You are right, this scenario isn't handled by Myddleware. We will work on it to give you a fix. We should check if the last document sent is a deleted one. If yes, we should set 'C' and not 'U'.
We will add a fix in the hotfix branch soon. When do you need this bug fixed ?

**Comment by francescobianco** [comment]
Actually we work with your `master` branch the exact version is `v2.5.7j`
You have perfect catch our problem, Thanks!

**Comment by Myddleware** [comment]
Ok, we will fix it on Myddleware 2 (branch master) and Myddleware 3 (branch main).

**Comment by Myddleware** [comment]
Hi @francescobianco , we have fixed the issue, here is the commit : https://github.com/Myddleware/myddleware/commit/03f63e00606d5c92ef2765218bb321e97cc39372

You can upgrade Myddleware to get the fix.

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue, but please if you encounter any difficulties equal or similar to this one, do not hesitate to re-open it if needs be. 
Thanks.
