### ISSUE TITLE
Fail to connect to MSSQL

### ISSUE THREAD

**Issue by cecov74** [Myddleware/myddleware#595]
Hi, when I try to connect to MSSQL not find the driver, I see that use PDO connection and is present to php.ini
` Connection failed : could not find driver /var/www/vhosts/xxxxxx/myddleware.karatti.it/myddleware/src/Solutions/microsoftsql.php Line : ( 46 )`

![image](https://user-images.githubusercontent.com/19213713/144604731-c2849890-1ae6-4c1d-a494-5bbc752e3823.png)

why not load it?

**Comment by AlexMyddleware** [comment]
@cecov74 i'm marking this issue as resolved for now but if you need it again, here is what i can suggest

Check if the extension=pdo_sqlsrv line is uncommented in your php.ini . 
If it's commented (i.e., if it starts with a semicolon ;), remove the semicolon and save the file, then restart your server and you can get us the php info.

For that, create a PHP file with the phpinfo(); function and run it in your browser. This will display your PHP configuration information. Check the 'PDO drivers' section to see if sqlsrv is listed.

If sqlsrv is not listed, it means the driver is not properly installed.

If you're running PHP on a Linux server, apparently these two can some compatibility issues. You can try dblib driver instead.
