### ISSUE TITLE
Alert email not translated

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#597]
This text has to be translated when A task is running for too long.

Une tâche en cours a dépassé la limite que vous avez autorisée : 60 minutes<br/> La tâche a commencé à .<br/> ID de la tâche : <br/> Vérifiez que la tâche est toujours en train de transférer des données. Si ce n'est pas le cas, nous vous recommandons de l'arrêter manuellement en ouvrant la tâche et en cliquant sur le bouton "Arrêter la tâche".

**Comment by AlexMyddleware** [comment]
this translation is made
