### ISSUE TITLE
On an "error" document the modification of a line does not work

### ISSUE THREAD

**Issue by CamillePMyddleware** [Myddleware/myddleware#601]
With one click it generates an inactive and invisible entry. If you click several times, it generates several entries, also inactive. The validate button is also invisible and inactive.
![error](https://user-images.githubusercontent.com/95077335/147338950-c5e28e88-c46f-4db3-a402-713e6d6b6dac.PNG)

**Comment by AlexMyddleware** [comment]
@cpichaud need to check but this is no longer the case from my testing. I also added some code to prevent the user from opening a check before closing the first one
https://github.com/Myddleware/myddleware/pull/1147/commits/dfb9f406a2cb984e8e9e656fc36f69422d3bbec6
