### ISSUE TITLE
Relationship Display Changement

### ISSUE THREAD

**Issue by RomanFaure** [Myddleware/myddleware#617]
The display of relationship during the rule creation :
![image](https://user-images.githubusercontent.com/97444658/150091238-b1aea1de-bb86-4b07-a6ee-96271cb76917.png)
When the rule is created, the display is different :
![image](https://user-images.githubusercontent.com/97444658/150091377-84f8f871-74ed-4a44-b813-762c94dd56e4.png)

**Comment by AlexMyddleware** [comment]
closing this as we will use lookup formula instead
