### ISSUE TITLE
The Myddleware version wich can be downloaded on the website (Installation guide) is the 3.0.0.

### ISSUE THREAD

**Issue by RomanFaure** [Myddleware/myddleware#619]
Version téléchargé : 3.0.0

**Comment by stlgaits** [comment]
@RomanFaure @Myddleware This should've been fixed already (with archive version 3.0.6), however I am not sure why but the download form triggers a new issue (Mixed Content issue) and prevents from downloading the archive entirely  : 
![image](https://user-images.githubusercontent.com/74190794/156522285-80d5d9b1-0e12-4529-aa14-f833d19fa631.png)
This needs to be sorted ASAP.

**Comment by RomanFaure** [comment]
@EstelleMyddleware It is fixed, this issue should no longer occur.
