### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by ModeBan** [Myddleware/myddleware#621]
Hi, I need help installing,

i can't get the installation to work. I cant get the webpage to access the web wizard

**Comment by Myddleware** [comment]
Hi @ModeBan ,
Sorry, we see that the archive that you have downloaded wasn't on the right branch. Could you install Myddleware using git by following this tutorial : https://myddleware.github.io/myddleware/#/?id=install-myddleware
Hope it helps.

**Comment by ModeBan** [comment]
Hi @Myddleware 

I have tried this on a fresh installation and i can't get it to work.

Always showing up error 404 ot 500 internal for the Web wizard install.

**Comment by Myddleware** [comment]
Could you give us more detail about the 500 error ? You should be able to get a log from file <myddleware>/var/log/prod.log, or from your php log file.
Thanks.

**Comment by ModeBan** [comment]
Hi,

okay so this is the install I have followed.

To get Myddleware from Github, use this command :

git clone https://github.com/Myddleware/myddleware.git
cd myddleware
composer install
yarn install
yarn build

Now when i go to http://myddleware.techbitsireland.ie/myddleware/public/

I see the 500 error:
![image](https://user-images.githubusercontent.com/21164341/151088960-67798ff1-9ef0-4c30-adce-eb7bf462f8d6.png)

To rule out that its something with permissions, which it is partially.

I ran sudo chmod 777 -R myddleware
this is the result now.

![image](https://user-images.githubusercontent.com/21164341/151089184-8b70fcd8-3b8d-40db-b9ed-c7c861526b6f.png)

If i click on install on the page it goes to a 404 page.

![image](https://user-images.githubusercontent.com/21164341/151089224-fe8d7682-8d54-41e8-821e-78a756acaa2e.png)


Any suggestions? What am i doing wrong here?


Also if i go composer update in the myddleware directory i get this?
![image](https://user-images.githubusercontent.com/21164341/151089366-5ba0ee7a-0733-4768-9f31-aed13064b7b1.png)

The 500 error is actually not in the log.

**Comment by ModeBan** [comment]
Any update?

**Comment by stlgaits** [comment]
@ModeBan Hi sorry for the delay, I've been working on this yesterday and got the same issue as you, still haven't found a fix yet but will be working on it today so I will definitely keep you in the loop as soon as it's fixed :)

**Comment by stlgaits** [comment]
@ModeBan Hello unfortunately so far I haven't been able to fix this issue, however I am convinced that it is an Apache conf issue. In the meantime, I've found out that if you add index.php to your url, you can access your myddleware website, like here :  http://myddleware.techbitsireland.ie/myddleware/public/index.php

Just in case, I've been trying to fiddle with Apache .htaccess conf (inside /public dir using symfony/apache-pack & overall server conf) but no luck so far, however if you want to have a look yourself here is a link to the Symfony documentation regarding Apache config for subdirectory installations : 
https://symfony.com/doc/4.4/setup/web_server_configuration.html
https://symfony.com/doc/4.4/frontend/encore/faq.html#my-app-lives-under-a-subdirectory
https://symfony.com/doc/4.4/setup/file_permissions.html#permissions-required-by-symfony-applications

**Comment by Myddleware** [comment]
Thanks @EstelleMyddleware ,
@ModeBan , if you have Myddleware version 3.0.5, please wait for the version 3.0.6. We will release it tomorrow. We have added the user timezone and it could block the user creation.

**Comment by albtarta** [comment]
@EstelleMyddleware you are right, the solution is the apache configuration. @ModeBan 
I had the same problem and I solved it, if you want I can show you my configuration.
The only problem I have is that I don't see all applications, for example I don't see mautic, facebook etc.

I have Myddleware version 3.0.6a

**Comment by stlgaits** [comment]
@albtarta I would love to see your Apache configuration too if you don't mind  as I haven't been able to find a decent one myself ! 
Facebook has been deactivated for now as we are having some issues with the SDK (there were requirements conflicts) but Mautic 3 should definetly be available since it was tested. 
While waiting for a merge pull request to correct this, you can activate it manually by passing active from 0 to 1 here : 
https://github.com/Myddleware/myddleware/blob/d739dac42eaa9ccade2b51ae51d0e5594ec427c8/src/DataFixtures/LoadSolutionData.php#L56

Then you will need to load your fixtures again with : 
`php bin/console doctrine:fixtures:load --append`

**Comment by albtarta** [comment]
Hi @EstelleMyddleware , i just followed these instructions from the link you posted, 
![apache-symfony_pack](https://user-images.githubusercontent.com/34136179/153953690-a176abb6-32e3-4c3b-8801-1c593bf05777.jpg)
then created the apache virtualhost config file:
```
<VirtualHost *:80>
    
    ServerName yourservername
    ServerAlias yourserveralias

    DocumentRoot /var/www/html/myddleware/public

    <Directory /var/www/html/myddleware/public>
        AllowOverride None

DirectoryIndex index.php
<IfModule mod_negotiation.c>
    Options -MultiViews
</IfModule>

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$
    RewriteRule ^(.*) - [E=BASE:%1]

        # 301 Redirect to fix bug on the duplicate build in the URL
        RewriteRule ^build/build/(.*) build/$1

    # Sets the HTTP_AUTHORIZATION header removed by Apache
    RewriteCond %{HTTP:Authorization} .
    RewriteRule ^ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    RewriteCond %{ENV:REDIRECT_STATUS} ^$
    RewriteRule ^index\.php(?:/(.*)|$) %{ENV:BASE}/$1 [R=301,L]

    # If the requested filename exists, simply serve it.
    # We only want to let Apache serve files and not directories.
    RewriteCond %{REQUEST_FILENAME} -f
    RewriteRule ^ - [L]

    # Rewrite all other queries to the front controller.
    RewriteRule ^ %{ENV:BASE}/index.php [L]

</IfModule>

<IfModule !mod_rewrite.c>
    <IfModule mod_alias.c>
        RedirectMatch 307 ^/$ /index.php/
    </IfModule>
</IfModule>

</Directory>
</VirtualHost>
```

Thanks for the solutions you gave me for the missing applications, I hope that for facebook it will be resolved soon.

**Comment by ModeBan** [comment]
Sorted thanks to @albtarta
