### ISSUE TITLE
Special chars create 500 error on database connection form from install/database/setup

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#629]
if your password or username (anything that will be pushed to DATABASE_URL in .env.local) contains special chars (such as ? or @) it generates a 500 error (Doctrine throws an error saying malformed parameter url) .

**Comment by CamillePMyddleware** [comment]
![capture](https://user-images.githubusercontent.com/95077335/152165405-eacd952b-c4ad-4cd7-88ef-928165747378.PNG)

**Comment by AlexMyddleware** [comment]
i made a correction for this issue, although it should be noted that any character should be escaped in mysql, but not in myddleware. 

I would recommend not using special characters in mysql passwords, as they don't add a lot of entropy to your password anyway. It's much better to have more letters. 

It should also be noted that it is required to modified vendor files in order for this to work. You need to copy the content of CustomVendor into its original location, 
vendor/doctrine/dbal/src/DriverManager.php

Here is an example: i Use the (fake, rest assured) password Charles?voix

In order for this to work in mysql, the character NEEDS to be escaped. that means that if you set up your password and try to enter Charles?voix, it will NOT work. However, if you escape it with a \, like this
Charles\?voix

then it works. 

Then in myddleware, you input the regular version

Charles?voix

and it works.

**Comment by AlexMyddleware** [comment]
we decided that it was better to not publish the custom driver in the myddleware code, but it is still found in this commit so no problem

https://github.com/Myddleware/myddleware/commit/ce409f613b517dc0d3b04accd544624e15662863
