### ISSUE TITLE
Release 3.0.5a uses upper case table names in SQL query

### ISSUE THREAD

**Issue by ulrichbayer** [Myddleware/myddleware#630]
Hi,
In file `DocumentManager.php` lines 1586+ the sql query uses a table name beginning with an uppercase letter.

```
			$sqlParamsSoure = "	SELECT 
								Document.id, 
								Document.target_id, 
								Document.type, 
								Document.global_status,
								if(Document.target_id = '', 0, 1) targetOrder
							FROM Document 
```
This leads to the following exception in my environment:
`SQLSTATE[42S02]: Base table or view not found: 1146 Table myddleware.Document doesnt exist /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php Line : ( 61 )Failed to check document predecessor : Failed to find a type for this document. /app/src/Manager/DocumentManager.php Line : ( 670 )Status : Predecessor_KO `

It looks like Release 3.0.5a (https://github.com/Myddleware/myddleware/commit/f978d31448cc846f112fd0158f4fd5b3a902a69c) wrongly undoes the commit "clean sql code" (https://github.com/Myddleware/myddleware/commit/f3351e3a94a696ecaec8d5e964db80edd46882cf).

**Comment by Myddleware** [comment]
Hi @ulrichbayer , thanks for your message.
You are completely right and this bug is already fixed in the release 3.0.6 that we plan to release today. We will finish the tests of this version today.
So please upgrade Myddleware once we have released it.

**Comment by ulrichbayer** [comment]
Sounds good. Thank you for your quick reply!

**Comment by ulrichbayer** [comment]
Works now, thanks.
