### ISSUE TITLE
I don't see all applications

### ISSUE THREAD

**Issue by albtarta** [Myddleware/myddleware#643]
Hi, i have installed Myddleware version 3.06a and applications are missing, for example Mautic, Facebook, etc. , what can I do? 
Thank you

**Comment by stlgaits** [comment]
Hi @albtarta regarding Facebook, please have a look at this discussion https://github.com/Myddleware/myddleware/issues/618
Other connectors such as Mautic will be added back shortly but meanwhile you can follow the procedure I mentioned here https://github.com/Myddleware/myddleware/issues/621#issuecomment-1038761227

**Comment by albtarta** [comment]
@EstelleMyddleware Thanks!

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue but please do not hesitate to re-open it if needs be.
Thanks.
