### ISSUE TITLE
URL Build/Builld issue

### ISSUE THREAD

**Issue by ModeBan** [Myddleware/myddleware#656]
Hi Guys,

There is 404 errors on the web page see below.

![image](https://user-images.githubusercontent.com/21164341/154495910-9b29ecd5-ce2e-412a-b72f-e0175449353d.png)

Seems to be an issue where the url is built using an extra build.

/build/build/images/logo.f27dc0c8.png
instead of /build/images/logo.f27dc0c8.png

**Comment by Myddleware** [comment]
Hi @ModeBan ,
Yes there is a bug in a specific case when your install Myddleware in linux. We think it depends alos on the web server.
Here is a workarond untilwe find the right solution. Go to public directory with a terminal and run this command : 
`rsync -Rr ./build/ ./build/`
