### ISSUE TITLE
Two bundles defining table cron_job lead to error message cron_job already exists

### ISSUE THREAD

**Issue by ulrichbayer** [Myddleware/myddleware#662]
I am using [Release 3.0.7c](https://github.com/Myddleware/myddleware/commit/a3067769e719049c0635bc6e216de26726883fc3):

When I execute:

`bin/console doctrine:schema:update`

I get the following error message:

```
In SchemaException.php line 112:
                                                             
  The table with name 'myddleware.cron_job' already exists.  
```

The problem is in my opinion that both of the following packages define a table cron_job:

- shapecode/cron-bundle
- cron/cron-bundle

**Comment by ulrichbayer** [comment]
I have solved the problem by removing cron/cron-bundle since it seems unused.

Steps:
1. `composer remove cron/cron-bundle`
2. and removing the line `Cron\CronBundle\CronCronBundle::class => ['all' => true],` in `config/bundles.php`.

**Comment by stlgaits** [comment]
Hi, thank you very much for this message. I have made a correction applying your solution.
