### ISSUE TITLE
Implement Code Quality  & Performance Tools 

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#668]
Code must be cleansed using code quality tools such as php-cs-fixer
https://github.com/FriendsOfPHP/PHP-CS-Fixer 
https://cs.symfony.com/ 

It will also require manual cleaning (removal of useless comments, fixing undefined variables etc)

In addition, a clear strategy must be adopted regarding code quality & performance third-party libraries (Codacy ? [Symfony Insight](https://insight.symfony.com/) ? [Blackfire](https://www.blackfire.io/) ?...) and then deployed to repo to help us further maintain our code source up-to-standards.

**Comment by stlgaits** [comment]
https://github.com/Myddleware/myddleware/commit/467c0cd97ddaae8096bd1c688f2f4133e651b920
first commit regarding code quality / purge

**Comment by AlexMyddleware** [comment]
To reopen in case of redeveloping
