### ISSUE TITLE
myddleware 3 missing buttons

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#670]
Hi,
in myddleware 2 in every rule we have these buttons:
![image](https://user-images.githubusercontent.com/6990139/156573101-47d4430d-f60d-4aa8-8d66-0b8f36c5c784.png)
In myddleware 3 these:
![image](https://user-images.githubusercontent.com/6990139/156573201-f2645fca-296a-4c52-93d8-fd3f86588751.png)
why CANCEL TRANSFER and DELETE TRANSFER are missing? 
these buttons are extremely useful

**Comment by stlgaits** [comment]
Hi @simonetravaglini , this is a feature which requires super admin privileges for your Myddleware user. You can activate these using the php bin/console myddleware:promote-user <youruser@emailaddress.com> ROLE_SUPER_ADMIN
