### ISSUE TITLE
duplicate rule issue

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#671]
Hi,
if I duplicate a rule with mysql as source then I can't see source fields in mapping for all rules with same connection:
![image](https://user-images.githubusercontent.com/6990139/156575523-c0721737-b544-4483-b758-c9f55832d2e4.png)

**Comment by Myddleware** [comment]
Hi @simonetravaglini , 
Thanks for this test. We will check it.
For information, we are fixing the last bugs on the duplicate rule feature on this branch : https://github.com/Myddleware/myddleware/commits/feature---scheduler
We plan to merge it tomorrow or early next week.
We will keep you updated.

**Comment by simonetravaglini** [comment]
Hi, it seems that it's no related to duplication.
But if I have 1 rules on mysql and then I add a second rule, then I face this problem. Did you have evidence of that?
In first rules fields are available, but not in following rules...
@Myddleware @EstelleMyddleware

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
We can't reproduce the issue. Could you tell us the version of Myddleware you are using ? Could you also tell us  how to reproduce the issue ? 
Thanks.

**Comment by francescobianco** [comment]
Hi @Myddleware I found the problem!
There are few query still using CapitalLetter tables:
- https://github.com/Myddleware/myddleware/blob/main/src/Solutions/database.php#L614

**Comment by Myddleware** [comment]
Thanks @francescobianco ,
We have fixed it, it will be merged in main today or tomorrow depending on our tests
https://github.com/Myddleware/myddleware/commit/7a49c37aefb15d9a6d6f8f0c2d043f27fc0051a2
