### ISSUE TITLE
Replace SwiftMailer by Mailer

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#672]
SwiftMailer is abandoned and needs to be replaced with Symfony Mailer

**Comment by stlgaits** [comment]
Mailer seems to be working fine with the new configuration, however, because emails don't actually send in dev environment (they remain visible only in the dev / web profiler toolbar), we will still need to ensure this is correctly implemented in prod

**Comment by AlexMyddleware** [comment]
To reopen in case of redeveloping
