### ISSUE TITLE
Manual simulation with DB

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#686]
Hi, if I want check a single record in manual simulation and source is a DB, what I have to set to get result?
in vtiger I have to set module x id record (ex 33x1204).
IN mssql?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
You are right, the manual simulation works for MySQL only if the fieldId is named "id". We will fix this bug.
I 'll keep you posted.

**Comment by simonetravaglini** [comment]
@Myddleware news?

**Comment by Myddleware** [comment]
Hi @simonetravaglini , 
We have done this small fix bug you have to save the field "Primary key in your source table" first, then edit the rule again and simulate the record.
Hope it will be OK for you.

**Comment by Myddleware** [comment]
We plan to release Myddleware 3.2.0 this week.

**Comment by AlexMyddleware** [comment]
@simonetravaglini  this issue seems to be fix, but feel free to re open it if the problem persists.
