### ISSUE TITLE
local installation

### ISSUE THREAD

**Issue by ibeppo993** [Myddleware/myddleware#70]
I'm trying to install myddleware locally, with XAMPP, but it gives me this issue: http://prntscr.com/i4fby6
How can I solve?
thanks

**Comment by Myddleware** [comment]
Hi,
Thanks for using Myddleware.
Could you try to run the php command directly in your windows command prompt. Maybe the word "php" is unknown by windows. In this case, you will have to set environment variables, could you check if php is regestered in your environment variables ? 
Here is something you should have (with a different path as you have to reach your php program), sorry for the french screenshot : 
![php_variable](https://user-images.githubusercontent.com/11330301/35279713-35f94e10-0024-11e8-9748-ab6830dc9464.png)

Please let us know if it works.

**Comment by ibeppo993** [comment]
i have to set environment variable,  
https://prnt.sc/i4ggjo but the issue continue. http://prntscr.com/i4gqnz
thanks

**Comment by Myddleware** [comment]
Hi,
Could you run the command php app/check.php (from you myddleware directory) in your windows prompt ? 
It will test you configuration and confirm that "php" work is known?
Thanks.

**Comment by ibeppo993** [comment]
it gives me this: http://prntscr.com/i4gwmk
thanks a lot for help.

**Comment by Myddleware** [comment]
This is perfect ;)
OK so there is probably a right problem on you cache folder for teh installation via the web page.
So could you try to install Myddlewar via command by following this tutorial : https://myddleware.github.io/myddleware/#/?id=install-myddleware

If you have a problem with this command : php app/console cache:clear --env=prod
You can just clear every folders (if exist) in the directory app/cache/ 

Please let me know if it works for you. Thanks.

**Comment by ATrogischDev** [comment]
Hi,
I had the same issue, the install via command works perfect. 

Thanks for Help 👍 

Just one thing is wrong in the installation guide:

> Create a database on your server then change these parameters in the file /myddleware/app/config/myddleware.yml

should be:

> Create a database on your server then change these parameters in the file /myddleware/app/config/parameters.yml

**Comment by Myddleware** [comment]
Hi,

Thank you so much for your feedback. We have changed the name of the file in the toturial.

Have a nice day.

**Comment by ibeppo993** [comment]
when i try to install Install via command, when i am in step: 
Create tables into your database
    php app/console doctrine:schema:update --force --env=prod
it report me this error: http://prntscr.com/i8jgcx
how can i solve?
thanks
