### ISSUE TITLE
Feat: Add the 'Install Myddleware' page/series of pages to allow users to setup Myddleware from browser

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#704]
- When user doesn't have a .env.local file yet, they are redirected towards route "install_requirements", however for now this route doesn't have any linked controller method to it & needs to be implemented
- We can take inspiration from Myddleware 3  & adapt the code( https://github.com/Myddleware/myddleware/blob/main/src/Controller/InstallRequirementsController.php & https://github.com/Myddleware/myddleware/blob/main/src/Controller/DatabaseSetupController.php ) 
- Steps needed:
    - checking Symfony requirements are met (PHP version, PHP extensions, etc)
    - defining Myddleware database connection parameters
    - attempt to log in to database
    - creating & loading database schema + fixtures
    - creating Myddleware user (registration form is already present, will only need a redirect towards 'app_register' )

**Comment by AlexMyddleware** [comment]
To reopen in case of redeveloping
