### ISSUE TITLE
Migration from myddleware 2 to myddleware 3

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#708]
Hi,
becouse myddleware 3 is extremly faster than 2 I want to understand how to manage migration in 2 different scenarios

1 - EASY - No need to migrate document: just need to move rules from 2 to 3. Can we simply use templates?
2 - Need to migrate everythings: there is a standard way to do migration?

@francescobianco

**Comment by Myddleware** [comment]
I advise you the second option. The most difficult part will be to adjust your custom code from Myddleware2 to Myddleware3. Please let me know by opening a new issue if you need more instruction about adding custom code in Myddleware 3. We are writing a new documentation website but it is isn't ready yet (https://myddleware.github.io/myddleware/#/)

Here are the instructions to upgrade Myddleware from version 2 to version 3 :
**Myddleware Upgrade Procedure** 

This procedure details how to upgrade from Myddleware 2.x to Myddleware 3.x. Throughout this process, the core software of Myddleware will be upgraded from Symfony 3.4 to Symfony 4.4, which is the engine that allows Myddleware to run, however we will also upgrade Myddleware’s code itself. 

**Back up your current Myddleware install** 

Before launching this upgrade procedure, create a backup of all your Myddleware files in a safe spot. 

We strongly recommend that you use git to ensure the upgrade process is smoother. If you don’t have git on your server, please follow this link: https://git-scm.com/download/linux  

**Technical requirements** 

You will first need to upgrade your PHP version to PHP 7.4. DO NOT upgrade to PHP 8.0 or 8.1 as Myddleware is not yet compatible with these versions. https://www.php.net/downloads.php  

The following extensions must be installed and enabled (they usually are by default): 
- Ctype 
- Iconv 
- JSON 
- PCRE 
- Session 
- SimpleXML 
- Tokenizer 

You need to upgrade Composer to Composer 2.x :  https://getcomposer.org/download/  .This can also be achieved by running the following command in your current Myddleware directory:  
`composer self-update `

You need to have the Symfony CLI installed as well. You can download the appropriate version here: https://symfony.com/download 

This will allow you to run the following commands in your terminal which will help to give you further info in case you’re missing some requirements:  
`symfony check:requirements `

Node.js version 14.16.1 https://nodejs.org/en/download/ 

Yarn version 1.22.10 https://classic.yarnpkg.com/lang/en/docs/install/#windows-stable  

Please ensure to download the exact versions of Node.js & yarn listed above as the very latest versions aren’t yet compatible with Myddleware. 

It is possible that according to your webserver, there might be some missing requirements. If you’re unsure, please check section 1.1. of the installation guide here: 
https://myddleware.github.io/myddleware/#/?id=technical-requirements

**Stop all scheduled tasks** 
If you use linux, comment the line that runs Myddleware in your crontab. If you use windows, stop Myddleware task in the task scheduled. 

**Clear your Myddleware cache** 
In your Myddleware root directory, run the following command in a terminal: 
```
php bin/console cache:clear --env=prod 
php bin/console cache:clear --env=background 
```
Alternatively, if this doesn’t work, you can delete the /myddleware/var/cache directory’s contents manually. 

**Fetch files from Git** 
If you have never used git with Myddleware, please run these commands from your Myddleware root directory: 
```
git init 
git remote add -t main origin https://github.com/Myddleware/myddleware.git 
git fetch 
git checkout origin/main -ft 
```
If you have custom code: remove directory src/Myddleware. But keep your custom code. 

**Install Myddleware** 
Go to the Myddleware root directory: 
`cd myddleware `
Install the vendors : 
`composer install `
Install assets : 
`yarn install `
Build assets : 
`yarn build `

 Create a .env.local file at the root of your myddleware subdirectory. This file will override the configuration defined in the .env file. Inside this file, add the following line and put your database parameters that you can find in the file myddleware\app\config\parameters.ym : 
```
DATABASE_URL= "mysql://username:password@host:port/dbname" 
APP_ENV=prod 
APP_DEBUG=false 
```

Copy the secret from your file myddleware\app\config\parameters.yml and paste it here:  
`APP_SECRET=<your secret from Myddleware2> `

Copy your custom code that you have adapted to Myddleware3 

Finally run these commands:  

```
php bin/console doctrine:schema:update --force 
php bin/console doctrine:fixtures:load --append 
php bin/console myddleware:upgrade --env=background 
```

If several images are missing (like the logo for example), rune this command from the directory <myddleware>/public
`rsync -Rr ./build/ ./build/ `

**Comment by fosullivan-usam** [comment]
Is there an equivalent process for upgrading from Version 3 to Version 4?

**Comment by Myddleware** [comment]
Hi @fosullivan-usam,
Sorry for the delay in my response. Yes, you can follow the same steps, but please make sure that your server is compatible with the version 4 requirements: : https://myddleware.github.io/myddleware-docs/#/?id=technical-requirements.
Also, don’t forget to back up your server first.
Have a great day.
