### ISSUE TITLE
Bug: when loading fixtures, error thrown saying references don't exist... but they do !

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#709]
I've followed documentation & implemented DependentFixtureInterface with method getDependencies()
And referenced fixtures using for example
```
// src/DataFixtures/UserFixtures.php 
  $this->addReference(self::FIRST_USER_REFERENCE, $user);
```
```
// src/DataFixturesJobschedulerFixtures.php
  $this->getReference(UserFixtures::FIRST_USER_REFERENCE) 
```
https://symfony.com/bundles/DoctrineFixturesBundle/current/index.html#sharing-objects-between-fixtures
https://symfony.com/bundles/DoctrineFixturesBundle/current/index.html#loading-the-fixture-files-in-order

However, when loading fixtures, I get the following error :
![image](https://user-images.githubusercontent.com/74190794/161568338-3c3adb00-8520-4bc4-9031-88c2e64ca811.png)

See [connectorparams](https://github.com/Myddleware/myddleware/tree/connectorparams) branch

**Comment by AlexMyddleware** [comment]
To reopen in case of redeveloping
