### ISSUE TITLE
Microsoft SQL: problem on CREATE and UPDATE records on DB

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#716]
Actually into base solution called 'database.php' all values prepared for the INSERT or UPDATE queries are submitted with a forced string syntax.

Look at this lines:
- https://github.com/Myddleware/myddleware/blob/main/src/Solutions/database.php#L408
- https://github.com/Myddleware/myddleware/blob/main/src/Solutions/database.php#L448

Is visible that the single quote (') is hardcoded. This is problematic for some version of MicrosoftSQL because if field is numeric you cannot pass value as string. Generally if you try, it respond with message like this:

```
ERROR (8114): Error converting data type varchar to numeric.
```

cc @simonetravaglini @Myddleware @EstelleMyddleware

**Comment by simonetravaglini** [comment]
@Myddleware did you had opportunity to give a look?

**Comment by Myddleware** [comment]
Hi @simonetravaglini and @francescobianco, very sorry for the delay.

We could probably run a query to get the field type before we generate the query. Then we could add the quote only for non numeric fields. 
Do you agree with this list of field type that shouldn't be separated by quote ?
bigint
numeric
bit
smallint
decimal
smallmoney
int
tinyint
money
float
real

Thanks.

**Comment by francescobianco** [comment]
Good point! Could be better usa an array like this on the Solution file, 

```
$ignoreQuotesOnQuery = [
'bigint',
'numeric'.
etc...
];
```

**Comment by AlexMyddleware** [comment]
https://github.com/Myddleware/myddleware/pull/1147/commits/f2e2b1f07dc852f4e9ee7a8b40e68ddb344d8ec1

https://github.com/Myddleware/myddleware/pull/1147/commits/9f015b065e8aa882b1bc6b6f35bb4b2a7cfd4308
added a way to handle non string values
