### ISSUE TITLE
Double level of customizations [Mydd 3.0/main]

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#724]
Hi! 

We need to have two level of customizations for a Solution/Connector,
in other words we want use two different files over the same 'microsoftsql.php'

One placed into `src/Custom/Solutions` directory and Another placed into `src/SpecialCustom/Solutions` directory

In this way we want this three files works as final Solution

- BASE: `src/Solutions/microsoftsql.php`
- FIRST OVERRIDE: `src/Custom/Solutions/microsoftsql.php`
- SECOND OVERRIDE: `src/SpecialCustom/Solutions/microsoftsql.php`

The final class MUST be the logic sum of all three class with inheritance.

cc @simonetravaglini @Myddleware @EstelleMyddleware

**Comment by Myddleware** [comment]
Hi @francescobianco ,
You can use decorator service. Here is more detail about it : https://github.com/Myddleware/myddleware/issues/664
You should use the priority parameter to set the highest priority for your second override if it exists. Here is the documentation : https://symfony.com/doc/current/service_container/service_decoration.html#decoration-priority

Please let me know if it helps.

**Comment by AlexMyddleware** [comment]
Hello,

we take the liberty to close this problem, however if you encounter a bug equal or similar to this one do not hesitate to reopen the issue.

Thanks
