### ISSUE TITLE
Error Message not Clear

### ISSUE THREAD

**Issue by JiahuiLuData** [Myddleware/myddleware#725]
Hi

I am doing the sync between from one SuiteCRM instance to another, and here is the error message i have got:

**error : Failed to send document. Status : Error_sending**

, which is different from the previous detailed error messages including the missing field name and other info. That has made my troubleshooting process much harder, so just wanna ask about the possible reason causing this problem. Thanks!

**Comment by Myddleware** [comment]
Hi @JiahuiLuData ,
Thanks for using this forum.
Wheh you get this error in Myddleware, it means that Myddleware couldn't send the document and SuiteCRM didn't return any error. 
Could you give us more detail about the document you tried to send ? Have you successfully sent other documents with the same rule ? 
Thanks.
