### ISSUE TITLE
Error Page selection button not working

### ISSUE THREAD

**Issue by JiahuiLuData** [Myddleware/myddleware#726]
Hi

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/91266642/167154904-68766077-6276-4461-9f30-562dd54719f3.png">

The buttons on the error document list for jumping between pages are not working. Whenever I click on the button it redirects me to this page:
<img width="457" alt="image" src="https://user-images.githubusercontent.com/91266642/167156205-dc405cb6-8305-481f-a576-464841880959.png">

The log file error message is shown as below:

 request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Page not found. Page "2" does not exist. The currentPage must be inferior to "1"" at /home/default/html/myddleware/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php line 294 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Page not found. Page \"2\" does not exist. The currentPage must be inferior to \"1\" at /home/default/html/myddleware/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php:294)"} []

I am using Myddleware - version 3.0.4a.

Thanks

**Comment by Myddleware** [comment]
Thanks @JiahuiLuData ,
We can reproduce this issue. We will do our best to fix fpor the next release. We will keep you posted.
Have a nice day.

**Comment by AlexMyddleware** [comment]
Hello,
We take the liberty to close this problem, however if you encounter a bug equal or similar to this one do not hesitate to reopen the problem. 
Thanks.
