### ISSUE TITLE
Error : FieldId has to be specified for the read. Myddleware\RegleBundle\Solutions\databasecore Line : ( 308 

### ISSUE THREAD

**Issue by Tanoh-Hermann** [Myddleware/myddleware#73]
Hello everyone. 

Has anyone ever encountered the following error:

Error : **FieldId** **has to be specified for the read**. Myddleware\RegleBundle\Solutions\databasecore Line : ( 308 

If so, what solution did you use to solve it? Thank you for sharing your experience with beginners.

**Comment by Myddleware** [comment]
Hi Tanoh,
Are you tryng to send data to a database (MySQL or MSSQL ?) or are you trying to read data from the database ? 
If you are trying to send data to a database, did you select a "Primary key" : 
![target_id](https://user-images.githubusercontent.com/11330301/35648234-7b5f5c5a-06ab-11e8-98f5-07c42ad3ee99.png)


This field has to be the reference in your table. Myddleware will use it in the case you want to update data already existing in your database.

Please let me know if it helps you.
Have a nice day,
Stéphane

**Comment by Tanoh-Hermann** [comment]
Hello!
I can not find, the field: ID Calls-to-mysql in drop-down menu. 

In fact, I want to synchronize my Mysql databases, through creation and modification of users data. At first, I want to synchronize users of the different databases (joomla, prestashop, dolibarr, and Moodle). But I get two error messages:
1 - Error : FieldId has to be specified for the read. Myddleware\RegleBundle\Solutions\databasecore Line : ( 308 )  by executing rules, and
2 - The CSRF token is invalid, Please return the form, ( filtering tasks).

**Comment by Myddleware** [comment]
Hi Tanoh,

So you want to send data to your database ? Am I right ?

Could you provide some screenshot to help us to identify your problems.

Other thing, the list in my the screenshot is an example. You should have the list of the fields of your own table you have selected (in module). You have to select the field which is the unique ID in your table.

Thanks.
