### ISSUE TITLE
No result from ERPNext Error

### ISSUE THREAD

**Issue by SharleneNdinda** [Myddleware/myddleware#735]
Hello,

I am using Myddleware version 3.1.1 and i am trying to transfer data from Salesforce to ERPNext. 

For Instance, I try to transfer account data from Salesforce to ERPNext, however the data does not transfer and brings up the error "No result from ERPNext. Failed to send document. Status : Error_sending"

![Screenshot (316)](https://user-images.githubusercontent.com/42218883/169337825-d8a7007e-718b-490e-9f3b-75ad80936465.png)

Please assist, thank you

**Comment by Myddleware** [comment]
Hi @SharleneNdinda,
We will try to reproduce you issue early next week.
We will keep you posted.
Best regards,
Stéphane

**Comment by Myddleware** [comment]
Hi @SharleneNdinda ,
Sorry for the delay of my answer. Busy time !
We have fixed the ERPNext issue in this commit : https://github.com/Myddleware/myddleware/commit/ffcdb6f88a61cb3f4f8da02aacada13de88ac04f
We will merge this commit into the main branch this week. 
You can change your ERPNext file manually or wait for our next release. 
Best regard,
Stéphane

**Comment by AlexMyddleware** [comment]
Hello,
We take the liberty to close this problem, however if you encounter a bug equal or similar to this one do not hesitate to reopen the problem. 
Thanks.
