### ISSUE TITLE
Cannot create new JOB on Job Scheduler [Mydd V3]

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#737]
If i create a new Job/Command into JobScheduler with the follwing arguments

```
Command: Synchro
Param Name 1: rule
Param Value 1: All active rules
Period: 5
Job order: 1
```

An error go back after "Create" click

```
ERROR This value is not valid.
```

Look how it appear

![Screenshot from 2022-05-24 15-42-29](https://user-images.githubusercontent.com/472171/170050975-1caaeef2-e446-421d-95a2-37350d1ed338.png)

**Comment by Myddleware** [comment]
HI @francescobianco ,
You should use the new crontab here : 
![image](https://user-images.githubusercontent.com/11330301/172255474-a623669c-e05f-4c0f-9a27-bbdf3239d13c.png)

Then add this command into your crontab : 
`*/5 * * * * cd <myddleware_directory>; php bin/console myddleware:cronrun --env=background`

Hope it will help you.

**Comment by simonetravaglini** [comment]
@Myddleware @francescobianco it's ok use crontab, but why you can access to rules creation and get error when saving?
IT's a normal behaviour?

**Comment by Myddleware** [comment]
hI @simonetravaglini ?

No It isn't a normal behavior. Sorry for that. We don't maintain this view anymore, it will be removed in the next main version. 

But if you really want to use this view, you can still modify it inthe database, table jobscheduler. You can set All or the rule id into the param1 column.
![image](https://user-images.githubusercontent.com/11330301/175124205-114aafa8-3cf5-40b4-bfe5-5096251afc1b.png)

Please let me know if it helps you.

**Comment by simonetravaglini** [comment]
ok thanks now is clear! @francescobianco

**Comment by AlexMyddleware** [comment]
Hello,
We take the liberty to close this problem, however if you encounter a bug equal or similar to this one do not hesitate to reopen the problem. 
Thanks.
