### ISSUE TITLE
issue creating MS SQL server connector

### ISSUE THREAD

**Issue by ibeppo993** [Myddleware/myddleware#74]
I'm trying to connect prestashop with a ms sql server, 
in prestashop I create the connection and it works all, instead on ms sql server I insert the data and it brings me back:
! Connection failed : could not find driver C:\xampp\htdocs\myddleware\src\Myddleware\RegleBundle\Solutions\microsoftsql.php Line : ( 40 )

how can i solve?
thanks

**Comment by Myddleware** [comment]
Hi,
We are currently working on MSSQL connector because the driver is different for Windows and Linux.
Is Myddleware installed on a windows server or a linux server ?
Thanks.
Best regards.

**Comment by ibeppo993** [comment]
in a windows server, thanks for the quick reply
------Edit 15:32
*is in localhost whit xampp on windows*

**Comment by Myddleware** [comment]
What is the version of your Myddleware  (you can see it in the footer in Myddleware) ?
Could you also check the file :  myddleware/src/Myddleware/RegleBundle/Solutions/microsoftsql.php
Do you have this at the line 30 : protected $driver = 'sqlsrv';   ?
Thanks.

**Comment by ibeppo993** [comment]
My versione is v2.3.3e,

yes, i have.
This is the file:
26- namespace Myddleware\RegleBundle\Solutions;
27-
28- class microsoftsqlcore extends database {
29-
30- protected $driver = 'sqlsrv';
31-
32- protected $fieldName = 'COLUMN_NAME';
33- protected $fieldLabel = 'COLUMN_NAME';
34- protected $fieldType = 'DATA_TYPE';
35-
36- protected $stringSeparatorOpen = '[';
37- protected $stringSeparatorClose = ']';
38-
39- protected function generatePdo() {		    
40-		return new \PDO($this->driver.':Server='.$this->paramConnexion['host'].','.$this->paramConnexion['port'].';Database='.$this->paramConnexion['database_name'],$this->paramConnexion['login'], $this->paramConnexion['password']);
41-	}

thanks

**Comment by Myddleware** [comment]
Alright, this code is for windows so everything is ok there.

Maybe, the driver sql server for PHP PDO isn't enabled. Which server web are you using (Apache with Xamp, Apache with Wamp, ISS...) ? 

Thanks.

**Comment by ibeppo993** [comment]
Xampp + apache

**Comment by Myddleware** [comment]
Alright,
Could you try to install sqlsrv driver with the help on this page : http://php.net/manual/en/ref.pdo-sqlsrv.php
Then your connector should work.
Please let me know if it works.
Have a nice day.

**Comment by ibeppo993** [comment]
I copy the file of sqlsrv32.exe (who support my php versione) in xampp\php\ext on ts because i have thread safety enable, but nothing change.

**Comment by Myddleware** [comment]
Hi,
Could you try agai with the latest version of Myddleware ? 
Please come back to us if you still have a problem.
Thanks.
