### ISSUE TITLE
Problem on change password [Mydd 3]

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#741]
Change password page seems broken due to a typo on capital letter of twig rendering

In this line
https://github.com/Myddleware/myddleware/blob/main/src/Controller/AccountController.php#L170

The word `account/resetPassword.html.twig` could be on capital letters `Account/resetPassword.html.twig`

**Comment by Myddleware** [comment]
Thanks @francescobianco 
@EstelleMyddleware could have a look into this ?

**Comment by stlgaits** [comment]
Thank you @francescobianco for this, I didn't notice this before as this doesn't generate an error for me, most probably because I'm on a Windows PC, this should be corrected in hotfix today.
https://github.com/Myddleware/myddleware/pull/742
