### ISSUE TITLE
After install all pages return 404

### ISSUE THREAD

**Issue by avico-her** [Myddleware/myddleware#746]
I am new to myddleware, installed according to writen instructions.
Now i get only the login page all other pages return a 404 error.
no problem seen in logs of apache or myddleware.

**Comment by stlgaits** [comment]
Hi, could you let me know specifically which steps / way of installing you used ? The reason I'm asking is that there are multiple ways of installing Myddleware.

Could  you run these commands and show me the output: 
`symfony check:requirements`
and
`php bin/console doctrine:schema:validate`

**Comment by avico-her** [comment]
Thank you very much,
I managed finally to find the problem,
As created a SSL certificate, and a VM it caused the allow override to be ignored.
I  changed the container and it works.

Thank you
