### ISSUE TITLE
issue creating connector for Prestashop 1.7

### ISSUE THREAD

**Issue by seseso** [Myddleware/myddleware#75]
When trying to create a connector to Prestashop 1.7, I get an error:
_Connection failed : This call to PrestaShop Web Services failed and returned an HTTP status of 400. That means: Bad Request._ 

Is Prestashop 1.7 not supported?

**Comment by seseso** [comment]
My bad, sorry! I was including in the URL the /api/ wich should not be done, acording to the documentation.

Thanks!

**Comment by Myddleware** [comment]
No problem.

Come back to us if you have any other questions.

Best regards.
