### ISSUE TITLE
Can't cancel a document in version 3.1.5

### ISSUE THREAD

**Issue by RomanFaure** [Myddleware/myddleware#750]
On version 3.1.5 : When I cancel a document in error, the link to see the task is "Failed to create the job" and the doc is not canceled

**Comment by stlgaits** [comment]
This should now be fixed once [this PR](https://github.com/Myddleware/myddleware/pull/752) is accepted into the Release : 
![image](https://user-images.githubusercontent.com/74190794/173612706-c9b7e243-c96b-4aa8-85ab-06bab4415c67.png)
![image](https://user-images.githubusercontent.com/74190794/173613089-7cdc1fec-7985-4d94-b0f8-b7d0320d45ad.png)
