### ISSUE TITLE
Error thrown when trying to create a connector (when selecting a Solution, the ConnectorParams / Credentials form should be displayed below)

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#753]
https://github.com/Myddleware/myddleware/pull/751
When selecting a solution in Create Connector Page, instead of displaying the ConnectorParams form, an error is thrown which I do not totally understand. 
![image](https://user-images.githubusercontent.com/74190794/173851478-fb437495-b041-4c5b-abea-bb49dbffd6c7.png)
![image](https://user-images.githubusercontent.com/74190794/173851538-26905abe-536e-4e9b-b961-c330669add94.png)
![image](https://user-images.githubusercontent.com/74190794/173851604-26a6c801-97b7-4623-b708-4d9ad9e969f4.png)
![image](https://user-images.githubusercontent.com/74190794/173851271-6656df27-3b0d-4525-a738-0fc03899f224.png)
Also please bear in mind if testing in local dev env that the AJAX request is super slow, especially to display the debug result, it can take up to 30sec to display the profiler's response. 
![image](https://user-images.githubusercontent.com/74190794/173852824-466528f3-606b-4746-8f22-078a0aea13b2.png)

Most of the relevant code is located in ConnectorController.php, ConnectorType.php, ConnectorParamFormType.php & ConnectorParamValueTransformer.php
Anny help appreciatied at this stage.

**Comment by AlexMyddleware** [comment]
To reopen in case of redeveloping
