### ISSUE TITLE
Error with Source filed listed into Target fields [Myddleware 3]

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#758]
During syncronization of a Rule with a Subrule (relation of type parent) uset to sync line items of Invoice as show in this image
![MicrosoftTeams-image](https://user-images.githubusercontent.com/472171/175490553-4978568a-62bb-412a-9b1b-cfcba5e9bb38.png)

We have the following error

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/472171/175490764-a5b5c61c-7db5-4da5-98f8-050017f683db.png)

It happen only during UPDATE and not at CREATE

The field called "CHIAVE" is a field from SOURCE and not exists it on TARGET system.
The query to fetch target data is the following

```sql
SELECT 
       id,
       modifiedtime,
       createdtime,
       subject,
       bill_city,
       bill_code,
       bill_country,
       bill_state,
       bill_street,
       chiave,
       invoicedate,
       numero_documento,
       serie,
       ship_city,
       ship_code,
       ship_country,
       ship_state,
       ship_street,
       tipo_documento_fattura,
       account_id,
       agente,
       condizioni_pagamento, 
       CHIAVE
 FROM Invoice
 WHERE id = '2x89628'
 LIMIT 0, 100;
```

After a small debug session we have found that the following line MUST be commented out to work
`$fields[] = $ruleRelationShip['field_name_source'];`

https://github.com/Myddleware/myddleware/blob/7601bf750f14f6b6c23a6ea67d59c3b71fe38ab7/src/Manager/DocumentManager.php#L1618

```php
                $ruleRelationShips = $result->fetchAllAssociative();
                if (!empty($ruleRelationShips)) {
                    foreach ($ruleRelationShips as $ruleRelationShip) {
                        // If it is a normal relationship we take the target field
                        // but if it is a parent relationship we have to take the source field in the relation (wich corresponding to the target field)
                        if (empty($ruleRelationShip['parent'])) {
                            $fields[] = $ruleRelationShip['field_name_target'];
                        } else {
                           // This line was commented to avoid listing SOURCE fields into TARGET fields list 
                           //  $fields[] = $ruleRelationShip['field_name_source'];
                        }
                    }
                }
```

Unfortunately this could create some problem or issue in others feature that we can't complain at moment

cc @simonetravaglini @Myddleware @myddleware-dev

**Comment by francescobianco** [comment]
Any luck @Myddleware @myddleware-dev @CamillePMyddleware ?

**Comment by Myddleware** [comment]
HI @francescobianco 
Sorry for the delay. We will do our best to answer you tomorrow.
Have a nice day

**Comment by Myddleware** [comment]
Hi @francescobianco ,
Thanks for the detail of your message. This is probably a bug. I think that it should always be the source field event for a parent relationship.
Could you try to replace : 
```
// If it is a normal relationship we take the target field
// but if it is a parent relationship we have to take the source field in the relation (wich corresponding to the target field)
if (empty($ruleRelationShip['parent'])) {
	$fields[] = $ruleRelationShip['field_name_target'];
} else {
	$fields[] = $ruleRelationShip['field_name_source'];
}
```
By 
`$fields[] = $ruleRelationShip['field_name_target'];`

I think that we haven't seen the bug when we have developped tested it because we developped it for Prestashop first. And all tables have an "id" field in Prestashop.  For example, by requesting the source field for an order, we requested the "id" field which exist in the order line table too. At the end we had no error but we had had the wrong id. We didn't see it because it is just for history data.
Could you test the change and let us know if it works. If yes we will apply it to the next version of Myddleware. Or you could create a pull request if you prefer.

Have a nice day.

**Comment by Myddleware** [comment]
Hi @francescobianco ,
Did you try the fix ? If yes does it work as expected. If yes we will fix Myddleware 's code.
Thanks.

**Comment by AlexMyddleware** [comment]
Hello,
We take the liberty to close this problem, however if you encounter a bug equal or similar to this one do not hesitate to reopen the problem. 
Thanks.
