### ISSUE TITLE
Reset Password Email Link throws "No reset password token found in the URL or in the session."

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#765]
When clicking the email's link, an error is triggered. It seems the token is not sent properly

![image](https://user-images.githubusercontent.com/74190794/177582071-374b05e8-60ea-49db-bb63-591d6ca35ebf.png)

![image](https://user-images.githubusercontent.com/74190794/177581904-9664d639-b897-431a-8c42-5e88aefc6b6b.png)

**Comment by AlexMyddleware** [comment]
To reopen in case of redeveloping
