### ISSUE TITLE
Hubspot field not getting populated

### ISSUE THREAD

**Issue by lokwaniyash** [Myddleware/myddleware#766]
![image](https://user-images.githubusercontent.com/12872852/177718243-c816eef7-8587-49f6-b959-49732aa2748c.png)
I made a connector for hubspot, and also tried to use the api call to fetch the fields, it worked from postman
salesforce fields seem to be getting populated as well, I've rechecked the api key, and tested the api myself so I'm sure the api key is correct, could you guys help me solve this, thanks

**Comment by Myddleware** [comment]
Hi @lokwaniyash ,
We can't reproduce you issue in Myddleware 3.1.5 : 
![image](https://user-images.githubusercontent.com/11330301/177881845-cc7c3ffd-7a0c-4b8f-852b-654ca5ff2c06.png)

Please could you tell me what Myddleware version you use ? Thanks

**Comment by AlexMyddleware** [comment]
Hello,

we take the liberty to close this problem, however if you encounter a bug equal or similar to this one do not hesitate to reopen the issue.

Thanks
