### ISSUE TITLE
[MYD3] Template issues

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#770]
Hi, playing with templates I found this 2 issues:
1 - if when loading a template an error occours the error it's not logged at frontend (in MYD2 I get a message with the error in example a missing field)
2 - if I have more than 1 template on same connectors, when I select a template, it could happen that load a different one

**Comment by simonetravaglini** [comment]
@Myddleware do you think you can manage this issue soon?

**Comment by CamillePMyddleware** [comment]
Hello @simonetravaglini, I am currently reproducing your issue and I can confirm that there is an unlogged bug which seems to be a doctrine error. I will investigate this further and keep you posted 
![image](https://user-images.githubusercontent.com/95077335/179756057-3aa36ff8-a903-4a0e-8dbc-054b8431065d.png)

@Myddleware I am unable to generate av template :'(

**Comment by Myddleware** [comment]
Hi @simonetravaglini , 
We forgot to tell you that we have fixed the issue here : https://github.com/Myddleware/myddleware/commit/ccef683bacad765d8385ad9050551b94b70ad0a4
Please upgrade Myddleware, it whould work now.
Let us know if you have any other issue.
