### ISSUE TITLE
Job Scheduler not working after update from 3.0.4a to 3.1.5

### ISSUE THREAD

**Issue by JiahuiLuData** [Myddleware/myddleware#771]
After upgrading myddleware, my job scheduler synchro stopped working( but manually running the rules is still ok). So I followed the instruction here: https://myddleware.github.io/myddleware/#/cron_jobs , here are the things I have tried:

1. Run php bin/symfony_requirements:
                                                  
<img width="623" alt="image" src="https://user-images.githubusercontent.com/91266642/179536822-ba382366-9893-4235-bb8c-68620a90e761.png">

2. According to the previous error message, I tried php composer.phar install:
<img width="797" alt="image" src="https://user-images.githubusercontent.com/91266642/179537124-05d03356-c94e-400e-919d-9d173e9f6ded.png">

It seems like there is a compatibility problem with php7.4, so here is my question: do I need to downgrade the current php version to 7.3? It will also affect other software we currently used in production env, so is it possible to solve the problem without changing the php version? It was weird because the php7.4 worked fine on the previous myddleware version3.0.4a. 

Looking forward to your reply!

**Comment by Myddleware** [comment]
Hi @JiahuiLuData ,
You should use the new scheduler version in Myddleware 3.1 : 
![image](https://user-images.githubusercontent.com/11330301/179609935-df34391b-99b0-41a6-b0d3-cbd0f6da1403.png)

Then replace your jobscheduler command into your crontab by this command : 
`php bin/console myddleware:cronrun --env=background`

Please let me know if you need more help^.
Stéphane

**Comment by JiahuiLuData** [comment]
Hi Stephane,

Thanks for your timely reply! I have tried the method above and it worked, thanks! However, it kept sending me this email content:
 Hello,
<p>A job is running beyond the limit you have set up : 60 minutes<br/>
The job started at  .<br/>
ID of this job : <br/>
Please check whether this job is still transferring data. If it's not, please stop the job manually by opening the job and clicking on the button "Stop task".<br/>
%%</p>

As you can see above, it didn't tell me the exact task id that takes a long time which is not very friendly for troubleshooting. So I went to our myddleware database to see what has been opened and I found all of the tasks are having the status to be 'end'. Just wondering if you have any advice on how to find out the running task.

Thanks!

**Comment by Myddleware** [comment]
Hi @JiahuiLuData, we will do our best to reproduce an dfix this issue. 
@AlexMyddleware could you check this ? Thanks.

**Comment by Myddleware** [comment]
@JiahuiLuData , you can install the latest version 3.1.6a, it should be fixed.
Have a nice day.
