### ISSUE TITLE
Time zone issue in Myddleware user interface

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#78]
All the date time are stored with the GMT timezone i Myddleware database but should be displayed according the php default timezone.

**Comment by dawoodjee** [comment]
Hi

I set the correct timezone in php.ini. PHP has the right time and Myddleware even gets the right time for rule creation time. But the task time is still 2 hours slower like its using the old timezone.

Please see in the attached screenshots.

![time](https://user-images.githubusercontent.com/7912989/62426755-38e9ea80-b6e9-11e9-8b6d-858f120503bc.PNG)
![time2](https://user-images.githubusercontent.com/7912989/62426756-39828100-b6e9-11e9-836b-f13328efe8b8.PNG)
![time3](https://user-images.githubusercontent.com/7912989/62426757-39828100-b6e9-11e9-94b8-c913e8de5b06.PNG)

**Comment by Myddleware** [comment]
Hi,
Could you check these dates in your database (table Rule and table Job) and let me know if you have the same problem ?

It will help us to know if this problem come from the dates saved in the database or from Myddleware interface. 

Thanks.

**Comment by rulotec** [comment]
I have a similar problem. My php.ini file has timezone = America/Mexico_City
![image](https://user-images.githubusercontent.com/36896420/80929647-57ae0800-8d73-11ea-8b08-a51c1174312f.png)

I created a script similar to @dawoodjee which shows the correct time:

![image](https://user-images.githubusercontent.com/36896420/80929667-84fab600-8d73-11ea-9cfa-9c300f745114.png)

If I execute it through a browser I get the same result.

For some reason myddleware shows times in UTC both for rule creation times and tasks execution time. Is there somewhere in myddleware where we can configure the timezone?

Thanks!

**Comment by Myddleware** [comment]
Hi @rulotec ,
Yes, every Myddleware dates are managed in UTC. We will work on this to manage local timezone in the next main release. 
I 'll keep you posted.

**Comment by rulotec** [comment]
Ok, good to know. I'll wait for the new release. Thanks!

**Comment by CamillePMyddleware** [comment]
Hi, I am archiving this issue but please do not hesitate to re-open it if needs be.
Thanks.
