### ISSUE TITLE
Zuora connector & third-party API files are obsolete and need replacing

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#780]
All files in src/Solutions/lib/zuora are obsolete (dating back to 2011 - the Zuora API has since massively changed) and need to be removed and replaced with something matching the current Zuora API: https://www.zuora.com/developer/API-Reference/ 
I suggest potentially replacing all this with https://packagist.org/packages/mhrabovcin/zuora-rest which seems up-to-date and well maintained.
It goes without saying however that this change of lib will mean revamping the Zuora connector entirely (src/Solutions/Zuora) to be able to use the new REST API Client.

**Comment by Myddleware** [comment]
@EstelleMyddleware , we can remove this connector from Myddleware. Thanks.

**Comment by AlexMyddleware** [comment]
To reopen in case of redeveloping
