### ISSUE TITLE
No available modules with Saleforce

### ISSUE THREAD

**Issue by jeremy-schweitzer** [Myddleware/myddleware#79]
I am doing some initial testing with Myddleware and worked on getting Moodle connected first and had no troubles there. I followed the instructions for Salesforce and successfully connected right away.
![salesforce connector](https://user-images.githubusercontent.com/10454996/36290848-38c0b770-128d-11e8-8ec4-66fce6f79a25.jpg)

However, when I went to create my first rule I ran into a problem. After doublechecking the salesforce setup, deleting the app and recreating it (to try to rule out user error as much as possible), I am still not seeing any available modules to choose from for Salesforce. 
![modules missing](https://user-images.githubusercontent.com/10454996/36290878-6b95526e-128d-11e8-8f2f-ff41c1d92c97.png)

Can you point me towards how I might troubleshoot whether this is an issue on the Myddleware side or whether it's on the Saleforce side? Thanks

**Comment by Myddleware** [comment]
Hi Jeremy,,
Could you tell me which version of Myddleware are you using (you can see it in Myddleware's footer) ? Are you using our cloud (with Platform.sh) or have you installed Myddleware on your own server ? In this cas is it a Linux or Windows server) ?
Have a nice day,
Stéphane

**Comment by jeremy-schweitzer** [comment]
Yes, it's v2.3.3f and I used the Platform.sh option for this initial review.

**Comment by Myddleware** [comment]
Hi Jeremy,

This is weird as I have done a test on Platform.sh just now and it works fine.  

Did you select full here : 
![sforce_full](https://user-images.githubusercontent.com/11330301/36327139-0e69c53c-1334-11e8-9520-eab518efbd03.png)

Could you follow this tutorial from the beginning and try again : https://myddleware.github.io/myddleware/#/connectors_credentials?id=salesforce
Please let me know if you still have the same error.
Stéphane

**Comment by jeremy-schweitzer** [comment]
I think it's an issue on the Salesforce side. I'll come back/repost if I need more assistance. Thanks for the quick replies.

**Comment by Myddleware** [comment]
Thanks for your feedback Jeremy.

**Comment by mjm2230** [comment]
Hi @jeremy-schweitzer and @Myddleware I'm running into this exact same issue. Would you mind sharing what the issue was on the Salesforce side? I'm wondering if it might help to update the Myddleware documentation for Salesforce connectors. I followed it exactly but am hitting this issue. Thank you for any help you can provide!

**Comment by CamillePMyddleware** [comment]
Hi @mjm2230,
Could you tell me which version of Myddleware are you using ? 

Thanks and have a nice day

**Comment by mjm2230** [comment]
Hi @CamillePMyddleware ! Thanks for getting back to me. 

We're using version 3.0.6a.

**Comment by mjm2230** [comment]
Hi @CamillePMyddleware ! I'm wondering if you had any ideas to help me. Thank you!

**Comment by Myddleware** [comment]
Hi @mjm2230 ,
We are very sorry for the delay in our reply.  We will make sure to reply quickly next time.
We try to reproduce your issue but we get all Salesforce modules : 
![image](https://user-images.githubusercontent.com/11330301/197873251-8320a22e-c6c1-4204-9bb4-4e6fa5090b2c.png)

Could you tell us if you use a sandbox or a production environnement ? 
Could you check the log in the directory var/log/prod.log ? 
Thanks.

Have a nice day,
Stéphane

**Comment by mjm2230** [comment]
Hi Stéphane,

It is a sandbox environment. 

Please excuse my ignorance, but how do I check there? When I add var/log/prod.log to my Myddleware url, I get an error that the directory does not exist. However, when I click on the job details through the homepage, I see the following information:

![image](https://user-images.githubusercontent.com/22847068/197913461-93f5d326-32f5-4b9b-9c8d-18190af0cd4d.png)

I hope this is helpful.

Thank you again for your help! It is much appreciated. :) 

Megan

**Comment by Myddleware** [comment]
Hi @mjm2230 ,

The "timezone" bug has been fixed. Could you install the latest version (3.1.7) ? You can run the command myddleware:upgrade : https://myddleware.github.io/myddleware/#/admin_tasks?id=automatic-myddleware-upgrade

ABout Salesforce, did you set the sandbox flag to 1 : 
![image](https://user-images.githubusercontent.com/11330301/198121774-56c737a1-c74c-4cc8-adec-e893567c7a42.png)

The logs are available directly on the server. You have to connect to the server (using ftp or ssh protocol) and open the file var/log/prod.log

Hope it will help.

**Comment by mjm2230** [comment]
This is super helpful -- thank you! I don't have access right now to the server but am working with the team who set up this instance of Myddleware to share that info with me ASAP.
