### ISSUE TITLE
change php command after server migration

### ISSUE THREAD

**Issue by rulotec** [Myddleware/myddleware#791]
Hi Myddleware team!

I had a myddleware 2.5.6 instance running on a server where the php command was php73.
Now I've migrated to a server where the php command is simply php.

I updated several config files like `app/config/public/parameters_public.yml` to change `executable: php73` to `executable: php`
However I was getting an error when running rules manually:

> 'Failed to get the task id.'

I found out that line 958 in `Myddleware\RegleBundle\Classes\rulecore`  is doing:

`exec($php['executable'].' '.__DIR__.'/../../../../bin/console myddleware:synchro '.$ruleSlugName.' --env='.$this->container->get( 'kernel' )->getEnvironment().' > '.$fileTmp.' &', $output);`

and it was using `php73` as value in `$php['executable']`.

If I replace `$php['executable']` with the 'php' string, then it works. But where is that `php73` coming from?

If I grep for php73, this is what I find:

![image](https://user-images.githubusercontent.com/36896420/182049902-d5e65754-7955-4a6f-ab7e-31e92d17b207.png)

Since those are all composer files, I don't want to change them.

Generally speaking, what is the correct procedure to follow when changing the php command name?

Also, I'm now using php 7.4 and I'm aware that in principle, myddleware 2 is not compatible with php 7.4. But so far, it's been working correctly. What is the risk of sticking to php 7.4?

**Comment by Myddleware** [comment]
Hi @rulotec ,
Could you first try to clear your cache ? The cache has to be clear after a modificication in config file. 
Please let us know if it solved your issue.
Thanks.

**Comment by rulotec** [comment]
When you say "clear your cache", do you mean I have to delete the `myddleware/var/cache` directory:

![image](https://user-images.githubusercontent.com/36896420/182219217-82d93ea2-2c1b-4f3a-adb9-b808ed6893e3.png)

Or is there a different way?

Also, about using myddleware 2.5.6 with php 7.4, do you think I could run into issues? So far I haven't and I'm only using the vtiger and facebook connectors.

**Comment by Myddleware** [comment]
Oh sorry about this topic, we forgot it. 
Yes you can clear the cache be deleting myddleware/var/cache/* . Otherwise there is a symfony command too. 

The latest version of Myddleware is compatible with php 7.4 so the best way would be that you upgrade Myddleware. Don't forget to backup your instance before the upgrade because the upgrade from Myddleware 2 to Myddleware 3 is a bug one.

**Comment by AlexMyddleware** [comment]
i'm marking this issue as closed as we are focusing on myddleware 3, but don't hesitate to reopen it if the need arise it
