### ISSUE TITLE
Mailchimp Connection Error

### ISSUE THREAD

**Issue by SunDownGroup** [Myddleware/myddleware#80]
Getting an error with mailchimp where it is showing a connection failed with no message as to the failure reason.

**Comment by Myddleware** [comment]
Oh sorry about that, we have an issue on Mailchimp connector. We will fix it into the version 2.3.4.
We will keep you posted via this issue.

**Comment by SunDownGroup** [comment]
This ever get resolved?

**Comment by Myddleware** [comment]
Hi,
Sorry again, we couldn't made the fix for the version 2.4.0 ;( . You are several who need Mailchimp connector working. We will fix it as soon as possible, we try to finish it before the end of the month.
I 'll keep you posted.

**Comment by SunDownGroup** [comment]
Any update on this fix?

**Comment by Myddleware** [comment]
Hi,
We are currently talking about it with a client. So we will develop it as soon as our client has decided to start the project. Hope it will be soon.
However, if you want we develop it for you before, please contact us privately via our contact form on our website http://www.myddleware.com.
I 'll keep you posted for sure anyway.

**Comment by SunDownGroup** [comment]
So you are not doing what you said you were going to do in the statement made 17 days ago that you were going to try and finish the fix by the end of September?

**Comment by Myddleware** [comment]
Hi,
I said : "we try to finish" not "we try and finish". We do our best to fix every bugs but we have to priorityze our development according to our client needs. So we will fix Mailchimp as soon as we can, we will plan the fix with our client. 
However we keep improving Myddleware, the new version 2.4.0 will be connected to ERPNext. We have also upgraded Myddleware framework from Symfony2 to Symfony3 which was the main priority of Myddleware 2.4.0.
Have a nice day.

**Comment by Myddleware** [comment]
Hi,

Great news, Mailchimp connector is back with the version 2.4.1 of Myddleware #128 . 

Here the detail of Myddleware can do : http://www.myddleware.com/solution/connected-applications?view=project&id=10:mailchimp

Sorry for the delay.

Have a nice day.
