### ISSUE TITLE
When opening dashboard time to load is too long

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#808]
Hi,
when you have lot of dcouments of transfer, opening dashboard (home page) it's a big problem, require some minutes.
I think it's something to solve soon.
Thanks.

@francescobianco

**Comment by CamillePMyddleware** [comment]
Hi @simonetravaglini, 
Sorry for the delay, we are going to make some tests on our side.
We will keep you posted as soon as possible.

Have a nice day

**Comment by Myddleware** [comment]
Yes @simonetravaglini you are right. 
For now we are using a workaround : we use this URL to connect to Myddleware to skip the homapage : <your myddleware URL>/index.php/rule/list
The issue in on the ERROR query, we have to improve it as it takes too long to get the result. We will work on it.

**Comment by Myddleware** [comment]
@AlexMyddleware , we should improve the queries for the homepage. We will work together on it.

**Comment by simonetravaglini** [comment]
@Myddleware news on this point?

**Comment by Myddleware** [comment]
Hi @simonetravaglini ,
We haven't fix the dashbord yet but this is our next main topic (performance on dashlet and document search view). We plan to release the new interface and the SMTP management this week. 
We will keep you posted.

**Comment by AlexMyddleware** [comment]
@simonetravaglini, recent releases of myddleware have improved the dashboard performance. Please consider upgrading your myddleware. I'm closing the issue for now but feel free to reopen it if need be

**Comment by AlexMyddleware** [comment]
@simonetravaglini in a recent released, the performance was improved in general, including the dashlet and document search view. I'm closing this issue but feel free to reopen it should the need arise.
