### ISSUE TITLE
MYD3: SMTP configuration password it's not hide

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#809]
![image](https://user-images.githubusercontent.com/6990139/186356476-64db1fc6-8dfe-47ae-97fb-0e6ea4e8d952.png)

**Comment by AlexMyddleware** [comment]
Hello @simonetravaglini , the bug has been fixed, the fix will be available in the next release. We will do some additional testing to see if the format is compatible all smtp configuration types,but if nothing arises then consider the problem solved.

**Comment by stlgaits** [comment]
https://github.com/Myddleware/myddleware/pull/817
