### ISSUE TITLE
Moodle Enhancement

### ISSUE THREAD

**Issue by SunDownGroup** [Myddleware/myddleware#81]
Would be nice to be able to import users from Moodle into a CRM or ESP.

**Comment by Myddleware** [comment]
Hi,
As you can see here (http://www.myddleware.com/solution/connected-applications?view=project&id=14:moodle), we only create/update user to Moodle, we don't read user from Moodle yet. But we can improve Moodle connector. Are you developper or do you know a developper who can do it? If yes we can guide you to develop it.
If you want we develop it, please contact us directly via this contact form and we will talk about it privately : http://www.myddleware.com/contact-us

About the CRM, to which CRM do you to send your Moodle user ? Here the application already connected : http://www.myddleware.com/solution/connected-applications
If the RM you want isn't in this list we can create a new connector.

Have a nice day,
Stéphane

**Comment by SunDownGroup** [comment]
Moodle to Hubspot was the intended target.

Actually solved my own problem. Used the MySQL connector to hit the Moodle backend DB and push to Hubspot.

**Comment by Myddleware** [comment]
Yes you can do this way. Well done.
Please come back to us if you have any other question.
Stéphane
