### ISSUE TITLE
Documents research

### ISSUE THREAD

**Issue by RomanFaure** [Myddleware/myddleware#818]
It will be more efficient if we can search document by date and by number of instances of loading by document. If you can add this 2 filters in the documents parts, thank you !

**Comment by Myddleware** [comment]
Hi @RomanFaure , 
Yes it would be great but maybe we can just change the field type for "Date of modification" field from date type to datime type : 
![image](https://user-images.githubusercontent.com/11330301/187702997-eaac065a-82fd-4556-ad1b-c4a47012559c.png)
