### ISSUE TITLE
Optimization of requests

### ISSUE THREAD

**Issue by RomanFaure** [Myddleware/myddleware#819]
Optimize the requests according to the search fields in the home page.

**Comment by Myddleware** [comment]
Yes, I am pretty sure that we can improve the search query. Maybe we can join DocumentData table to the query only if we source or target data are requesting. We also have to check the index.

**Comment by AlexMyddleware** [comment]
performance was fixed in recent release of myddleware, but this issue can be reopened for future performance issue in the index.
