### ISSUE TITLE
PrestaShop 1.7 connector

### ISSUE THREAD

**Issue by OscarPsy** [Myddleware/myddleware#82]
Hello, is it possible to create a connector of PrestaShop 1.7? 

I am trying it but I get:

>  Connection failed : Bad auth key

EDIT: This is solver, It was my fault. But I have another question.

**Comment by OscarPsy** [comment]
Hello, I am sorry but it is solved. It was a problem with my server, not myddleware fault.

**Comment by OscarPsy** [comment]
Hello, using prestashop-suitecrm template I get this error: 

> Field newsletter_c not found in the module Contacts. Please make sure that you have access to this field.

May it be because of suitecrm version?

**Comment by Myddleware** [comment]
Hi,
You answer faster than us ;). This is great that you could connect Prestashop.

About the template, this is our mistake as we left a custom field in the template. 
2 ways to fix it : 
 1) You create a custom field on the module contact and name it exactly newsletter_c (or newsletter as SuiteCRM will automaticaly add "_c") : 
![newsletter_suitecrm](https://user-images.githubusercontent.com/11330301/37342842-2a9eeb80-269c-11e8-9ac9-9bc3aa3ed31e.png)

 2) You remove the line in the template as we have done here : https://github.com/Myddleware/myddleware/commit/2fdf5a406505e27090b53f29bf9dd97baffc7a91#diff-c39e438188586ca8457e665dca129d83

This second option is possible only if you have installed Myddleare on your own server. If you use our Cloud, you will have to wait the next hotfix release (very soon). 

Could you tell me if you have solved you problem ?
Best regards,
Stéphane

**Comment by Myddleware** [comment]
Hi,
The template has been fixed few months ago. 
So I close this issue.
Have a nice day
