### ISSUE TITLE
Unable to edit target fields when handling a document in error

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#830]
Documents in error should be editable (inside the target field section of the Document view) when the document is in error, as per the screenshot below :

![image](https://user-images.githubusercontent.com/74190794/196150534-91ee426c-d096-4265-a835-7974c8d96d7f.png)

However, it is currently impossible to edit a target field's data, hence making the Run the same record / Reload the document actions useless since the data will remain the same as the first time the document was read.

![image](https://user-images.githubusercontent.com/74190794/196150102-24a0b3eb-427d-4a19-835b-ca8b7470d9ca.png)

Specifically, when attempting to double-click the field, nothing happens. No error is displayed, the section simply isn't clickable anymore.

Myddleware version 3.1.7b

**Comment by AlexMyddleware** [comment]
this issue was solved on the release of myddleware 3.4.0a, the fields are now clickable and editable
