### ISSUE TITLE
Minor issue: project ID field improperly displayed on Airtable connector creation form

### ISSUE THREAD

**Issue by stlgaits** [Myddleware/myddleware#831]
This fields translation isn't properly loading (probably a typo?) and instead displaying "solution.fields.projectid".

![image](https://user-images.githubusercontent.com/74190794/196446866-0994fc54-ae70-441d-bfa0-cbcfe84f2cc9.png)

Myddleware version 3.1.7b

**Comment by AlexMyddleware** [comment]
![image](https://github.com/Myddleware/myddleware/assets/106162060/3b493b3a-99ac-4695-acf2-0683f27b1e22)
this issue was solved.
