### ISSUE TITLE
error: Field email not found in the module customers

### ISSUE THREAD

**Issue by rafaelb26-dv** [Myddleware/myddleware#837]
Hi, I'm creating a connection from my prestashop to moodle. When I create the default rule, it shows me this error: Field email not found in the module customers. Please make sure you have access to this field

![image01](https://user-images.githubusercontent.com/85837915/198276238-6c236b41-b3d4-413b-8e12-f2b92e712b43.png)
![image02](https://user-images.githubusercontent.com/85837915/198276246-2b90ca37-53b0-444e-b694-0fe7e0ac3c10.png)

**Comment by Myddleware** [comment]
Hi @rafaelb26-dv ,
Could you check that you have access to the field email in the module customer (Prestashop) and in the module user (Moodle) ?

A simple way to test this : create a test rule using modules (not template) between customer module (Prestashop) and user module (Moodle) and check that the field email appears into the field mapping view for Moodle and Prestashop.

**Comment by rafaelb26-dv** [comment]
which one?
![Screenshot_20221027_131342](https://user-images.githubusercontent.com/85837915/198343583-f655f083-ff4d-4d03-94f5-59ce7462e244.png)

**Comment by Myddleware** [comment]
If I remember well, it is something like "The e-shop customers" .

**Comment by rafaelb26-dv** [comment]
it only shows customers on the prestashop side

![image01](https://user-images.githubusercontent.com/85837915/198363395-2b897403-bbeb-41f9-bd08-ae9d01b58404.png)

![image02](https://user-images.githubusercontent.com/85837915/198363430-3a9ad3f9-6286-4eb1-8d4b-aa4df8d490c7.png)

**Comment by Myddleware** [comment]
OK so your problem comes from here. 
Could you check if you have enable the webservice for module customer into Prestashop ?
![image](https://user-images.githubusercontent.com/11330301/198365686-9eb3769b-6f3a-4aaa-aaec-d7a360b08bf7.png)

**Comment by rafaelb26-dv** [comment]
was already

![Screenshot_20221027_151522](https://user-images.githubusercontent.com/85837915/198367948-f28539d7-6d9c-459a-abed-4dce7caaa030.png)

**Comment by Myddleware** [comment]
Please could you tell us which Myddleware version and PRestashop version you use ? 
We will try to reproduce your issue tomorrow.
Have a nice day.

**Comment by rafaelb26-dv** [comment]
Sure,
Myddleware - version 3.1.7b
Prestashop - version 1.7.8.7
Have a nice day you too

**Comment by Myddleware** [comment]
Sorry @rafaelb26-dv , 
We couldn't reproduce the issue. We will be able to work on it again only next week. Sorry for that.
We will keep you posted.
Stephane

**Comment by Myddleware** [comment]
Hi Rafael,
We have set the same version than you and we get all the fields from Prestashop (email included) : 
![image](https://user-images.githubusercontent.com/11330301/199860517-14fc8d8c-adb0-477e-9526-529b72972e13.png)

Maybe the issue could come from your Prestashop instance. Could you try to get the schema from your API using this URL : 
Prestashop_URL/api/customers?schema=synopsis
Add your API key into the field user of the popup, and keep the password empty. 
If the API of your Prestashop instance works properly, you should get something like this : 
![image](https://user-images.githubusercontent.com/11330301/199860860-8e499131-2c87-425f-a410-00dc6cfbf138.png)

Please let me know what you get. Thanks.

**Comment by rafaelb26-dv** [comment]
Hi Myddleware, i did what you asked and it showed this error:

![12345](https://user-images.githubusercontent.com/85837915/199963203-d81747f0-2ade-436b-809f-8c86deb088ee.png)

**Comment by RomanFaure** [comment]
Hi Rafael,
I guess you don't have the right version of prestashop, you should try with the 7.3 for prestashop.
Have a nice day !

**Comment by Myddleware** [comment]
Hi @rafaelb26-dv ,
Sorry @RomanFaure  means your php version used for your Prestashop instance. 
Could you check if you have the right version : 
https://devdocs.prestashop-project.org/1.7/basics/installation/system-requirements/

Thanks.

**Comment by rafaelb26-dv** [comment]
Hi myddleware, my php version is 7.4.32, I looked at the requirements and it's ok

**Comment by rafaelb26-dv** [comment]
Hi @RomanFaure, is there a way to change the Prestashop version without losing data?

**Comment by Myddleware** [comment]
Hi @rafaelb26-dv ,
I think the issue is on Prestashop side. You should get the API schema when you call the URL I gave you. 
Unfortunately, we aren't Prestashop expert so I advise you to search on Prestashop forum why you don't get the API schema. Once you will get the right XML, you should get the Prestashop's fields in Myddleware.
Please keep us updated.

**Comment by Myddleware** [comment]
But yes @rafaelb26-dv , your php version seems to be the right one.

**Comment by rafaelb26-dv** [comment]
Hi, @Myddleware,  how it's going? is it supposed to be like this?
![api](https://user-images.githubusercontent.com/85837915/200551967-ee964c03-7ad6-4d63-8e34-d163e6a30df6.png)

**Comment by Myddleware** [comment]
Hi @rafaelb26-dv ,
I think you already have the module list into Myddleware. The error is when you try to get the field list. For example, you should get the customer field list with this URL : 
Prestashop_URL/api/customers?schema=synopsis

**Comment by rafaelb26-dv** [comment]
Hi @Myddleware, i changed the prestashop version to 1.7.7.7 and apparently it worked
![api](https://user-images.githubusercontent.com/85837915/201109430-896e878a-8d6a-4474-864d-61406c09dc15.png)

**Comment by Myddleware** [comment]
Great, thanks for your feedback.
