### ISSUE TITLE
Plesk Installation

### ISSUE THREAD

**Issue by codrotech** [Myddleware/myddleware#84]
Anybody tried to install it on Plesk with directives for web dir.  I get error on installation  Exit Code: 255(Unknown error) Working directory: /

**Comment by Myddleware** [comment]
Hi,
Sorry for the delay of our response.
Could you have a look to this article, it will give you some clues to configure your virtual host : 
https://symfony.com/doc/2.8/setup/web_server_configuration.html
Please let us know if it works.
Thanks.
