### ISSUE TITLE
Remove/Disable users when not in filter anymore

### ISSUE THREAD

**Issue by lordimac** [Myddleware/myddleware#840]
Hello,
is there any way to remove/disable Moodle users when they are not anymore in the filter but synced before? I'm unsure if this should be inside myddleware or the Moodle plugin.

**Comment by Myddleware** [comment]
HI @lordimac ,
Could you tell me what how does your rule work (from which application/module to which application/module) ? 

Or maybe you could use the field suspended ? 

Have a nice day
Stéphane

**Comment by lordimac** [comment]
Yes, I want to sync an Database with Member Informations to Moodle. But also want to disable/delete users which are disabled in the database. Can be filtered with a field named "Status".

**Comment by Myddleware** [comment]
Hi @lordimac ,
I advise you to create a formula for the field suspended depending on the status in your database. Something like : 
({status}=="Active" ? "0" : "1")
![image](https://user-images.githubusercontent.com/11330301/200832079-e4c69567-9bbd-48fb-9810-d90b381ae7ce.png)

![image](https://user-images.githubusercontent.com/11330301/200831998-88d499f6-6d48-425d-8fec-3baa6174e789.png)

Please adapte the formula depending on your status field in your database.
Hope it helps.

**Comment by lordimac** [comment]
Oh wow, I didnt even know that we can create custom formulas for every field. My bad! Thank you very much, this should do the trick.

**Comment by Myddleware** [comment]
Great ;)
I close the issue but don't hesitate to re open it or create another one if you have another issue.
