### ISSUE TITLE
errorcatcontextnotvalid

### ISSUE THREAD

**Issue by rafaelb26-dv** [Myddleware/myddleware#853]
Hi @Myddleware, my rule is not able to associate the products (prestashop) with the courses (moodle)
![error4](https://user-images.githubusercontent.com/85837915/201385611-64387533-cf8d-48c4-921d-42b5be90c4c1.png)

the error:

errorcatcontextnotvalid : You cannot perform functions in category context (Category Id: 1). The context error was: Invalid parameter value detectedFailed to send document. Status : Error_sending

**Comment by Myddleware** [comment]
Hi @rafaelb26-dv ,
If I remember well, we have forced the category 1 when we create a course into Moodle. But in your case, maybe the category 1 doesn't exist, in this cas you have to edit the rule and change the id 1 by the right one.
Hope it helps.

**Comment by AlexMyddleware** [comment]
i'm marking this issue as resolved. With proper formula of 1 in the category id, then the transfer works. Feel free to reopen this issues should the need arise

![image](https://github.com/Myddleware/myddleware/assets/106162060/c4c49225-803c-4288-80ef-ed9a2ae9a5fb)
