### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by MyddlewareDirectContact** [Myddleware/myddleware#86]
Hi. I have centos 7 php 7.2.3
 
Whenn install via command i have this error:
 
Create tables into your database
 
php app/console doctrine:schema:update --force --env=prod
 
 
 
Error:
[Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'CREATE TABLE JobScheduler (id INT AU
  TO_INCREMENT NOT NULL, date_created DATETIME NOT NULL, date_modified DATETI
  ME on update CURRENT_TIMESTAMP, created_by INT DEFAULT 1 NOT NULL, modified
  _by INT DEFAULT 1 NOT NULL, command VARCHAR(50) NOT NULL, paramName1 VARCHA
  R(50) NOT NULL, paramValue1 VARCHAR(50) NOT NULL, paramName2 VARCHAR(50) NO
  T NULL, paramValue2 VARCHAR(50) NOT NULL, period INT DEFAULT 5 NOT NULL, la
  stRun DATETIME DEFAULT NULL, active TINYINT(1) DEFAULT '1' NOT NULL, jobOrd
  er INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE ut
  f8_unicode_ci ENGINE = InnoDB':
 
  SQLSTATE[HY000]: General error: 1294 Invalid ON UPDATE clause for 'date_mod
  ified' column
 
[Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000]: General error: 1294 Invalid ON UPDATE clause for 'date_mod
  ified' column
 
[PDOException]
  SQLSTATE[HY000]: General error: 1294 Invalid ON UPDATE clause for 'date_mod
  ified' column

**Comment by Myddleware** [comment]
Hi,
Are you using MySQL to install Myddleware ?

**Comment by MyddlewareDirectContact** [comment]
Yess. Mariadb

**Comment by Myddleware** [comment]
Alright,
You need a MySQL database to install Myddleware. Please install a MySQL database and you will be able to install Myddleware.

**Comment by MyddlewareDirectContact** [comment]
Hi. than you for the answer. I install mysql and all work fine. 
I connect with mssql and prestashop.
