### ISSUE TITLE
Prestashop webservice wrong call from myddleware

### ISSUE THREAD

**Issue by Timertygit** [Myddleware/myddleware#863]
Hi Developers,

I've noticed a bug in the myddleware preshashop module "Shops_urls". When I try to use this module there is no information retrieved from prestashop. 
When i look at the apache access log on the prestashop side I've noticed that the request is done with a "date_add" and "date_upd" filter, but for this request we can't use those filters. 
When i remove the "%2Cdate_upd%2Cdate_add" and "&sort=[date_upd_ASC]" from the request I get the correct values. 

Create a rule for prestashop to erpnext.
Select prestashop module "Shop urls from mulitstore feature" and erpnext module "Territory".
Map the field domain to territory_name 
![1](https://user-images.githubusercontent.com/118681183/202914914-dbd5fdad-60e1-41a1-9e46-853b7807c279.png)

Now when i run a simulation i will get the message "There is no data in the source server or fields in the target solution"
![2](https://user-images.githubusercontent.com/118681183/202915590-9b8a4a3d-380c-47dc-866a-1f9027a8e2e7.png)

When i take a look at the apache access log the following is logged:
[19/Nov/2022:23:32:23 +0100] "GET /webshops/api/ HTTP/2.0" 200 35585 "-" "-"
[19/Nov/2022:23:32:24 +0100] "GET /webshops/api/shop_urls?schema=synopsis HTTP/2.0" 200 1442 "-" "-"
[19/Nov/2022:23:32:25 +0100] "GET /webshops/api/ HTTP/2.0" 200 35585 "-" "-"
[19/Nov/2022:23:32:25 +0100] "GET /webshops/api/ HTTP/2.0" 200 35585 "-" "-"
[19/Nov/2022:23:32:25 +0100] "GET /webshops/api/shop_urls?schema=synopsis HTTP/2.0" 200 1442 "-" "-"
[19/Nov/2022:23:32:31 +0100] "GET /webshops/api/ HTTP/2.0" 200 35585 "-" "-"
[19/Nov/2022:23:32:31 +0100] "GET /webshops/api/shop_urls&date=1?filter%5Bdate_upd%5D=%5B1970-01-01+00%3A00%3A00%2C9999-12-31+00%3A00%3A00%5D&display=%5Bdomain%2Cid%2Cdate_upd%2Cdate_add%5D&sort=%5Bdate_upd_ASC%5D&limit=1 HTTP/2.0" 200 1039

When i run the last request from above within the browser i will get this:
![3](https://user-images.githubusercontent.com/118681183/202915834-fda26e4c-6882-4587-a44c-47c6765e09cd.png)

When i remove "&date=1?filter%5Bdate_upd%5D=%5B1970-01-01+00%3A00%3A00%2C9999-12-31+00%3A00%3A00%5D" from the request and do the request as follow "webshops/api/shop_urls&display=[domain%2Cid%2Cdate_upd%2Cdate_add]&sort=[date_upd_ASC]&limit=1" we will get an error:
![4](https://user-images.githubusercontent.com/118681183/202916023-d8fa158b-2f68-4e0d-af2f-f8678ee9ae5a.png)

This error tells us that the field "date_upd" cannot be displayed and we must choose another field from the available fields.

When i run the request as follow i will get the right values: 
webshops/api/shop_urls&display=[domain%2Cid]&limit=1

System setup is as follow:
Prestashop 1.7.8.x server PHP 7.4.30
Myddleware server (Docker) - Myddleware version 3.1.8a
ERPnext server ERPnext v13 - Frappe v14

**Comment by Myddleware** [comment]
Hi @Timertygit ,
I think this module isn't properly managed, thanks for your feedback with all the detail. 
Could you edit this file this file <myddleware_directory>\src\Solutions\prestashop.php and add this code into the method getRefFieldName : 
```
    public function getRefFieldName($moduleSource, $RuleMode): string
    {
        // We force date_add for some module (when there is no date_upd (order_histories) or when the date_upd can be empty (customer_messages))
        if (in_array($moduleSource, ['order_histories', 'order_payments', 'order_carriers', 'customer_messages'])) {
            return 'date_add';
        }
        if (in_array($moduleSource, ['order_details'])) {
            return 'id';
        }
        // BEGIN CODE TO BE ADDED
        if (in_array($moduleSource, ['shop_urls'])) {
            return 'id_shop_url';
        }
        // END CODE TO BE ADDED
        if (in_array($RuleMode, ['0', 'S'])) {
            return 'date_upd';
        } elseif ('C' == $RuleMode) {
            return 'date_add';
        }
        throw new \Exception("$RuleMode is not a correct Rule mode.");
    }
```
Then put 0 in the reference field of you rule 
![image](https://user-images.githubusercontent.com/11330301/203104886-d0a29664-0540-4774-b044-0a63138d9692.png)

Please let us know if it works then we will upgrade Myddleware's code.
Thanks.

**Comment by Timertygit** [comment]
Hi,

Thanks for the fast response. I've altered the code but it seems that the &date=1 filter is still added.
Tried the Reference date with a 0 but also with 1 and an empty field, al the same result.  

[21/Nov/2022:20:39:41 +0100] "GET /webshops/api/ HTTP/2.0" 200 35585 "-" "-"
[21/Nov/2022:20:39:42 +0100] "GET /webshops/api/shop_urls&date=1?filter%5Bdate_upd%5D=%5B1%2C9999-12-31+00%3A00%3A00%5D&display=%5Bid_shop%2Cdomain%2Cid%2Cdate_upd%2Cdate_add%5D&sort=%5Bdate_upd_ASC%5D&limit=101 HTTP/2.0" 200 1039 "-" "-"

![Code-Edit](https://user-images.githubusercontent.com/118681183/203144586-f6e7b813-f3fc-4f0b-a19e-a7c6ea3697c9.JPG)

**Comment by Myddleware** [comment]
Hi @Timertygit ,
We have reproduced the issue on our test environement. We will fix it as soon as possible.
We will keep you updated.

**Comment by Myddleware** [comment]
Hi @Timertygit ,
We have fixed the issue in this commit : https://github.com/Myddleware/myddleware/commit/7010c0ec6f47d7ae784d357abef5c6129976cd5f

We will add this fix in the next release but you can change the code into your instance before if you want.
Have a nice day.

**Comment by Timertygit** [comment]
Hi @Myddleware

I've tested the commit 7010c0e, but it seems to create another error on the SQL syntax for invalid source_date_modified. 
In the parameter -> Reference field I've tried multiple entries, but it doesn't matter if you give a date or not.

Failed to create document (id source : 1): An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1' for column 'source_date_modified' at row 1 /var/www/html/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php Line : ( 117 )
Failed to create document (id source : 2): An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2' for column 'source_date_modified' at row 1 /var/www/html/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php Line : ( 117 )
Failed to create document (id source : 3): An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '3' for column 'source_date_modified' at row 1 /var/www/html/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php Line : ( 117 )

**Comment by Myddleware** [comment]
Oh very sorry, I have tested only in simulation.

We have fix the issue on document creation : https://github.com/Myddleware/myddleware/commit/a23d671aa95738404edc67db0899c7bae7bf37ce

We will release the new Myddleware version this week but you can set change your code using the commit before if you want.

**Comment by Timertygit** [comment]
Hi @Myddleware 

No problem, I can confirm that the issue has been fixed.

Thanks!
