### ISSUE TITLE
installation without docker under windows

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#869]
Hi,
normally we use docker to install myddleware.
But we have some specific case where it's a little bit hard.
The typical scenario is a customer that need to install under a VM with windows instead of linux. In this case the standard docker installation could not work.
Do you have something ready to install under XAMP on a windows VM?
@francescobianco

**Comment by Myddleware** [comment]
Hi @simonetravaglini , 
Could you try using this tuto : https://myddleware.github.io/myddleware/#/?id=install-myddleware
Have a nice day
