### ISSUE TITLE
No data transfer sent from MysqL to Prestashop

### ISSUE THREAD

**Issue by MyddlewareDirectContact** [Myddleware/myddleware#87]
Hi,
I make one rule but I can’t transfer nothing from sql to prestashop.

**Comment by Myddleware** [comment]
Hi,
I guess your problem come from the reference date you put in your rule. You have first to choose the right field (edit view) :
![reference_field](https://user-images.githubusercontent.com/11330301/37969352-7f2a9084-319e-11e8-9e46-f33abe9f5c96.jpg)

You fieldname is maybe not “date_modified” but the field you have to choose would be a field where the last modification date of the record is stored. It could be the last creation date as well, but in this case Myddleware will send only record creation, not record modification to Prestashop.

When this field is chosen, please set the reference date in the past in your rule (detail view) : 
![reference_date](https://user-images.githubusercontent.com/11330301/37969382-8f29b47e-319e-11e8-8cb1-a774a8341fdf.jpg)

Then Myddleware will read every record created/modified after this date.
Could you let me know if it is working ?

**Comment by MyddlewareDirectContact** [comment]
Hi. thank you. It works.
But now I have another problem. 
Prestashop use only number in ID of product. But I hava text. Maybe you have one solution?
![datatransfer](https://user-images.githubusercontent.com/37838101/37969433-bb579642-319e-11e8-9ac0-47966b90ec94.png)

**Comment by Myddleware** [comment]
Hi,
Myddleware won't set an ID for Prestashop product as Prestashop will automaticaly generate it.  However will retrieve the Prestashop product ID once it will be successfully sent.

Could you give me more information about this data transfer. Why is it cancelled ? You can just give me the logs  you have under the data transfer. Your screenshot cut the page so I can't see these logs.
Thanks.

**Comment by MyddlewareDirectContact** [comment]
It works 
![screen shot 03-27-18 at 05 08 pm](https://user-images.githubusercontent.com/37838101/38111035-96567b64-336b-11e8-887f-acf06fb14dc9.PNG)
Thanks.
