### ISSUE TITLE
SuiteCRM 8.2.1 Connection problems

### ISSUE THREAD

**Issue by pelucapampa** [Myddleware/myddleware#887]
When I Update my SuiteCRM to 8.2.1 version, i couldn't connect.
" Connection failed : Please check url"

I tried put with /public/ and same error

**Comment by Myddleware** [comment]
Hi @pelucapampa ,
If you add this "/service/v4_1/rest.php" to your URL, do you get something like this : 
![image](https://user-images.githubusercontent.com/11330301/207980804-b27aea88-e237-44ea-9c89-fe202f51e71e.png)

Thanks.

**Comment by pelucapampa** [comment]
Hi, thanks for your reply.
When I try with your instructions, y couldn't obtain this.

I've obtain blank page, and, when I open DevTools, on console, I can see this error.

"Failed to load resource: the server responded with a status of 500 ()"
________________________________
De: Myddleware ***@***.***>
Enviado: jueves, 15 de diciembre de 2022 19:29
Para: Myddleware/myddleware ***@***.***>
Cc: pelucapampa ***@***.***>; Mention ***@***.***>
Asunto: Re: [Myddleware/myddleware] SuiteCRM 8.2.1 Connection problems (Issue #887)


Hi @pelucapampa<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpelucapampa&data=05%7C01%7C%7Cc7cdab6ff3da47900ecf08dadeebde29%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638067401880362660%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rHtmxNK%2BkvP2ImzQJ04qJzJD3jJGlF9WuFWRP7wCz8U%3D&reserved=0> ,
If you add this "/service/v4_1/rest.php" to your URL, do you get something like this :
[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F11330301%2F207980804-b27aea88-e237-44ea-9c89-fe202f51e71e.png&data=05%7C01%7C%7Cc7cdab6ff3da47900ecf08dadeebde29%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638067401880362660%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5gkd61yuudNlwK2EeyFoOi2cmdF%2BmFFQQKLCSfWmPKE%3D&reserved=0>

Thanks.

**Comment by Myddleware** [comment]
Hi @pelucapampa ,
If you can't reach the page <Your SuiteCRM URL>/service/v4_1/rest.php , you have to fix your suiteCRM installation first. This URL is used by Myddleware to use SuiteCRM REST webservices.
Please try to connect suiteCRM to Myddleware again once you can reach the SuiteCRM rest URL.

**Comment by pelucapampa** [comment]
Hi, i set url  with public/legacy

**Comment by peterarends** [comment]
To clarify a bit more: if you normally login at https://suitcrm.example.com, your url in Myddleware would be https://suitcrm.example.com/legacy making the full url Myddleware uses https://suitcrm.example.com/legacy/service/v4_1/rest.php (test this one first in your browser).

At this time of writing, make sure to use php 7.4 for SuiteCRM 8.x.x. php 8.0 does not work for the 4.1 legacy api.

**Comment by Myddleware** [comment]
Thanks @peterarends
