### ISSUE TITLE
Force rules

### ISSUE THREAD

**Issue by simonetravaglini** [Myddleware/myddleware#889]
Hi,
it seems you finally introduced force rules in 3.2.
With API automatically is forced.
How to force a rule from cron?

**Comment by Myddleware** [comment]
Hi @simonetravaglini , 
You are right, we have added a parameter to force the execution of a job even if another one is already running. 

If you want to force a rule from cron, you have to set the force parameter to 1. 
This is the second parameter in the synchro command : https://github.com/Myddleware/myddleware/blob/0f88ec0eec733490907a3b4389c01584f4c68bf8/src/Command/SynchroCommand.php#L74
The forth in the massacton command : 
https://github.com/Myddleware/myddleware/blob/0f88ec0eec733490907a3b4389c01584f4c68bf8/src/Command/MassActionCommand.php#L63
....
Please let me know if you have any other question.
