### ISSUE TITLE
Close all opened transfer 

### ISSUE THREAD

**Issue by MyddlewareDirectContact** [Myddleware/myddleware#89]
There is one option to close all opened transfer at once? Because i can’t modify the rule.

**Comment by Myddleware** [comment]
Hi,
You can go to the data transfer search view and filter on the ones in error. Then you can select them and cancel them : 
![data_transfer_close](https://user-images.githubusercontent.com/11330301/38111150-e1f52c64-336b-11e8-8932-1a100a41df42.png)

But you can do it only 20 by 20. You can increase a little bit this number by changing the pager parameter in the file \app\config\parameter.yml file. But this isn't a very massive process.
Hope it is fine.

**Comment by MyddlewareDirectContact** [comment]
I saw this. But i have a lot opened transfer (9.000) because i made a mistake.

**Comment by Myddleware** [comment]
Oh I understand.

We plan to add functionalities for admin like massive cancellation but is isn’t developed yet.

The only way is to do it via SqL queries like this one :
UPDATE Document SET status = 'Cancel', global_status = 'Cancel' WHERE rule_id = '' AND global_status = 'Error';

But be careful with SQL query, I advise you to do a select before to be sure of what you are updating. Something like :
SELECT * FROM Document WHERE rule_id = '' AND global_status = 'Error';

**Comment by MyddlewareDirectContact** [comment]
Thank you.
