### ISSUE TITLE
3.2.0 version, cannot access to Home Page

### ISSUE THREAD

**Issue by pelucapampa** [Myddleware/myddleware#902]
Hi, when i extract all files, and try to install from myddleware/public/ the browser cannot show install or login page.

Show error HTTP ERROR 500

**Comment by pelucapampa** [comment]
[26-Dec-2022 12:03:08 UTC] PHP Warning:  require(/home5/aceleradora/public_html/myddleware-main/vendor/autoload.php): failed to open stream: No such file or directory in /home5/aceleradora/public_html/myddleware-main/config/bootstrap.php on line 5
[26-Dec-2022 12:03:08 UTC] PHP Warning:  require(/home5/aceleradora/public_html/myddleware-main/vendor/autoload.php): failed to open stream: No such file or directory in /home5/aceleradora/public_html/myddleware-main/config/bootstrap.php on line 5
[26-Dec-2022 12:03:08 UTC] PHP Fatal error:  require(): Failed opening required '/home5/aceleradora/public_html/myddleware-main/vendor/autoload.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /home5/aceleradora/public_html/myddleware-main/config/bootstrap.php on line 5

**Comment by Myddleware** [comment]
Hi @pelucapampa , could you try to remove the cache directory : 
`rm -rf <myddleware>/var/cache/*`
Then try to execute the following commands :  
```
composer install
yarn install 
yarn build
```

Do you still have the error ?

**Comment by pelucapampa** [comment]
I don't have files into this folder. But i deleted .gitkeep file

But i navigating into zip folder, and cannot vendor folder.

________________________________
De: Myddleware ***@***.***>
Enviado: lunes, 26 de diciembre de 2022 14:02
Para: Myddleware/myddleware ***@***.***>
Cc: pelucapampa ***@***.***>; Mention ***@***.***>
Asunto: Re: [Myddleware/myddleware] 3.2.0 version, cannot access to Home Page (Issue #902)


Hi @pelucapampa<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpelucapampa&data=05%7C01%7C%7C4e621d8eeb874b2f4fe208dae7630533%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638076709723830105%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VLj%2FeEaZPfopnC3XPA%2FIMx4qc3BSjO5wwlq%2F4b1A3oU%3D&reserved=0> , could you try to remove the cache directory :
rm -rf <myddleware>/var/cache/*
Then try to execute the following commands :

composer install
yarn install
yarn build


Do you still have the error ?

**Comment by pelucapampa** [comment]
It's fresh installation.
Y donwloaded the Code ZIP file, and extract on Hosting Folder, and then i try to open /public.
________________________________
De: Ignacio Navarro ***@***.***>
Enviado: lunes, 26 de diciembre de 2022 14:25
Para: Myddleware/myddleware ***@***.***>; Myddleware/myddleware ***@***.***>
Cc: Mention ***@***.***>
Asunto: RE: [Myddleware/myddleware] 3.2.0 version, cannot access to Home Page (Issue #902)

I don't have files into this folder. But i deleted .gitkeep file

But i navigating into zip folder, and cannot vendor folder.

________________________________
De: Myddleware ***@***.***>
Enviado: lunes, 26 de diciembre de 2022 14:02
Para: Myddleware/myddleware ***@***.***>
Cc: pelucapampa ***@***.***>; Mention ***@***.***>
Asunto: Re: [Myddleware/myddleware] 3.2.0 version, cannot access to Home Page (Issue #902)


Hi @pelucapampa<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpelucapampa&data=05%7C01%7C%7C4e621d8eeb874b2f4fe208dae7630533%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638076709723830105%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VLj%2FeEaZPfopnC3XPA%2FIMx4qc3BSjO5wwlq%2F4b1A3oU%3D&reserved=0> , could you try to remove the cache directory :
rm -rf <myddleware>/var/cache/*
Then try to execute the following commands :

composer install
yarn install
yarn build


Do you still have the error ?

**Comment by Myddleware** [comment]
Hi @pelucapampa ,
Could you try to install Myddleware using git and the terminal tutorial : 
https://myddleware.github.io/myddleware/#/?id=install-myddleware

![image](https://user-images.githubusercontent.com/11330301/209571696-e670d692-593c-4bf4-9e19-d33221028b90.png)

**Comment by pelucapampa** [comment]
Thanks, but directory don't have vendor folder

**Comment by Myddleware** [comment]
Hi @pelucapampa ,

If you don't have the vendor folder, it is probably because the cammande `composer install ` didn't work. Could you try to run it again ? 
Thanks.

**Comment by mushoodmujeeb05** [comment]
Hi, 
I am facing an error when accessing the link http://199.127.180.225:30080/index.php/ it gives me below error:

"Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused."

i got the below logs 

"myddleware_1  | 103.151.43.70 - - [20/Apr/2023:21:39:54 +0000] "GET /index.php/ HTTP/1.1" 500 1044 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.48"
"

How to resolve this issue?

**Comment by AlexMyddleware** [comment]
since there was no update on this issue and i haven't been able to reproduce the bug, i'm closing this issue for now. @mushoodmujeeb05 feel free to re open it if you encounter the problem again.
