### ISSUE TITLE
[Mydd3] Rule with 'Compare source table with Myddleware' not working

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#923]
Hi! we have found a problem on Rule with the flag 'Compare source table with Myddleware'

![Screenshot from 2023-01-17 15-15-45](https://user-images.githubusercontent.com/472171/212921844-80473699-ced5-4d18-be51-24bccedcf961.png)

If I run this kind of rule the Task never ends

![Screenshot from 2023-01-17 15-17-12](https://user-images.githubusercontent.com/472171/212922153-16bb3ec3-c60b-4ea8-88aa-24624feaa8a3.png)

It seems stop working at this level 'prod.log'

```
[2023-01-17 13:53:06] php.CRITICAL: Uncaught Error: Typed property App\Entity\RuleParam::$value must be string, null used {"exception":"[object] (TypeError(code: 0): Typed property App\\Entity\\RuleParam::$value must be string, null used at /var/www/html/src/Entity/RuleParam.php:82)"} []
```

Related to the casuality of $ruleParam->setValue(null)

at this level

https://github.com/Myddleware/myddleware/blob/8abe80f0f8512fc42140f7db39de03796a9f580f/src/Manager/RuleManager.php#L448

The expected result is that a record will be removed in target system, but in that case the Task never ends

- SOURCE: Is MSSQL (Microsoft SQL)
- TARGET: Is Vtiger

@simonetravaglini

**Comment by Myddleware** [comment]
Hi @francescobianco , 
You are right, the value has to be a string now and it can't be null. We will try to reproduce this issue with the latest version of Myddleware.
@CamillePMyddleware , could you work on this on Monday please ? You have to use the option "Compare source table with Myddleware" only available with a database connector like MySQL. Thanks.
@francescobianco, we will come back to you on Monday.

**Comment by Myddleware** [comment]
Hi @francescobianco and @simonetravaglini,
The issue is fixed. It will be deploy in version 3.3.1 but you can already apply the above commit if you want.
Have a nice day.
