### ISSUE TITLE
Create a formula

### ISSUE THREAD

**Issue by z3n4j** [Myddleware/myddleware#93]
Hi. How can I create a formula to change " "(empty space)  in "-" and change characters in lower-case?

**Comment by Myddleware** [comment]
Hi,
You can replace space by "-" with this formula : replace( " ","-",{your_field}).
To change to lower-case, you can use this formula lower( {your_field})
If you want to do both, use this formula : replace(" ", "-", lower( {your_field}))

Don't forget to map your field with a drag and drop first : 
![formula](https://user-images.githubusercontent.com/11330301/38306973-3d22927a-37e0-11e8-864a-665c0072245b.png)

Please let me know if it is working.
Best regards,
Stéphane

**Comment by z3n4j** [comment]
Hi. It is working. Thank you.

**Comment by Myddleware** [comment]
Hi,
Great. Thanks for your feedback.
