### ISSUE TITLE
jobScheduler

### ISSUE THREAD

**Issue by z3n4j** [Myddleware/myddleware#94]
Hi.

I run the command:

php app/console myddleware: jobScheduler –env=background

and below is the error?

PHP Warning:  PHP Startup: Unable to load dynamic library 'mssql.so' (tried: /usr/lib64/php/modules/mssql.so (/usr/lib64/php/modules/mssql.so: cannot open shared object file: No such file or directory), /usr/lib64/php/modules/mssql.so.so (/usr/lib64/php/modules/mssql.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  Module 'PDO' already loaded in Unknown on line 0

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "myddleware:" is ambiguous (myddleware:rerunerror, myddleware:synch
  ro and 6 more).

Can you help me?

**Comment by Myddleware** [comment]
Hi, 
Have you installed Myddleware on your own server or do you use our Cloud offer ?
If you have installed Myddleware on your own server , could you send us a screenshot of the content of your table JobSchesuler ? 
Thanks.

**Comment by z3n4j** [comment]
![screen shot 04-10-18 at 09 09 am](https://user-images.githubusercontent.com/18057413/38541313-03023c30-3c9f-11e8-848e-6baac1fd42ec.PNG)

**Comment by Myddleware** [comment]
Thanks.
Could you run the command : php app/console myddleware:synchro ALL --env=background
Coudl you telle me if you get the same error ?

**Comment by z3n4j** [comment]
Hi. I get this.

PHP Warning:  PHP Startup: Unable to load dynamic library 'mssql.so' (tried: /usr/lib64/php/modules/mssql.so (/usr/lib64/php/modules/mssql.so: cannot open shared object file: No such file or directory), /usr/lib64/php/modules/mssql.so.so (/usr/lib64/php/modules/mssql.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

PHP Warning:  Module 'PDO' already loaded in Unknown on line 0

 

                                                                                

  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException] 

  Invalid configuration for path "monolog.handlers.main": Warning: count(): P   

  arameter must be an array or an object that implements Countable              

                                                                                

 

 

  [Symfony\Component\Debug\Exception\ContextErrorException]

  Warning: count(): Parameter must be an array or an object that implements C

  ountable

**Comment by Myddleware** [comment]
Alright, this is not an error in jobscheduler command but certainly a server configuration.

I guess you are using a linux server. Could you confirm ? 
Could you tell me which version of Myddleware you are using ? 

Tanks.

**Comment by z3n4j** [comment]
Server with CENT OS 7
Myddleware v2.3.3f

**Comment by Myddleware** [comment]
Hi,
Because you have a linux server you have to install the driver PDO_DBLIB. Is this driver already installed on your server ?

We have just updated our documentation about the MSSQL connector : https://myddleware.github.io/myddleware/#/connectors_credentials?id=microsoft-sql-server

**Comment by z3n4j** [comment]
The package php70u-pdo-dblib-7.0.28-1.ius.centos7.x86_64 is rendered obsolete by php-pdo-dblib-7.2.3-2.el7.remi.x86_64, which is already installed

**Comment by Myddleware** [comment]
Thanks.
Could you try to edit your rule. Could you tell me if you see the field of your MSSQL table in the field mapping. 
I need to check if the connector works when we send the query to get the field list from your MSSQL database.

**Comment by z3n4j** [comment]
Hi. The rule wokrs. From MSSQL to Prestashop. 

![screen shot 04-11-18 at 04 37 pm](https://user-images.githubusercontent.com/18057413/38623752-ba30a402-3da6-11e8-9c26-18903796de88.PNG)

**Comment by z3n4j** [comment]
![screen shot 04-11-18 at 04 39 pm](https://user-images.githubusercontent.com/18057413/38623882-14fb9036-3da7-11e8-81ac-b3808d0eaaeb.PNG)

**Comment by Myddleware** [comment]
Hi,
Did you transfer data with this rule ?
If yes could you explain me with more detail what is not working ? 
Tanks.

**Comment by z3n4j** [comment]
The rule wokr. But i want that it start automaticly.

![screen shot 04-12-18 at 06 41 am](https://user-images.githubusercontent.com/18057413/38656701-8ac4cc9a-3e1c-11e8-9025-7bbd46994a2e.PNG)

**Comment by Myddleware** [comment]
Alright,
If it works in the web and not via command, it is probably because your file php.ini (for command) has a configuration problem. You could have 2 php.ini file, one for the web and on for the command)

The php.ini location for the web could be find with phpinfo function. About the php.ini location for the command, you can run this command from the root of Myddleware : 

> php app/check.php

You will see if everything is alright to run Symfony2 (Myddleware 's framework) and your php.ini file location for the command : 
![image](https://user-images.githubusercontent.com/11330301/38679414-af694494-3e31-11e8-8385-71b9c1016582.png)

Please let me know if you find the problem.

**Comment by z3n4j** [comment]
I have 1 php.ini.

 PHP is using the following php.ini file:
  /etc/php.ini

> Checking Symfony requirements:
  .............................WW......


 [OK]
 Your system is ready to run Symfony projects


Optional recommendations to improve your setup

![screen shot 04-12-18 at 04 24 pm](https://user-images.githubusercontent.com/18057413/38683575-12daa4dc-3e6e-11e8-8e98-bd2c67edb970.PNG)

**Comment by Myddleware** [comment]
Sorry I keep trying to understand what's going on.

You told me that your ruke works. I see that you could create the rule, but did you manage the send data via Myddleware by clicking on "run the rule" ? 

Thanks.

**Comment by z3n4j** [comment]
Sorry but my English is not perfect. Synchronization works well. I wanted to know how synchronization can be done automatically.

**Comment by Myddleware** [comment]
No problem, mine is not perfect either.

OK you can use crontab and add this command : 

> cd mydelware_directory; php app/console myddleware: jobScheduler –env=background 

In your crontab, if you want to run the synchronisation evry  minutes, you have to put this commande line : 
![image](https://user-images.githubusercontent.com/11330301/38684929-cce09858-3e3e-11e8-8e8d-4d658081b0b2.png)
(just change the Myddleware directory)

Does it meet your needs ?

**Comment by z3n4j** [comment]
But i receve this error.

 [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "myddleware:" is ambiguous (myddleware:rerunerror, myddleware:synch
  ro and 6 more).

**Comment by Myddleware** [comment]
OK,
I see that you have a space between myddleware and jobScheduler in myddleware: jobScheduler.
An I see this space is also in our documentation in english version ;(. We have fixed the documentaton now.
Could you remove the space and try again ? Thanks.
Best regards

**Comment by z3n4j** [comment]
I correct:

 php app/console myddleware:jobScheduler –env=background

Now the error is this: 
  [Symfony\Component\Console\Exception\RuntimeException]
  Too many arguments, expected arguments "command".


myddleware:jobScheduler [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by z3n4j** [comment]
myddleware:jobScheduler [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by Myddleware** [comment]
Another bug in the documentation (happend during the translation in english ;( ) : 

> cd mydelware_directory; php app/console myddleware:jobScheduler --env=background

There is 2 "-" before "env"
Could  you change it and tell me if it work ? Thanks.

**Comment by z3n4j** [comment]
Now the error is different:

 [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  Invalid configuration for path "monolog.handlers.main": Warning: count(): Parameter must be an array or an object that implements Countable



  [Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: count(): Parameter must be an array or an object that implements Countable

**Comment by z3n4j** [comment]
php app/console myddleware:jobScheduler -env=background

statut New id = 5acf7e18693336.42516339  2018-04-12 15:41:12
statut New id = 5acf7e18a73b16.83134757  2018-04-12 15:41:12
statut New id = 5acf7e18a7ef75.52218350  2018-04-12 15:41:12
statut New id = 5acf7e18a896a2.04356802  2018-04-12 15:41:12
statut New id = 5acf7e18a940c7.72241472  2018-04-12 15:41:12
statut New id = 5acf7e18a9eaf8.99191249  2018-04-12 15:41:12
statut New id = 5acf7e18aaa772.56228652  2018-04-12 15:41:12
statut New id = 5acf7e18ab5430.24320819  2018-04-12 15:41:12
statut New id = 5acf7e18abfda4.34961042  2018-04-12 15:41:12
statut New id = 5acf7e18aca922.73372564  2018-04-12 15:41:12
statut New id = 5acf7e18ad5ca4.28950849  2018-04-12 15:41:12
statut Filter id = 5acf7e18693336.42516339  2018-04-12 15:41:12
statut Filter id = 5acf7e18a73b16.83134757  2018-04-12 15:41:12
statut Filter id = 5acf7e18a7ef75.52218350  2018-04-12 15:41:12
statut Filter id = 5acf7e18a896a2.04356802  2018-04-12 15:41:12
statut Filter id = 5acf7e18a940c7.72241472  2018-04-12 15:41:12
statut Filter id = 5acf7e18a9eaf8.99191249  2018-04-12 15:41:12
statut Filter id = 5acf7e18aaa772.56228652  2018-04-12 15:41:12
statut Filter id = 5acf7e18ab5430.24320819  2018-04-12 15:41:12
statut Filter id = 5acf7e18abfda4.34961042  2018-04-12 15:41:12
statut Filter id = 5acf7e18aca922.73372564  2018-04-12 15:41:12
statut Filter id = 5acf7e18ad5ca4.28950849  2018-04-12 15:41:12

**Comment by Myddleware** [comment]
That's a good news. 
What have you done to fix your lats problem ? 
best regards.

**Comment by z3n4j** [comment]
I made a mistake in typing.

Thank you.

**Comment by Myddleware** [comment]
OK.
Thanks for you feedback.
Contact us if you need anything else.
Best regards.
Stéphane
