### ISSUE TITLE
Formula number caracters

### ISSUE THREAD

**Issue by z3n4j** [Myddleware/myddleware#95]
Hi. There is a formula to limit import description to the first 20 caracters?

**Comment by Myddleware** [comment]
Hi,
Yes you can use the formula : substr( {your_field},0,20)
![image](https://user-images.githubusercontent.com/11330301/38575223-ecdc60b4-3cc8-11e8-98d9-0ac2dab42e17.png)

**Comment by z3n4j** [comment]
Hi. thank you. It works fine.
