### ISSUE TITLE
Issue creating a Moodle Connector: "Connection failed : accessexception"

### ISSUE THREAD

**Issue by boiraeditorial** [Myddleware/myddleware#96]
Hi,
I´m trying to create a Myddleware Moodle Connector but I´m getting the following error:  "Connection failed : accessexception" 
I´ve followed all the steps given in this tutorials, but I´m not able to create it.

https://myddleware.github.io/myddleware/#/connectors_credentials?id=moodle
https://docs.moodle.org/34/en/Using_web_services

I´m using Myddleware to sell Moodle Courses with Prestashop. I´ve created the connector for prestashop but I´m not able to do it with Moodle. Any idea?
Thanks and Best Regards

**Comment by Myddleware** [comment]
Hi,
Could you test your token without Myddleware by going to this URL (please change your instance address "your_moodle_instance.com" and your token "your_token" in the URL) : 
http://your_moodle_instance.com/webservice/rest/server.php?wstoken=your_token&wsfunction=core_webservice_get_site_info&moodlewsrestformat=json

Youshould get a result like this one : 
![image](https://user-images.githubusercontent.com/11330301/39301332-fc2eb502-494e-11e8-9e07-79cb14b1e8c0.png)

Otherwise, you Moodle webservice configuration isn't good.

Please let me know if it helps.

Best regards.

**Comment by boiraeditorial** [comment]
Hi! 

thanks for your prompt answer. Effectively the Webservice Moodle Configuration is not good. 

I´ve followed this steps:

1. I´ve created a new user and I´ve assigned it to a new rol that has the capability to use the REST protocol.


2. I´ve created a new web service and I ´ve assigned the two funcions to it.
This web service is available for All the users and there is no extra capability required.

3. I´ve created a new token and I´ve assigned it to the new user and to the webservice. 

I don´t know how to configure it! 
Have a nice day you too!!!
Thanks and best regards

**Comment by Myddleware** [comment]
Hi,
There is not only 2 functions to add in the webservice, you should add all these functions : 
![image](https://user-images.githubusercontent.com/11330301/39355623-fc345b1e-4a0d-11e8-9987-c2550ee773e3.png)

Could you try and test again ?
Thanks.

**Comment by boiraeditorial** [comment]
Hi,
ooohh! great! Reading the manual I was thinking that I´ve to added only the two last functions! Now, it works. Thank you very much for your help!
Now, I need to sell my Moodle Courses throw Prestashop. So I´ve to create a new Rule where the source is Prestashop and the Target is Moodle right?  In any case, which of all the possibilities have I to use?
Thanks and Best Regards

**Comment by Myddleware** [comment]
Hi,
Good news.

I have added a template between Prestashop and Moodle below. This template will be available in the new release (2.3.4) however you can install it manually in Myddleware 2.3.3.Please unzip this file then copy it in the directory \src\Myddleware\RegleBundle\Templates :
[prestashop_moodle_user_enrolment_course.zip](https://github.com/Myddleware/myddleware/files/1970862/prestashop_moodle_user_enrolment_course.zip)

Then you will be able to select this template when you create a rule :+1: 
![image](https://user-images.githubusercontent.com/11330301/39577116-b3a0fb8c-4ee0-11e8-9e3c-26f57ef1d8ec.png)

This template will help you by creating 4 rules. Then you will be able to modify these rules according your specific needs.

**Comment by Khaled4** [comment]
If you receive "**Connection failed : accessexception**" error, which I broke my head over for a whole day :) the fastest solution is to do the integration while your system has no users yet. Meaning, create your connector as the system administration while no other user is on the system. This should take care of this error.
**Attention: Do NOT delete your users if your system is already in use as this will also delete all their course enrollments, grades, etc.**
You might want to test backup and restore of users.
I hope this helps.

**Comment by Myddleware** [comment]
Hi Khaleb,
Thanks for your feedback. 
If you do some tests by creating a user, you can delete this user in Moodle. Yes it will remove the enrolments of this user, bit it will be OK if it is a test user.
Hope I am clear.
Have a nice day.
