### ISSUE TITLE
error transfers/list "service unavailable"

### ISSUE THREAD

**Issue by Alexandre17220** [Myddleware/myddleware#97]
Hi all,
I try to add a rule bidirectionnal for update product (name,price,description) from SuiteCRM to PrestaShop 1.7.
I have 4000 products in Prestashop, for information, and I have a rule for transfer product from PS to SuiteCRM.
When I go in Myddleware menu Transfer/list , I have error "service unavailable".
How to unlock the situation ?
I have tried to restart httpd, disable the rule... no success.
Can I go in mysql database myddleware for delete all transfer ?
Thanks,

**Comment by Myddleware** [comment]
Hi Alexandre,
Could you use dev environment to have more detail about the error?
To use dev environment, you can change your URL by adding app.php by app_dev.php, something like : http://<root_url>/web/app_dev.php/ 
Could you tell me if you get more detail ? 
You an always delete transfer in your database, you can clean document and documentData tables.
Have a nice day.

**Comment by Alexandre17220** [comment]
> Could you use dev environment to have more detail about the error?
no more detail 
"Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later."
If I delete document an document data, there is impact for myddleware ? or it's simply log?

**Comment by Myddleware** [comment]
OK, your are not in a test environment so you shouldn't delete Mydleware data transfer.
Maybe, the query sent in the data transfer list view is too big for your server configuration.

Could you try to change the value search_limit in the file app\config\parameters.yml
    transfer:
        search_limit: 1000
You can set the value to 10 to test and increase it after.

If you use dev environment, you will have just to unlog and log again to Myddleware. If you use standard environment, you will have to clear the cache by removing the directory myddleware\app\cache\prod and log again

Please keep me posted.
Have a nice day.

**Comment by Alexandre17220** [comment]
No section transfer in parameters.yml, I add it, delete cache directory but I have 1000 limit always:
`parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: '3309'
    database_name: myddleware
    database_user: usermyddleware
    database_password: xxx
    mailer_transport: mail
    mailer_host: null
    mailer_port: null
    mailer_auth_mode: null
    mailer_user: null
    mailer_password: null
    mailer_email: null
    mailer_name: null
    secret: xxx
    myddleware_support: 0
    param:
        mode: front_office
    extension_allowed:
        - xml
        - wsdl
    myd_version: 2.2.3
    php:
        executable: php
    locale: en
    pager: 20
    block_install: 1
    transfer:
    search_limit: 10
`

**Comment by Myddleware** [comment]
What is your Myddleware version ? You can see it in Myddleware footer.

**Comment by Alexandre17220** [comment]
2.2.3

**Comment by Myddleware** [comment]
OK, this parameter is only available in version 2.3.X
Could you upgrade your Myddleware  ? You can use this tutorial : https://myddleware.github.io/myddleware/#/admin_tasks?id=upgrading-myddleware

For information we will launch Myddleware 2.4 by the end of this month.

**Comment by Alexandre17220** [comment]
ok I try, thanks

**Comment by Myddleware** [comment]
Alright. If you have any problem during the upgrade, please open a new issue in this forum.

**Comment by Alexandre17220** [comment]
Update done, error now ; "
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please e-mail us at contact@myddleware.com and let us know what you were doing when this error occurred. We will fix it as soon as possible.
You can also log the issue on our Github : Myddleware Github project 

Sorry for any inconvenience caused.
"
Parameters.yml already "transfer: null
    search_limit: 10" strange

**Comment by Myddleware** [comment]
Could you connect with dev URL : http://<root_url>/web/app_dev.php/
You should get more detail after a 500 error.
Could you give me the daail of your error ? Thanks.

**Comment by Alexandre17220** [comment]
Whoops, looks like something went wrong.
1/1
OutOfMemoryException in PDOStatement.php line 105:
Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 173741632 bytes)
in PDOStatement.php line 105

**Comment by Myddleware** [comment]
Does it append when you open the list transfer view or another page ?

**Comment by Alexandre17220** [comment]
append when I select my rule in the transfert list 
like this
![image](https://user-images.githubusercontent.com/7665521/40428246-1d8c52a2-5ea0-11e8-91d3-7db9b4dd6698.png)
and click filter

**Comment by Myddleware** [comment]
Thanks,
You told me that in parameter.yml file, you have "transfer: null search_limit: 10" . You should have this data format (without null) : 
![image](https://user-images.githubusercontent.com/11330301/40429359-d21dd25c-5ea2-11e8-8be5-c8cbf83f7e86.png)
Could you check you have this format. If you don't have it, could you change it, put 10 instead of 1000, clear the cache and log again ?
Thanks.

**Comment by Alexandre17220** [comment]
same error, my file, clear cached, I have tried too in dev
![image](https://user-images.githubusercontent.com/7665521/40430818-44533b52-5ea6-11e8-97a6-55402feb7214.png)

**Comment by Myddleware** [comment]
Could you increase the memory limit (memory_limit variable) to 512M minimum in your php.ini file ?
Thanks.

**Comment by Alexandre17220** [comment]
512, restart php-fpm always the same error

**Comment by Myddleware** [comment]
Hi Alexandre,

Does you error still something like : Error: Allowed memory size of 268435456 .....

Dos the number 268435456  change to a value greater than 512000000 ? If not, your modification in the php.ini file hasn't been commited. After this modification you have to restart your http service (probably apache or nginx). Or maybe you change the wrong php.ini file, it could be several php.ini files in your server.

Please let me know if you still have the error with a number greater than 512000000. If yes could you increase it more ? Thanks.

**Comment by Alexandre17220** [comment]
I restart php-fpm, in dev mod I see 512mo memory for php
![image](https://user-images.githubusercontent.com/7665521/40479082-096c852a-5f4b-11e8-8c4b-06bd58040f94.png)
the error : (in mode dev)
![image](https://user-images.githubusercontent.com/7665521/40479135-2a00e2f4-5f4b-11e8-9bae-7a7bd3ebb0ed.png)

**Comment by Myddleware** [comment]
Hi Alexandre,
This is odd to get 500 error witout detail in dev environment. Is there a way to have access to your Myddleware to be able to analyse your problem.
If you are OK with that, could you contact us via our contact page http://www.myddleware.com/contact-us
Thanks.

**Comment by Alexandre17220** [comment]
Sorry for the delay, I think I go to make my own connector solution, I cannot use your solution for production.
But I keep contact, maybe I retest it in many years.
Thanks

**Comment by Myddleware** [comment]
No problem Alexandre and thanks for your feedback. You can use our code (in solution directory) to help you to build your own connector ;). 

Just let you know that we have launched the Myddleware version 2.3.4. So you can try another update, it could resolve your 500 error.

Good luck
