### ISSUE TITLE
Vtiger - Prestashop Call failed Array

### ISSUE THREAD

**Issue by AnthonyFrench84** [Myddleware/myddleware#970]
Hello everyone.

I've been racking my brains for several days installing and configuring Myddleware, but I'm encountering an error that I can't fix.

- Prestashop 1.6.5.1
- Myddleware 3.3.0b
- Vtiger 7.5.0
- PHP 8.1.16
- Ubuntu 20

I'm not a great professional lines of code but I manage by following the documents.

Prestashop connection = **OK**
Vtiger connection = **OK**

I have met all the installation conditions for Myddleware, installation by FTP + web setup.
Installation of Composer with all necessary applications via Plesk.

Now when I create a rule I get the following error during validation:
**Alert: Call failed Array /var/www/vhosts/mysite.com/myddleware/src/Solutions/prestashop.php Line: (367)**

I checked the logs and can't find any details about this error.
Can anyone here help me fix this issue so I can move forward with the setup?

Good day to all.

![Capture d’écran 2023-03-09 142505](https://user-images.githubusercontent.com/90352536/224051933-3416c2f3-8cae-42d7-9855-67d4309e7da1.jpg)

**Comment by Myddleware** [comment]
Hi @AnthonyFrench84 ,
Thanks for your interest in Myddleware. We have successfully tested a rule between Prestashop and Vitiger. However we test only with Prestashop 1.7.x as we don't maintain the connector for Prestashop 1.6.5.
Please contact us directly on our website if you want to discuss about it : https://www.myddleware.com/contact-us
I guess that we could speak in french ;)

**Comment by AnthonyFrench84** [comment]
Good morning,
The problem seems to be compatibility with Prestashop 1.6 and the latest version of Myddleware. I read on the forum that other users have successfully connected with Prestashop 1.6 and Myddleware 2.5

What is the latest version compatible with Prestashop 1.6 that you are using?

THANKS

**Comment by AnthonyFrench84** [comment]
Hello, great, I just sent you an email.

Good day

**Comment by Myddleware** [comment]
Hi @AnthonyFrench84 ,
Thanks for the direct message.
You are right, Myddleware 2.5 was compatible with Prestashop 1.6 but we no longer support Myddleware 2.5.
Sorry for that.
