### ISSUE TITLE
[MsSQL][Mydd3] Missing record on database after create()

### ISSUE THREAD

**Issue by francescobianco** [Myddleware/myddleware#971]
Hi! 

We have somethimes missing records when TARGET is a MsSQL database, in a case where $idTarget is provided from source.

Our idea is that record cannot be created due to problems

It is possible add check to verify if after a CREATE operation the record was surely created.

for example adding something like "SELECT FROM WHERE id = $idTarget" here:

- https://github.com/Myddleware/myddleware/blob/310a9e8c4e294e93b528b552cad0a61ea31594d7/src/Solutions/database.php#L432

cc @simonetravaglini

**Comment by Myddleware** [comment]
Hi @francescobianco ,
Yes you are right, if idTarget is provided from source, we aren't 100% sure that the record is created. It is an important issue. 
We could send a query to check if the record exists but it will generate bad perfomance. We will try to get more details after the creation (and the update) returned by the query. We should at least now how many rows have been created or update. And if it is 0 then we generate an error message.
We will get back to you as soon as we have fixed this issue.
@AlexMyddleware , could you work on this next week please ? Thanks.

**Comment by AlexMyddleware** [comment]
hello @francescobianco, I found the origin of the bug, I'm working on a solution, I will keep you posted.

**Comment by AlexMyddleware** [comment]
Hello @francescobianco, the bug was corrected and the fix will be in the 3.3.1c, thanks a lot for your input.

**Comment by AlexMyddleware** [comment]
3.3.1c came out, i'm marking this issue as solved.
