### ISSUE TITLE
upgrade problem what version of mysql now?

### ISSUE THREAD

**Issue by Alexandre17220** [Myddleware/myddleware#98]
upgrade problem what version of mysql now?
When I do:
php app/console doctrine:schema:update --force --env=background
I have :
![image](https://user-images.githubusercontent.com/7665521/40418979-20f181b8-5e84-11e8-9d0c-84ef7bca3e1b.png)

**Comment by Myddleware** [comment]
Hi Alexandre,
Could you replace dthisline : 
`     * @ORM\Column(name="date_modified", columnDefinition="DATETIME on update CURRENT_TIMESTAMP"))`
By this one : 
`     * @ORM\Column(name="date_modified", type="datetime")`
In the file src\Myddleware\RegleBundle\Entity\JobScheduler.php
The could you re run the command ?
Thanks.

**Comment by Myddleware** [comment]
I see in another discussion that your installation is done.
Have a nice day. #92

**Comment by Alexandre17220** [comment]
yes I have upgraded my mysql version.
thnaks,
