### ISSUE TITLE
Add comment on a document

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#996]
Add the possibilité to add a comment on a document. This comment will be saved as a log type info on the document.

A text area should be added here with the possibility to add a comment : 
![image](https://user-images.githubusercontent.com/11330301/232885683-125e62ea-49d5-4d1b-914a-7e38b0e23f2e.png)

**Comment by AlexMyddleware** [comment]
Completed, will be available as a feature in a coming release.
