### ISSUE TITLE
Add comments on a rule

### ISSUE THREAD

**Issue by Myddleware** [Myddleware/myddleware#997]
The description field (that already exists) should be changed to a text area that could be edited in detail view.
![image](https://user-images.githubusercontent.com/11330301/232886656-ea02add3-dfa6-47ad-9f53-056077abe7e3.png)

**Comment by CamillePMyddleware** [comment]
Hi @Myddleware, here is the rendering
![image](https://user-images.githubusercontent.com/95077335/233945675-5855483b-284d-4fca-8f21-3974036b5774.png)
![image](https://user-images.githubusercontent.com/95077335/233945848-c0c5bb5e-704c-472f-a5aa-d16d4d79c8d7.png)
